GoogleCloudPlatform/k8s-config-connector

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/question.md

Update issue templates

---

CONTRIBUTING.md

Also suggest running the mockgcp tests, for faster validation.

Update contributing doc to suggest use of gh CLI

---

operator/Makefile

Add "install", "uninstall", "deploy" and "destroy" rules to the operator Makefile.

Add a few rules in the operator Makefile.

---

.gitattributes

This helps with the presentation in github PR reviews.

Mark go.sum as generated files

---

pkg/controller/dcl/controller.go
pkg/controller/registration/registration_controller.go

These messages don't seem to add a lot of value.

Reduce logging during controller startup

---

OWNERS

Aiming for a broad set of approvers/reviewers.

Create initial OWNERS file

---

.github/workflows/presubmit.yaml
build/builder/Dockerfile
operator/Dockerfile

So we get the latest and greatest security fixes.

Bump golang version to latest 1.21

---

operator/pkg/controllers/configconnector/configconnector_controller.go
operator/pkg/controllers/configconnector/configconnector_controller_test.go
operator/pkg/controllers/utils.go
operator/pkg/test/controller/customization.go

Check for duplicate webhooks in `.spec.webhooks` list of webhook configuration customization CRs.
Fixes #893, b/296513545

Check for duplicate webhooks in customization CR

---

operator/pkg/controllers/configconnector/configconnector_controller.go

The operator currently ignores webhooks in the `ValidatingWebhookConfigurationCustomization` and `MutatingWebhookConfigurationCustomization` custom resources that do not match any KCC webhooks. This PR surfaces these invalid webhooks in the CR status field so that users are aware of them.
Fixes #895, b/296633669

Surface ignored webhooks during webhook configuration customization

---

config/samples/resources/containerattachedcluster/container-attached-cluster-basic/containerattached_v1beta1_containerattachedcluster.yaml
config/samples/resources/containerattachedcluster/container-attached-cluster-basic/resourcemanager_v1beta1_project.yaml
config/samples/resources/containerattachedcluster/container-attached-cluster-full/containerattached_v1beta1_containerattachedcluster.yaml
config/samples/resources/containerattachedcluster/container-attached-cluster-full/resourcemanager_v1beta1_project.yaml
config/samples/resources/containerattachedcluster/container-attached-cluster-ignore-errors/containerattached_v1beta1_containerattachedcluster.yaml
config/samples/resources/containerattachedcluster/container-attached-cluster-ignore-errors/resourcemanager_v1beta1_project.yaml
scripts/generate-google3-docs/resource-reference/generated/resource-docs/containerattached/containerattachedcluster.md

Fix comments in attached cluster samples to meet documentation guidelines
No code change.

Fix comments in attached cluster samples

---

mockgcp/README.md

Tackling the question of how accurate we want the mock to be, focusing
on the journey over perfection from the outset.

mockgcp: update README to define "good enough" criteria

---

config/tests/samples/create/harness.go
mockgcp/mockcertificatemanager/names.go
mockgcp/mockcertificatemanager/v1.go

Add mockgcp support for CertificateManager CertificateMap and dnsAuthorizations

mockgcp support for CertificateManager CertificateMap and dnsAuthorizations

---

.github/workflows/presubmit.yaml

Fixes "net/http: rapid stream resets can cause excessive work" issue.

Version-bump golang to 1.21.3

---

config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_alloydbclusters.alloydb.cnrm.cloud.google.com.yaml
config/servicemappings/alloydb.yaml
pkg/clients/generated/apis/alloydb/v1beta1/alloydbcluster_types.go
scripts/generate-google3-docs/resource-reference/generated/resource-docs/alloydb/alloydbcluster.md

Remove extra double quote
Fixes #

Addressing comments from Terraform 4.84.0 Upgrade

---

pkg/cli/cmd/bulkexport/singleresourceiamclient/singleresourceiamclient_test.go
pkg/cli/gcpclient/client_integration_test.go
pkg/controller/dynamic/dynamic_controller_integration_test.go
pkg/controller/iam/auditconfig/iamauditconfig_controller_integration_test.go
pkg/controller/iam/iamclient/iamclient_integration_test.go
pkg/controller/iam/partialpolicy/iampartialpolicy_controller_integration_test.go
pkg/controller/iam/policy/iampolicy_controller_integration_test.go
pkg/controller/iam/policymember/iampolicymember_controller_integration_test.go
pkg/controller/resourcecontention/resourcecontention_integration_test.go
pkg/lease/leaser/leaser_integration_test.go
pkg/lease/leaser/resource_leaser_integration_test.go
pkg/test/controller/reconcile.go
pkg/test/controller/reconciler/testreconciler.go
pkg/test/iam/resource_level_test_runner.go
pkg/test/resourcefixture/test_runner.go
pkg/test/runner/runner.go

tests: wire in context to the next "wave" of functions

---

mockgcp/README.md
mockgcp/mock_http_roundtrip.go
mockgcp/mockgkemulticloud/attachedcluster.go
mockgcp/mockgkemulticloud/names.go
mockgcp/mockgkemulticloud/service.go

Fixes b/304550821
N/a, doc update

Add more details to mock gcp readme

---

config/tests/samples/create/samples.go
config/tests/samples/create/samples_test.go
mockgcp/mock_http_roundtrip.go
mockgcp/mockcertificatemanager/v1.go
mockgcp/mockcloudfunctions/v1.go
mockgcp/mockgkemulticloud/attachedcluster.go
mockgcp/mockiam/serviceaccounts.go
mockgcp/mocknetworkservices/networkservices.go
mockgcp/mockprivateca/capool.go
mockgcp/mocksecretmanager/secretversions.go
tests/e2e/unified_test.go

This ensures that we get a bit more test coverage here.

Add updates to tests/e2e

---

scripts/generate-field-diffs-tf-upgrade/generate_field_changes.py

A quick and dirty fix for the field changes generator script.
It's hacky, but... it works for now.
Fixes #

cheap fix for field changes generator

---

config/tests/samples/create/harness.go
config/tests/samples/create/samples.go

Set some of the informational messages that are repeated a lot to V(2).

tests: reduce log verbosity

---

config/tests/samples/create/samples_test.go

Fixes the test naming in sample test

Fixs edgecontaienr naming in sample test

---

Makefile
mockgcp/dev/fix-gofmt
mockgcp/mockedgenetwork/names.go
mockgcp/mockedgenetwork/network.go
mockgcp/mockedgenetwork/subnet.go
mockgcp/pkg/storage/memory.go

We weren't covering the mockgcp module.

tests: verify gofmt

---

k8s-config-connector

Remove a dead symlink. Seems to be introduced by accident.
Fixes #

Remove dead symlink

---

config/tests/samples/create/harness.go
operator/pkg/test/main/testmain.go
pkg/apis/iam/v1beta1/v1beta1_suite_test.go
pkg/crd/crdloader/crdloader_test.go
pkg/test/environment/environment.go

We were setting the start timeout, but the stop timeout was unset and
defaulting to 20 seconds.

envtest: set ControlPlaneStopTimeout to one minute.

---

pkg/test/constants/constants.go
pkg/test/constants/presubmitconstants.go
pkg/test/resourcefixture/testdata/basic/edgecontainer/v1beta1/edgecontainercluster/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/edgecontainer/v1beta1/edgecontainernodepool/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/edgecontainer/v1beta1/edgecontainervpnconnection/dependencies.yaml
scripts/shared-vars-public.sh

Fix the edgecontainercluster integration test, local test passed: https://screenshot.googleplex.com/3F6y4h3aXr2HtF6.png
Tested with make ready-pr
- [x ] Run `make ready-pr` to ensure this PR is ready for review.
- [x ] Perform necessary E2E testing for changed resources.

Update the edgecontainercluster integration test

---

mockgcp/mocksecretmanager/tests/service_test.go
pkg/controller/mocktests/secretmanager_secret_test.go
pkg/controller/mocktests/testdata/secretmanager/secret_and_secretversion/input.yaml
scripts/github-actions/ga-mock-test.sh

We weren't running the tests in mockgcp in github actions (and I broke them!)

mockgcp: Run tests in github actions

---

.github/workflows/presubmit.yaml
experiments/composite/go.mod
go.mod
mockgcp/go.mod

Bump to golang 1.21.4 in a few more places

versionbump: golang 1.21.4

---

README.ChangingTerraform.md

This is required as we have now removed all the previous Terraform "patches" and abandoned the patch approach.
Fixes b/314326104

Update README.ChangingTerraform.md to be based on TF Git Subtree

---

README.ChangingTerraform.md
README.UpdatingTerraformProvider.md

Change Terraform upgrade guide with clarifications and Git Subtree example command

---

.github/workflows/presubmit.yaml
experiments/composite/go.mod
go.mod
mockgcp/go.mod

Will keep the security scanners happy.

chore: update golang to 1.21.5

---

pkg/test/constants/constants.go

Disable containerattachedcluster integration test

---

README.NewResourceFromTerraform.md

Fixes b/315229133, b/315185717
* Added instructions to add the observed fields.
* Added instructions to support the resourceID.
* Fixed the link to servicemapping types.
* Fixed the indentation issue in the YAML snippets.
* Replaced the TODO with instructions about getting the template variable.

Update the NewResourceFromTerraform readme with instructions for the observed fields

---

operator/pkg/apis/core/v1beta1/configconnectorcontext_types.go
operator/pkg/controllers/configconnectorcontext/e2e_test.go

- operator: create smoke test for ConfigConnectorContext
- ConfigConnectorContext should implement CommonObject

ConfigConnectorContext should implement CommonObject

---

scripts/generate-google3-docs/resource-reference/generated/resource-docs/sql/sqlsslcert.md
scripts/generate-google3-docs/resource-reference/overview.md
scripts/generate-google3-docs/resource-reference/templates/sql_sqlsslcert.tmpl

Fixes b/320298417, b/320297276

Fix broken link in resources documentation

---

CONTRIBUTING.md
config/samples/resources/artifactregistryrepository/artifactregistry_v1beta1_artifactregistryrepository.yaml
scripts/generate-google3-docs/resource-reference/generated/resource-docs/artifactregistry/artifactregistryrepository.md

Some small changes to the getting started guide that I'd have found useful going thru and a small fix potentially to the sample from the getting started guide.

add annotation to sample; troubleshooting instructions

---

config/tests/samples/create/harness.go

This is much faster than envtest, at the expense of being less
accurate (most immediately relevant to us: webhooks are not supported).

tests: support mockkubeapiserver as E2E_KUBE_TARGET

---

operator/cmd/manager/main.go
operator/pkg/controllers/configconnector/e2e_test.go
operator/pkg/controllers/scheme.go
operator/pkg/test/main/testmain.go

- Add e2e test for ConfigConnector operator
- operator: build scheme once and reuse in tests

Create very simple test for operators

---

go.mod
go.sum
pkg/test/resourcefixture/resourcefixture.go
scripts/generate-google3-docs/resource-reference/main.go

We weren't using it significantly.

Remove last uses of go-datastructures library

---

mockgcp/mockcompute/networksv1.go
mockgcp/mockcompute/subnetsv1.go

Avoids building a string just to parse it.

mockgcp: refactor name parsing

---

pkg/k8s/state_into_spec_annotation.go
pkg/k8s/state_into_spec_annotation_test.go
scripts/generate-google3-docs/resource-reference/generated/resource-docs/compute/computeaddress.md
scripts/generate-google3-docs/resource-reference/main.go

Remove special handling for ComputeAddress about 'state-into-status' annotation

---

config/tests/samples/create/harness.go

nits from #1133

---

config/tests/samples/create/harness.go

When we close the controller-manager runtime, wait for it to actually
shutdown.
The shutdown is fairly slow, and otherwise it may reconnect to
kube-apiserver during shutdown.
(Aside: not sure if this kube-apiserver approach to shutdown is sound; it seems likely to
cause production issues)

tests: even more careful cleanup

---

pkg/test/resourcefixture/test_runner.go

This will enable us to split the execution by service.

tests: run tests grouped by GVK group

---

config/tests/samples/create/harness.go
mockgcp/common/httpmux/json.go
mockgcp/common/httpmux/mux.go
mockgcp/common/operations/http.go
mockgcp/common/operations/operations.go
mockgcp/mockresourcemanager/service.go
mockgcp/mockresourcemanager/tagkeys.go
pkg/test/http_recorder.go
pkg/test/resourcefixture/testdata/basic/tags/v1beta1/tagstagkey/tagkeybasic/_http.log
pkg/test/resourcefixture/testdata/basic/tags/v1beta1/tagstagkey/tagkeyproject/_http.log
pkg/test/resourcefixture/testdata/basic/tags/v1beta1/tagstagkey/tagkeyproject/create.yaml
tests/e2e/unified_test.go

mockgcp: add mock for TagsTagKey
Also improve our golden testing framework to support this use case.
Builds on #957

mockgcp: add mock for TagsTagKey

---

config/tests/samples/create/harness.go

Clean up the imports for config/tests/samples/create/harness.go as it imported duplicated packages.

Clean up the imports for sample harness.go

---

config/tests/samples/create/harness.go
mockgcp/mockcompute/disksv1.go
mockgcp/mockcompute/regiondisksv1.go
mockgcp/mockcompute/service.go

mockgcp: Implement ComputeDisk resource

---

.github/workflows/lint.yaml
.golangci.yaml
Makefile
config/tests/samples/create/samples.go
operator/pkg/controllers/utils.go
operator/pkg/logging/logging_test.go
pkg/cli/cmd/apply/yamlresource/yaml_to_unstructured_resource_test.go
pkg/cli/cmd/commonparams/commonparams.go
pkg/cli/stream/asset_to_unstructured_resource_stream_test.go
pkg/cluster/installation_identifier_test.go
pkg/controller/iam/iamclient/tfiamclient.go
pkg/controller/lifecyclehandler/handler.go
pkg/controller/lifecyclehandler/handler_test.go
pkg/controller/mocktests/harness.go
pkg/controller/resourcewatcher/resourcewatcher_test.go
pkg/crd/testutils/tesutils.go
pkg/dcl/kcclite/conversion_test.go
pkg/dcl/kcclite/templating_test.go
pkg/krmtotf/references_test.go
pkg/logging/logging_test.go
pkg/resourceoverrides/dns_record_set.go
pkg/test/main/testmain.go
pkg/tf/serialization/tf_resource_test.go
tests/e2e/unified_test.go

Branching off from https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1186. 
Commits mostly cherry-picked for errcheck with some fixup.

ci: stage golangci-lint, ci: add errcheck linter

---

config/tests/samples/create/harness.go

This avoids a lot of logspam and lets us better see what is actually
happening.

tests: Filter log messages

---

mockgcp/README.md

Update Mock GCP guide

---

README.NewResourceFromTerraform.md

Add a note on observedFields when adding a new resource

---

pkg/controller/lifecyclehandler/handler.go

Small follow up from the lint changes to log errors from recording events.

enh: log err to record event

---

.github/workflows/lint.yaml
.golangci.yaml
Makefile
README.UpdatingDCL.md

Updated linter to get past infinite recursion bug. 
Fix doc explaning the steps.
Added extended timeout to work around long running linter. 
Added exclusions to prevent problems showing up on DCL generation.
Fixes #

chore:lint upgrade golangci-lint

---

config/tests/servicemapping/servicemapping_test.go

test: ensure alpha resource is not referenced by stable resource

---

operator/scripts/update-kcc-manifest/manager_sidecar_patch.yaml
operator/scripts/update-kcc-manifest/recorder_sidecar_patch.yaml

versionbump: update prometheus-to-sd image

---

config/tests/samples/create/harness.go
pkg/test/utils.go
pkg/tf/serialization/testdata/cluster.golden.tf
pkg/tf/serialization/tf_resource_test.go

Our existing testing was not very strict.

tests: use golden testing framework for hcl tests

---

config/tests/samples/create/samples.go
tests/e2e/unified_test.go

basic smoke test for pause; this will fail until DCL controller also starts using the `actuationMode` field

test: basic golden test for pause

---

pkg/krmtotf/tftokrm.go

Fixes b/328854103
Test details can be found at #1343 .

Stop merging sensitive fields in SQLInstance and ComputeBackendService

---

third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/services/alloydb/resource_alloydb_cluster.go

Stop reading display_name in alloydb_cluster

---

config/tests/servicemapping/servicemapping_test.go
pkg/crd/crdgeneration/crdgeneration.go
pkg/dcl/metadata/metadata.go
pkg/dcl/metadata/metadata_test.go
pkg/k8s/constants.go
pkg/k8s/state_into_spec_annotation.go
pkg/test/resourcefixture/sets.go
scripts/resource-autogen/allowlist/allowlist.go

Updated the constant name for 'v1beta1' to be more readable. Context: https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1353#discussion_r1524114167.

Update the constant name for 'v1beta1' version

---

config/tests/servicemapping/servicemapping_test.go

Updated the servicemapping unit tests to ensure observed fields are 'spec' fields.
Also flattened some assertions to avoid additional checks.

Ensure observed fields are 'spec' fields

---

config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_secretmanagersecrets.secretmanager.cnrm.cloud.google.com.yaml
pkg/clients/generated/apis/secretmanager/v1beta1/secretmanagersecret_types.go
scripts/generate-google3-docs/resource-reference/generated/resource-docs/secretmanager/secretmanagersecret.md
third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/services/secretmanager/resource_secret_manager_secret.go

Remove deprecation warning since we are not going to deprecate this and we control the fork 😛 .
internal: b/326487555

docs: remove deprecation warning

---

docs/releasenotes/release-1.114.0.md
docs/releasenotes/release-1.115.0.md

Also stage the 1.115.0 release notes for on-the-fly contribution.

chore: Add release notes for 1.114.0

---

config/servicemappings/spanner.yaml
scripts/generate-google3-docs/resource-reference/generated/resource-docs/iam/iampartialpolicy.md
scripts/generate-google3-docs/resource-reference/generated/resource-docs/iam/iampolicy.md
scripts/generate-google3-docs/resource-reference/generated/resource-docs/iam/iampolicymember.md
scripts/generate-google3-docs/resource-reference/generated/resource-docs/spanner/spannerdatabase.md

Fixes #1317
Refactored the test framework a bit to enable the local testing in #1406 .

Enable IAM conditions in SpannerDatabase

---

scripts/generate-third-party-licenses/main.go

Fix license check

---

pkg/controller/registration/registration_controller.go

This would be surprising to users!

Don't use other reconcilers if direct reconciler was requested

---

CONTRIBUTING.md

Create a separate Setup Troubleshooting section.
Fixes #

chore: Update Contributing doc

---

.github/PULL_REQUEST_TEMPLATE.md

ci: update pull request template

---

pkg/krmtotf/resource.go

https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1403#discussion_r1537619483
`go test -timeout 1200s -v -tags=integration ./pkg/controller/dynamic/ -test.run TestCreateNoChangeUpdateDelete -run-tests pubsubtopic` passed

Return nil when observedState is not found in status

---

config/tests/samples/create/harness.go
config/tests/samples/create/samples.go
pkg/test/eventsink.go
tests/e2e/export.go
tests/e2e/httplog.go
tests/e2e/normalize.go
tests/e2e/script_test.go
tests/e2e/testdata/scenarios/README.md
tests/e2e/testdata/scenarios/ccc_state_into_spec_absent/_export1.yaml
tests/e2e/testdata/scenarios/ccc_state_into_spec_absent/_object00.yaml
tests/e2e/testdata/scenarios/ccc_state_into_spec_absent/_object01.yaml
tests/e2e/testdata/scenarios/ccc_state_into_spec_absent/script.yaml
tests/e2e/testdata/scenarios/ccc_state_into_spec_merge/_export1.yaml
tests/e2e/testdata/scenarios/ccc_state_into_spec_merge/_object00.yaml
tests/e2e/testdata/scenarios/ccc_state_into_spec_merge/_object01.yaml
tests/e2e/testdata/scenarios/ccc_state_into_spec_merge/script.yaml
tests/e2e/unified_test.go

Rebases #1366 and integrates by adding a small change to use DeleteResources without waiting.

chore: Add tests for CCC stateIntoSpec

---

config/tests/samples/create/harness.go
mockgcp/mockcompute/globalhealthcheckv1.go
mockgcp/mockcompute/regionalhealthcheckv1.go
mockgcp/mockcompute/service.go

mockgcp: Implement compute healthchecks

---

config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_accesscontextmanagerserviceperimeterresources.accesscontextmanager.cnrm.cloud.google.com.yaml
config/servicemappings/accesscontextmanager.yaml
pkg/clients/generated/apis/accesscontextmanager/v1beta1/accesscontextmanagerserviceperimeterresource_types.go
scripts/generate-google3-docs/resource-reference/generated/resource-docs/accesscontextmanager/accesscontextmanagerserviceperimeterresource.md

We try to use "Config Connector", not KCC in our docs.

chore: update product name in docstring

---

config/samples/resources/alloydbcluster/secondary-cluster/alloydb_v1beta1_alloydbcluster.yaml
config/samples/resources/alloydbcluster/secondary-cluster/iam_v1beta1_iampartialpolicy.yaml
config/samples/resources/alloydbcluster/secondary-cluster/kms_v1beta1_kmscryptokey.yaml
config/samples/resources/alloydbcluster/secondary-cluster/kms_v1beta1_kmskeyring.yaml
config/samples/resources/alloydbcluster/secondary-cluster/serviceusage_v1beta1_serviceidentity.yaml
scripts/generate-google3-docs/resource-reference/generated/resource-docs/alloydb/alloydbcluster.md

Add encryption to AlloyDB secondary cluster sample

---

.golangci.yaml
operator/scripts/copy-dependency-manifests/main.go
operator/scripts/update-kcc-manifest/main.go
scripts/client-gen/main.go
scripts/deepcopy-gen/main.go
scripts/generate-crds/main.go
scripts/generate-google3-docs/resource-lists/main.go
scripts/generate-google3-docs/resource-reference/main.go
scripts/parse-crds/parse-crds.go
scripts/resource-autogen/main.go
scripts/resource-autogen/servicemapping/embed/generated/main/assets_generate.go

chore:lint: Start linting golang file under scripts/

---

pkg/controller/iam/iamclient/iamclient_integration_test.go

We observed a test flake here against real GCP.

tests: add a retry for concurrent changes to setting iam policy

---

mockgcp/README.md

Small change to flash the changes for the fixup script in the guide so it sticks out for people like me 🤦🏼 .

docs: spell out additions to fixup script

---

mockgcp/mockmonitoring/dashboard.go
mockgcp/mockmonitoring/service.go

mockgcp: fix monitoring to use environment

---

config/samples/resources/containerattachedcluster/container-attached-cluster-basic/containerattached_v1beta1_containerattachedcluster.yaml
config/samples/resources/containerattachedcluster/container-attached-cluster-full/containerattached_v1beta1_containerattachedcluster.yaml
config/samples/resources/containerattachedcluster/container-attached-cluster-ignore-errors/containerattached_v1beta1_containerattachedcluster.yaml
scripts/generate-google3-docs/resource-reference/generated/resource-docs/containerattached/containerattachedcluster.md

Fix sample yaml

---

config/tests/samples/create/harness.go
config/tests/samples/create/samples.go
mockgcp/mockresourcemanager/service.go
mockgcp/mockresourcemanager/tagkeys.go
mockgcp/mockresourcemanager/tagvalues.go
pkg/test/resourcefixture/testdata/basic/tags/v1beta1/tagstagkey/tagkeyprojectbasic/_http.log
pkg/test/resourcefixture/testdata/basic/tags/v1beta1/tagstagvalue/tagvalueproject/_http.log
pkg/test/resourcefixture/testdata/basic/tags/v1beta1/tagstagvalue/tagvalueproject/create.yaml
pkg/test/resourcefixture/testdata/basic/tags/v1beta1/tagstagvalue/tagvalueproject/dependencies.yaml
tests/e2e/unified_test.go

- mockgcp: Implement TagsTagValue
- tests: run deletion in order when we're doing golden testing
Note that we also enforce strict deletion ordering when doing golden testing, so that the http log is consistent.

mockgcp: Add support for TagsTagValue

---

tests/e2e/unified_test.go

We would like to fail fast on individual tests; with our mocks no test
should take very long.

tests: try introducing a subtest timeout to unified_test

---

OWNERS

Working particularly on compositions - welcome!

Add barney-s to OWNERS

---

experiments/compositions/Design Notes/API Design.md
experiments/compositions/Design Notes/Architecture.md
experiments/compositions/Design Notes/Feedback.md
experiments/compositions/composition/internal/controller/expander_applier.go

Cleanup. Replace instances of charlie with Platform Admin and variants

replace instances of charlie with Platform Admin and variants

---

pkg/test/http_recorder.go

Should help us understand what's going on here.

tests: log error if we fail to read response

---

scripts/generate-google3-docs/resource-reference/generated/resource-docs/dns/dnsrecordset.md

Generate doc for DNS

---

pkg/test/controller/reconciler/testreconciler.go

Our dynamic tests actually test that the jitter generator reconciles after a mean determined amount:
https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/59a3462509b854bbb98ae0bfa47d9044cf1b4d3c/pkg/test/controller/reconciler/testreconciler.go#L234-L243
So let's use an actual jitter generator for dynamic tests! I've not seen evidence that the samples tests need an actual jitter generator yet.
-----
Tested with a `logmetric` resource.
Before change:
```bash
$ ENV_VARS=REDCATED go test -v -tags=integration ./pkg/controller/dynamic/ -timeout 1600s -test.count=1 -test.run TestCreateNoChangeUpdateDelete -run-tests linearlogmetric 2>&1
...
dynamic_controller_integration_test.go:223: reconcile for LoggingLogMetric:xh5kfipx3ys3fzor5t5q/logginglogmetric-xh5kfipx3ys3fzor5t5q took …
```

fix:tests: use actual jitter generator

---

OWNERS

Add @jiefenghe as a OWNER to help with Compositions.
Welcome @jiefenghe

add  jiefenghe to OWNERS

---

tests/README.VCRTesting.md

Add readme for vcr and share example commands.

vcr: Add README for vcr testing

---

.github/workflows/presubmit.yaml
operator/Makefile
scripts/github-actions/ga-unit-test.sh
scripts/unit-test.sh

enh: Use gotestsum to provide better unit test output

---

mockgcp/mockiam/serviceaccounts.go
pkg/test/resourcefixture/testdata/basic/iam/v1beta1/iamserviceaccount/_http.log

- mockgcp: update IAMServiceAccount mock for more fidelity
- tests: update golden output for iamserviceaccount test

mockgcp: update IAMServiceAccount mock for more fidelity

---

pkg/test/utils.go

WRITE_GOLDEN_OUTPUT should always write the updated output, for use
with e.g. `git diff`

tests: CompareGoldenObject should follow the golden output pattern

---

mockgcp/mockmonitoring/dashboard.go
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/_http.log

- mockgcp: add golden output for monitoringdashboard
- mockgcp: update with latest monitoring protos
- mockgcp: Customizable formatting for errors
- mockgcp: fix a few inaccuracies in MonitoringDashboard mock

mockgcp: update MonitoringDashboard

---

pkg/controller/direct/logging/logmetric_controller.go
scripts/github-actions/tests-e2e-direct.sh
tests/e2e/httplog.go
tests/e2e/script_test.go
tests/e2e/testdata/scenarios/direct/llm_set_unset/SCENARIO_README.MD
tests/e2e/testdata/scenarios/direct/llm_set_unset/basic/_http00.log
tests/e2e/testdata/scenarios/direct/llm_set_unset/basic/_http01.log
tests/e2e/testdata/scenarios/direct/llm_set_unset/basic/_http02.log
tests/e2e/testdata/scenarios/direct/llm_set_unset/basic/_object00.yaml
tests/e2e/testdata/scenarios/direct/llm_set_unset/basic/_object01.yaml
tests/e2e/testdata/scenarios/direct/llm_set_unset/basic/_object02.yaml
tests/e2e/testdata/scenarios/direct/llm_set_unset/basic/script.yaml
tests/e2e/testdata/scenarios/direct/llm_set_unset/metric_descriptor/_http00.log
tests/e2e/testdata/scenarios/direct/llm_set_unset/metric_descriptor/_http01.log
tests/e2e/testdata/scenarios/direct/llm_set_unset/metric_descriptor/_http02.log
tests/e2e/testdata/scenarios/direct/llm_set_unset/metric_descriptor/_object00.yaml
tests/e2e/testdata/scenarios/direct/llm_set_unset/metric_descriptor/_object01.yaml
tests/e2e/testdata/scenarios/direct/llm_set_unset/metric_descriptor/_object02.yaml
tests/e2e/testdata/scenarios/direct/llm_set_unset/metric_descriptor/script.yaml

Adding step based testing for logMetric. Checking both the DCL results and direct results.

tests: set/unset scenarios for logMetric 

---

.gitignore

Ignore record_gcp artifact

---

scripts/generate-google3-docs/resource-reference/generated/resource-docs/vertexai/vertexaiendpoint.md
scripts/generate-google3-docs/resource-reference/templates/vertexai_vertexaiendpoint.tmpl

doc: fix resource type for vertex AI endpoint

---

config/tests/samples/create/samples_test.go

Small patch adds a context plumbed through for the samples tests setup.

tests: plumb context in samples

---

experiments/compositions/composition/internal/controller/expander_reconciler.go
experiments/compositions/composition/pkg/containerexecutor/jobcontainerexecutor/jobcontainerrunner.go
experiments/compositions/composition/release/cc/operator.yaml
experiments/compositions/composition/release/crds.yaml
experiments/compositions/composition/release/kind/operator.yaml
experiments/compositions/composition/tests/data/TestSimpleCompositionAddFacadeField/input.yaml
experiments/compositions/composition/tests/data/TestSimpleCompositionCreate/input.yaml
experiments/compositions/composition/tests/data/TestSimpleCompositionDeleteFacade/input.yaml
experiments/compositions/composition/tests/data/TestSimpleCompositionDeleteFacadeField/input.yaml
experiments/compositions/composition/tests/data/TestSimpleCompositionExpansion/input.yaml
experiments/compositions/composition/tests/data/TestSimpleCompositionStatusFacadeCRDMissing/input.yaml
experiments/compositions/composition/tests/data/TestSimpleCompositionStatusValidation/fixed_composition.yaml
experiments/compositions/composition/tests/data/TestSimpleCompositionStatusValidation/input.yaml
experiments/compositions/composition/tests/data/TestSimpleFacadeByoSchema/input.yaml
experiments/compositions/composition/tests/data/TestSimpleNamespaceExplicit/input.yaml
experiments/compositions/composition/tests/data/TestSimpleNamespaceInherit/input.yaml
experiments/compositions/composition/tests/data/TestSimplePlanStatusErrorExpansionFailed/composition_fixed.yaml
experiments/compositions/composition/tests/data/TestSimplePlanStatusErrorExpansionFailed/input.yaml
experiments/compositions/composition/tests/data/TestSimplePlanStatusErrorFailedApplyingManifests/composition_fixed.yaml
experiments/compositions/composition/tests/data/TestSimplePlanStatusErrorFailedApplyingManifests/input.yaml
experiments/compositions/composition/tests/data/TestSimplePlanStatusErrorFailedLoadingManifestsFromPlan/composition_fixed.yaml
experiments/compositions/composition/tests/data/TestSimplePlanStatusErrorFailedLoadingManifestsFromPlan/input.yaml
experiments/compositions/composition/tests/data/TestSimplePlanStatusWaitingForValues/input.yaml
experiments/compositions/samples/AppTeam/composition/appteam.yaml
experiments/compositions/samples/AttachedAKS/01-composition.yaml
experiments/compositions/samples/AttachedEKS/01-composition.yaml
experiments/compositions/samples/CloudSQL/composition/hasql.yaml

feat: add the expander version field
Run `make e2e-test`

Add the expander version field.

---

pkg/test/resourcefixture/testdata/basic/iam/v1beta1/iamserviceaccount/_http.log
tests/e2e/unified_test.go

- tests: don't record duplicate GETs in golden log
- tests: update golden output for iamserviceaccount test

tests: ignore duplicated GET requests

---

operator/pkg/test/controller/customization.go
operator/pkg/test/controller/manifest.go

Make sure we are on latest prom-to-sd image even on our tests.

Upgrade to v0.11.12-gke.11

---

mockgcp/mockaiplatform/dataset.go
pkg/test/resourcefixture/testdata/basic/vertexai/v1beta1/vertexaidataset/vertexaidatasetbasic/_generated_object_vertexaidatasetbasic.golden.yaml
pkg/test/resourcefixture/testdata/basic/vertexai/v1beta1/vertexaidataset/vertexaidatasetbasic/_http.log
tests/e2e/normalize.go
tests/e2e/unified_test.go

Also a few tweaks to the mock to better match real-GCP

tests: more normalization for vertexaidataset tests

---

OWNERS

Add Yuwen and Jason to OWNER file

---

experiments/compositions/composition/api/v1alpha1/expanderversion_types.go
experiments/compositions/composition/config/crd/bases/composition.google.com_expanderversions.yaml
experiments/compositions/composition/go.mod
experiments/compositions/composition/go.sum
experiments/compositions/composition/internal/controller/expander_reconciler.go
experiments/compositions/composition/release/crds.yaml
experiments/compositions/composition/release/kind/jinja2_expander_version.yaml
experiments/compositions/composition/release/kind/operator.yaml
experiments/compositions/composition/tests/cluster/cluster.go
experiments/compositions/composition/tests/data/TestSimpleCompositionAddFacadeField/input.yaml
experiments/compositions/composition/tests/data/TestSimpleCompositionCreate/input.yaml
experiments/compositions/composition/tests/data/TestSimpleCompositionDeleteFacadeField/input.yaml
experiments/compositions/composition/tests/data/TestSimpleCompositionExpansion/input.yaml
experiments/compositions/composition/tests/testcases/main_test.go

Feat:Add default version selection for composition expanders.

---

tests/e2e/testdata/scenarios/direct/llm_custom_diff/value_type/SCENARIO_README.md
tests/e2e/testdata/scenarios/direct/llm_custom_diff/value_type/label/_http00.log
tests/e2e/testdata/scenarios/direct/llm_custom_diff/value_type/label/_http01.log
tests/e2e/testdata/scenarios/direct/llm_custom_diff/value_type/label/_object00.yaml
tests/e2e/testdata/scenarios/direct/llm_custom_diff/value_type/label/_object01.yaml
tests/e2e/testdata/scenarios/direct/llm_custom_diff/value_type/label/script.yaml
tests/e2e/testdata/scenarios/direct/llm_custom_diff/value_type/metric_descriptor/_http00.log
tests/e2e/testdata/scenarios/direct/llm_custom_diff/value_type/metric_descriptor/_http01.log
tests/e2e/testdata/scenarios/direct/llm_custom_diff/value_type/metric_descriptor/_object00.yaml
tests/e2e/testdata/scenarios/direct/llm_custom_diff/value_type/metric_descriptor/_object01.yaml
tests/e2e/testdata/scenarios/direct/llm_custom_diff/value_type/metric_descriptor/script.yaml

Captured with:
```bash
$ WRITE_GOLDEN_OUTPUT=1 GOLDEN_REQUEST_CHECKS=1 \
E2E_KUBE_TARGET=envtest E2E_GCP_TARGET=mock RUN_E2E=1 \
go test -test.count=1 -timeout 360s -v ./tests/e2e -run TestE2EScript/scenarios/direct/custom_diff 2>&1 
```

tests: custom diff checks for llms

---

scripts/crd-tools/cmd/deleteannotation/deleteannotation.go
scripts/crd-tools/cmd/deletefield/deletefield.go
scripts/crd-tools/cmd/setannotation/setannotation.go
scripts/crd-tools/cmd/setfield/setfield.go
scripts/crd-tools/main.go
scripts/crd-tools/pkg/objectvisitor/objectvisitor.go

A bunch of highly-specialized commands to sync-up the CRD generation.

chore: create tool for crd manipulation

---

pkg/controller/direct/logging/logmetric_controller.go
pkg/controller/direct/logging/utils.go
pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/logbucketmetric/create.yaml
pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/logbucketmetric/dependencies.yaml

Start using the LoggingLogBucketRef!

feat: use LoggingLogBucketRef

---

pkg/controller/direct/apikeys/apikeyskey_controller.go
pkg/controller/direct/directbase/directbase_controller.go
pkg/controller/direct/directbase/interfaces.go
pkg/controller/direct/logging/logmetric_controller.go
pkg/controller/direct/resourcemanager/tagkey_controller.go

This will allow for resolving references to other objects.

chore: refactor direct controller interface to pass client.Reader

---

pkg/controller/direct/logging/logmetric_controller.go

A few PRs crossed with incompatible changes.

chore: fix merge conflict in LoggingLogMetric direct controller

---

pkg/controller/direct/logging/logmetric_controller.go
pkg/controller/direct/logging/projectref.go

- **chore: refactor direct controller interface to pass client.Reader**
- **feat: resolve project in direct controller for LoggingLogMetric**

Resolve project references in LoggingLogMetric

---

.github/workflows/presubmit.yaml
Makefile
operator/Makefile

Fixes upset presubmit I think.

chore:ci:fix: concurrency stanza

---

OWNERS

Adding xiaoweim as owner to help with reviews.

Add xiaoweim as approver

---

.github/workflows/presubmit.yaml

Exclude experiments/** from presubmits
We will soon be adding tests targeting experiments only.

Exclude experiments/ from presubmits

---

pkg/controller/direct/logging/utils.go
pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/explicitlogmetric/_generated_object_explicitlogmetric.golden.yaml
pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/explicitlogmetric/_http.log
pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/exponentiallogmetric/_generated_object_exponentiallogmetric.golden.yaml
pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/exponentiallogmetric/_http.log
pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/linearlogmetric/_http.log
scripts/github-actions/tests-e2e-direct.sh

It looks like a server-generated field, and should not be the same as
displayName.

fix: LoggingLogMetric - don't pass metricDescriptor.name

---

pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbcluster/basicalloydbcluster/_generated_object_basicalloydbcluster.golden.yaml
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbcluster/basicalloydbcluster/_http.log
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbcluster/basicalloydbcluster/create.yaml
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbcluster/basicalloydbcluster/update.yaml

Change location for basicalloydbcluster test

Change location for basicalloydbcluster test

---

.github/workflows/presubmit-compositions.yaml
experiments/compositions/composition/Makefile
experiments/compositions/composition/tests/data/TestSimpleExpanderInvalid/input.yaml
experiments/compositions/composition/tests/data/TestSimpleExpanderVersionInvalid/input.yaml
experiments/compositions/composition/tests/scenario/scenario.go
experiments/compositions/composition/tests/testcases/kcc_samples_test.go
experiments/compositions/composition/tests/testcases/simple_test.go
experiments/compositions/scripts/github-actions/e2e-test.sh
experiments/compositions/scripts/github-actions/jinja2-test.sh

Add presubmits for compositions.
- Add github action targetting experiments/**
- Run tests for jinja expander
- Run e2e tests
- fix test data in compositions to trigger tests
- increase timeouts for reducing flakes

Add presubmits for compositions

---

pkg/controller/direct/gkehub/acmconversion.go
pkg/controller/direct/gkehub/client.go
pkg/controller/direct/gkehub/featuremembership_controller.go
pkg/controller/direct/gkehub/mappings.go
pkg/controller/direct/gkehub/meshconversion.go
pkg/controller/direct/gkehub/pococonversion.go
pkg/controller/direct/gkehub/util.go

Add the direct controller for gkehubfeaturemembership

Add basic gkehubfeaturemembership direct controller

---

pkg/controller/direct/gkehub/featuremembership_controller.go

Additions for interface changes

refactor: interface changes for fm contlr

---

config/tests/samples/create/harness.go
mockgcp/mockalloydb/cluster.go
mockgcp/mockalloydb/instance.go
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbinstance/basicalloydbinstance/_generated_object_basicalloydbinstance.golden.yaml
tests/e2e/normalize.go

- Add mockgcp for AlloyDBInstance.
- Add mock CreateSecondary method for AlloyDBCluster

Add mockgcp for AlloyDB instance

---

config/tests/samples/create/harness.go
pkg/cli/cmd/bulkexport/singleresourceiamclient/singleresourceiamclient.go
pkg/cli/cmd/export/outputstream/outputstream.go
pkg/cli/cmd/export/parameters/parameters.go
pkg/cli/stream/url_to_unstructured_resource_stream.go
pkg/cli/stream/url_to_unstructured_resource_stream_test.go
pkg/controller/direct/logging/logmetric_controller.go
pkg/controller/direct/logging/utils.go
pkg/controller/direct/registry.go
pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/explicitlogmetric/_generated_export_explicitlogmetric.golden
pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/explicitlogmetric/_http.log
pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/exponentiallogmetric/_generated_export_exponentiallogmetric.golden
pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/exponentiallogmetric/_http.log
pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/linearlogmetric/_generated_export_linearlogmetric.golden
pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/linearlogmetric/_http.log
tests/e2e/export.go
tests/e2e/testdata/scenarios/direct/llm_set_unset/basic/_export0.yaml
tests/e2e/testdata/scenarios/direct/llm_set_unset/basic/_export1.yaml
tests/e2e/testdata/scenarios/direct/llm_set_unset/basic/_export2.yaml
tests/e2e/testdata/scenarios/direct/llm_set_unset/metric_descriptor/_export0.yaml
tests/e2e/testdata/scenarios/direct/llm_set_unset/metric_descriptor/_export1.yaml
tests/e2e/testdata/scenarios/direct/llm_set_unset/metric_descriptor/_export2.yaml

Wiring up support for our direct controllers here.

feat: support export of LoggingLogMetric

---

config/tests/samples/create/samples.go

A step in running samples more like fixtures.

chore: Add SourceDir to samples

---

pkg/controller/direct/gkehub/mappings.go

Fix resource conversion to guard nil pointers

---

pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbbackup/basicalloydbbackup/create.yaml
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbbackup/basicalloydbbackup/dependencies.yaml

Fix the test failure introduced in #1739 
Local test passed:
```
--- PASS: TestCreateNoChangeUpdateDelete (0.12s)
--- PASS: TestCreateNoChangeUpdateDelete/alloydb (0.00s)
--- PASS: TestCreateNoChangeUpdateDelete/alloydb/basic-basicalloydbbackup (978.34s)
PASS
{"severity":"info","timestamp":"2024-05-21T22:48:44.019Z","msg":"Stopping and waiting for non leader election runnables"}
{"severity":"info","timestamp":"2024-05-21T22:48:44.019Z","msg":"Stopping and waiting for leader election runnables"}
{"severity":"info","timestamp":"2024-05-21T22:48:44.019Z","msg":"Stopping and waiting for caches"}
{"severity":"info","timestamp":"2024-05-21T22:48:44.019Z","msg":"Stopping and waiting for webhooks"}
{"severity":"info","timestamp":"2024-05-21T22:48:44.019Z","logger":"controller-runtime.webhook","msg …
```

tests: Fix basicalloydbbackup dynamic test

---

tests/e2e/httplog.go
tests/e2e/testdata/scenarios/direct/llm_immutable_field/labels_value_type/SCENARIO_README.MD
tests/e2e/testdata/scenarios/direct/llm_immutable_field/labels_value_type/_http00.log
tests/e2e/testdata/scenarios/direct/llm_immutable_field/labels_value_type/_http01.log
tests/e2e/testdata/scenarios/direct/llm_immutable_field/labels_value_type/_object01.yaml
tests/e2e/testdata/scenarios/direct/llm_immutable_field/metric_kind_and_value_type/SCENARIO_README.MD
tests/e2e/testdata/scenarios/direct/llm_immutable_field/metric_kind_and_value_type/_http00.log
tests/e2e/testdata/scenarios/direct/llm_immutable_field/metric_kind_and_value_type/_http01.log

tests: Update llm_immutable_field test http log and exported object

---

dev/tools/proto-to-mapper/.gitignore
dev/tools/proto-to-mapper/Makefile
dev/tools/proto-to-mapper/gocode/ast.go
dev/tools/proto-to-mapper/main.go
dev/tools/proto-to-mapper/notes.md

A first-pass at a tool to generate types & map functions.

chore: Tool to generate mapping functions from proto

---

pkg/controller/direct/gkehub/mappings.go

fix: fm controller mapping

---

pkg/controller/direct/gkehub/featuremembership_controller.go
pkg/controller/direct/logging/logbucketref.go
pkg/controller/direct/logging/logmetric_controller.go
pkg/controller/direct/references/projectref.go
pkg/controller/direct/utils/projectref.go

Resolve project Ref for hub controller

Resolve projectRef for the FM direct controller

---

CONTRIBUTING.md
README.ChangingTerraform.md

Fixes confusing steps in CONTRIBUTING.md and README.ChangingTerraform.md.

Update the contribution guide

---

config/tests/samples/create/harness.go
pkg/cli/cmd/root.go
pkg/cli/powertools/changestateintospec/cmd.go
pkg/cli/powertools/cmd.go
pkg/cli/powertools/forcesetfield/cmd.go
pkg/cli/powertools/kubecli/client.go
pkg/cli/powertools/kubecli/options.go
pkg/stateintospec/remove.go
tests/e2e/export.go
tests/e2e/normalize.go
tests/e2e/script_test.go
tests/e2e/testdata/scenarios/README.md
tests/e2e/testdata/scenarios/clear_state_into_spec/_cli-2-stderr.log
tests/e2e/testdata/scenarios/clear_state_into_spec/_cli-2-stdout.log
tests/e2e/testdata/scenarios/clear_state_into_spec/_http00.log
tests/e2e/testdata/scenarios/clear_state_into_spec/_http01.log
tests/e2e/testdata/scenarios/clear_state_into_spec/_object00.yaml
tests/e2e/testdata/scenarios/clear_state_into_spec/_object01.yaml
tests/e2e/testdata/scenarios/clear_state_into_spec/_object03.yaml
tests/e2e/testdata/scenarios/clear_state_into_spec/script.yaml
tests/e2e/testdata/scenarios/powertool_set_bucket_location/_cli-1-stdout.log
tests/e2e/testdata/scenarios/powertool_set_bucket_location/_http00.log
tests/e2e/testdata/scenarios/powertool_set_bucket_location/_object00.yaml
tests/e2e/testdata/scenarios/powertool_set_bucket_location/_object02.yaml
tests/e2e/testdata/scenarios/powertool_set_bucket_location/script.yaml
tests/e2e/unified_test.go

This PR is basically #1646 with the changes to fix the conflicts.
N/A

Powertool to update state-into-spec value

---

dev/ci/postsubmits/release-kcc-cli
dev/tasks/build-cli-bundle

- **chore: generate license metadata**
- **chore: create script to build KCC CLI**

chore: create script to build KCC CLI

---

mockgcp/mockalloydb/names.go
pkg/controller/direct/alloydb/client.go
pkg/controller/direct/alloydb/cluster_controller.go
pkg/controller/direct/alloydb/mapping.go
pkg/controller/direct/alloydb/maputils.go
pkg/controller/direct/alloydb/utils.go
pkg/controller/registration/registration_controller.go

feat: scifi: Direct controller for Alloy DB Cluster

---

mockgcp/Makefile

chore: remove downloaded openapi json after proto generation in mockgcp makefile

---

pkg/controller/direct/apikeys/apikeyskey_controller.go
pkg/controller/direct/directbase/directbase_controller.go
pkg/controller/direct/logging/logmetric_controller.go
pkg/controller/direct/registry.go
pkg/controller/direct/resourcemanager/tagkey_controller.go
pkg/controller/registration/registration_controller.go
pkg/test/controller/reconciler/testreconciler.go
pkg/test/resourcefixture/contexts/register.go

follow up on https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1910, resolve comments.

chore: register direct controller from crd annotation (part 2)

---

pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/logmetricprojectref/_generated_object_logmetricprojectref.golden.yaml
pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/logmetricprojectref/_http.log
pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/logmetricprojectref/create.yaml
pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/logmetricprojectref/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/logmetricprojectref/update.yaml

Demonstrates the regression around kind being required.

tests: create test of LoggingLogMetric projectRef

---

apis/monitoring/v1beta1/monitoringdashboard_types.go
apis/refs/v1beta1/projectref.go
apis/resources/logging/v1beta1/logmetric_types.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_apikeyskeys.apikeys.cnrm.cloud.google.com.yaml
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_logginglogmetrics.logging.cnrm.cloud.google.com.yaml
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_monitoringdashboards.monitoring.cnrm.cloud.google.com.yaml
pkg/controller/direct/gkehub/featuremembership_controller.go
pkg/controller/direct/logging/logbucketref.go
pkg/controller/direct/logging/utils.go
pkg/controller/direct/references/projectref.go
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardrefs/_generated_object_monitoringdashboardrefs.golden.yaml
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardrefs/_http.log
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardrefs/create.yaml
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardrefs/update.yaml
scripts/add-validation-to-crds/parse-crds.go
scripts/generate-google3-docs/resource-reference/generated/resource-docs/logging/logginglogmetric.md
scripts/generate-google3-docs/resource-reference/generated/resource-docs/monitoring/monitoringdashboard.md

This regression was introduced because we reused the ResourceRef type.

LoggingLogMetric - kind should not be require in projectRef

---

experiments/compositions/composition/release/crds.yaml
experiments/compositions/composition/release/manifest.yaml

Update release manifests

---

pkg/controller/kccmanager/kccmanager.go
pkg/controller/ratelimiter/ratelimiter.go

Bump client-side rate limit to 80. 

---

build/builder/Dockerfile
build/tooling/Dockerfile
dev/codebots/update-golang-version
experiments/composite/go.mod
experiments/compositions/composition/Dockerfile
experiments/compositions/composition/Dockerfile.getter.expander
experiments/compositions/composition/Dockerfile.inline
experiments/compositions/composition/Dockerfile.jinja2.expander
experiments/compositions/composition/go.mod
experiments/compositions/facade/Dockerfile
experiments/compositions/facade/go.mod
go.mod
mockgcp/go.mod
operator/Dockerfile

- **chore: add script to update golang version**
- **versionbump: update to golang 1.22.4**

Add script to update golang; bump to 1.22.4

---

mockgcp/mockcompute/networksv1.go
mockgcp/mockcompute/operations.go
mockgcp/mockcompute/service.go
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computenetwork/_generated_object_computenetwork.golden.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computenetwork/_http.log
tests/e2e/normalize.go
tests/e2e/script_test.go
tests/e2e/unified_test.go

- tests: capture golden output for ComputeNetwork
- mockgcp: improve fidelity of ComputeNetwork mock

mockgcp: improve fidelity of ComputeNetwork mock

---

mockgcp/tools/gapic/pkg/sorted/map.go

Looks like two PRs both added the same Get method to Map.

fix: remove duplicate method

---

pkg/test/http_recorder.go
pkg/test/resourcefixture/testdata/basic/cloudbuild/v1alpha1/cloudbuildworkerpool/_http.log

chore: make mock test RemoveHeader be case insensitive

---

pkg/controller/direct/gkehub/featuremembership_controller.go
pkg/controller/direct/gkehub/references.go
pkg/webhook/immutable_fields_validator.go
pkg/webhook/immutable_fields_validator_test.go

Resolve memebership and feature refs 

---

pkg/webhook/immutable_fields_validator.go
pkg/webhook/immutable_fields_validator_test.go

Added immutability checks for gkehubfeaturemembership resource.
The check is done only in the webhook instead of in the direct controller and should reject any mutations and is sufficient.
The immutable fields are featureRef, membershipRef, projectRef, location and membershipLocation.
They are used as references and we can't validate changes on references in the controller.
More thoughts on this:
During each update, the base controller creates a fresh adapter to use the updated value for the desired state see [link](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/11789529f889361430df67c04401c95346ca9f55/pkg/controller/direct/directbase/directbase_controller.go#L270) and then refresh the actual state in [Find](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob …

Add immutability check for hubfeaturemembership

---

CONTRIBUTING.md

This fixes errors returned by the immutable fields validating webhook encountered when creating resources using a local controller manager:
```
annotation cnrm.cloud.google.com/state-into-spec is immutable
```
In order to pass the validating webhook, the local controller manager must use the cnrm-controller-manager service account credentials (instead of local user credentials) when making requests that modify resource annotations.
- [n/a] Perform necessary E2E testing for changed resources.

fix: Update contributing guide for running locally

---

dev/ci/postsubmits/release-kcc-images

chore: Always create ARTIFACTS dir in CI, if set

---

apis/cloudbuild/v1alpha1/workerpool_types.go
apis/cloudbuild/v1alpha1/zz_generated.deepcopy.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_cloudbuildworkerpools.cloudbuild.cnrm.cloud.google.com.yaml
pkg/clients/generated/apis/cloudbuild/v1alpha1/cloudbuildworkerpool_types.go
pkg/clients/generated/apis/cloudbuild/v1alpha1/zz_generated.deepcopy.go

Follow up PR to resolve comment in https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1920#discussion_r1630762649
Change the field `status.NetworkConfig` from required to optional.

chore: change CBWP required status field to optional

---

pkg/test/http_recorder.go

Follow up PR to resolve comments in #1979.

chore: add methods for mock http record `Header`

---

mockgcp/mockcompute/operations.go
mockgcp/mockcompute/subnetsv1.go
mockgcp/mockcompute/utils.go
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computesubnetwork/_generated_object_computesubnetwork.golden.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computesubnetwork/_http.log
tests/e2e/normalize.go
tests/e2e/unified_test.go

- **tests: capture golden output for computesubnetwork test**
- **mockgcp: improve ComputeSubnetwork fidelity**
- **tests: allowSubnetCidrRoutesOverlap not yet available in googleapis**

mockgcp: improve ComputeSubnetwork fidelity

---

mockgcp/mockcompute/service.go

We hit some self-recursion in a test, this structure is much simpler.

chore: simplify compute mux handler

---

pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbcluster/fullalloydbcluster/_generated_object_fullalloydbcluster.golden.yaml
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbcluster/fullalloydbcluster/_http.log
tests/e2e/unified_test.go

Generate golden log for fullalloydbcluster and normalize logic for alloydb

Generate golden log/object fullalloydbcluster test

---

scripts/generate-google3-docs/resource-reference/generated/resource-docs/logging/logginglogmetric.md
scripts/generate-google3-docs/resource-reference/templates/logging_logginglogmetric.tmpl

Addressed the comment in #2000 and replaced the hard-coded keywords.

Clarify the K8s object is SoT for LLM in 1.118.1

---

config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_monitoringdashboards.monitoring.cnrm.cloud.google.com.yaml
pkg/clients/generated/apis/monitoring/v1beta1/monitoringdashboard_types.go
scripts/generate-google3-docs/resource-reference/generated/resource-docs/monitoring/monitoringdashboard.md

Seem to have some diff / errors from monitoringdashboard in presubmit. Ran `make ready-pr` to fix.
- [n/a] Perform necessary E2E testing for changed resources.

fix: make ready-pr

---

pkg/test/utils.go

These merged because the PR was super-old (and maybe a prow bug also?)

chore: Fix some linter issues

---

experiments/compositions/samples/FirstComposition/README.md
experiments/compositions/samples/FirstComposition/composition/teampage.yaml

for the user guide, add a simple webserver with static page as an example

Add a simple First Composition example

---

experiments/compositions/samples/FirstGCPComposition/README.md
experiments/compositions/samples/FirstGCPComposition/composition/cors-bucket.yaml

Adding a simple GCP example that creates a storage bucket

Adding a simple GCP example that creates a storage bucket

---

docs/releasenotes/release-1.119.md
docs/releasenotes/release-1.120.md
docs/releasenotes/release-1.121.md

doc: Add release note for v1.119.0

---

pkg/controller/direct/gkehub/acmconversion.go
pkg/controller/direct/gkehub/featuremembership_controller.go
pkg/controller/direct/gkehub/mappings.go
pkg/controller/direct/gkehub/meshconversion.go
pkg/controller/direct/gkehub/pococonversion.go
pkg/controller/direct/gkehub/references.go

Support IAM references in the controller

---

experiments/compositions/samples/AttachedAKS/01-composition.yaml
experiments/compositions/samples/AttachedAKS/03-attached-1.yaml
experiments/compositions/samples/AttachedAKS/aks-charlie.sh
experiments/compositions/samples/AttachedEKS/01-composition.yaml
experiments/compositions/samples/AttachedEKS/03-attached-1.yaml
experiments/compositions/samples/AttachedEKS/eks-charlie.sh

Change the composition samples for the new format. 
Manually tested

Change the samples for the new composition format

---

mockgcp/mockmonitoring/dashboard.go
pkg/controller/direct/export.go
pkg/controller/direct/monitoring/maputils.go
pkg/controller/direct/monitoring/monitoringdashboard_controller.go
pkg/controller/direct/registry/registry.go
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardbasic/_generated_export_monitoringdashboardbasic.golden
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardbasic/create.yaml
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardbasic/update.yaml
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardfull/_generated_export_monitoringdashboardfull.golden
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardfull/_generated_object_monitoringdashboardfull.golden.yaml
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardfull/_http.log
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardfull/create.yaml
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardrefs/_generated_export_monitoringdashboardrefs.golden
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardrefs/_generated_object_monitoringdashboardrefs.golden.yaml
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardrefs/_http.log
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardrefs/create.yaml
tests/e2e/export.go

- **feat: Add support for export to MonitoringDashboard direct actuation**
- **chore: testdata for MonitoringDashboard including export**

feat: Add support for export to MonitoringDashboard direct actuation

---

apis/gkehub/v1beta1/gkehubfeaturemembership_types.go
apis/gkehub/v1beta1/zz_generated.deepcopy.go
apis/refs/v1beta1/gcpserviceaccountref.go
pkg/controller/direct/gkehub/featuremembership_controller.go
pkg/controller/direct/gkehub/references.go

This makes it easier to consume.

refactor: move IAMServiceAccount reference resolution into API package

---

experiments/compositions/samples/AttachedAKS/01-composition.yaml
experiments/compositions/samples/AttachedAKS/aks-alice.sh
experiments/compositions/samples/AttachedEKS/eks-alice.sh

Change the composition samples to make them up to date.
Manual test

Update the composition samples

---

experiments/compositions/samples/AttachedAKS/01-composition.yaml
experiments/compositions/samples/AttachedAKS/02-context.yaml
experiments/compositions/samples/AttachedAKS/setup-Azure-ASO.md
experiments/compositions/samples/AttachedEKS/01-composition.yaml
experiments/compositions/samples/AttachedEKS/03-attached-1.yaml
experiments/compositions/samples/AttachedEKS/setup-AWS-ACK.md

Update the samples for composition
manually tested

Update composition samples

---

experiments/compositions/samples/AttachedAKS/aks-charlie.sh
experiments/compositions/samples/AttachedEKS/02-context.yaml
experiments/compositions/samples/AttachedEKS/eks-charlie.sh

Fix composition sample error

---

config/tests/samples/create/harness.go
mockgcp/mockmonitoring/dashboard.go
mockgcp/mockmonitoring/fieldmaskutils.go
mockgcp/mockmonitoring/service.go
mockgcp/mockmonitoring/uptimecheck.go
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/_http.log
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringuptimecheckconfig/httpuptimecheckconfig/_generated_object_httpuptimecheckconfig.golden.yaml
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringuptimecheckconfig/httpuptimecheckconfig/_http.log
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringuptimecheckconfig/httpuptimecheckconfig/update.yaml
tests/e2e/normalize.go
tests/e2e/unified_test.go

Introduce a fieldmask helper also.

mockgcp: support MonitoringUptimeCheckConfig

---

apis/monitoring/v1beta1/monitoringdashboard_types.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_monitoringdashboards.monitoring.cnrm.cloud.google.com.yaml
pkg/clients/generated/apis/monitoring/v1beta1/monitoringdashboard_types.go
scripts/github-actions/tests-e2e-fixtures

So that users can use these new fields.

monitoringdashboard: move to direct actuation

---

docs/releasenotes/release-1.120.md
docs/releasenotes/release-1.122.md

docs: mention resource promotions

---

tests/e2e/testdata/scenarios/iam_add_remove/_http00.log
tests/e2e/testdata/scenarios/iam_add_remove/_http01.log
tests/e2e/testdata/scenarios/iam_add_remove/_http02.log
tests/e2e/testdata/scenarios/iam_add_remove/_http03.log
tests/e2e/testdata/scenarios/iam_add_remove/_http04.log
tests/e2e/testdata/scenarios/iam_add_remove/_http05.log
tests/e2e/testdata/scenarios/iam_add_remove/_http06.log
tests/e2e/testdata/scenarios/iam_add_remove/_http07.log
tests/e2e/testdata/scenarios/iam_add_remove/_http08.log
tests/e2e/testdata/scenarios/iam_add_remove/_object00.yaml
tests/e2e/testdata/scenarios/iam_add_remove/_object01.yaml
tests/e2e/testdata/scenarios/iam_add_remove/_object02.yaml
tests/e2e/testdata/scenarios/iam_add_remove/_object03.yaml
tests/e2e/testdata/scenarios/iam_add_remove/_object04.yaml
tests/e2e/testdata/scenarios/iam_add_remove/_object05.yaml
tests/e2e/testdata/scenarios/iam_add_remove/script.yaml

- **tests: create scenario tests for IAM policy**

tests: create scenario tests for IAM policy

---

mockgcp/mockmonitoring/dashboard.go
pkg/controller/direct/monitoring/monitoringdashboard_controller.go
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardbasic/_http.log
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardfull/_generated_export_monitoringdashboardfull.golden
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardfull/_generated_object_monitoringdashboardfull.golden.yaml
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardfull/_http.log
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardfull/create.yaml
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardmosaiclayout/_generated_export_monitoringdashboardmosaiclayout.golden
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardmosaiclayout/_generated_object_monitoringdashboardmosaiclayout.golden.yaml
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardmosaiclayout/_http.log
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardmosaiclayout/create.yaml
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardmosaiclayout/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardrefs/_http.log

- **monitoringdashboard: work on GCP fidelity**
- **mockgcp: monitoringdashboard sectionHeader must be in mosaicLayout**
- **mockgcp: monitoringdashboard collapsibleGroup must be in mosaicLayout**

mockgcp: monitoringdashboard collapsibleGroup must be in mosaicLayout

---

mockgcp/mockmonitoring/dashboard.go
pkg/controller/direct/monitoring/monitoringdashboard_controller.go
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardbasic/_http.log
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardfull/_generated_export_monitoringdashboardfull.golden
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardfull/_generated_object_monitoringdashboardfull.golden.yaml
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardfull/_http.log
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardfull/create.yaml
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardmosaiclayout/_generated_export_monitoringdashboardmosaiclayout.golden
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardmosaiclayout/_generated_object_monitoringdashboardmosaiclayout.golden.yaml
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardmosaiclayout/_http.log
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardmosaiclayout/create.yaml
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardmosaiclayout/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardrefs/_http.log

Split out mosaiclayout test, as singleViewGroup widget can only be in
mosaic layout (and add validation to mockgcp)

monitoringdashboard: work on GCP fidelity

---

apis/monitoring/v1beta1/monitoringdashboard_types.go
apis/monitoring/v1beta1/zz_generated.deepcopy.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_monitoringdashboards.monitoring.cnrm.cloud.google.com.yaml
pkg/clients/generated/apis/monitoring/v1beta1/monitoringdashboard_types.go
pkg/clients/generated/apis/monitoring/v1beta1/zz_generated.deepcopy.go
pkg/controller/direct/monitoring/dashboard_generated.mappings.go
pkg/controller/direct/monitoring/dashboard_mappings.go
pkg/controller/direct/monitoring/refs.go
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardfull/_generated_export_monitoringdashboardfull.golden
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardfull/_generated_object_monitoringdashboardfull.golden.yaml
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardfull/_http.log
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardfull/create.yaml
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardmosaiclayout/_http.log
scripts/generate-google3-docs/resource-reference/generated/resource-docs/monitoring/monitoringdashboard.md
tests/e2e/normalize.go

- **monitoringdashboard: alertPolicyNames should be refs**

monitoringdashboard: alertPolicyNames should be refs

---

apis/monitoring/v1beta1/monitoringdashboard_types.go
apis/monitoring/v1beta1/zz_generated.deepcopy.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_monitoringdashboards.monitoring.cnrm.cloud.google.com.yaml
mockgcp/mockmonitoring/dashboard.go
pkg/clients/generated/apis/monitoring/v1beta1/monitoringdashboard_types.go
pkg/clients/generated/apis/monitoring/v1beta1/zz_generated.deepcopy.go
pkg/controller/direct/monitoring/dashboard_generated.mappings.go
pkg/controller/direct/monitoring/dashboard_mappings.go
pkg/controller/direct/monitoring/refs.go
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardfull/_generated_export_monitoringdashboardfull.golden
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardfull/_generated_object_monitoringdashboardfull.golden.yaml
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardfull/_http.log
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardfull/create.yaml
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardmosaiclayout/_http.log
scripts/generate-google3-docs/resource-reference/generated/resource-docs/monitoring/monitoringdashboard.md
tests/e2e/normalize.go

- **monitoringdashboard: alertPolicyNames should be refs**
- **mockgcp: monitoringDashboard should default minAlignmentPeriod in timeSeriesTable**

mockgcp: monitoringDashboard should default minAlignmentPeriod in timeSeriesTable

---

dev/tools/controllerbuilder/template/controller.go

- Use new package for `RegisterModel`
- Update `NewModel` function to match interface

fix: Update controllerbuilder template for interface changes

---

build/builder/Dockerfile
build/tooling/Dockerfile
dev/tools/controllerbuilder/go.mod
experiments/composite/go.mod
experiments/compositions/composition/Dockerfile
experiments/compositions/composition/Dockerfile.getter.expander
experiments/compositions/composition/Dockerfile.inline
experiments/compositions/composition/Dockerfile.jinja2.expander
experiments/compositions/composition/go.mod
experiments/compositions/facade/Dockerfile
experiments/compositions/facade/go.mod
go.mod
mockgcp/go.mod
operator/Dockerfile

- **chore: Update golang to 1.22.5**

codebots update golang version 1.22.5

---

config/tests/samples/create/harness.go
mockgcp/mock_http_roundtrip.go
mockgcp/mockcompute/disksv1.go
mockgcp/mockcompute/imagesv1.go
mockgcp/mockcompute/instancesv1.go
mockgcp/mockcompute/regionaladdress.go
mockgcp/mockcompute/service.go
mockgcp/mockcompute/zonesv1.go
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeaddress/regionalcomputeaddress/_generated_object_regionalcomputeaddress.golden.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeinstance/computeinstancebasicexample/_generated_object_computeinstancebasicexample.golden.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeinstance/computeinstancebasicexample/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeinstance/computeinstancewithencrypteddisk/_generated_object_computeinstancewithencrypteddisk.golden.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeinstance/computeinstancewithencrypteddisk/_http.log
pkg/test/resourcefixture/testdata/resourceoverrides/computeinstance/networkipcomputeinstance/_generated_object_networkipcomputeinstance.golden.yaml
pkg/test/resourcefixture/testdata/resourceoverrides/computeinstance/networkipcomputeinstance/_http.log
pkg/test/resourcefixture/testdata/resourceoverrides/computeinstance/networkipcomputeinstance/create.yaml
pkg/test/resourcefixture/testdata/resourceoverrides/computeinstance/networkipcomputeinstance/update.yaml
tests/e2e/normalize.go
tests/e2e/unified_test.go

Add mock suppor tfor ComputeInstance, that's required for ComputeForwardingRule
Cherry-picked code from #936

MockGCP: Support for ComputeInstance

---

dev/codebots/update-gcp-dependencies
dev/codebots/update-golang-version

Makes it a bit clearer e.g. which branch, which commit mesage etc

chore: have codebots create their own commits

---

dev/tasks/update-dependency
dev/tasks/update-golangx-dependencies

And add a script to do this for us.

chore: update golang.org/x dependencies

---

docs/releasenotes/release-1.120.md

doc: add release note for 1.120.1

---

pkg/resourceskeleton/resourceskeleton_test.go
pkg/resourceskeleton/testdata/uri-skeleton.yaml

tests: err out if skeleton non null

---

pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicacmgkehubfeaturemembership/_generated_object_basicacmgkehubfeaturemembership.golden.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicacmgkehubfeaturemembership/_http.log
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicacmgkehubfeaturemembership/create.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicacmgkehubfeaturemembership/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicacmgkehubfeaturemembership/update.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullacmgkehubfeaturemembership/_generated_object_fullacmgkehubfeaturemembership.golden.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullacmgkehubfeaturemembership/_http.log
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullacmgkehubfeaturemembership/create.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullacmgkehubfeaturemembership/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullacmgkehubfeaturemembership/update.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/meshgkehubfeaturemembership/_generated_object_meshgkehubfeaturemembership.golden.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/meshgkehubfeaturemembership/_http.log
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/meshgkehubfeaturemembership/create.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/meshgkehubfeaturemembership/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/meshgkehubfeaturemembership/update.yaml

* Added basic and full test cases for configmanagement feature
* Added test case for servicemesh feature(only one test as the resource only has one field)
* Excluded Poco fields as the fields are problematic, see https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/1790

Add basic and full test for gkehubfeaturemembership

---

pkg/test/resourcefixture/testdata/basic/dataform/v1alpha1/dataformrepository/_generated_object_dataformrepository.golden.yaml

Add golden object for DataformRepository. Should've went in with https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2232

tests: capture golden object

---

scripts/generate-google3-docs/resource-reference/_toc.yaml
scripts/generate-google3-docs/resource-reference/overview.md

doc: add cbwp to doc index

---

pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicacmgkehubfeaturemembership/_http.log
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicacmgkehubfeaturemembership/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullacmgkehubfeaturemembership/_http.log
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullacmgkehubfeaturemembership/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/meshgkehubfeaturemembership/_http.log
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/meshgkehubfeaturemembership/dependencies.yaml

Cluster.name must be less than 40 characters.

shorten the name for gke cluster

---

pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computemanagedsslcertificate/_generated_object_computemanagedsslcertificate.golden.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargetvpngateway/_generated_object_computetargetvpngateway.golden.yaml
tests/e2e/normalize.go

Address comment: https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2255#discussion_r1671269100

minor fix: normalized ID should be integer

---

dev/tools/controllerbuilder/pkg/commands/generatetypes/generatetypescommand.go
dev/tools/controllerbuilder/scaffold/apis.go
dev/tools/controllerbuilder/scaffold/controller.go
dev/tools/controllerbuilder/template/apis/doc.go
dev/tools/controllerbuilder/template/apis/groupversion_info.go
dev/tools/controllerbuilder/template/apis/types.go

go run main.go generate-types   --proto-source-path ../proto-to-mapper/build/googleapis.pb --service google.cloud.kms.v1 --version v1beta1 --output-api ~/go/src/github.com/GoogleCloudPlatform/k8s-config-connector/ --kinds KeyRing

CLI: scaffold API

---

mockgcp/mockgkehub/gkehubfeature.go
mockgcp/mockiam/serviceaccounts.go
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicacmgkehubfeaturemembership/_generated_object_basicacmgkehubfeaturemembership.golden.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicacmgkehubfeaturemembership/_http.log
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicacmgkehubfeaturemembership/create.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicacmgkehubfeaturemembership/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicacmgkehubfeaturemembership/update.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullacmgkehubfeaturemembership/_generated_object_fullacmgkehubfeaturemembership.golden.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullacmgkehubfeaturemembership/_http.log
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullacmgkehubfeaturemembership/create.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullacmgkehubfeaturemembership/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullacmgkehubfeaturemembership/update.yaml

Fix issues
* service account name was too long
* feature resource should not be cleaned up when running tests concurrently
* features under spec.configmanagement should not be empty as it would rejected by the GCP API.

fix gkehub test cases

---

dev/tools/controllerbuilder/scaffold/controller.go
dev/tools/controllerbuilder/template/controller.go

enh: some template changes

---

dev/tools/controllerbuilder/pkg/codegen/mappergenerator.go

chore: Handle List of enum kind

---

experiments/compositions/composition/config/release/kustomization.yaml
experiments/compositions/composition/release/manifest.yaml

Update composition image to using the lates image version.

update composition version

---

mockgcp/README.md

Added the detailed steps about how to implement the mockgcp logic based on the golden files.
Added the detailed steps about how to implement the mockgcp logic based on the golden files.

Update mockgcp README.md

---

experiments/compositions/samples/CloudSQL/README.md
experiments/compositions/samples/CloudSQL/composition/hasql.yaml

Fixing cloudsql samples
- Use Pre created CRD instead of Facade CR
- Change the group to be generic
- remove Cluster role and binding
- Tweak readme to remove context
- minor changes in readme

Fixing cloudsql samples

---

experiments/compositions/samples/FirstGCPComposition/README.md
experiments/compositions/samples/FirstGCPComposition/composition/cors-bucket.yaml

Use a prebuilt CRD instead of Facade builder
- Adjust the CRD group
- Update the readme
- Rename the CRD fields

Update the First GCP sample to use a pre generated CRD

---

apis/dataform/v1alpha1/repository_types.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_dataformrepositories.dataform.cnrm.cloud.google.com.yaml
dev/tasks/generate-crds
pkg/clients/generated/apis/dataform/v1alpha1/dataformrepository_types.go
pkg/test/resourcefixture/testdata/basic/dataform/v1alpha1/dataformrepository/_generated_object_dataformrepository.golden.yaml
pkg/test/resourcefixture/testdata/basic/dataform/v1alpha1/dataformrepository/_http.log

Turn on the _direct_ `DataformRepository` ctrl. This is still an alpha resource. Next PRs will change the API.

refactor: direct DataformRepository

---

experiments/compositions/expanders/cel-expander/config/crd/bases/composition.google.com_celconfigurations.yaml
experiments/compositions/expanders/cel-expander/pkg/cel/engine.go
experiments/compositions/expanders/cel-expander/pkg/resource/resource.go
experiments/compositions/expanders/cel-expander/pkg/resource/variables.go
experiments/compositions/expanders/cel-expander/release/manifest.yaml

Add license header to few files

Add the missing license header to a few files

---

pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableinstance/bigtableinstanceautoscaling2/_generated_object_bigtableinstanceautoscaling2.golden.yaml
pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableinstance/bigtableinstanceautoscaling2/_http.log
pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableinstance/bigtableinstanceautoscaling2/create.yaml
pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableinstance/bigtableinstanceautoscaling2/update.yaml

- **tests: add another bigtableInstance test**

tests: Create another bigtable test

---

experiments/compositions/samples/AppTeam/README.md
experiments/compositions/samples/AppTeam/cleanup_appteam.sh
experiments/compositions/samples/AppTeam/get_appteam.sh
experiments/compositions/samples/CloudSQL/README.md
experiments/compositions/samples/CloudSQL/cleanup_cloudsql.sh
experiments/compositions/samples/CloudSQL/get_cloudsql.sh
experiments/compositions/samples/README.md

Some very minor cleanup to the AppTeam and CloudSQL compositions samples

Minor cleanup to AppTeam and CloudSQL compositions samples

---

experiments/compositions/samples/AppTeam/composition/appteam.yaml
experiments/compositions/samples/FirstComposition/composition/teampage.yaml

Fixes for samples from second fishfood

Fixes for samples from second fishfood

---

experiments/compositions/samples/FirstGCPComposition/composition/cors-bucket.yaml

Fix the composition to use the correct spec fields

Fix the first-gcp composition to use the correct spec fields

---

dev/tools/controllerbuilder/template/controller.go
dev/tools/proto-to-mapper/main.go

Adds changes to the template to use the factored out maptuils. More context: https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2346

enh: use maputils

---

experiments/compositions/samples/AppTeam/get_appteam.sh

fix bash script error for get_appteam

fix bash script error for get_appteam

---

dev/tools/controllerbuilder/pkg/codegen/mappergenerator.go

The mapping only needs to be computed once.

tools: refactor mapper generator to precompute the mapping

---

config/tests/samples/create/harness.go
mockgcp/mock_http_roundtrip.go
mockgcp/mockbigtable/cluster.go
mockgcp/mockbigtable/instance.go
mockgcp/mockbigtable/service.go
pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableinstance/bigtableinstanceautoscaling/_http.log
pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableinstance/bigtableinstanceautoscaling2/_generated_object_bigtableinstanceautoscaling2.golden.yaml
pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableinstance/bigtableinstanceautoscaling2/_http.log
pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableinstance/bigtableinstancebasic/_http.log
tests/e2e/httplog.go
tests/e2e/normalize.go
tests/e2e/script_test.go
tests/e2e/testdata/scenarios/bigtableinstance/unchanged-absent/_http00.log
tests/e2e/testdata/scenarios/bigtableinstance/unchanged-absent/_http02.log
tests/e2e/testdata/scenarios/bigtableinstance/unchanged-absent/_object00.yaml
tests/e2e/testdata/scenarios/bigtableinstance/unchanged-absent/_object02.yaml
tests/e2e/testdata/scenarios/bigtableinstance/unchanged-absent/_object03.yaml
tests/e2e/testdata/scenarios/bigtableinstance/unchanged-absent/script.yaml
tests/e2e/testdata/scenarios/bigtableinstance/unchanged-merge/_http00.log
tests/e2e/testdata/scenarios/bigtableinstance/unchanged-merge/_http02.log
tests/e2e/testdata/scenarios/bigtableinstance/unchanged-merge/_http03.log
tests/e2e/testdata/scenarios/bigtableinstance/unchanged-merge/_object00.yaml
tests/e2e/testdata/scenarios/bigtableinstance/unchanged-merge/_object02.yaml
tests/e2e/testdata/scenarios/bigtableinstance/unchanged-merge/_object03.yaml
tests/e2e/testdata/scenarios/bigtableinstance/unchanged-merge/script.yaml
tests/e2e/testdata/scenarios/fields/llm_lazy_reconcile/_object01.yaml
tests/e2e/unified_test.go

- **tests: record more accurate bigtable golden log**
- **tests: create scenario tests for bigtableinstance**
- **tests: run all scenario tests in tests-e2e-scenarios**
- **tests: support MockGCP-backdoor command**
- **mockgcp: improve fidelity of BigTable**
- **tests: add support for "TOUCH" magic**

tests: more testing for BigTable

---

.github/workflows/presubmit-compositions.yaml

Scope github workflows to the compositions experiments folder.

ci: scope compositions gh wf

---

experiments/kompanion/README.md
experiments/kompanion/cmd/export/export.go
experiments/kompanion/main.go

Small, self contained UX changes.

kompanion ux changes

---

mockgcp/mockartifactregistry/repository.go
mockgcp/mockartifactregistry/service.go
pkg/test/resourcefixture/testdata/basic/artifactregistry/v1beta1/artifactregistryrepository/_http.log
pkg/test/resourcefixture/testdata/iammemberreferences/serviceidentityref/_http.log

- **mockgcp: improve artifactregistry fidelity**
- **tests: update artifactregistryrepository golden output**

mockgcp: improve artifactregistry fidelity

---

docs/releasenotes/release-1.121.md

doc: add release note for v1.121.0

---

experiments/compositions/composition/Makefile
experiments/compositions/composition/expanders.mk
experiments/compositions/composition/inline.mk
experiments/compositions/expanders/cel-expander/Makefile
experiments/compositions/expanders/helm-expander/Makefile

* parameterize GOWORK for all make targets
* Turn it off by default for now

parameterize GOWORK for all make composition targets

---

apis/refs/v1beta1/computerefs.go
pkg/controller/direct/networkconnectivity/client.go
pkg/controller/direct/networkconnectivity/refs.go
pkg/controller/direct/networkconnectivity/serviceconnectionpolicy_controller.go
pkg/controller/direct/networkconnectivity/utils.go
pkg/controller/direct/register/register.go
pkg/test/resourcefixture/testdata/basic/networkconnectivity/v1alpha1/serviceconnectionpolicy/serviceconnectionpolicybasic/_generated_object_serviceconnectionpolicybasic.golden.yaml
pkg/test/resourcefixture/testdata/basic/networkconnectivity/v1alpha1/serviceconnectionpolicy/serviceconnectionpolicybasic/_http.log
pkg/test/resourcefixture/testdata/basic/networkconnectivity/v1alpha1/serviceconnectionpolicy/serviceconnectionpolicybasic/create.yaml
pkg/test/resourcefixture/testdata/basic/networkconnectivity/v1alpha1/serviceconnectionpolicy/serviceconnectionpolicybasic/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/networkconnectivity/v1alpha1/serviceconnectionpolicy/serviceconnectionpolicybasic/update.yaml

- **feat: add direct controller for NetworkConnectivityServiceConnectionPolicy**
- **tests: add test for NetworkConnectivityServiceConnectionPolicy**

feat: add direct controller for NetworkConnectivityServiceConnectionPolicy

---

config/tests/samples/create/harness.go
mockgcp/mock_http_roundtrip.go
mockgcp/mocknetworkconnectivity/service.go
mockgcp/mocknetworkconnectivity/serviceconnectionpolicies.go
mockgcp/mocknetworkconnectivity/utils.go
pkg/test/resourcefixture/testdata/basic/networkconnectivity/v1alpha1/serviceconnectionpolicy/serviceconnectionpolicybasic/_generated_object_serviceconnectionpolicybasic.golden.yaml
pkg/test/resourcefixture/testdata/basic/networkconnectivity/v1alpha1/serviceconnectionpolicy/serviceconnectionpolicybasic/_http.log
pkg/test/resourcefixture/testdata/basic/networkconnectivity/v1alpha1/serviceconnectionpolicy/serviceconnectionpolicybasic/create.yaml
pkg/test/resourcefixture/testdata/basic/networkconnectivity/v1alpha1/serviceconnectionpolicy/serviceconnectionpolicybasic/update.yaml

- mockgcp: Implement NetworkConnectivityServiceConnectionPolicy
- tests: update NetworkConnectivityServiceConnectionPolicy test

mockgcp support for NetworkConnectivityServiceConnectionPolicy

---

pkg/controller/direct/cloudbuild/externalresource.go
pkg/controller/direct/cloudbuild/workerpool_controller.go

chore: resolve comments in #2407

---

pkg/test/resourcefixture/testdata/basic/networkconnectivity/v1alpha1/serviceconnectionpolicy/serviceconnectionpolicybasic/_http.log

Seems to be a merge conflict between:
- https://github.com/GoogleCloudPlatform/k8s-config-connector/commit/29a08e3bf64f6752785ca2c4a074de4df407c2de
- https://github.com/GoogleCloudPlatform/k8s-config-connector/commit/16454226fab7932c77fbecb185fdfc87804fd660

fix: fix serviceconnectionpolicybasic test fixture

---

dev/tools/controllerbuilder/generate.sh
dev/tools/controllerbuilder/pkg/commands/generatetypes/generatetypescommand.go
dev/tools/controllerbuilder/pkg/options/generateoptions.go

fix: wrong flag reference in generate-type CLI

---

apis/cloudbuild/v1beta1/workerpool_types.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_cloudbuildworkerpools.cloudbuild.cnrm.cloud.google.com.yaml

feat: use CEL to validate network immutable field for cbwp

---

dev/tasks/create-test-project

* Fix bash syntax error
* Add more comments

chore: more project creation tweaks

---

tests/e2e/httplog.go
tests/e2e/normalize.go
tests/e2e/replacements.go
tests/e2e/script_test.go
tests/e2e/testdata/scenarios/acquisition/monitoringgroup/_http00.log
tests/e2e/testdata/scenarios/acquisition/monitoringgroup/_http01.log
tests/e2e/testdata/scenarios/acquisition/monitoringgroup/_object00.yaml
tests/e2e/testdata/scenarios/acquisition/monitoringgroup/_object01.yaml
tests/e2e/testdata/scenarios/acquisition/monitoringgroup/script.yaml
tests/e2e/unified_test.go

This is a little easier to understand than the "resourceId magic".

tests: move resource acquistion test to script test

---

pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringuptimecheckconfig/tcpuptimecheckconfig/_generated_object_tcpuptimecheckconfig.golden.yaml
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringuptimecheckconfig/tcpuptimecheckconfig/_http.log
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringuptimecheckconfig/tcpuptimecheckconfig/update.yaml

tests: fix tcpuptimecheckconfig test for immutable change

---

go.work.sum
mockgcp/mockkms/cryptokey.go
mockgcp/mockkms/cryptokeyversion.go
mockgcp/mockkms/keyring.go
mockgcp/mockkms/utils.go
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbcluster/fullalloydbcluster/_http.log
pkg/test/resourcefixture/testdata/basic/container/v1beta1/containercluster/_http.log
pkg/test/resourcefixture/testdata/basic/kms/v1beta1/kmscryptokey/_generated_object_kmscryptokey.golden.yaml
pkg/test/resourcefixture/testdata/basic/kms/v1beta1/kmscryptokey/_http.log
pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstanceencryptionkey/_http.log
pkg/test/resourcefixture/testdata/basic/vertexai/v1beta1/vertexaidataset/vertexaidatasetencryptionkey/_http.log
pkg/test/resourcefixture/testdata/basic/vertexai/v1beta1/vertexaiendpoint/vertexaiendpointencryptionkey/_http.log
tests/e2e/unified_test.go

- mockgcp: Initial support for KMSKeyRing

mockgcp: more fidelity for KMSKeyRing

---

.github/workflows/presubmit-compositions.yaml
experiments/compositions/composition/Makefile
experiments/compositions/composition/proto/expander.pb.go
experiments/compositions/composition/proto/expander_grpc.pb.go
experiments/compositions/scripts/github-actions/format-gomod.sh
experiments/compositions/scripts/github-actions/verify-goimports.sh

Add more github actions for experiments/compositions:
- verify gomod
- verify go imports

More github actions for Compositions

---

mockgcp/mockredis/cluster.go
pkg/test/resourcefixture/testdata/basic/redis/v1alpha1/rediscluster/redisclustersimple/_http.log
pkg/test/resourcefixture/testdata/basic/redis/v1beta1/basicrediscluster/_generated_object_basicrediscluster.golden.yaml
pkg/test/resourcefixture/testdata/basic/redis/v1beta1/basicrediscluster/_http.log
pkg/test/resourcefixture/testdata/basic/redis/v1beta1/fullrediscluster/_http.log

- **mockgcp: improve fidelity of RedisCluster**

mockgcp: improve fidelity of RedisCluster

---

experiments/compositions/composition/api/v1alpha1/plan_types.go
experiments/compositions/composition/cmd/inline/main.go
experiments/compositions/composition/config/crd/bases/composition.google.com_plans.yaml
experiments/compositions/composition/expanders/expand/main.go
experiments/compositions/composition/expanders/getter/main_test.go
experiments/compositions/composition/expanders/jinja2/main.go
experiments/compositions/composition/expanders/jinja2/main_test.go
experiments/compositions/composition/internal/controller/composition_controller.go
experiments/compositions/composition/internal/controller/expander_reconciler.go
experiments/compositions/composition/internal/controller/expanderversion_controller.go
experiments/compositions/composition/pkg/applier/applier.go
experiments/compositions/composition/pkg/containerexecutor/jobcontainerexecutor/jobcontainerrunner.go
experiments/compositions/composition/pkg/crds/crds.go
experiments/compositions/composition/tests/cluster/cluster.go
experiments/compositions/composition/tests/cluster/configcontroller/cluster.go
experiments/compositions/composition/tests/cluster/kind/cluster.go
experiments/compositions/composition/tests/scenario/scenario.go
experiments/compositions/composition/tests/testcases/kcc_samples_test.go
experiments/compositions/composition/tests/testcases/main_test.go
experiments/compositions/composition/tests/testcases/simple_samples_test.go
experiments/compositions/composition/tests/testclient/client.go
experiments/compositions/composition/tests/testclient/framework.go
experiments/compositions/composition/tests/utils/utils.go

fixing linter errors

---

config/tests/samples/create/harness.go
config/tests/samples/create/samples_test.go
pkg/controller/direct/registry/registry.go
pkg/controller/registration/registration_controller.go
pkg/test/main/testmain.go
tests/e2e/unified_test.go

-Fix postsubmit failures for direct controller
-Deprecate old samples test harness
```
--- PASS: TestAll (0.75s)
--- PASS: TestAll/linear-log-metric (23.70s)
PASS
{"severity":"info","timestamp":"2024-08-15T21:16:13.140Z","msg":"Stopping and waiting for non leader election runnables"}
{"severity":"info","timestamp":"2024-08-15T21:16:13.141Z","msg":"Stopping and waiting for leader election runnables"}
{"severity":"info","timestamp":"2024-08-15T21:16:13.141Z","msg":"Stopping and waiting for caches"}
{"severity":"info","timestamp":"2024-08-15T21:16:13.141Z","msg":"Stopping and waiting for webhooks"}
{"severity":"info","timestamp":"2024-08-15T21:16:13.141Z","logger":"controller-runtime.webhook","msg":"Shutting down webhook server with timeout of 1 minute"} …
```

fixit: Initialize direct controller registry for postsubmit samples tests

---

config/tests/samples/create/harness.go
config/tests/samples/create/samples_test.go
pkg/controller/direct/registry/registry.go
pkg/controller/registration/registration_controller.go
pkg/test/main/testmain.go
tests/e2e/unified_test.go

revert: fixit: Initialize direct controller registry for postsubmit samples tests

---

Makefile

Add unified simple commands to build binaries for KCC controllers.

add commands to build binaries for controllers

---

experiments/compositions/composition/internal/controller/expander_reconciler.go

Reduce cyclomatic complexity of Reconcile() function:
* Seperate code that gets a new planCR into its own function
* Separate code that updates plan status into its own function
* Refactor a nested if check

reduce cyclomatic complexity of Reconcile function 

---

experiments/kompanion/cmd/export/export.go
experiments/kompanion/main.go

Also only create directories if we're writing a file, and a few general refactorings for cobra-style.

kompanion: refactor to avoid global variables

---

hack/record-gcp
mockgcp/mockredis/cluster.go
pkg/controller/direct/redis/cluster/rediscluster_controller.go
pkg/k8s/condition.go
pkg/test/resourcefixture/testdata/basic/redis/v1alpha1/rediscluster/redisclustersimple/_http.log
pkg/test/resourcefixture/testdata/basic/redis/v1beta1/basicrediscluster/_http.log
pkg/test/resourcefixture/testdata/basic/redis/v1beta1/fullrediscluster/_generated_object_fullrediscluster.golden.yaml
pkg/test/resourcefixture/testdata/basic/redis/v1beta1/fullrediscluster/_http.log
pkg/test/resourcefixture/testdata/basic/redis/v1beta1/fullrediscluster/create.yaml
pkg/test/resourcefixture/testdata/basic/redis/v1beta1/fullrediscluster/update.yaml

- **Multi field update test case for redis cluster**
- **redis: handle multi-field updates**
- **tests: capture golden output for redis multi-field update**

fix: rediscluster multiple field updates

---

pkg/cli/cmd/bulkexport/execute.go
pkg/cli/cmd/bulkexport/filteredinputstream/filteredinputstream.go
pkg/cli/cmd/bulkexport/filteredinputstream/filteredinputstream_test.go
pkg/cli/cmd/bulkexport/outputstream/outputstream.go
pkg/cli/cmd/bulkexport/parameters/parameters.go
pkg/cli/cmd/export/execute.go
pkg/cli/cmd/export/parameters/parameters.go
pkg/cli/cmd/root.go
pkg/cli/stream/asset_to_unstructured_resource_stream.go
pkg/cli/stream/asset_to_unstructured_resource_stream_test.go
pkg/controller/direct/export.go
pkg/controller/direct/registry/registry.go

- **feat: initialize direct exporters in config-connector CLI**
- **feat: support bulk-export with direct-exporters**
- **chore: plumb through config.ControllerConfig in export**

Support direct exporters in config-connector CLI

---

pkg/controller/direct/apikeys/apikeyskey_controller.go

Gob CL with the change: https://cnrm-review.git.corp.google.com/c/cnrm/+/70860
TestCreateNoChangeUpdateDelete/apikeys/basic-apikeyskeybasic passed [prow presubmit job](https://prow-gob.gcpnode.com/view/gs/cnrm-prow/pr-logs/pull/cnrm-review.googlesource.com_cnrm/70860/cnrm-test/1825738346719088640)(Ignored other flaky test cases)

Support Export in apikeyskey controller

---

config/tests/samples/create/samples_test.go

Fix -skip-tests logic in samples test so that when it is unset, no sample will be skipped.
Verified that a single test can be triggered properly with `-run-tests=custom-budget` but without `-skip-tests`.

Fix -skip-tests logic in samples test

---

experiments/kompanion/cmd/export/export.go

Switching to calling into the kube config loader directly here.

fix: use KUBECONFIG if specified

---

.github/workflows/presubmit-compositions.yaml

We have been seeing compositions linter timeout more often than not. Adding timeout as per resolution here: 'https://github.com/golangci/golangci-lint-action/issues/308#issuecomment-896815985'

Add a timeout param to compositions/lint action

---

Makefile

This PR adds commands for
- deploy the config connector manifests to standard GKE clusters
- run config connector e2e tests locally

Add commands for deploying kcc manifests and run tests locally

---

tests/apichecks/crds_test.go

We only want refs in spec; in the status we expect "full links" in the
"external" format.

tests: add api check to warn if there are refs in status

---

config/tests/samples/create/samples_test.go

Register direct controllers and handle context cancellation
Tested locally without issues, triggered a prow job to double verify: https://cnrm-review.git.corp.google.com/c/cnrm/+/70920

fixit: Fix samples tests

---

.github/workflows/presubmit.yaml
scripts/github-actions/tests-e2e-fixtures-compute
scripts/github-actions/tests-e2e-fixtures-gkehub
scripts/github-actions/tests-e2e-scenarios.sh
tests/e2e/unified_test.go

fixit: Run presubmit fixtures tests by services

---

pkg/controller/direct/compute/forwardingrule_controller.go
pkg/controller/direct/compute/mapper.go

--- PASS: TestCreateNoChangeUpdateDelete (0.13s)
--- PASS: TestCreateNoChangeUpdateDelete/compute (0.00s)
--- PASS: TestCreateNoChangeUpdateDelete/compute/basic-regionalcomputeforwardingrule (136.60s)
PASS
--- PASS: TestCreateNoChangeUpdateDelete (0.13s)
--- PASS: TestCreateNoChangeUpdateDelete/compute (0.00s)
--- PASS: TestCreateNoChangeUpdateDelete/compute/basic-globalcomputeforwardingrule (245.53s)
PASS

direct: Implement export for ComputeForwardingRule

---

dev/tasks/create-test-project

Starting with the services we definitely need!

tests: enable some services in e2e

---

config/tests/samples/create/harness.go

Fixes https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/2621
Context: https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2620

Temporarily skip compute service attachment tests

---

cmd/recorder/kube/dynamic_watch.go
cmd/recorder/kube/kubeview.go
cmd/recorder/kube/target.go
cmd/recorder/main.go

Otherwise we look for CRDs that are not installed.
Issue #2402

recorder: watch CRDs instead of using a static list

---

pkg/test/resourcefixture/testdata/basic/certificatemanager/v1beta1/certificatemanagercertificate/certificatemanagercertificatemanageddns/_http.log
pkg/test/resourcefixture/testdata/basic/certificatemanager/v1beta1/certificatemanagerdnsauthorization-full/_generated_object_certificatemanagerdnsauthorization-full.golden.yaml
pkg/test/resourcefixture/testdata/basic/certificatemanager/v1beta1/certificatemanagerdnsauthorization-full/_http.log
pkg/test/resourcefixture/testdata/basic/certificatemanager/v1beta1/certificatemanagerdnsauthorization-full/create.yaml
pkg/test/resourcefixture/testdata/basic/certificatemanager/v1beta1/certificatemanagerdnsauthorization-full/update.yaml
pkg/test/resourcefixture/testdata/basic/certificatemanager/v1beta1/certificatemanagerdnsauthorization-minimal/_generated_object_certificatemanagerdnsauthorization-minimal.golden.yaml
pkg/test/resourcefixture/testdata/basic/certificatemanager/v1beta1/certificatemanagerdnsauthorization-minimal/_http.log
pkg/test/resourcefixture/testdata/basic/certificatemanager/v1beta1/certificatemanagerdnsauthorization-minimal/create.yaml
pkg/test/resourcefixture/testdata/basic/certificatemanager/v1beta1/certificatemanagerdnsauthorization-minimal/update.yaml
tests/e2e/normalize.go
tests/e2e/unified_test.go

This is the 1st PR; create.yaml and update.yaml have the same content
Fixes #

Add full test and minimal test for Certificate Manager DNS Authorization

---

pkg/test/resourcefixture/testdata/basic/certificatemanager/v1beta1/certificatemanagerdnsauthorization-full/_generated_object_certificatemanagerdnsauthorization-full.golden.yaml
pkg/test/resourcefixture/testdata/basic/certificatemanager/v1beta1/certificatemanagerdnsauthorization-full/_http.log
pkg/test/resourcefixture/testdata/basic/certificatemanager/v1beta1/certificatemanagerdnsauthorization-full/create.yaml
pkg/test/resourcefixture/testdata/basic/certificatemanager/v1beta1/certificatemanagerdnsauthorization-full/update.yaml
pkg/test/resourcefixture/testdata/basic/certificatemanager/v1beta1/certificatemanagerdnsauthorization-minimal/_generated_object_certificatemanagerdnsauthorization-minimal.golden.yaml
pkg/test/resourcefixture/testdata/basic/certificatemanager/v1beta1/certificatemanagerdnsauthorization-minimal/_http.log
pkg/test/resourcefixture/testdata/basic/certificatemanager/v1beta1/certificatemanagerdnsauthorization-minimal/update.yaml

CertificateManagerDnsAuthorization test cases
Fixes #

Add changes to all immutable fields in update.yaml for

---

pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-authorizednetworks/_generated_object_sqlinstance-authorizednetworks.golden.yaml
pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-authorizednetworks/_http.log
pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-authorizednetworks/create.yaml
pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-authorizednetworks/update.yaml

fix: Update sqlinstance-authorizednetworks timestamp format

---

mockgcp/README.md

docs:mockgcp: Update README.md

---

dev/tools/controllerbuilder/cmd/root.go
dev/tools/controllerbuilder/template/controller.go
dev/tools/controllerbuilder/template/externalresource.go

chore: improve controller builder to align flags

---

dev/ci/periodics/e2e-service-cloudkms
dev/tasks/create-test-project

tests: add e2e job for cloudkms

---

docs/releasenotes/release-1.122.md
docs/releasenotes/release-1.123.md

doc: Add 1.122 release note

---

config/tests/servicemapping/servicemapping_test.go
pkg/k8s/allowlist_test.go

Small changes that I am seen necessary for a direct conversion and promotion from alpha to beta.

tests: direct changes

---

pkg/test/resourcefixture/testdata/basic/dataflow/v1beta1/dataflowflextemplatejob/streamingdataflowflextemplatejob/_generated_object_streamingdataflowflextemplatejob.golden.yaml
pkg/test/resourcefixture/testdata/basic/dataflow/v1beta1/dataflowflextemplatejob/streamingdataflowflextemplatejob/_http.log
pkg/test/resourcefixture/testdata/basic/dataflow/v1beta1/dataflowflextemplatejob/streamingdataflowflextemplatejob/create.yaml

It was referrring to a non-existent pubsubtopic

tests: fix streamingdataflowflextemplatejob

---

dev/tools/controllerbuilder/generate.sh

Fix the ordering of the entries in `generate.sh`.

chore: fix generate.sh

---

config/tests/samples/create/harness.go
mockgcp/mockcompute/globaltargettcpproxyv1.go
mockgcp/mockcompute/service.go
pkg/controller/direct/compute/forwardingrule_controller.go
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingruletcp/_generated_object_globalcomputeforwardingruletcp.golden.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingruletcp/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingruletcp/create.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingruletcp/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingruletcp/update.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargettcpproxy/_generated_object_computetargettcpproxy.golden.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargettcpproxy/_http.log
tests/e2e/unified_test.go

based on #2628 
-Add mocks for global compute targettcpproxy
-Add tests case for computeforwardingrule with target TCP proxy
-Collect logs

Support Mock Compute TargetTcpProxy

---

config/tests/samples/create/harness.go
mockgcp/mockcompute/globaltargethttpsproxiesv1.go
mockgcp/mockcompute/regionaltargethttpsproxiesv1.go
mockgcp/mockcompute/service.go
pkg/controller/direct/compute/forwardingrule_controller.go
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrulehttps/_generated_object_globalcomputeforwardingrulehttps.golden.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrulehttps/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrulehttps/create.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrulehttps/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrulehttps/update.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargethttpsproxy/crossregiontargethttpsproxy/_generated_object_crossregiontargethttpsproxy.golden.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargethttpsproxy/crossregiontargethttpsproxy/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargethttpsproxy/globaltargethttpsproxy-certmap/_generated_object_globaltargethttpsproxy-certmap.golden.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargethttpsproxy/globaltargethttpsproxy-certmap/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargethttpsproxy/globaltargethttpsproxy-certmap/create.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargethttpsproxy/globaltargethttpsproxy-certmap/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargethttpsproxy/globaltargethttpsproxy-certmap/update.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargethttpsproxy/globaltargethttpsproxy/_generated_object_globaltargethttpsproxy.golden.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargethttpsproxy/globaltargethttpsproxy/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargethttpsproxy/globaltargethttpsproxycertificatemanagercertificates/_generated_object_globaltargethttpsproxycertificatemanagercertificates.golden.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargethttpsproxy/globaltargethttpsproxycertificatemanagercertificates/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargethttpsproxy/globaltargethttpsproxycertificatemap/_generated_object_globaltargethttpsproxycertificatemap.golden.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargethttpsproxy/globaltargethttpsproxycertificatemap/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargethttpsproxy/regionaltargethttpsproxy/_generated_object_regionaltargethttpsproxy.golden.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargethttpsproxy/regionaltargethttpsproxy/_http.log
tests/e2e/unified_test.go

Support Mock Compute TargetHttpsProxy

---

dev/tasks/find-missing-fields
pkg/controller/direct/compute/mapper.generated.go
pkg/controller/direct/compute/roundtrip_test.go
pkg/test/fuzz/generate.go

fuzz: elapsed: 1m0s, execs: 1046608 (21329/sec), new interesting: 32 (total: 250)
fuzz: elapsed: 1m0s, execs: 1046608 (0/sec), new interesting: 32 (total: 250)
--- PASS: FuzzComputeForwardingRuleSpec (60.16s)
=== NAME  
PASS
ok      github.com/GoogleCloudPlatform/k8s-config-connector/pkg/controller/direct/compute       60.429s

Add FuzzComputeForwardingRuleSpec test

---

dev/tools/controllerbuilder/cmd/root.go
dev/tools/controllerbuilder/scaffold/controller.go
dev/tools/controllerbuilder/template/controller/controller.go
dev/tools/controllerbuilder/template/controller/externalresource.go

chore: improve controller-builder template and fix externalRef issues

---

pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrulefull/_generated_object_globalcomputeforwardingrulefull.golden.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrulefull/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrulefull/create.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrulefull/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrulefull/update.yaml

Commit1: add full test case with all required and optional fields for global forwarding rule
Commit2: modify mutable fields in update.yaml and update the golden files

test: Add full test case for global forwarding rule

---

dev/tasks/find-missing-fields
pkg/controller/direct/dataform/repository_mappings.go
pkg/controller/direct/dataform/roundtrip_test.go

Adds a fuzz roundtrip for DataformRepository.

tests: roundtrip for DataformRepository

---

dev/tools/controllerbuilder/scaffold/controller.go
dev/tools/controllerbuilder/template/controller/controller.go

chore: controller-template use gcp-client options && ToLower

---

.github/workflows/fuzz.yaml

ci: add fuzzer job

---

docs/develop-resources/scenarios/migrate-tf-resource-alpha.md
docs/develop-resources/scenarios/migrate-tf-resource-beta.md
docs/develop-resources/scenarios/new-field.md
docs/develop-resources/scenarios/new-resource.md

doc: require real GCP log for PR review

---

go.mod
go.sum
pkg/controller/direct/certificatemanager/mapper.generated.go

Add Certificate Manager generated mapper

---

.github/workflows/presubmit.yaml

Upgrade to remove node.js version warning during presumit test
Fixes #

chore: Upgrade checkout and setup-go action

---

docs/develop-resources/api-conventions/resource-reference.md

doc: add direct resource reference guide

---

apis/refs/v1beta1/computerefs.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_cloudbuildworkerpools.cloudbuild.cnrm.cloud.google.com.yaml
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_computeforwardingrules.compute.cnrm.cloud.google.com.yaml
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_dataflowflextemplatejobs.dataflow.cnrm.cloud.google.com.yaml
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_networkconnectivityserviceconnectionpolicies.networkconnectivity.cnrm.cloud.google.com.yaml
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_redisclusters.redis.cnrm.cloud.google.com.yaml
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_sqlinstances.sql.cnrm.cloud.google.com.yaml
pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-privatenetwork-backwardcompatible/_generated_object_sqlinstance-privatenetwork-backwardcompatible.golden.yaml
pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-privatenetwork-backwardcompatible/_generated_object_sqlinstance-privatenetwork.golden.yaml
pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-privatenetwork-backwardcompatible/_http.log
pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-privatenetwork-backwardcompatible/create.yaml
pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-privatenetwork-backwardcompatible/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-privatenetwork-backwardcompatible/update.yaml
scripts/generate-google3-docs/resource-reference/generated/resource-docs/cloudbuild/cloudbuildworkerpool.md
scripts/generate-google3-docs/resource-reference/generated/resource-docs/compute/computeforwardingrule.md
scripts/generate-google3-docs/resource-reference/generated/resource-docs/dataflow/dataflowflextemplatejob.md
scripts/generate-google3-docs/resource-reference/generated/resource-docs/sql/sqlinstance.md

fix: Compute service "External" value allows selfLink"

---

docs/releasenotes/release-1.123.md

docs: release notes update

---

dev/tasks/build-images

This means the image tag matches the git tag.

chore: build images with git tag, if we match exactly

---

mockgcp/mockcompute/globalforwardingrulesv1.go
mockgcp/mockcompute/regionalforwardingrulev1.go
pkg/controller/direct/compute/forwardingrule_controller.go
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrule/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrulefull/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrulehttps/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrulessl/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingruletcp/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/regionalcomputeforwardingrule/_http.log

Cherry-picked from #2711
Based on #2720, check the last commit

(Part 2)Fix diffs in compute forwarding rule: Labels can only be added or modified by the setLabels method

---

Makefile

Add ensure to make ready-pr

---

pkg/krmtotf/krmtotf.go

This is to fix the bug introduced in #2735. The field name should be in snake case instead of camel case.
- [Pending] Perform necessary E2E testing for changed resources.

Fix the default field name for CloudIdentityGroup

---

mockgcp/mockbigqueryconnection/connection.go
pkg/controller/direct/bigqueryconnection/connection_controller.go
pkg/test/resourcefixture/testdata/basic/bigqueryconnection/v1alpha1/bigqueryconnectionconnection/bigqueryconnectionconnectionbasic/_http.log
pkg/test/resourcefixture/testdata/basic/bigqueryconnection/v1alpha1/bigqueryconnectionconnection/bigqueryconnectionconnectionfull/_http.log

fix: bigqueryconnectionconnection misuse projectNum for projectID

---

docs/releasenotes/release-1.123.md
docs/releasenotes/release-1.124.md
docs/releasenotes/release-1.125.md

docs: release note for 1.123

---

docs/develop-resources/guides/1-add-mockgcp-tests.md

doc: create test suite in "step 1. mockgcp"

---

.github/workflows/presubmit.yaml
scripts/github-actions/ga-pause-test.sh

test: Increase timeout for pause test

---

docs/develop-resources/api-conventions/external-reference.md
docs/develop-resources/api-conventions/validations.md
docs/develop-resources/guides/2-define-apis.md
docs/develop-resources/scenarios/new-field.md

doc: add external ref

---

pkg/k8s/allowlist_test.go

Context: https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2776

Remove the check in allowlist_test to unblock TF to direct migration

---

dev/tools/controllerbuilder/template/controller/controller.go
dev/tools/controllerbuilder/template/controller/externalresource.go

chore: several improvements and fixes to controller template

---

dev/tools/controllerbuilder/pkg/codegen/mappergenerator.go
pkg/controller/direct/maputils.go
pkg/controller/direct/maputils_test.go

feat: add StringDuration <-> Proto mapper

---

mockgcp/Makefile

mockgcp: fix makefile for KMS OpenAPI -> proto

---

docs/releasenotes/release-1.124.md

Add release doc for DNSAuthorization

---

pkg/controller/direct/certificatemanager/dnsauthorization_controller.go

nit: Address minor comments for DNSAuthorization Direct controller

---

pkg/test/iam/resource.go

Fixes the following failed integration tests:
* TestAllGetSetDeleteAuditConfig
* TestAllGetSetDeletePolicy
* TestAllGetSetDeletePolicyMember
* TestAllGetSetPolicyWithAuditConfigs

Skip direct CRDs when checking IAM support in IAM integration tests

---

dev/tools/controllerbuilder/scaffold/controller.go

Fixes a bad merge in our tooling

fix: bad merge

---

hack/update-images.sh
operator/channels/packages/configconnector/1.121.0/cluster/workload-identity/0-cnrm-system.yaml
operator/channels/packages/configconnector/1.121.0/namespaced/0-cnrm-system.yaml
operator/channels/packages/configconnector/1.121.0/namespaced/per-namespace-components.yaml
operator/channels/packages/configconnector/1.122.0/cluster/workload-identity/0-cnrm-system.yaml
operator/channels/packages/configconnector/1.122.0/namespaced/0-cnrm-system.yaml
operator/channels/packages/configconnector/1.122.0/namespaced/per-namespace-components.yaml
operator/channels/packages/configconnector/1.123.1/cluster/workload-identity/0-cnrm-system.yaml
operator/channels/packages/configconnector/1.123.1/namespaced/0-cnrm-system.yaml
operator/channels/packages/configconnector/1.123.1/namespaced/per-namespace-components.yaml
operator/config/gke-addon/image_configmap.yaml
operator/scripts/update-kcc-manifest/manager_sidecar_patch.yaml
operator/scripts/update-kcc-manifest/recorder_sidecar_patch.yaml

Need to have gcrane installed.
However the script finds the new version and will fix yaml files to use that.
Expect to extend this to update other images as well.
Fixes # N/A
Validated the docker image can be pulled.

Added script to update the prometheus-to-sd image.

---

pkg/controller/direct/redis/cluster/rediscluster_controller.go

Fix redis cluster delete error due to not honoring AllowPartial flag

---

dev/tools/controllerbuilder/template/apis/refs.go

Fixes a nil deference in the refs template and a style callout.

fix: nil dereference

---

config/tests/samples/create/harness.go
mockgcp/mockmonitoring/monitoringservice.go
mockgcp/mockmonitoring/service.go
mockgcp/mockmonitoring/utils.go
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringservice/_generated_object_monitoringservice.golden.yaml
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringservice/_http.log

- **tests: record golden output for monitoringservice**
- **mockgcp: support for MonitoringService**

mockgcp: support for MonitoringService

---

CONTRIBUTING.md

Updates CONTRIBUTING.md to use an environment variable for the GitHub username (`YOUR_USERNAME`). Makes it much easier to follow the setup documentation as no need to keep editing the commands.
N/A - Docs only change.

Update Github username to use an environment variable

---

config/tests/samples/create/harness.go
mockgcp/mockcompute/firewallpoliciesv1.go
mockgcp/mockcompute/globalorganizationoperationsv1.go
mockgcp/mockcompute/operations.go
mockgcp/mockcompute/service.go
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computefirewallpolicy/_generated_object_computefirewallpolicy.golden.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computefirewallpolicy/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computefirewallpolicyrule/_generated_object_computefirewallpolicyrule.golden.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computefirewallpolicyrule/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computefirewallpolicyrule/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/tags/v1beta1/tagstagkey/tagkeyorgbasic/_generated_object_tagkeyorgbasic.golden.yaml
scripts/generate-google3-docs/resource-reference/overview.md
tests/e2e/normalize.go
tests/e2e/replacements.go
tests/e2e/unified_test.go

Commit 1: collect logs from realGCP
Commit 2: add mocks for ComputeFirewallPolicy and compare mock logs with realGCP
Commit 3: add mocks for ComputeFirewallPolicyRule and compare mock logs with realGCP
I'm still seeing some diffs with realGCP. Comment in the PR and we can determine if they are acceptable.

mockGCP: Mock ComputeFirewallPolicy and mock ComputeFirewallPolicyRule

---

.github/workflows/lint.yaml
.github/workflows/presubmit-compositions.yaml
.golangci.yaml

Increase lint workflow timeout to 10m

---

dev/tools/controllerbuilder/scaffold/apis.go
dev/tools/controllerbuilder/template/apis/types.go

dev:tools: various small changes

---

dev/tools/controllerbuilder/template/apis/refs.go

Small quick fix so others don't run into this.

dev:tools:fix: {

---

docs/develop-resources/guides/5-releases.md

Add IsPureDirectResource step to Direct Controller resource guide

---

pkg/controller/direct/dataflow/dataflowflextemplatejob_controller.go

Adding export for the dataflow job. This should make the postsubvmits happy (or -ier).

feat: dataflowjob export

---

docs/releasenotes/release-1.125.md

Add RedisCluster v1beta1 promotion to release doc

---

dev/tools/controllerbuilder/template/controller/controller.go
pkg/controller/direct/secretmanager/secret_controller.go

chore: simplify setStatus

---

experiments/compositions/dev-setup/poc_setup.sh

Remove unnecessary lines from POC Script. 
Fixes #

Update POC Script

---

dev/tools/controllerbuilder/template/controller/controller.go

Error: template/controller/controller.go:30:28: string not terminated

fix: missing end quote in controller template

---

docs/releasenotes/release-1.124.md

doc: 1.124.0 release notes

---

config/samples/resources/rediscluster/compute_v1beta1_computenetwork.yaml
config/samples/resources/rediscluster/compute_v1beta1_computesubnetwork.yaml
config/samples/resources/rediscluster/networkconnectivity_v1alpha1_networkconnectivityserviceconnectionpolicy.yaml
config/samples/resources/rediscluster/redis_v1beta1_rediscluster.yaml
scripts/generate-google3-docs/resource-reference/generated/resource-docs/redis/rediscluster.md

feat: Add sample test for RedisCluster

---

mockgcp/mockcompute/globalforwardingrulesv1.go
mockgcp/mockcompute/regionalforwardingrulev1.go
pkg/controller/direct/compute/forwardingrule/forwardingrule_controller.go
pkg/controller/direct/compute/forwardingrule/refs.go
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/regionalcomputeforwardingrulefull/_generated_object_regionalcomputeforwardingrulefull.golden.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/regionalcomputeforwardingrulefull/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/regionalcomputeforwardingrulefull/create.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/regionalcomputeforwardingrulefull/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/regionalcomputeforwardingrulefull/update.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/regionalforwardingrulepsc/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeserviceattachment/_http.log

- update `labels` and `allowGlobalAccess` field
- have to comment out `serviceDirectoryRegistrations` field, because forwarding rule integrates with serviceDirectoryRegistrations cannot be updated.
git diff between realGCP w/TF controller: https://paste.googleplex.com/5031876684414976, only API version diffs and they are expected.

test: (part2)update regional forwarding rule full test

---

README.md
docs/develop-resources/README.md
mockgcp/README.md

doc: fix jargon and clean up stale doc

---

scripts/generate-google3-docs/resource-reference/_toc.yaml
scripts/generate-google3-docs/resource-reference/overview.md

Update toc and overview for RedisCluster

---

config/tests/samples/create/harness.go
mockgcp/mockmonitoring/metricdescriptor.go
mockgcp/mockmonitoring/service.go
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringmetricdescriptor/_generated_object_monitoringmetricdescriptor.golden.yaml
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringmetricdescriptor/_http.log

- **mockgcp: golden output for MonitoringMetricDescriptor**
- **mockgcp: support for MonitoringMetricDescriptor**

mockgcp: support for MonitoringMetricDescriptor

---

mockgcp/mockserviceusage/service.go
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbcluster/fullalloydbcluster/_http.log
pkg/test/resourcefixture/testdata/basic/cloudbuild/v1beta1/cloudbuildworkerpool/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeserviceattachment/_http.log
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeature/acmfeature/_http.log
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeature/mcifeature/_http.log
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeature/mcsdfeature/_http.log
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicacmgkehubfeaturemembership/_http.log
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullacmgkehubfeaturemembership/_http.log
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/meshgkehubfeaturemembership/_http.log
pkg/test/resourcefixture/testdata/basic/secretmanager/v1beta1/fullsecretmanagersecret/_http.log
pkg/test/resourcefixture/testdata/basic/serviceusage/v1beta1/service/_http.log
pkg/test/resourcefixture/testdata/basic/serviceusage/v1beta1/serviceidentity/_http.log
pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-encryptionkey-direct/_http.log
pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-encryptionkey/_http.log
pkg/test/resourcefixture/testdata/basic/vertexai/v1beta1/vertexaidataset/vertexaidatasetencryptionkey/_http.log
pkg/test/resourcefixture/testdata/basic/vertexai/v1beta1/vertexaiendpoint/vertexaiendpointencryptionkey/_http.log
pkg/test/resourcefixture/testdata/iammemberreferences/serviceidentityref/_http.log
tests/e2e/normalize.go

- **mockgcp: improve fidelity of serviceusage**
- **tests: update golden output for serviceusage**

mockgcp: improve fidelity of serviceusage

---

docs/develop-resources/api-conventions/validations.md
docs/develop-resources/guides/3-add-mapper.md
docs/develop-resources/guides/4-add-controller.md
docs/develop-resources/scenarios/migrate-tf-resource-beta.md
mockgcp/README.md

docs: modifications on SciFi migraiton documents

---

dev/ci/periodics/e2e-service-bigquery
dev/ci/periodics/e2e-service-dataflow
dev/ci/periodics/e2e-service-logging
dev/ci/periodics/e2e-service-monitoring
dev/ci/periodics/e2e-service-pubsub
dev/ci/periodics/e2e-service-redis
dev/ci/periodics/e2e-service-securesourcemanager
dev/ci/periodics/e2e-service-sql
scripts/github-actions/tests-e2e-fixtures-compute
scripts/github-actions/tests-e2e-fixtures-gkehub
tests/e2e/unified_test.go

Adding support for more services!

tests: add new CI test runs for bigquery

---

experiments/OWNERS

Removing old permissions which have aged out.
Also seperating experiment permissions from the primary product.
Fixes # N/A

Normalizing the repo reviwers and owners.

---

dev/tools/controllerbuilder/template/controller/controller.go

It should be set in the context already.

controllerbuilder: don't add log name

---

.github/workflows/presubmit.yaml

This should resolve the nodejs warnings

chore: update upload-artifact to v4

---

cmd/recorder/main.go

Fixes #2874
Built the change locally and verified that orphaned CRDs covered by the IgnoredCRDList won't cause the issue any more.

Skip ignored CRDs when listing CRDs in the recorder

---

pkg/controller/direct/common/labels.go
pkg/controller/direct/monitoring/client.go
pkg/controller/direct/monitoring/monitoringdashboard_controller.go

Some small non-functional changes to avoid the IDE giving us false-positive problem warnings.

chore: cleanup a few lint problems

---

experiments/compositions/composition/internal/controller/expander_reconciler.go

Change the error to info for missing composition context. 
Tested locally

[Compositions] Change missing context to info

---

CONTRIBUTING.md
Makefile

build:add deploy commands

---

dev/tools/controllerbuilder/template/controller/controller.go

Small changes to add learnings from the `Export` PRs I have been working on.

dev:tools: add export changes

---

config/tests/samples/create/samples.go

We should be logging the wrapped err.

tests: log wrapped err

---

.github/workflows/presubmit.yaml
apis/workstations/v1alpha1/workstationcluster_types.go
apis/workstations/v1alpha1/zz_generated.deepcopy.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_workstationclusters.workstations.cnrm.cloud.google.com.yaml
dev/ci/presubmits/test-mappers-roundtrip
pkg/clients/generated/apis/workstations/v1alpha1/workstationcluster_types.go
pkg/clients/generated/apis/workstations/v1alpha1/zz_generated.deepcopy.go
pkg/controller/direct/workstations/workstationcluster_controller.go
pkg/controller/direct/workstations/workstationcluster_mappings.go
pkg/fuzztesting/fuzzkrm.go
pkg/fuzztesting/fuzztests/fuzz_test.go

Fix some nits in the workstation cluster mapper also.

tests: create generic fuzz tester

---

experiments/compositions/expanders/helm-expander/Dockerfile
experiments/compositions/expanders/helm-expander/hack/update-images.sh

Add script to upgrade helm image.
Updated helm image.
Removed unused kustomize variable.

Add script to update images in expander-helm

---

pkg/controller/direct/sql/sqlinstance_controller.go

Create helper function to consolidate duplicate code.

chore: Cleanup duplicate LRO polling code

---

pkg/controller/direct/bigqueryconnection/connection_controller.go
pkg/test/resourcefixture/contexts/bigquery_context.go
pkg/test/resourcefixture/testdata/basic/bigqueryconnection/v1alpha1/bigqueryconnectionconnection/bigqueryconnectionconnectionfull/_generated_object_bigqueryconnectionconnectionfull.golden.yaml
pkg/test/resourcefixture/testdata/basic/bigqueryconnection/v1alpha1/bigqueryconnectionconnection/bigqueryconnectionconnectionfull/_http.log
pkg/test/resourcefixture/testdata/basic/bigqueryconnection/v1alpha1/bigqueryconnectionconnection/bigqueryconnectionconnectionfull/create.yaml
pkg/test/resourcefixture/testdata/basic/bigqueryconnection/v1alpha1/bigqueryconnectionconnection/bigqueryconnectionconnectionfull/update.yaml

chore: fix dynamic test for bigqueryconnectionconnection

---

pkg/test/resourcefixture/testdata/basic/bigqueryconnection/v1alpha1/bigqueryconnectionconnection/cloudspannerconnectionbasic/_http.log
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerdatabase/_http.log
pkg/test/resourcefixture/testdata/externalref/externalwithsubresource/_http.log

fix: presubmit test that depends on spannerInstance"

---

pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerinstance-basic/_generated_object_spannerinstance-basic.golden.yaml
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerinstance-basic/_http.log
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerinstance-basic/update.yaml
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerinstance-full/_generated_object_spannerinstance-full.golden.yaml
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerinstance-full/_http.log
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerinstance-full/update.yaml

Add changes to update.yaml for Spanner Instance

---

dev/tasks/list-tests
dev/tasks/run-e2e

Also a few small improvements.

tests: add the missing list-tests script for turbo-e2e

---

pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeature/acmfeature/_http.log
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeature/mcsdfeature/_http.log
pkg/test/resourcefixture/testdata/basic/kms/v1alpha1/kmsautokeyconfig/_http.log
pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogbucket/folderlogbucket/_http.log
pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardrefs/_http.log
pkg/test/resourcefixture/testdata/basic/privilegedaccessmanager/v1alpha1/privilegedaccessmanagerentitlement/privilegedaccessmanagerentitlementfullfolder/_http.log
pkg/test/resourcefixture/testdata/basic/resourcemanager/v1beta1/folder/folderinfolder/_http.log
pkg/test/resourcefixture/testdata/basic/resourcemanager/v1beta1/folder/foldermovedfoldertofolder/_http.log
pkg/test/resourcefixture/testdata/basic/resourcemanager/v1beta1/project/projectinfolder/_http.log
pkg/test/resourcefixture/testdata/basic/resourcemanager/v1beta1/project/projectmovedfoldertofolder/_http.log
pkg/test/resourcefixture/testdata/containerannotations/folderid/_http.log
tests/e2e/unified_test.go

Reducing the size of the bigger refactor to how replacements happen.

tests: switch placeholder from testFolderId -> folderID

---

mockgcp/common/fields/updatemask.go

feat: simplify the mockgcp UPDATE based on field-mask

---

docs/develop-resources/deep-dives/5-releases.md

docs: Update 5-releases.md

---

mockgcp/mockbigqueryconnection/connection.go
pkg/controller/direct/bigqueryconnection/connection_controller.go
pkg/controller/direct/bigqueryconnection/connection_mapping.go
pkg/test/resourcefixture/testdata/basic/bigqueryconnection/v1alpha1/bigqueryconnectionconnection/awsconnectionbasic/_http.log
pkg/test/resourcefixture/testdata/basic/bigqueryconnection/v1alpha1/bigqueryconnectionconnection/azureconnectionbasic/_http.log
pkg/test/resourcefixture/testdata/basic/bigqueryconnection/v1alpha1/bigqueryconnectionconnection/bigqueryconnectionconnectionfull/_http.log
pkg/test/resourcefixture/testdata/basic/bigqueryconnection/v1alpha1/bigqueryconnectionconnection/cloudspannerconnectionbasic/_generated_object_cloudspannerconnectionbasic.golden.yaml
pkg/test/resourcefixture/testdata/basic/bigqueryconnection/v1alpha1/bigqueryconnectionconnection/cloudspannerconnectionbasic/_http.log
pkg/test/resourcefixture/testdata/basic/bigqueryconnection/v1alpha1/bigqueryconnectionconnection/cloudspannerconnectionbasic/update.yaml

fix dynamic test cloudspannerconnectionbasic

---

mockgcp/mockredis/cluster.go
pkg/test/resourcefixture/testdata/basic/redis/v1beta1/basicrediscluster/_generated_object_basicrediscluster.golden.yaml
pkg/test/resourcefixture/testdata/basic/redis/v1beta1/basicrediscluster/_http.log
pkg/test/resourcefixture/testdata/basic/redis/v1beta1/fullrediscluster/_generated_object_fullrediscluster.golden.yaml
pkg/test/resourcefixture/testdata/basic/redis/v1beta1/fullrediscluster/_http.log
tests/e2e/normalize.go

This avoids the non-determinism

tests: normalize addresses for RedisInstance

---

mockgcp/mockbigquery/datasets.go
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/basicbigquerydataset/_generated_export_basicbigquerydataset.golden
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/basicbigquerydataset/_http.log
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/bigquerydatasetaccessblock/_generated_export_bigquerydatasetaccessblock.golden
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/bigquerydatasetaccessblock/_http.log
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable/_http.log
pkg/test/resourcefixture/testdata/basic/bigquerydatatransfer/v1beta1/bigquerydatatransferconfig/bigquerydatatransferconfig-salesforce/_http.log
pkg/test/resourcefixture/testdata/basic/bigquerydatatransfer/v1beta1/bigquerydatatransferconfig/bigquerydatatransferconfig-scheduledquery/_http.log
pkg/test/resourcefixture/testdata/basic/dataflow/v1beta1/dataflowflextemplatejob/streamingdataflowflextemplatejob/_http.log
pkg/test/resourcefixture/testdata/basic/pubsub/v1beta1/pubsubsubscription/bigquerypubsubsubscription/_http.log
pkg/test/resourcefixture/testdata/containerannotations/projectid/_generated_export_projectid.golden
pkg/test/resourcefixture/testdata/containerannotations/projectid/_http.log
pkg/test/resourcefixture/testdata/reconcileintervalannotations/bigquerydataset/_generated_export_bigquerydataset.golden
pkg/test/resourcefixture/testdata/reconcileintervalannotations/bigquerydataset/_http.log
pkg/test/resourcefixture/testdata/resourceid/referencewithuserspecifiedresourceid/_http.log
pkg/test/resourcefixture/testdata/resourceid/userspecifiedresourceid/_generated_export_userspecifiedresourceid.golden
pkg/test/resourcefixture/testdata/resourceid/userspecifiedresourceid/_http.log
pkg/test/resourcefixture/testdata/stateabsentinspec/bigquerydataset/_generated_export_bigquerydataset#01.golden
pkg/test/resourcefixture/testdata/stateabsentinspec/bigquerydataset/_http.log

tests:fix mockgcp for bigquery to mimic real GCP behavoir

---

docs/releasenotes/release-1.125.md

Add `DataExchange` for the upcoming release.

docs: Update release-1.125.md

---

dev/tools/controllerbuilder/cmd/root.go
dev/tools/controllerbuilder/pkg/commands/exportcsv/exportcsvcommand.go
dev/tools/controllerbuilder/pkg/commands/exportcsv/prompt.go
dev/tools/controllerbuilder/pkg/toolbot/csv.go
dev/tools/controllerbuilder/pkg/toolbot/datapoint.go
dev/tools/controllerbuilder/pkg/toolbot/enhancewithprotodefinition.go
dev/tools/controllerbuilder/pkg/toolbot/extracttoolmarkers.go
mockgcp/mockkms/cryptokey.go
mockgcp/mockkms/cryptokeyversion.go
mockgcp/mockkms/keyring.go
mockgcp/mocklogging/logbucket.go
mockgcp/mocklogging/logmetric.go
mockgcp/mocklogging/logview.go
mockgcp/mockpubsublite/reservation.go
mockgcp/mockpubsublite/subscription.go
mockgcp/mockpubsublite/topic.go

Splitting off from the CSV PR ( #2276 ) so that we can get this onto the main branch

feat: add gemini prompting to controllerbuilder

---

dev/tasks/turbo-e2e

tests: improve turbo-e2e tool to run on mac and linux

---

dev/widgets/retest
dev/widgets/whyfail

I find these handy, maybe others will also?

chore: add some experimental scripts for working with github

---

pkg/controller/direct/workstations/workstationcluster_controller.go
pkg/controller/direct/workstations/workstationcluster_externalresource.go
pkg/test/resourcefixture/testdata/basic/workstations/workstationcluster/workstationcluster-full/_generated_object_workstationcluster-full.golden.yaml
pkg/test/resourcefixture/testdata/basic/workstations/workstationcluster/workstationcluster-minimal/_generated_object_workstationcluster-minimal.golden.yaml

Can refactor the ref code into apis/ later, for now just a quick fix to use the correct format

fix: Remove service prefix from WorkstationCluster

---

apis/compute/v1beta1/computefirewallpolicyrule_reference.go
pkg/controller/direct/compute/firewallpolicyrule/firewallpolicyrule_controller.go

Address https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3035#discussion_r1831466329
Verify that the priority in externalRef(i.e. locations/global/firewallPolicies/${firewallPolicyID}/rules/**9000**) is an integer

Verify `priority` string in externalRef can be converted to an integer

---

pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicpocogkehubfeaturemembership/_generated_object_basicpocogkehubfeaturemembership.golden.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicpocogkehubfeaturemembership/_http.log
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicpocogkehubfeaturemembership/create.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicpocogkehubfeaturemembership/update.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullpocogkehubfeaturemembership/_generated_object_fullpocogkehubfeaturemembership.golden.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullpocogkehubfeaturemembership/_http.log
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullpocogkehubfeaturemembership/create.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullpocogkehubfeaturemembership/update.yaml

Fix for error
```
=== NAME  TestCreateNoChangeUpdateDelete/gkehub/basic-basicpocogkehubfeaturemembership
dynamic_controller_integration_test.go:234: reconcile for GKEHubFeatureMembership:spo7ttueh7h4kei/gkehubfeaturemembership-basic-poco-spo7ttueh7h4kei took 2.541537647s, result was ({false 0s}, Update call failed: error applying desired state: googleapi: Error 400: InvalidValueError for field membership_specs["projects/xxxx/locations/us-central1/memberships/gkehubmembership-basic-poco-spo7ttueh7h4kei"].feature_spec: does not match a current membership in this project. Keys should be in the form: projects/xxxx/locations/{l}/memberships/{m})
reconcile.go:191: error was not considered transient; chain is [[*fmt.wrapError: Update call failed: error applying desired state: googleapi: Error …
```

Fix poco test

---

docs/releasenotes/release-1.125.md

Add notes for WorkstationCluster and SQLInstance changes.

chore: Add release-1.125 release notes

---

dev/tools/controllerbuilder/generate.sh
dev/tools/controllerbuilder/pkg/codegen/generatorbase.go
dev/tools/controllerbuilder/pkg/codegen/mappergenerator.go
dev/tools/controllerbuilder/pkg/codegen/typegenerator.go
dev/tools/controllerbuilder/pkg/commands/generatetypes/generatetypescommand.go

Otherwise our types.generated.go was being overwritten

chore: support multiple resources in controllerbuilder

---

config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_cloudbuildtriggers.cloudbuild.cnrm.cloud.google.com.yaml
pkg/clients/generated/apis/cloudbuild/v1beta1/cloudbuildtrigger_types.go
scripts/generate-google3-docs/resource-reference/generated/resource-docs/cloudbuild/cloudbuildtrigger.md
third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/services/cloudbuild/resource_cloudbuild_trigger.go

doc: fix description for CloudBuildTrigger

---

tests/e2e/unified_test.go

tests: vcr: minor revisions

---

config/samples/resources/cloudfunctionsfunction/eventtrigger-with-pubsubtopic/cloudfunctions_v1beta1_cloudfunctionsfunction.yaml
pkg/controller/direct/logging/logbucketref.go
pkg/controller/ratelimiter/ratelimiter.go
pkg/k8s/references.go
scripts/generate-google3-docs/resource-reference/_toc.yaml
scripts/generate-google3-docs/resource-reference/generated/resource-docs/cloudfunctions/cloudfunctionsfunction.md

discovered this during kcc release

fix: typo in kcc doc

---

tests/apichecks/crds_test.go
tests/apichecks/testdata/exceptions/sensitive.txt

feat: Check if CRD contains sensitive data

---

mockgcp/Makefile
mockgcp/apis/mockgcp/cloud/apigee/v1/service.proto
mockgcp/apis/mockgcp/cloud/bigquery/v2/api.proto
mockgcp/apis/mockgcp/cloud/ids/v1/service.proto
mockgcp/apis/mockgcp/cloud/kms/v1/service.proto
mockgcp/apis/mockgcp/cloud/networkconnectivity/v1/networkconnectivity.proto
mockgcp/apis/mockgcp/cloud/servicenetworking/v1/servicenetworking.proto
mockgcp/apis/mockgcp/storage/v1/service.proto
mockgcp/tools/gapic/pkg/protogen/convert.go
mockgcp/tools/gapic/pkg/protogen/render.go

Also, fixes the comments, so they are now applied.

feat: Add support for nested arrays to gapic converter

---

docs/releasenotes/release-1.125.md
docs/releasenotes/release-1.126.md
docs/releasenotes/release-1.127.md

doc: rewrote 1.125 release note

---

pkg/controller/direct/bigqueryconnection/connection_controller.go
pkg/test/resourcefixture/testdata/basic/bigqueryconnection/v1beta1/bigqueryconnectionconnection/awsconnectionbasic/_generated_object_awsconnectionbasic.golden.yaml
pkg/test/resourcefixture/testdata/basic/bigqueryconnection/v1beta1/bigqueryconnectionconnection/awsconnectionbasic/_http.log

fix: bqcc aws identity output-only and required in update

---

apis/refs/v1beta1/computerefs.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_computefirewallpolicyrules.compute.cnrm.cloud.google.com.yaml
scripts/generate-google3-docs/resource-reference/generated/resource-docs/compute/computefirewallpolicyrule.md

docs: Fix description for ComputeFirewallPolicyRef

---

pkg/controller/direct/cloudbuild/workerpool_controller.go
pkg/test/resourcefixture/testdata/basic/cloudbuild/v1beta1/cloudbuildworkerpool/_http.log

Try to fix flaky samples

---

dev/tools/controllerbuilder/cmd/root.go
dev/tools/controllerbuilder/generate.sh
dev/tools/controllerbuilder/pkg/commands/generatecontroller/generatecontrollercommand.go
dev/tools/controllerbuilder/pkg/commands/generatedirectreconciler/command.go
dev/tools/controllerbuilder/pkg/commands/generatemapper/generatemappercommand.go
dev/tools/controllerbuilder/pkg/commands/generatetypes/generatetypescommand.go
dev/tools/controllerbuilder/template/apis/types.go

feat: a simple cmd to add a basic scifi reconciler

---

apis/gkehub/v1beta1/featuremembership_types.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_gkehubfeaturememberships.gkehub.cnrm.cloud.google.com.yaml
pkg/clients/generated/apis/gkehub/v1beta1/gkehubfeaturemembership_types.go
pkg/gvks/supportedgvks/gvks_generated.go
tests/e2e/testdata/scenarios/fields/gkehubfeaturemembership/set_unset/_http03.log
tests/e2e/testdata/scenarios/fields/gkehubfeaturemembership/set_unset/_http04.log
tests/e2e/testdata/scenarios/fields/gkehubfeaturemembership/set_unset/_http05.log

Use gkehub direct controller.
I verified that post submit tests are passing for gkehubfeaturemembership resource.

Turn on gkehubfeaturemembership direct controller

---

pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computefirewallpolicyrule/computefirewallpolicyrule-egress-full-direct/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computefirewallpolicyrule/computefirewallpolicyrule-egress-full-direct/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computefirewallpolicyrule/computefirewallpolicyrule-egress-full/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computefirewallpolicyrule/computefirewallpolicyrule-egress-full/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computefirewallpolicyrule/computefirewallpolicyrule-ingress-full-direct/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computefirewallpolicyrule/computefirewallpolicyrule-ingress-full-direct/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computefirewallpolicyrule/computefirewallpolicyrule-ingress-full/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computefirewallpolicyrule/computefirewallpolicyrule-ingress-full/dependencies.yaml

Update compute firewall policy test description

---

scripts/generate-google3-docs/resource-reference/main.go

Moving deeply-nested singleton parameters to a type.

chore: start to refactor resource reference generator

---

CONTRIBUTING.md
README.ConfigureResourceReferences.md
apis/dataflow/v1beta1/types.generated.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_osconfigguestpolicies.osconfig.cnrm.cloud.google.com.yaml
crds/container_v1beta1_containercluster.yaml
crds/dns_v1beta1_dnsrecordset.yaml
crds/networkservices_v1alpha1_networkservicesedgecacheservice.yaml
crds/osconfig_v1beta1_osconfigguestpolicy.yaml
crds/privateca_v1beta1_privatecacertificate.yaml
crds/privateca_v1beta1_privatecacertificateauthority.yaml
crds/vertexai_v1alpha1_vertexaifeaturestoreentitytype.yaml
dev/tools/controllerbuilder/pkg/commands/updatetypes/updatetypescommand.go
dev/tools/controllerbuilder/scaffold/apis.go
docs/releasenotes/release-1.119.md
experiments/compositions/Design Notes/Controller Runtime and Dynamic Controllers.md
experiments/compositions/Design Notes/Feedback.md
experiments/kubectl-plan/pkg/plan/planner.go
mockgcp/README.md
mockgcp/mockgkehub/gkehubfeature.go
pkg/cli/outputsink/sink_test.go
pkg/clients/generated/apis/osconfig/v1beta1/osconfigguestpolicy_types.go
pkg/controller/direct/gkehub/acmconversion.go
pkg/dcl/fields.go
pkg/k8s/managedfields.go
pkg/test/controller/reconciler/testreconciler.go
pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableappprofile/create.yaml
scripts/generate-google3-docs/resource-reference/generated/resource-docs/osconfig/osconfigguestpolicy.md
third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/services/osconfig/resource_os_config_guest_policies.go
third_party/github.com/hashicorp/terraform-provider-google-beta/website/docs/r/os_config_guest_policies.html.markdown

[CHORE] Spelling 5/n

---

config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_discoveryenginedatastores.discoveryengine.cnrm.cloud.google.com.yaml
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_osconfigguestpolicies.osconfig.cnrm.cloud.google.com.yaml
scripts/generate-google3-docs/resource-reference/generated/resource-docs/osconfig/osconfigguestpolicy.md

Related to some recent spell check fixes.

chore: update doc due to merge issue

---

pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/basicbigquerydataset-direct/_http.log
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/basicbigquerydataset/_http.log
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/bigquerydatasetaccessblock-direct/_http.log
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/bigquerydatasetaccessblock/_http.log
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/fullybigquerydataset-direct/_http.log
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/fullybigquerydataset/_http.log
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable/_http.log
pkg/test/resourcefixture/testdata/basic/bigquerydatatransfer/v1beta1/bigquerydatatransferconfig/bigquerydatatransferconfig-salesforce/_http.log
pkg/test/resourcefixture/testdata/basic/bigquerydatatransfer/v1beta1/bigquerydatatransferconfig/bigquerydatatransferconfig-scheduledquery/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargettcpproxy/regionalcomputetargettcpproxy-direct/_http.log
pkg/test/resourcefixture/testdata/basic/dataflow/v1beta1/dataflowflextemplatejob/streamingdataflowflextemplatejob/_http.log
pkg/test/resourcefixture/testdata/basic/pubsub/v1beta1/pubsubsubscription/bigquerypubsubsubscription/_http.log
pkg/test/resourcefixture/testdata/containerannotations/projectid/_http.log
pkg/test/resourcefixture/testdata/reconcileintervalannotations/bigquerydataset/_http.log
pkg/test/resourcefixture/testdata/resourceid/referencewithuserspecifiedresourceid/_http.log
pkg/test/resourcefixture/testdata/resourceid/userspecifiedresourceid/_http.log
pkg/test/resourcefixture/testdata/stateabsentinspec/bigquerydataset/_http.log
tests/e2e/normalize.go
tests/e2e/unified_test.go

* Normalize the access list in BigQuery
* Update some headers for PRs that crossed.

chore: update e2e tests

---

.github/workflows/presubmit.yaml

feat: use `merge_group` action to avoid incompatible PRs

---

apis/bigqueryanalyticshub/v1beta1/dataexchange_types.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_bigqueryanalyticshubdataexchanges.bigqueryanalyticshub.cnrm.cloud.google.com.yaml
pkg/clients/generated/apis/bigqueryanalyticshub/v1beta1/bigqueryanalyticshubdataexchange_types.go
scripts/generate-google3-docs/resource-reference/generated/resource-docs/bigqueryanalyticshub/bigqueryanalyticshubdataexchange.md

Adds the CRD shortnames back for DataExchange

fix: crd shortnames

---

dev/ci/periodics/e2e-service-secretmanager
dev/tasks/create-test-project

tests: add e2e for secretmanager

---

dev/tools/controllerbuilder/template/apis/identity.go
dev/tools/controllerbuilder/template/apis/refs.go

fix: some direct scaffold typo 

---

mockgcp/Makefile
mockgcp/generated/google/bigtable/admin/v2/bigtable_instance_admin.pb.gw.go
mockgcp/generated/google/bigtable/admin/v2/bigtable_table_admin.pb.gw.go
mockgcp/go.mod

- **mockgcp: ping googleapis for GRPC generation also**
- **mockgcp: update generated GRPC bindings**

mockgcp: pin googleapis for GRPC generation also

---

pkg/test/utils.go

When there are a lot of dependent non-direct resources in the test case, the comparison between real GCP http log and mock GCP http log can be messy. With the new env var `ONLY_COMPARE_URL_PREFIX`, we can focus on the comparison of the target resource/API in the http log events.

Support env var to only compare http log events with given URL prefix

---

Makefile

chore: add fmt to `make ready-pr`

---

pkg/controller/direct/gkehub/diffs.go
pkg/controller/direct/gkehub/featuremembership_controller.go

Given that the server defaults values if certain fields are not set, the PR  Improves update method to avoid permanent diff

Improve update method to avoid permanent diff

---

config/tests/samples/create/harness.go
mockgcp/mockbigquery/routine.go
mockgcp/mockbigquery/service.go
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigqueryroutine/basicbigqueryroutine/_generated_object_basicbigqueryroutine.golden.yaml
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigqueryroutine/basicbigqueryroutine/_http.log
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigqueryroutine/basicbigqueryroutine/create.yaml
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigqueryroutine/basicbigqueryroutine/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigqueryroutine/basicbigqueryroutine/update.yaml
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigqueryroutine/fullybigqueryroutine/_generated_object_bigqueryroutineautogen.golden.yaml
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigqueryroutine/fullybigqueryroutine/_generated_object_fullybigqueryroutine.golden.yaml
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigqueryroutine/fullybigqueryroutine/_http.log
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigqueryroutine/fullybigqueryroutine/create.yaml
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigqueryroutine/fullybigqueryroutine/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigqueryroutine/fullybigqueryroutine/update.yaml

feat: add mockgcp for bigqueryroutine

---

dev/tasks/create-test-project

chore: enable bigquery in e2e

---

pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigqueryroutine/basicbigqueryroutine/_http.log
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigqueryroutine/fullybigqueryroutine/_http.log

Seems like the presubmit is blocked on this.

fix: regen logs

---

docs/releasenotes/release-1.126.md

Adds the awesome work by @ziyue-101 to the release notes.

docs:Update release-1.126.md

---

config/tests/samples/create/harness.go
mockgcp/mockprivateca/certificateauthority.go
pkg/test/resourcefixture/testdata/basic/privateca/v1beta1/privatecacertificateauthority/_generated_object_privatecacertificateauthority.golden.yaml
pkg/test/resourcefixture/testdata/basic/privateca/v1beta1/privatecacertificateauthority/_http.log
pkg/test/resourcefixture/testdata/basic/privateca/v1beta1/privatecacertificateauthority/create.yaml
pkg/test/resourcefixture/testdata/basic/privateca/v1beta1/privatecacertificateauthority/update.yaml

A private SecureSourceManagerInstance needs a CAPool with a CA. But there is no existing mock for it. So we implement a mock here, it may not be super accurate

Add MockPrivateCACertificateAuthority

---

pkg/test/fuzz/fuzz_test.go
pkg/test/fuzz/krmgen.go

Staging a filler I think we can use for KRM first fuzzing (where we start w a KRM struct rather than a proto message).
We can also use this filler (and extend it) to generate scenario tests in the future.

tests: stage random filler

---

config/samples/resources/iampolicymember/policy-member-with-bigqueryconnection-reference/bigqueryconnection_v1beta1_bigqueryconnectionconnection.yaml
config/samples/resources/iampolicymember/policy-member-with-bigqueryconnection-reference/iam_v1beta1_iampolicymember.yaml
config/samples/resources/iampolicymember/policy-member-with-bigqueryconnection-reference/secret.yaml
config/samples/resources/iampolicymember/policy-member-with-bigqueryconnection-reference/sql_v1beta1_sqldatabase.yaml
config/samples/resources/iampolicymember/policy-member-with-bigqueryconnection-reference/sql_v1beta1_sqlinstance.yaml
config/samples/resources/iampolicymember/policy-member-with-bigqueryconnection-reference/sql_v1beta1_sqluser.yaml
scripts/generate-google3-docs/resource-reference/generated/resource-docs/iam/iampolicymember.md

TESTED
```
$ go test -v -tags=integration ./config/tests/samples/create/ -run-tests policy-member-with-bigqueryconnection-reference
```

chore: add public sample for BigQueryConnection referenced by IAMPolicyMember

---

scripts/generate-google3-docs/resource-reference/generated/resource-docs/apigee/apigeeenvironment.md
scripts/generate-google3-docs/resource-reference/generated/resource-docs/iam/iampartialpolicy.md
scripts/generate-google3-docs/resource-reference/generated/resource-docs/iam/iampolicy.md
scripts/generate-google3-docs/resource-reference/main.go
scripts/generate-google3-docs/resource-reference/templates/shared/iamsupport.tmpl

ApigeeEnvironment does not support conditional IAM.

fix: Update docs for ApigeeEnvironment conditional IAM support

---

dev/tools/controllerbuilder/pkg/codegen/typegenerator.go

These were used in WorkstationConfig.

fix: Add known acronyms for type generator

---

scripts/generate-google3-docs/resource-reference/overview.md

Correct typo in autokey config documentation

---

pkg/test/fuzz/fuzz_test.go
pkg/test/fuzz/krmgen.go

This change adds an overrides func to deal with fields that look like a string but may behave differently. I'm removing the custom logic for enums and we can push it all in the overrides. We can build custom overrides like string -> int or string -> time and have those live closer to the filler too.

refactor:tests: add overrides

---

pkg/controller/direct/compute/targettcpproxy/targettcpproxy_controller.go
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargettcpproxy/regionalcomputetargettcpproxy-direct/_generated_object_regionalcomputetargettcpproxy-direct.golden.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargettcpproxy/regionalcomputetargettcpproxy-direct/create.yaml

Enable direct controller when location is set for regional target tcp proxy

feat: Enable direct controller for regional tcp proxy

---

mockgcp/mockbigqueryanalyticshub/analyticshub.go
pkg/test/resourcefixture/testdata/basic/bigqueryanalyticshub/v1alpha1/bigqueryanalyticshublisting-full/_generated_object_bigqueryanalyticshublisting-full.golden.yaml
pkg/test/resourcefixture/testdata/basic/bigqueryanalyticshub/v1alpha1/bigqueryanalyticshublisting-full/_http.log
pkg/test/resourcefixture/testdata/basic/bigqueryanalyticshub/v1alpha1/bigqueryanalyticshublisting-full/_http.log.real
pkg/test/resourcefixture/testdata/basic/bigqueryanalyticshub/v1alpha1/bigqueryanalyticshublisting-full/create.yaml
pkg/test/resourcefixture/testdata/basic/bigqueryanalyticshub/v1alpha1/bigqueryanalyticshublisting-full/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/bigqueryanalyticshub/v1alpha1/bigqueryanalyticshublisting-full/update.yaml

Adds the full test for a listing. Real passes too ✅

tests: add full listing suite

---

scripts/generate-google3-docs/resource-reference/_toc.yaml

fix: misspell in toc

---

apis/refs/v1beta1/computerefs.go
pkg/controller/direct/dataflow/refs.go
pkg/test/resourcefixture/testdata/basic/dataflow/v1beta1/dataflowflextemplatejob/dataflowflextemplatejob-direct-subnetwork/_generated_object_batchdataflowflextemplatejob-direct.golden.yaml
pkg/test/resourcefixture/testdata/basic/dataflow/v1beta1/dataflowflextemplatejob/dataflowflextemplatejob-direct-subnetwork/_generated_object_dataflowflextemplatejob-direct-subnetwork.golden.yaml
pkg/test/resourcefixture/testdata/basic/dataflow/v1beta1/dataflowflextemplatejob/dataflowflextemplatejob-direct-subnetwork/_http.log
pkg/test/resourcefixture/testdata/basic/dataflow/v1beta1/dataflowflextemplatejob/dataflowflextemplatejob-direct-subnetwork/create.yaml
pkg/test/resourcefixture/testdata/basic/dataflow/v1beta1/dataflowflextemplatejob/dataflowflextemplatejob-direct-subnetwork/dependencies.yaml

fix: dataflowflextemplatejob specialize subnetwork format

---

pkg/controller/direct/directbase/directbase_controller.go

small change to remove outdated comment

docs: Update directbase_controller.go

---

config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_bigqueryanalyticshublistings.bigqueryanalyticshub.cnrm.cloud.google.com.yaml
scripts/generate-google3-docs/resource-reference/generated/resource-docs/bigqueryanalyticshub/bigqueryanalyticshublisting.md

fix: PR merge issue

---

apis/refs/v1beta1/bigqueryref.go

Small fix for the external parsing

fix: table ref

---

config/samples/resources/gkehubfeaturemembership/configsync-auto-upgrade-feature-membership/container_v1beta1_containercluster.yaml
config/samples/resources/gkehubfeaturemembership/configsync-auto-upgrade-feature-membership/gkehub_v1beta1_gkehubfeature.yaml
config/samples/resources/gkehubfeaturemembership/configsync-auto-upgrade-feature-membership/gkehub_v1beta1_gkehubfeaturemembership.yaml
config/samples/resources/gkehubfeaturemembership/configsync-auto-upgrade-feature-membership/gkehub_v1beta1_gkehubmembership.yaml
config/samples/resources/gkehubfeaturemembership/configsync-auto-upgrade-feature-membership/resourcemanager_v1beta1_project.yaml
config/samples/resources/gkehubfeaturemembership/configsync-auto-upgrade-feature-membership/serviceusage_v1beta1_service.yaml
scripts/generate-google3-docs/resource-reference/generated/resource-docs/gkehub/gkehubfeaturemembership.md

Add sample to enable configsync autoupgrade

Add sample to enable configsync autoupgrade

---

docs/releasenotes/release-1.127.md

Add gkehubfeaturemembership new field in the release note

docs: gkehubfeaturemembership

---

apis/securesourcemanager/v1alpha1/instance_reference.go
config/tests/samples/create/harness.go
mockgcp/mocksecuresourcemanager/repository.go
pkg/controller/direct/registry/registry.go
pkg/controller/direct/securesourcemanager/mapper.generated.go
pkg/controller/direct/securesourcemanager/repository_controller.go
pkg/test/resourcefixture/testdata/basic/securesourcemanager/securesourcemanagerrepository/securesourcemanagerrepositorybasic/_generated_object_securesourcemanagerrepositorybasic.golden.yaml
pkg/test/resourcefixture/testdata/basic/securesourcemanager/securesourcemanagerrepository/securesourcemanagerrepositorybasic/_http.log
pkg/test/resourcefixture/testdata/basic/securesourcemanager/securesourcemanagerrepository/securesourcemanagerrepositorybasic/create.yaml
pkg/test/resourcefixture/testdata/basic/securesourcemanager/securesourcemanagerrepository/securesourcemanagerrepositorybasic/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/securesourcemanager/securesourcemanagerrepository/securesourcemanagerrepositoryfull/_generated_object_securesourcemanagerrepositoryfull.golden.yaml
pkg/test/resourcefixture/testdata/basic/securesourcemanager/securesourcemanagerrepository/securesourcemanagerrepositoryfull/_http.log
pkg/test/resourcefixture/testdata/basic/securesourcemanager/securesourcemanagerrepository/securesourcemanagerrepositoryfull/create.yaml
pkg/test/resourcefixture/testdata/basic/securesourcemanager/securesourcemanagerrepository/securesourcemanagerrepositoryfull/dependencies.yaml

Add SecureSourceManagerRepository controller and mockgcp

---

apis/workstations/v1alpha1/cluster_types.go
apis/workstations/v1beta1/cluster_types.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_workstationclusters.workstations.cnrm.cloud.google.com.yaml
scripts/generate-google3-docs/resource-reference/generated/resource-docs/workstations/workstationcluster.md
tests/apichecks/testdata/exceptions/shortnames.txt

Following up on https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3407 adding shortnames to WorkstationCluster.

fix:shortnames: worstationcluster

---

pkg/controller/direct/kms/keyhandle/keyhandle_controller.go

no-op on keyhandle update operation

---

dev/tools/controllerbuilder/template/controller/controller.go

fix: wrong var in controller template

---

dev/tools/controllerbuilder/go.mod
dev/tools/controllerbuilder/go.sum
dev/tools/controllerbuilder/pkg/commands/exportcsv/prompt.go
dev/tools/controllerbuilder/pkg/llm/gemini.go
dev/tools/controllerbuilder/pkg/toolbot/csv.go

feat: write prompt result to a file

---

dev/tools/controllerbuilder/cmd/codebot/main.go
dev/tools/controllerbuilder/generate.sh

Can we create a chatbot that is better than "generic" chatbots,
for coding KCC?

experiment: a command line interactive AI chatbot for KCC coding

---

dev/tools/controllerbuilder/cmd/codebot/main.go
dev/tools/controllerbuilder/cmd/ctf/main.go
dev/tools/controllerbuilder/pkg/codebot/chat.go
dev/tools/controllerbuilder/pkg/codebot/tools.go

- **experiment: a command line interactive AI chatbot for KCC coding**
- **codebot: create a simple capture-the-flag test**

codebot: create a simple capture-the-flag test

---

mockgcp/mockapigee/envgroupattachment.go

Stages the mock for ApigeeEnvgroupAttachment.
Not wired up yet I want to split things up in smaller PRs!

mockgcp: apigeeenvgroupattachement

---

.github/workflows/presubmit.yaml
Makefile
config/tests/samples/create/harness.go
dev/ci/presubmits/test-mockgcp
mockgcp/mock_http_roundtrip.go
mockgcp/mockgcptests/e2e_test.go
mockgcp/mockgcptests/harness.go
mockgcp/mockgcptests/project.go
mockgcp/mockgcptests/proxy.go
mockgcp/mockpubsub/testdata/topic/crud/_http.log
mockgcp/mockpubsub/testdata/topic/crud/script.yaml
mockgcp/mockstorage/testdata/bucket/crud/_http.log
mockgcp/mockstorage/testdata/bucket/crud/script.yaml

This can enable testing of mockgcp before we have the full controller etc.

tests: add mock tests that use gcloud

---

apis/networkconnectivity/v1alpha1/serviceconnectionpolicy_types.go
apis/privilegedaccessmanager/v1alpha1/entitlement_types.go
apis/privilegedaccessmanager/v1beta1/privilegedaccessmanagerentitlement_types.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_networkconnectivityserviceconnectionpolicies.networkconnectivity.cnrm.cloud.google.com.yaml
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_privilegedaccessmanagerentitlements.privilegedaccessmanager.cnrm.cloud.google.com.yaml
scripts/generate-google3-docs/resource-reference/generated/resource-docs/privilegedaccessmanager/privilegedaccessmanagerentitlement.md
tests/apichecks/testdata/exceptions/shortnames.txt

Missed these two in the big one https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3466

fix: last shortnames missing

---

dev/tools/controllerbuilder/cmd/benchmark/type/main.go
dev/tools/controllerbuilder/pkg/benchmark/const.go
dev/tools/controllerbuilder/pkg/io/cache.go
dev/tools/controllerbuilder/pkg/io/compare.go
dev/tools/controllerbuilder/pkg/io/replace.go
dev/tools/controllerbuilder/tasks/init-type
dev/tools/controllerbuilder/tasks/update-type

codebot: add a benchmark to evaluate the prediction job about API generation

---

pkg/controller/dcl/controller.go
pkg/dcl/clientconfig/config.go

This likely wasn't working correctly anyway.

chore: remove UserAgent live-mutation

---

config/tests/samples/create/harness.go
tests/e2e/unified_test.go

We now have a place for a simple affirmative test of the user agent.

tests: add some user agent verification to the unified tests

---

cmd/recorder/main.go

This will help with system load. With this change, K8s API server no longer needs to collect all resources when we fetch metrics.

feat: Watch resources to record metrics instead of List

---

dev/tools/controllerbuilder/cmd/codebot/notes.md
dev/tools/controllerbuilder/pkg/codebot/chat.go
dev/tools/controllerbuilder/pkg/codebot/registry.go
dev/tools/controllerbuilder/pkg/codebot/tool_edit_file.go
dev/tools/controllerbuilder/pkg/codebot/tool_find_in_workspace.go
dev/tools/controllerbuilder/pkg/codebot/tool_read_file.go
dev/tools/controllerbuilder/pkg/codebot/tool_verify_code.go
dev/tools/controllerbuilder/pkg/codebot/tools.go

Also start to clean up how we register and invoke tools.

codebot: add a few more tools

---

go.mod
go.sum
pkg/cli/outputsink/filename/filename.go
pkg/cli/outputsink/filename/safefilename.go
pkg/cli/outputsink/filename/safefilename_test.go
pkg/cli/outputsink/sink.go
pkg/cli/outputsink/sink_test.go

We should own this behaviour, so we can guarantee compatability.

chore: replace slugify dependency

---

dev/tools/controllerbuilder/cmd/codebot/main.go
dev/tools/controllerbuilder/cmd/ctf/main.go
dev/tools/controllerbuilder/go.mod
dev/tools/controllerbuilder/go.sum
dev/tools/controllerbuilder/pkg/codebot/chat.go
dev/tools/controllerbuilder/pkg/codebot/tool_edit_file.go
dev/tools/controllerbuilder/pkg/codebot/tool_find_in_workspace.go
dev/tools/controllerbuilder/pkg/codebot/tool_read_file.go
dev/tools/controllerbuilder/pkg/codebot/tool_verify_code.go
dev/tools/controllerbuilder/pkg/codebot/tools.go
dev/tools/controllerbuilder/pkg/llm/gemini.go
dev/tools/controllerbuilder/pkg/llm/interfaces.go
dev/tools/controllerbuilder/pkg/llm/ollama.go
dev/tools/controllerbuilder/pkg/llm/vertexai.go
dev/tools/controllerbuilder/pkg/toolbot/csv.go
dev/tools/controllerbuilder/pkg/toolbot/datapoint.go
dev/tools/controllerbuilder/pkg/typeupdater/insertfield-gemini.go
dev/tools/controllerbuilder/pkg/typeupdater/insertmessage-gemini.go

Helps us set up a nice abstraction, and useful for benchmarking.

codebot: support more LLMs (e.g. gemma)

---

mockgcp/mockcompute/regionaladdress.go
mockgcp/mockcompute/testdata/address/crud/_http.log
mockgcp/mockcompute/testdata/address/crud/script.yaml
mockgcp/mockcompute/utils.go
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeaddress/regionalcomputeaddress/_generated_object_regionalcomputeaddress.golden.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeaddress/regionalcomputeaddress/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrulepscgoogleapis-direct/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/regionalcomputeforwardingrule-direct/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/regionalcomputeforwardingrulepsc-direct/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeinstance/computeinstancebasicexample/_http.log
pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-privatenetwork-direct/_http.log
pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-privatenetwork-legacyref-direct/_http.log
pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-privatenetwork-legacyref/_http.log
pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-privatenetwork/_http.log
tests/e2e/normalize.go

- **mockgcp: test for compute address**
- **mockgcp: Capture golden output for mockcompute/testdata/address/crud**

mockgcp: test for compute address

---

dev/tools/controllerbuilder/pkg/toolbot/csv.go
dev/tools/controllerbuilder/pkg/toolbot/datapoint.go

- **codebot: support more LLMs (e.g. gemma)**
- **codebot: fix format of structured prompts**

controllerbuilder: fix formatting of prompts

---

pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/regionalcomputeforwardingrule-direct/_generated_object_regionalcomputeforwardingrule-direct.golden.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/regionalcomputeforwardingrule-direct/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/regionalcomputeforwardingrule-direct/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/regionalcomputeforwardingrule-direct/update.yaml

Fix TestCreateNoChangeUpdateDelete/compute/basic-regionalcomputeforwardingrule-direct
Error message: 
```
googleapi: Error 400: Invalid value for field 'resource.IPAddress': ''. A reserved IP should be specified for forwarding rule with target type TARGET_VPN_GATEWAY
```
go test -v -tags=integration ./pkg/controller/dynamic/ -test.run TestCreateNoChangeUpdateDelete -run-tests regionalcomputeforwardingrule-direct  -timeout 900s
--- PASS: TestCreateNoChangeUpdateDelete (0.17s)
--- PASS: TestCreateNoChangeUpdateDelete/compute (0.00s)
--- PASS: TestCreateNoChangeUpdateDelete/compute/basic-regionalcomputeforwardingrule-direct (160.30s)
PASS

Fix regionalcomputeforwardingrule-direct integration test

---

docs/releasenotes/release-1.128.md

Add SpannerInstance direct controller to release doc

---

scripts/shared-vars-public.sh

Fixes #
- [] Run `make ready-pr` to ensure this PR is ready for review.
- [] Perform necessary E2E testing for changed resources.

test: enable ssm api and add to long running list

---

config/tests/samples/create/harness.go
mockgcp/mockapigee/environment.go
mockgcp/mockapigee/service.go
pkg/test/resourcefixture/testdata/basic/apigee/v1beta1/apigeeenvironment/_generated_object_apigeeenvironment.golden.yaml
pkg/test/resourcefixture/testdata/basic/apigee/v1beta1/apigeeenvironment/_http.log

Adds the mock for `ApigeeEnvironment` so I can use it for the `ApigeeEnvgroupAttachement` mock.

mock: ApigeeEnvironment

---

scripts/shared-vars-public.sh

Follow up of #3534, fix string in shell script for correct parsing.
tested locally:
```
echo LONG_RUNNING_CRUD_TESTS_REGEX="basicalloydbbackup|\
basicalloydbinstance"
LONG_RUNNING_CRUD_TESTS_REGEX=basicalloydbbackup|basicalloydbinstance
```

Fix: Fix string parsing in shell

---

pkg/controller/direct/common/refs.go

chore: fix format validation for MonitoringAlertPolicyRef

---

docs/releasenotes/release-1.128.md
docs/releasenotes/release-1.129.md
docs/releasenotes/release-1.130.md

finalize 1.128 release note

---

dev/tasks/run-e2e

Fixes https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/3196 
`GKEHubFeatureMembership` is a direct resource as of 2/3 releases ago.

refactor: cleanup

---

dev/tools/controllerbuilder/template/apis/doc.go
dev/tools/controllerbuilder/template/apis/groupversion_info.go
dev/tools/controllerbuilder/template/apis/identity.go
dev/tools/controllerbuilder/template/apis/refs.go
dev/tools/controllerbuilder/template/apis/types.go
dev/tools/controllerbuilder/template/controller/controller.go

chore: update controllerbuilder template to year 2025

---

pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spanneinstance-unset-compute-fields/_generated_object_spanneinstance-unset-compute-fields.golden.yaml
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spanneinstance-unset-compute-fields/_http.log
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spanneinstance-unset-compute-fields/create.yaml
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spanneinstance-unset-compute-fields/update.yaml

Add Spanner instance unset compute field test

---

pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spanneinstance-unset-compute-fields/_generated_object_spanneinstance-unset-compute-fields.golden.yaml
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spanneinstance-unset-compute-fields/_http.log

Update golden log/object for fixtures/spanneinstance-unset-compute-fields

---

dev/tools/controllerbuilder/pkg/codebot/tool_run_cmd.go
dev/tools/controllerbuilder/pkg/codebot/tools.go
dev/tools/controllerbuilder/pkg/llm/vertexai.go

Let codebot to do some contributor work like  `go test ./tests/apichecks` `make ready-pr`, and it will try to fix from the result.

codebot: do KCC specific tasks like a developer

---

apis/alloydb/v1alpha1/instance_types.go
apis/alloydb/v1beta1/instance_types.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_alloydbinstances.alloydb.cnrm.cloud.google.com.yaml
pkg/gvks/supportedgvks/gvks_generated.go
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbcluster/basicsecondaryalloydbcluster/_http.log
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbinstance/basicalloydbinstance/_generated_object_basicalloydbinstance.golden.yaml
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbinstance/basicalloydbinstance/create.yaml
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbinstance/basicalloydbinstance/update.yaml
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbinstance/basicsecondaryalloydbinstance/_generated_object_basicsecondaryalloydbinstance.golden.yaml
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbinstance/basicsecondaryalloydbinstance/create.yaml
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbinstance/basicsecondaryalloydbinstance/update.yaml
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbinstance/fullalloydbinstance/_generated_object_fullalloydbinstance.golden.yaml
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbinstance/fullalloydbinstance/create.yaml
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbinstance/fullalloydbinstance/update.yaml
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbinstance/readalloydbinstance/_generated_object_readalloydbinstance.golden.yaml
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbinstance/readalloydbinstance/create.yaml
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbinstance/readalloydbinstance/update.yaml
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbinstance/zonalalloydbinstance/_generated_object_zonalalloydbinstance.golden.yaml
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbinstance/zonalalloydbinstance/create.yaml

Switched AlloyDBInstance to pure direct resource and updated test cases to reflect the change.
Noticed that we actually don't support resource conflict management so filed an issue #3620.

Switch AlloyDBInstance to pure direct resource

---

dev/tools/controllerbuilder/pkg/commands/generatecontroller/generatecontrollercommand.go
dev/tools/controllerbuilder/scaffold/controller.go

with this PR I can run `generate-controller` outside of the repo.

chore: run generate-controller anywhere

---

dev/tools/controllerbuilder/pkg/commands/exportcsv/prompt.go
dev/tools/controllerbuilder/pkg/llm/gemini.go
dev/tools/controllerbuilder/pkg/llm/interfaces.go
dev/tools/controllerbuilder/pkg/llm/ollama.go
dev/tools/controllerbuilder/pkg/llm/vertexai.go
dev/tools/controllerbuilder/pkg/toolbot/csv.go

This can give more consistent results than the chat method.

codebot: add support for completion method

---

dev/tools/controllerbuilder/template/controller/controller.go
pkg/controller/direct/apigee/envgroup_controller.go
pkg/controller/direct/apigee/instance_controller.go
pkg/controller/direct/firestore/firestoredatabase_controller.go
pkg/controller/direct/sql/sqlinstance_controller.go
pkg/controller/direct/workstations/cluster_controller.go
pkg/controller/direct/workstations/config_controller.go
pkg/controller/direct/workstations/workstation_controller.go

Also, log a message when this occurs.
This is a follow-up on @yuwenma 's comment here: https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3554#discussion_r1936547473

feat: Update controller template, skip delete for non-existent resources

---

dev/tasks/find-missing-fields
pkg/controller/direct/apigee/converters.go
pkg/controller/direct/apigee/envgroupattachment_mappings.go
pkg/controller/direct/apigee/roundtrip_test.go

Adds mapper and KRM based fuzzer for `ApigeeEnvironmentGroupAttachment`.

feat: mappers, fuzzz tests AEgA

---

dev/tools/controllerbuilder/cmd/resourcerunner/main.go
dev/tools/controllerbuilder/generate-proto.sh
dev/tools/controllerbuilder/pkg/commands/iteratetypes/command.go
proto-list-final.yaml

tool: find out all protos

---

pkg/controller/direct/apigee/roundtrip_test.go
pkg/test/utils.go

refactor: pretty prints

---

dev/tools/controllerbuilder/pkg/codebot/tool_edit_file.go

We try to match lines of context, and accept some fuzzy matching.
This is what the LLM keeps sending us, so we should probably work with it!

codebot: improve EditFile tool

---

dev/tools/controllerbuilder/template/controller/controller.go

* Updated `a.id` and `a.id.External` to `a.id.String()` to match the latest framework.
* Removed the status update when there is no diff.
* Updated NBSP to regular space.

Fix controller template

---

mockgcp/mockcompute/globalforwardingrulesv1.go
mockgcp/mockcompute/regionaltargethttpsproxiesv1.go
mockgcp/mockcompute/regionaltargettcpproxyv1.go
pkg/controller/direct/compute/forwardingrule/forwardingrule_controller.go
pkg/controller/direct/compute/utils.go
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/regionalcomputeforwardingrulepsc-direct/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/regionalcomputeforwardingrulepsc-direct/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeserviceattachment/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeserviceattachment/dependencies.yaml
pkg/test/resourcefixture/testdata_test.go

Error message:
```
googleapi: Error 400: Invalid value for field 'resource.targetService': 'https://www.googleapis.com/compute/v1/projects/cnrm-test-udo6e6om04up6ano/regions/us-central1/forwardingRules/computeforwardingrule-1-li7wpyaetbu34zq'. ServiceAttachment and Producer ForwardingRule should be in the same project., invalid
```
Need to specify the same project for the producer forwarding rule.
(Reference: https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/42f6aa96957a8d0f4475b01bc99df28a02a8a308/pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeserviceattachment/create.yaml#L21)
```
go test -v -tags=integration ./pkg/controller/dynamic/ -test.run TestCreateNoChangeUpdateDelete -run-tests regionalcomputeforwardingrulepsc-direct  -timeout 900s …
```

Fix regionalcomputeforwardingrulepsc-direct integration test

---

dev/tools/controllerbuilder/pkg/llm/gemini.go
dev/tools/controllerbuilder/pkg/llm/vertexai.go

codebot: retry with jitter on 429

---

scripts/crd-tools/cmd/removedescriptions/removedescriptions.go
scripts/crd-tools/main.go
scripts/crd-tools/pkg/objectvisitor/objectvisitor.go

This is super-handy for diffing CRDs

crd-tools: add command to remove descriptions

---

experiments/conductor/cmd/runner/scripts/crd_mapper_fuzzer/02-generate-spec-and-status.sh
experiments/conductor/cmd/runner/scripts/crd_mapper_fuzzer/03-generate-fuzzer.sh
experiments/conductor/cmd/runner/scripts/crd_mapper_fuzzer/_generate-resource.sh
experiments/conductor/cmd/runner/scripts/crd_mapper_fuzzer/generate-service-dataproc.sh
experiments/conductor/cmd/runner/scripts/mockgcp/01-generate-script.sh
experiments/conductor/cmd/runner/scripts/mockgcp/02-run-script-real-gcp.sh
experiments/conductor/cmd/runner/scripts/mockgcp/03-implement-mocks.sh
experiments/conductor/cmd/runner/scripts/mockgcp/03a-add-to-makefile.sh
experiments/conductor/cmd/runner/scripts/mockgcp/04-run-script-mockgcp.sh
experiments/conductor/cmd/runner/scripts/mockgcp/_generate-resource.sh
experiments/conductor/cmd/runner/scripts/mockgcp/do-service-iam.sh

Not feeling passionate about the headers here; we can also ignore but either way I think we should check in one of the solutions bc it's making the validations CI sad.

add headers

---

dev/tools/controllerbuilder/pkg/toolbot/csv.go
dev/tools/controllerbuilder/pkg/toolbot/enhancewithprotodefinition.go

Some of the fixes that I added to generate https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3791

refactor: small changes

---

mockgcp/mockspanner/admin/database.go
mockgcp/mockspanner/admin/instance.go
mockgcp/mockspanner/testdata/backupschedules/crud/_http.log
mockgcp/mockspanner/testdata/backupschedules/crud/script.yaml

Add mock for spanner backup schedule

---

experiments/conductor/branches-all.yaml
experiments/conductor/cmd/runner/mock_commands.go
experiments/conductor/cmd/runner/runner.go
experiments/conductor/cmd/runner/utilities.go

Added functionality to attempt to determine the proto path. Also added better handling of stderr.
./bin/conductor runner --branch-repo=/usr/local/google/home/wfender/go/src/github.com/cheftako/k8s-config-connector_branches --branch-conf=branches-all.yaml --logging-dir=./logs --command=-1

Added better handling of Proto Path.

---

config/tests/samples/create/harness.go
mockgcp/mockgcptests/e2e_test.go
mockgcp/mockgcptests/harness.go
mockgcp/mockgcptests/proxy.go
mockgcp/mocknotebooks/instance.go
mockgcp/mocknotebooks/testdata/instance/crud/_http.log
mockgcp/mocknotebooks/testdata/instance/crud/script.yaml
tests/e2e/normalize.go
tests/e2e/replacements.go

Adding mocks for vertex notebook

Add mocks for vertex notebook

---

dev/tools/controllerbuilder/template/controller/controller.go

Just a small change that I noticed could make AI/ developers' life easier 😛

tool:template: sets

---

experiments/conductor/branches-all.yaml
experiments/conductor/cmd/runner/runner.go

Fix up metadata and add split metadata functionality.
Added hint in square brackets to help for operation type.
./bin/conductor runner --branch-repo=/usr/local/google/home/wfender/go/src/github.com/cheftako/k8s-config-connector_branches --branch-conf=branches-all.yaml --logging-dir=./logs --command=1
./bin/conductor runner --branch-repo=/usr/local/google/home/wfender/go/src/github.com/cheftako/k8s-config-connector_branches --branch-conf=branches-all.yaml --logging-dir=./logs --command=-2

Fix up metadata and add split metadata functionality.

---

pkg/test/resourcefixture/testdata/basic/vertexai/v1alpha1/metadatastore/metadatastorebasic/_http.log
pkg/test/resourcefixture/testdata/basic/vertexai/v1alpha1/metadatastore/metadatastorefullyconfigured/_http.log
pkg/test/resourcefixture/testdata/basic/vertexai/v1beta1/vertexaiendpoint/vertexaiendpointbasic/_http.log
pkg/test/resourcefixture/testdata/basic/vertexai/v1beta1/vertexaiendpoint/vertexaiendpointencryptionkey/_http.log
pkg/test/resourcefixture/testdata/basic/vertexai/v1beta1/vertexaiendpoint/vertexaiendpointnetwork/_http.log

Seems to have been a merge conflict.

fix: Fix vertexai presubmits

---

OWNERS

Adding Jingyi to the approvers list.
N/A

Adding Jingyi to the approvers list.

---

docs/releasenotes/release-1.129.md

1.129-release note

---

mockgcp/mock_http_roundtrip.go
mockgcp/mockdocumentai/processors.go
mockgcp/mockdocumentai/service.go
mockgcp/mockdocumentai/versions.go

mockGCP: documentai processor and version

---

experiments/conductor/cmd/runner/scripts/controller/_generate-controller.sh
experiments/conductor/cmd/runner/scripts/controller/llm-fix-gobuild.txt
experiments/conductor/cmd/runner/scripts/controller/llm-gcp-imports.txt

feat: add controller generator

---

experiments/conductor/cmd/runner/utilities.go

Minor upgrade: Separate logs for each step for easier debugging
example result: https://screenshot.googleplex.com/5KGtVA9xusjMaBr.png

tool: Separate log output for each step

---

experiments/conductor/cmd/runner/mock_commands.go
experiments/conductor/cmd/runner/runner.go

Support command to view generated files in conductor

---

config/tests/samples/create/harness.go

Only artifacts, because we keep our golden log for GCP.
This gives a more complete picture of what is happening.

tests: capture kube-apiserver logs into artifacts

---

experiments/conductor/cmd/runner/runner.go

* Adjust setSkipOnBranchModifier logic to just use partial command without --help. Because with --help some of the help text contained 'create' resulting in false positives
* Use commandExecute in skip metadata modifier

Conductore: modify setSkipOnBranchModifier logic

---

experiments/conductor/branches-all.yaml

Making a small yaml contribution to patch the metadata; next ones might be batches!

conductor:branches: fix ai model

---

experiments/conductor/cmd/runner/crd_generator_commands.go
experiments/conductor/cmd/runner/mock_commands.go
experiments/conductor/cmd/runner/utilities.go

Fix retry count logic and update deterministic steps retry to 1

---

pkg/webhook/immutable_fields_validator.go
pkg/webhook/immutable_fields_validator_test.go

Fixes #3830
Added test case to ensure direct resources are always allowed by the immutable validator.

Avoid fetching resource config for direct resources

---

pkg/test/eventsink.go

This should hopefully help with the problem we're hitting with
control characters in yaml.

eventsink: fallback to JSON marshal in DirectoryEventSink

---

mockgcp/mockstorage/folder.go
mockgcp/mockstorage/objects.go
mockgcp/mockstorage/service.go
mockgcp/mockstorage/testdata/folder/crud/_http.log
mockgcp/mockstorage/testdata/folder/crud/script.yaml
pkg/test/resourcefixture/testdata/basic/dataflow/v1beta1/dataflowflextemplatejob/batchdataflowflextemplatejob-direct/_http.log
pkg/test/resourcefixture/testdata/basic/dataflow/v1beta1/dataflowflextemplatejob/batchdataflowflextemplatejob/_http.log
pkg/test/resourcefixture/testdata/basic/dataflow/v1beta1/dataflowflextemplatejob/dataflowflextemplatejob-direct-subnetwork/_http.log
pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogsink/orgsink/_http.log
pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-auditconfig-direct/_http.log
pkg/test/resourcefixture/testdata/basic/storage/v1beta1/storagebucket/storagebucketbasic/_http.log
pkg/test/resourcefixture/testdata/basic/storage/v1beta1/storagebucket/storagebucketsoftdelete/_http.log
pkg/test/resourcefixture/testdata/basic/storage/v1beta1/storagebucket/storagebucketzero/_http.log
pkg/test/resourcefixture/testdata/basic/storage/v1beta1/storagenotification/storagenotificationbase/_http.log
pkg/test/resourcefixture/testdata/basic/storage/v1beta1/storagenotification/storagenotificationfull/_http.log
pkg/test/resourcefixture/testdata/directives/forcedestroy/_http.log
pkg/test/resourcefixture/testdata/reconcileintervalannotations/storagebucket/_http.log
pkg/test/resourcefixture/testdata/stateabsentinspec/clusterleveloverride/_http.log

Create a mock for resource storage folder

---

mockgcp/Makefile
mockgcp/mockdataproc/service.go
mockgcp/mockdataproc/testdata/workflowtemplate/crud/_http.log
mockgcp/mockdataproc/testdata/workflowtemplate/crud/script.yaml
mockgcp/mockdataproc/workflowtemplate.go

Create mock for resource dataproc workflowtemplate

---

experiments/conductor/cmd/runner/mock_commands.go

* Include instructions to generate pre and post steps
* Include restrictions on variables to be used in the commands
* Include instructions to set all required params
Update logic to remove existing script file when --force flag is passed.
This prevents the case where codebot fails when it sees the file already present.

Conductor: gcloud Script generation improvements

---

mockgcp/mockgcptests/e2e_test.go

Support pre and post steps in gcloud script yaml.
We dont use proxy for pre and post commands. 
We dont yet sort the commands. We want to run them as they appear in the script in order. 
```
- pre: gcloud pubsub topics create test-topic-${uniqueId} --project=${projectId}
- exec: gcloud asset feeds create test-${uniqueId} --pubsub-topic=projects/${projectId}/topics/test-topic-${uniqueId} --project=${projectId}
- exec: gcloud asset feeds describe test-${uniqueId} --project=${projectId}
- exec: gcloud asset feeds update test-${uniqueId} --project=${projectId} --content-type=resource
- exec: gcloud asset feeds delete test-${uniqueId} --project=${projectId}
- post: gcloud pubsub topics delete test-topic-${uniqueId} --project=${projectId}
```  
This is a backward compatible change. Existing …

Support pre and post steps in gcloud script yaml

---

experiments/conductor/cmd/runner/github_commands.go

tool: Checkout master before creating new branch

---

Makefile
go.mod

Make ensure

---

mockgcp/mockgcptests/e2e_test.go

We still need the proxy for pre and post, we just don't want to capture the events.

mockgcp tests: only capture events from "normal" steps

---

mockgcp/mockbigtable/appprofile.go
mockgcp/mockbigtable/testdata/appprofile/crud/_http.log
mockgcp/mockbigtable/testdata/appprofile/crud/script.yaml
tests/e2e/httplog.go

mockGCP: Resource bigtable appprofile

---

mockgcp/Makefile
mockgcp/mockbigtable/testdata/appprofile/crud/_http.log
mockgcp/mockstorage/managedfolder.go
mockgcp/mockstorage/normalize.go
mockgcp/mockstorage/objects.go
mockgcp/mockstorage/service.go
mockgcp/mockstorage/testdata/folder/crud/_http.log
mockgcp/mockstorage/testdata/managedfolder/crud/_http.log
mockgcp/mockstorage/testdata/managedfolder/crud/script.yaml
pkg/test/resourcefixture/testdata/basic/dataflow/v1beta1/dataflowflextemplatejob/batchdataflowflextemplatejob-direct/_http.log
pkg/test/resourcefixture/testdata/basic/dataflow/v1beta1/dataflowflextemplatejob/batchdataflowflextemplatejob/_http.log
pkg/test/resourcefixture/testdata/basic/dataflow/v1beta1/dataflowflextemplatejob/dataflowflextemplatejob-direct-subnetwork/_http.log
pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogsink/orgsink/_http.log
pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-auditconfig-direct/_http.log
pkg/test/resourcefixture/testdata/basic/storage/v1beta1/storagebucket/storagebucketbasic/_http.log
pkg/test/resourcefixture/testdata/basic/storage/v1beta1/storagebucket/storagebucketsoftdelete/_http.log
pkg/test/resourcefixture/testdata/basic/storage/v1beta1/storagebucket/storagebucketzero/_http.log
pkg/test/resourcefixture/testdata/basic/storage/v1beta1/storagenotification/storagenotificationbase/_http.log
pkg/test/resourcefixture/testdata/basic/storage/v1beta1/storagenotification/storagenotificationfull/_http.log
pkg/test/resourcefixture/testdata/directives/forcedestroy/_http.log
pkg/test/resourcefixture/testdata/reconcileintervalannotations/storagebucket/_http.log
pkg/test/resourcefixture/testdata/stateabsentinspec/clusterleveloverride/_http.log

Create a mock for resource storage managedfolder

---

apis/composer/v1alpha1/generate.sh
config/tests/samples/create/harness.go
mockgcp/mockcomposer/environment.go
pkg/controller/direct/composer/environment_controller.go
pkg/test/resourcefixture/testdata/basic/composer/v1alpha1/composerenvironment/_generated_object_composerenvironment.golden.yaml
pkg/test/resourcefixture/testdata/basic/composer/v1alpha1/composerenvironment/_http.log
pkg/test/resourcefixture/testdata/basic/composer/v1alpha1/composerenvironment/create.yaml
pkg/test/resourcefixture/testdata/basic/composer/v1alpha1/composerenvironment/update.yaml

Support ComposerEnvironment  direct controller.
Dynamic test using the real API passed locally.

ComposerEnvironment direct controller

---

experiments/conductor/cmd/runner/utilities.go

This makes it easier to see what conductor is doing.

conductor: echo stdout/stderr even when capturing

---

mockgcp/Makefile
mockgcp/mock_http_roundtrip.go
mockgcp/mockedgecontainer/cluster.go
mockgcp/mockedgecontainer/service.go
mockgcp/mockedgecontainer/testdata/vpnconnection/crud/_http.log
mockgcp/mockedgecontainer/testdata/vpnconnection/crud/script.yaml
mockgcp/mockedgecontainer/vpnconnection.go
pkg/test/resourcefixture/testdata/basic/edgecontainer/v1beta1/edgecontainercluster/_generated_object_edgecontainercluster.golden.yaml
pkg/test/resourcefixture/testdata/basic/edgecontainer/v1beta1/edgecontainercluster/_http.log
pkg/test/resourcefixture/testdata/basic/edgecontainer/v1beta1/edgecontainernodepool/_http.log

Create a mockd for resource edgecontainer vpnconnection

---

mockgcp/mockapphub/discoveredservice.go
mockgcp/mockapphub/service.go
mockgcp/mockapphub/testdata/discoveredservice/crud/_http.log
mockgcp/mockapphub/testdata/discoveredservice/crud/script.yaml

Create mock for resource apphub discoveredservice

---

mockgcp/mockapphub/testdata/discoveredservice/crud/_http.log

fix: Remove Cache-Control header

---

experiments/conductor/cmd/runner/crd_generator_commands.go
experiments/conductor/cmd/runner/mock_commands.go
experiments/conductor/cmd/runner/runner.go
experiments/conductor/cmd/runner/utilities.go

conductor: Refactor to simplify each branch function
processBranches calls branchFunction for each branch and handles common:
* logging setup
* branchCheckout
* git staging and commits
* make ready-pr (and other checks in future)

conductor: Refactor to simplify each branch function

---

operator/channels/packages/configconnector/1.127.0/cluster/workload-identity/0-cnrm-system.yaml
operator/channels/packages/configconnector/1.127.0/namespaced/0-cnrm-system.yaml
operator/channels/packages/configconnector/1.127.0/namespaced/per-namespace-components.yaml
operator/channels/packages/configconnector/1.128.0/cluster/workload-identity/0-cnrm-system.yaml
operator/channels/packages/configconnector/1.128.0/namespaced/0-cnrm-system.yaml
operator/channels/packages/configconnector/1.128.0/namespaced/per-namespace-components.yaml
operator/channels/packages/configconnector/1.129.2/cluster/workload-identity/0-cnrm-system.yaml
operator/channels/packages/configconnector/1.129.2/namespaced/0-cnrm-system.yaml
operator/channels/packages/configconnector/1.129.2/namespaced/per-namespace-components.yaml
operator/config/channels/cluster-workload-identity/manager_sidecar_patch.yaml
operator/config/channels/cluster-workload-identity/recorder_sidecar_patch.yaml
operator/config/channels/namespaced-main/recorder_sidecar_patch.yaml
operator/config/channels/namespaced-per-namespace-components/manager_sidecar_patch.yaml
operator/config/gke-addon/image_configmap.yaml
operator/scripts/update-kcc-manifest/manager_sidecar_patch.yaml
operator/scripts/update-kcc-manifest/recorder_sidecar_patch.yaml

Ran ./hack/update-images.sh
Updated the version of prometheus-to-sd

Updated prom-to-sd for CVE

---

mockgcp/mockbigtable/appprofile.go
mockgcp/mockbigtable/authorizedview.go
mockgcp/mockbigtable/instance.go
mockgcp/mockbigtable/service.go
mockgcp/mockbigtable/table.go
mockgcp/mockbigtable/testdata/authorizedview/crud/_http.log
mockgcp/mockbigtable/testdata/authorizedview/crud/authorized_view.json
mockgcp/mockbigtable/testdata/authorizedview/crud/script.yaml
mockgcp/mockspanner/testdata/backupschedules/crud/_http.log

mockGCP: Resource bigtable authorizedview

---

experiments/conductor/branches-all.yaml
experiments/conductor/cmd/runner/scripts/controller/01-create-controller-client.sh
experiments/conductor/cmd/runner/scripts/controller/02-create-controller.sh
experiments/conductor/cmd/runner/scripts/controller/03-create-identity.sh
experiments/conductor/cmd/runner/scripts/controller/04-create-test.sh
experiments/conductor/cmd/runner/scripts/controller/05-capture-golden-test-output.sh
experiments/conductor/cmd/runner/scripts/controller/_generate-resource.sh
experiments/conductor/cmd/runner/scripts/controller/generate-resource-targetsite.sh
experiments/conductor/cmd/runner/scripts/controller/generate-service-tpu.sh
experiments/conductor/cmd/runner/scripts/controller/notes.md
pkg/controller/direct/dataflow/client.go
pkg/controller/direct/discoveryengine/datastore_controller.go
pkg/controller/direct/monitoring/client.go

- **DiscoveryEngineSiteConfig: update metadata**
- **Add notes for Controller gen**
- **chore: add some annotations to start to guide generation**
- **chore: upload scripts for creating controllers**

chore: upload scripts for creating controllers

---

mockgcp/Makefile
mockgcp/mockbatch/job.go
mockgcp/mockbatch/service.go
mockgcp/mockbatch/task.go
mockgcp/mockbatch/testdata/task/crud/_http.log
mockgcp/mockbatch/testdata/task/crud/job.json
mockgcp/mockbatch/testdata/task/crud/script.yaml

Create mock for resource batch task

---

mockgcp/mockbigtable/backup.go
mockgcp/mockbigtable/service.go
mockgcp/mockbigtable/testdata/backup/crud/_http.log
mockgcp/mockbigtable/testdata/backup/crud/script.yaml
tests/e2e/normalize.go

mockGCP: Resource bigtable backup

---

tests/e2e/normalize.go

We sort replacements so that we replace the longest values first,
which also deals with "substring replacements"
e.g. subnetwork-a => ${subnetworkID}, network-a => ${networkID}

chore: make replacements reproducible

---

experiments/conductor/cmd/runner/crd_generator_commands.go
experiments/conductor/cmd/runner/runner.go
experiments/conductor/cmd/runner/utilities.go

CRD generation improvements
* split types and mapper generation
* make adjust types multi step:
* update spec and status
* update parent
* update identity parent
* update identity methods
* regenerate types

conductor: CRD generation improvements

---

apis/backupdr/v1alpha1/backupplan_types.go
apis/backupdr/v1alpha1/zz_generated.deepcopy.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_backupdrbackupplans.backupdr.cnrm.cloud.google.com.yaml
pkg/controller/direct/backupdr/backupplan_mappers.go
pkg/controller/direct/backupdr/mapper.generated.go
tests/apichecks/testdata/exceptions/missingrefs.txt

BackupDRBackupPlan: spec.backupVault is a reference field

---

apis/securesourcemanager/v1alpha1/instance_types.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_securesourcemanagerinstances.securesourcemanager.cnrm.cloud.google.com.yaml
pkg/gvks/supportedgvks/gvks_generated.go

SSM: Remove alpha label for SSM instance

---

experiments/conductor/cmd/runner/scripts/crd_mapper_fuzzer/02-generate-spec-and-status.sh

chore: update 02 spec-and-status script

---

experiments/conductor/cmd/runner/controller_commands.go
experiments/conductor/cmd/runner/runner.go
experiments/conductor/cmd/runner/utilities.go

* based on scrtips/controller/

Conductor: First version of implementing controller commands

---

experiments/conductor/cmd/runner/controller_commands.go
experiments/conductor/cmd/runner/crd_generator_commands.go
experiments/conductor/cmd/runner/mock_commands.go
experiments/conductor/cmd/runner/runner.go
experiments/conductor/cmd/runner/utilities.go

As encouraged in https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3963/files#r1989857408, renaming the field.

refactor: rename

---

dev/tools/controllerbuilder/pkg/annotations/fileannotation.go
dev/tools/controllerbuilder/pkg/annotations/fileannotation_test.go
dev/tools/controllerbuilder/pkg/codegen/generatorbase.go
dev/tools/controllerbuilder/pkg/codegen/mappergenerator.go
dev/tools/controllerbuilder/pkg/commands/generatemapper/generatemappercommand.go
dev/tools/controllerbuilder/pkg/toolbot/extracttoolmarkers.go

- **chore: refactor tool marker extractions to support generated code**
- **chore: emit generated annotations from generate-mapper**

chore: write markers from generate-mapper to support regeneration

---

.gitignore

chore: Ignore failing fuzz output in git

---

dev/tools/controllerbuilder/Makefile
dev/tools/controllerbuilder/pkg/codebot/tool_create_file.go
dev/tools/controllerbuilder/pkg/llm/gemini.go
dev/tools/controllerbuilder/pkg/llm/ollama.go
dev/tools/controllerbuilder/pkg/llm/vertexai.go
experiments/conductor/cmd/runner/crd_generator_commands.go
experiments/conductor/cmd/runner/runner.go
experiments/conductor/cmd/runner/utilities.go

* Previous versions produced incomplete commits or no changes for the steps in cmd 21 > 50% of the time
* On debugging the logs over several iterations (tuning prompt), discovered that gemini was producing whole file changes which were good but it did not translate to Edit tool calls
* So added an option to CreateFileTool to overwrite existing files. And used that in the prompt.
* With these changes the instances of skipped steps (no change) reduced dramatically and now has only ~ 10% failure rate.
* Batch run: https://github.com/GoogleCloudPlatform/k8s-config-connector/pulls?q=is%3Apr+is%3Aopen+author%3Abarney-s+WIP%3A+Types+and+Mapper
* mapper run is failing ignore the last commit. Rest are from steps 20, 21 (bulk), 22
* git push origin <branch> --force
* (future planning to add make …

Conductor: Improve Type generation

---

mockgcp/mockresourcemanager/service.go
mockgcp/mockresourcemanager/tagvalues.go
mockgcp/mockresourcemanager/testdata/tagvalue/crud/_http.log
mockgcp/mockresourcemanager/testdata/tagvalue/crud/script.yaml

- **autogen: generate-script for gcloud resource-manager tags values**
- **mockgcp: update resource-manager tagvalue**
- **mockgcp: golden output for resource-manager tagvalue**

mockgcp: tests for resourcemanager tagvalue

---

tests/apichecks/crds_test.go
tests/apichecks/testdata/exceptions/shortname_pluralization.txt

Follow up to #4034, adding a test to validate the CRD shortName pluralization.

test: add validation for CRD shortName pluralization

---

pkg/controller/direct/backupdr/client.go
pkg/controller/direct/backupdr/managementserver_controller.go

Refactor client code and add controller tool markers to improve prompt results when generating new controllers in the same API group.

chore: refactor BackupDRManagementServer controller client

---

apis/spanner/v1beta1/instance_types.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_spannerinstances.spanner.cnrm.cloud.google.com.yaml
pkg/controller/direct/spanner/instance_controller.go
pkg/gvks/supportedgvks/gvks_generated.go
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spanneinstance-unset-compute-fields/_generated_object_spanneinstance-unset-compute-fields.golden.yaml
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerdatabase/_vcr_cassettes/nontf.yaml
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerdatabase/_vcr_cassettes/oauth.yaml
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerdatabase/_vcr_cassettes/tf.yaml
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerinstance-basic/_generated_object_spannerinstance-basic.golden.yaml
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerinstance-direct-full/_generated_object_spannerinstance-direct-full.golden.yaml
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerinstance-downgrade-edition/_generated_object_spannerinstance-downgrade-edition.golden.yaml
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerinstance-full/_generated_object_spannerinstance-full.golden.yaml
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerinstance/_generated_object_spannerinstance.golden.yaml

Enable Direct Controller for Spanner Instance

---

apis/bigquerydatatransfer/v1beta1/types.generated.go
apis/managedkafka/v1alpha1/types.generated.go
apis/managedkafka/v1beta1/types.generated.go
dev/tools/controllerbuilder/config/v1beta1/managedkafka.yaml
dev/tools/controllerbuilder/pkg/annotations/fileannotation.go
dev/tools/controllerbuilder/pkg/codegen/typegenerator.go
dev/tools/controllerbuilder/pkg/commands/generatetypes/generatetypescommand.go
pkg/controller/direct/bigquerydatatransfer/mapper.generated.go
pkg/controller/direct/managedkafka/mapper.generated.go

Follow up of #4060, adding file annotation to generated types as well.

controllerbuilder: add file annotation to generated types

---

mockgcp/mocknetworkconnectivity/internalranges.go
mockgcp/mocknetworkconnectivity/service.go
mockgcp/mocknetworkconnectivity/testdata/internalranges/crud/_http.log
mockgcp/mocknetworkconnectivity/testdata/internalranges/crud/script.yaml

[conductor] Mock for resource networkconnectivity internalranges

---

dev/tools/controllerbuilder/cmd/regenerate/main.go
dev/tools/controllerbuilder/pkg/annotations/fileannotation.go

This shows how we "complete the loop", by extracting the generation markers,
and using them to regenerate.
This currently only prints the (approximate) commands, but shows the direction.

chore: create regenerate command

---

apis/apphub/v1alpha1/application_types.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_apphubapplications.apphub.cnrm.cloud.google.com.yaml
config/tests/samples/create/harness.go
mockgcp/mockapphub/application.go
pkg/controller/direct/apphub/application_controller.go
pkg/test/resourcefixture/testdata/basic/apphub/v1alpha1/apphubapplication/apphubapplication-minimal/_generated_object_apphubapplication-minimal.golden.yaml
pkg/test/resourcefixture/testdata/basic/apphub/v1alpha1/apphubapplication/apphubapplication-minimal/_http.log
pkg/test/resourcefixture/testdata/basic/apphub/v1alpha1/apphubapplication/apphubapplication-minimal/create.yaml
pkg/test/resourcefixture/testdata/basic/apphub/v1alpha1/apphubapplication/apphubapplication-minimal/update.yaml

feat: add resource apphub application controller

---

mockgcp/mocknetworkconnectivity/regionalendpoints.go
mockgcp/mocknetworkconnectivity/service.go
mockgcp/mocknetworkconnectivity/testdata/regionalendpoints/crud/_http.log
mockgcp/mocknetworkconnectivity/testdata/regionalendpoints/crud/script.yaml

[conductor] Mock for resource networkconnectivity regionalendpoints

---

pkg/controller/direct/batch/job_mappings.go

fix: fuzztest BatchJobSpec

---

dev/tools/controllerbuilder/pkg/codegen/typegenerator.go
dev/tools/controllerbuilder/pkg/typeupdater/insertfield-ast.go

In particular, if we depend on apis/ we cannot make progress when apis is not compiling,
for example when we have not generated the types.

controllerbuilder: avoid external dependencies

---

config/samples/resources/bigqueryconnectionconnection/cloudspanner-connection/spanner_v1beta1_spannerinstance.yaml
config/samples/resources/spannerdatabase/spanner_v1beta1_spannerinstance.yaml
config/samples/resources/spannerinstance/spanner_v1beta1_spannerinstance.yaml
scripts/generate-google3-docs/resource-reference/generated/resource-docs/bigqueryconnection/bigqueryconnectionconnection.md
scripts/generate-google3-docs/resource-reference/generated/resource-docs/spanner/spannerdatabase.md
scripts/generate-google3-docs/resource-reference/generated/resource-docs/spanner/spannerinstance.md
scripts/github-actions/tests-e2e-samples

Remove alpha opt-in annotation for spanner instance

---

apis/spanner/v1alpha1/instanceconfig_identity.go
config/tests/samples/create/harness.go
mockgcp/mockspanner/admin/instance.go
pkg/controller/direct/spanner/client.go
pkg/controller/direct/spanner/instance_controller.go
pkg/controller/direct/spanner/instanceconfig_controller.go
pkg/controller/direct/spanner/spannerinstanceconfig_controller.go
pkg/test/resourcefixture/testdata/basic/spanner/v1alpha1/spannerinstanceconfig/spannerinstanceconfig-minimal/_generated_object_spannerinstanceconfig-minimal.golden.yaml
pkg/test/resourcefixture/testdata/basic/spanner/v1alpha1/spannerinstanceconfig/spannerinstanceconfig-minimal/_http.log
pkg/test/resourcefixture/testdata/basic/spanner/v1alpha1/spannerinstanceconfig/spannerinstanceconfig-minimal/create.yaml
pkg/test/resourcefixture/testdata/basic/spanner/v1alpha1/spannerinstanceconfig/spannerinstanceconfig-minimal/update.yaml
tests/e2e/normalize.go

mockGCP&Controller: Resource spanner instanceconfig

---

dev/tools/controllerbuilder/cmd/regenerate/main.go

Following up on #4060, #4075, and #4099 - find the generated types.

controllerbuilder: find generated types

---

mockgcp/mockeventarc/testdata/googlechannelconfig/crud/_http.log

Update http log for googlechannelconfig/crud

---

scripts/shared-vars-public.sh

Enabled a few recently supported services for test project.

chore: enable services for test project

---

docs/releasenotes/release-1.130.md

Add labels to spannerinstance and secret release note to 1.130

---

docs/releasenotes/release-1.130.md

update release notes for 1.130

---

docs/releasenotes/release-1.130.1.md

Add Release note for 1.130.1

---

pkg/controller/direct/datastream/connectionprofile_controller.go

Properly resolve reference fields for `DatastreamConnectionProfile`.

feat: properly resolve reference fields in DatastreamConnectionProfile controller

---

pkg/controller/direct/datastream/privateconnection_controller.go

Properly resolve reference fields for DatastreamPrivateConnection.

feat: properly resolve reference fields in DatastreamPrivateConnection controller

---

docs/develop-resources/scenarios/migrate-tf-resource-beta.md

Reformatted the file to be more readable.
Updated the file according to https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3598#issuecomment-2638638411.

Update the instruction for the migration scenario

---

dev/tools/controllerbuilder/template/controller/controller.go

Make template changes to update status even when no cloud provider fields need to be updated!

template: update status

---

config/tests/samples/create/harness.go
mockgcp/mockgkebackup/backup.go
pkg/controller/direct/gkebackup/backup_controller.go
pkg/test/resourcefixture/testdata/basic/gkebackup/v1alpha1/gkebackupbackup/gkebackupbackup-minimal/_generated_object_gkebackupbackup-minimal.golden.yaml
pkg/test/resourcefixture/testdata/basic/gkebackup/v1alpha1/gkebackupbackup/gkebackupbackup-minimal/_http.log
pkg/test/resourcefixture/testdata/basic/gkebackup/v1alpha1/gkebackupbackup/gkebackupbackup-minimal/create.yaml
pkg/test/resourcefixture/testdata/basic/gkebackup/v1alpha1/gkebackupbackup/gkebackupbackup-minimal/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/gkebackup/v1alpha1/gkebackupbackup/gkebackupbackup-minimal/update.yaml
tests/e2e/normalize.go
tests/e2e/unified_test.go

There are too many diff in the GKE container, causing GitHub's diff system to fail. Here is the actual diff between the real and mock for `GKEBackupBackup`: https://www.diffchecker.com/cRxkr5KT/

feat: add controller, test and mock support for GKEBackupBackup

---

mockgcp/mockaiplatform/testdata/model/crud/script.yaml
mockgcp/mockaiplatform/testdata/runtime/crud/script.yaml
mockgcp/mockaiplatform/testdata/runtimetemplate/crud/script.yaml
mockgcp/mockaiplatform/testdata/schedule/crud/script.yaml
mockgcp/mockapigateway/testdata/api/crud/script.yaml
mockgcp/mockapphub/testdata/application/crud/script.yaml
mockgcp/mockapphub/testdata/discoveredservice/crud/script.yaml
mockgcp/mockasset/testdata/feed/crud/script.yaml
mockgcp/mockasset/testdata/savedquery/crud/script.yaml
mockgcp/mockbackupdr/testdata/managementserver/crud/script.yaml
mockgcp/mockbatch/testdata/job/crud/script.yaml
mockgcp/mockbigtable/testdata/appprofile/crud/script.yaml

This should allow for easier bulk manipulation.

mockgcp: add comments to test scripts

---

dev/tools/controllerbuilder/cmd/codebot/main.go
dev/tools/controllerbuilder/pkg/toolbot/csv.go

We might be using vertex, not gemini (directly)

controllerbuilder: clearer error messages

---

mockgcp/mock_http_roundtrip.go
mockgcp/mockbigtable/instance.go
mockgcp/mockbigtable/normalize.go
mockgcp/mockbigtable/service.go
mockgcp/mockbigtable/testdata/instance/crud/_http.log
mockgcp/mockbigtable/testdata/instance/crud/script.yaml

- **mockgcp: create test script for gcloud bigtable instances.**
- **mockgcp: golden output for TestScripts/mockbigtable/testdata/instance/crud**
- **mockgcp: move bigtable to normalize pattern**
- **mockgcp: implement bigtable instance update**

mockgcp: gcloud test for bigtable instance

---

apis/bigtable/v1beta1/appprofile_identity.go

[Cloud Bigtable App Profile Beta Migration] Split the app profile parent from instance into project ID and instance ID

---

apis/gkebackup/v1alpha1/restore_types.go
apis/gkebackup/v1alpha1/types.generated.go
apis/gkebackup/v1alpha1/zz_generated.deepcopy.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_gkebackuprestores.gkebackup.cnrm.cloud.google.com.yaml
config/tests/samples/create/harness.go
mockgcp/mockgkebackup/restore.go
pkg/controller/direct/gkebackup/mapper.generated.go
pkg/controller/direct/gkebackup/restore_controller.go
pkg/controller/direct/gkebackup/restore_mappers.go
pkg/test/resourcefixture/testdata/basic/gkebackup/v1alpha1/gkebackuprestore/gkebackuprestore-minimal/_generated_object_gkebackuprestore-minimal.golden.yaml
pkg/test/resourcefixture/testdata/basic/gkebackup/v1alpha1/gkebackuprestore/gkebackuprestore-minimal/_http.log
pkg/test/resourcefixture/testdata/basic/gkebackup/v1alpha1/gkebackuprestore/gkebackuprestore-minimal/create.yaml
pkg/test/resourcefixture/testdata/basic/gkebackup/v1alpha1/gkebackuprestore/gkebackuprestore-minimal/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/gkebackup/v1alpha1/gkebackuprestore/gkebackuprestore-minimal/update.yaml

/hold
Based on #4258
There are too many diff in the GKE container, causing GitHub's diff system to fail. Here is the actual diff between the real and mock for `GKEBackupRestore`:
https://www.diffchecker.com/oQOHANek/

feat: add controller, test and mock support for GKEBackupRestore

---

dev/tasks/propose-tag
operator/config/rbac/cnrm_viewer_patch.yaml
operator/config/rbac/kustomization.yaml

fix: KCC release misses the RBAC for CCC

---

config/tests/samples/create/harness.go
mockgcp/mockdataplex/entrygroup.go
mockgcp/mockdataplex/service.go
pkg/controller/direct/dataplex/client.go
pkg/controller/direct/dataplex/entrygroup_controller.go
pkg/test/resourcefixture/testdata/basic/dataplex/v1alpha1/dataplexentrygroup/dataplexentrygroup-minimal/_generated_object_dataplexentrygroup-minimal.golden.yaml
pkg/test/resourcefixture/testdata/basic/dataplex/v1alpha1/dataplexentrygroup/dataplexentrygroup-minimal/_http.log
pkg/test/resourcefixture/testdata/basic/dataplex/v1alpha1/dataplexentrygroup/dataplexentrygroup-minimal/create.yaml
pkg/test/resourcefixture/testdata/basic/dataplex/v1alpha1/dataplexentrygroup/dataplexentrygroup-minimal/update.yaml

MockGCP&Controller: Resource dataplex entrygroup

---

pkg/controller/direct/compute/firewallpolicyrule/firewallpolicyrule_controller.go

Fixes https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/4199/files#r2045499996

Update KRM status even when no field changes

---

config/tests/samples/create/samples.go
tests/e2e/unified_test.go

If we mix-and-match, we get surprising behaviours e.g. we can't clear a field
We would ideally roll this out for all resources, but there are
a lot of tests that accidentally verify the odd behvaiour,
so practically we need to roll it out group-by-group.

tests: use server-side-apply for create and update

---

.github/workflows/ci-presubmit.yaml
scripts/github-actions/tests-e2e-fixtures
scripts/github-actions/tests-e2e-fixtures-alloydb
scripts/github-actions/tests-e2e-fixtures-cloudidentity

Should help with test-e2e-fixtures runtime

tests: split alloydb and cloudidentity tests

---

apis/dataplex/v1alpha1/entrytype_identity.go
mockgcp/mockdataplex/entrytype.go
mockgcp/mockdataplex/lake.go
pkg/controller/direct/dataplex/entrytype_controller.go
pkg/controller/direct/dataplex/mapper.generated.go
pkg/test/resourcefixture/testdata/basic/dataplex/v1alpha1/dataplexentrytype/dataplexentrytype-minimal/_generated_object_dataplexentrytype-minimal.golden.yaml
pkg/test/resourcefixture/testdata/basic/dataplex/v1alpha1/dataplexentrytype/dataplexentrytype-minimal/_http.log
pkg/test/resourcefixture/testdata/basic/dataplex/v1alpha1/dataplexentrytype/dataplexentrytype-minimal/create.yaml
pkg/test/resourcefixture/testdata/basic/dataplex/v1alpha1/dataplexentrytype/dataplexentrytype-minimal/update.yaml

MockGCP&Controller: Resource dataplex entrytype

---

dev/tasks/warm-devcontainer

Ensure that a devcontainer is ready!

chore: add script to prewarm devcontainer

---

dev/tasks/update-golden

Runs all the tests in "WRITE_GOLDEN_OUTPUT" mode

chore: create script to update golden output

---

mockgcp/mockmonitoring/alertpolicy.go
mockgcp/mockmonitoring/normalize.go
mockgcp/mockmonitoring/notificationchannel.go
mockgcp/mockmonitoring/testdata/alertpolicy/crud/_http.log
mockgcp/mockmonitoring/testdata/alertpolicy/crud/high-cpu-usage.json
mockgcp/mockmonitoring/testdata/alertpolicy/crud/script.yaml

- **mockgcp: create gcloud test for monitoring alertPolicy**
- **mockgcp: golden output from mockmonitoring/testdata/alertpolicy/crud**
- **mockgcp: fixup monitoring alertPolicy**

mockgcp: gcloud test for monitoring alertPolicy

---

config/tests/samples/create/harness.go
pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableappprofile/_generated_object_bigtableappprofile.golden.yaml
pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableappprofile/_http.log
pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableappprofile/create.yaml
pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableappprofile/update.yaml

[Cloud Bigtable App Profile Beta Migration] Record real GCP log

---

experiments/conductor/README.md

fix a typo in README.md

---

mockgcp/mockbigtable/appprofile.go
pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableappprofile/_http.log

mock: update mock for BigTable AppProfile to match real

---

docs/releasenotes/release-1.131.md

doc: update 1.131 release notes

---

config/tests/samples/create/harness.go
go.mod
go.sum
mockgcp/mockdataplex/lake.go
mockgcp/mockdataplex/service.go
mockgcp/mockdataplex/task.go
mockgcp/mockdataplex/zone.go
pkg/controller/direct/dataplex/task_controller.go
pkg/test/resourcefixture/testdata/basic/dataplex/v1alpha1/dataplextask/dataplextask-minimal/_generated_object_dataplextask-minimal.golden.yaml
pkg/test/resourcefixture/testdata/basic/dataplex/v1alpha1/dataplextask/dataplextask-minimal/_http.log
pkg/test/resourcefixture/testdata/basic/dataplex/v1alpha1/dataplextask/dataplextask-minimal/create.yaml
pkg/test/resourcefixture/testdata/basic/dataplex/v1alpha1/dataplextask/dataplextask-minimal/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/dataplex/v1alpha1/dataplextask/dataplextask-minimal/update.yaml
tests/e2e/normalize.go
tests/e2e/unified_test.go

MockGCP&Controller: Resource dataplex task

---

mockgcp/mockcompute/ids.go
mockgcp/mockcompute/testdata/computezones/crud/_http.log
mockgcp/mockcompute/testdata/computezones/crud/script.yaml
mockgcp/mockcompute/zonesv1.go
pkg/test/resourcefixture/testdata/basic/backupdr/v1alpha1/backupdrbackupplanassociation/backupdrbackupplanassociation-minimal/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeinstance/computeinstancebasicexample/_http.log
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeinstance/computeinstancewithencrypteddisk/_http.log
pkg/test/resourcefixture/testdata/resourceoverrides/computeinstance/networkipcomputeinstance/_http.log

- **mockgcp: improve fidelity of compute zones**

mockgcp: improve fidelity of compute zones

---

pkg/test/controller/k8s.go
pkg/test/gcp/gcp.go
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeinterconnectattachment/create.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeinterconnectattachment/update.yaml
tests/apichecks/testdata/exceptions/missingfields.txt

Use placeholder for test interconnect names in tests

---

mockgcp/mock_http_roundtrip.go
mockgcp/mockmanagedkafka/cluster.go
mockgcp/mockmanagedkafka/normalize.go
mockgcp/mockmanagedkafka/service.go
mockgcp/mockmanagedkafka/testdata/cluster/crud/_http.log
mockgcp/mockmanagedkafka/testdata/cluster/crud/script.yaml
pkg/test/resourcefixture/testdata/basic/managedkafka/v1beta1/managedkafkacluster/managedkafkacluster/managedkafkacluster-basic/_http.log
pkg/test/resourcefixture/testdata/basic/managedkafka/v1beta1/managedkafkacluster/managedkafkacluster/managedkafkacluster-cmek/_http.log
pkg/test/resourcefixture/testdata/basic/managedkafka/v1beta1/managedkafkatopic/_http.log

- **mockgcp: create test script for gcloud managed-kafka clusters**
- **mockgcp: golden output for TestScripts/mockmanagedkafka/testdata/cluster/crud**
- **mockgcp: more fidelity for managedkafka cluster**

resource managedkafka cluster

---

experiments/conductor/branches-all.yaml

Some updates so far for the my metadata chunk

chore: update metadata

---

experiments/conductor/branches-all.yaml
experiments/conductor/cmd/runner/runner.go

Fixed bug where it wasn't detecting duplicate kinds. Added more information when a duplicate was detected.
Fixed the metadata to remove duplicate entries.

Fixed metadata check.

---

pkg/controller/dynamic/dynamic_controller_integration_test.go

Add an option to skip Alpha resources in dynamic test.
Our periodic test failed since last week, due to panic error in one of the Conductor generated resource: https://screenshot.googleplex.com/5diRTqYmdb3a2Hq.png
Given the increasing number of direct-based Alpha resources, I think maybe we could exclude them from periodic tests to better focus our monitoring on Beta resources. I will update the internal test script in followup CLs.

tests: skip alpha dynamic tests

---

apis/iam/v1beta1/partialpolicy_types.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_iampartialpolicies.iam.cnrm.cloud.google.com.yaml
scripts/generate-google3-docs/resource-reference/generated/resource-docs/iam/iampartialpolicy.md

Addresses https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/4435#discussion_r2067535561

fix: gcp prefixed shortnames

---

docs/releasenotes/release-1.131.md
docs/releasenotes/release-1.132.md

update release notes

---

mockgcp/mockbigquery/tables.go
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable-ignore-schema-changes/_generated_object_bigquerytable-ignore-schema-changes.golden.yaml
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable-ignore-schema-changes/_http.log
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable-nested-schema-field/_generated_export_bigquerytable-nested-schema-field.golden
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable-nested-schema-field/_generated_object_bigquerytable-nested-schema-field.golden.yaml
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable-nested-schema-field/_http.log
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable-nested-schema-field/create.yaml
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable-nested-schema-field/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable-nested-schema-field/update.yaml
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable/_generated_object_bigquerytable.golden.yaml
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable/_http.log
pkg/test/resourcefixture/testdata/basic/dataflow/v1beta1/dataflowflextemplatejob/streamingdataflowflextemplatejob/_http.log
pkg/test/resourcefixture/testdata/basic/pubsub/v1beta1/pubsubsubscription/bigquerypubsubsubscription/_http.log
pkg/test/resourcefixture/testdata/resourceid/referencewithuserspecifiedresourceid/_generated_object_referencewithuserspecifiedresourceid.golden.yaml
pkg/test/resourcefixture/testdata/resourceid/referencewithuserspecifiedresourceid/_http.log
tests/apichecks/testdata/exceptions/missingfields.txt

Bigquerytable test nested field

---

apis/cloudidentity/v1beta1/group_types.go
apis/cloudidentity/v1beta1/membership_types.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_cloudidentitygroups.cloudidentity.cnrm.cloud.google.com.yaml
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_cloudidentitymemberships.cloudidentity.cnrm.cloud.google.com.yaml
pkg/test/resourcefixture/testdata/basic/cloudidentity/v1beta1/cloudidentitygroup/cloudidentitygroupbasic/_generated_object_cloudidentitygroupbasic.golden.yaml
scripts/generate-google3-docs/resource-reference/generated/resource-docs/cloudidentity/cloudidentitygroup.md
scripts/generate-google3-docs/resource-reference/generated/resource-docs/cloudidentity/cloudidentitymembership.md
tests/e2e/normalize.go
tests/e2e/testdata/scenarios/acquisition/cloudidentitygroup/_http00.log
tests/e2e/testdata/scenarios/acquisition/cloudidentitygroup/_http01.log
tests/e2e/testdata/scenarios/acquisition/cloudidentitygroup/_object00.yaml
tests/e2e/testdata/scenarios/acquisition/cloudidentitygroup/_object01.yaml
tests/e2e/testdata/scenarios/acquisition/cloudidentitygroup/script.yaml
tests/e2e/testdata/scenarios/acquisition/cloudidentitymembership/_http00.log
tests/e2e/testdata/scenarios/acquisition/cloudidentitymembership/_http01.log
tests/e2e/testdata/scenarios/acquisition/cloudidentitymembership/_http02.log
tests/e2e/testdata/scenarios/acquisition/cloudidentitymembership/_object00.yaml
tests/e2e/testdata/scenarios/acquisition/cloudidentitymembership/_object01.yaml
tests/e2e/testdata/scenarios/acquisition/cloudidentitymembership/_object02.yaml
tests/e2e/testdata/scenarios/acquisition/cloudidentitymembership/script.yaml

Followup of customer issue https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/4439

CloudIdentity server-generated resourceID for acquisition

---

mockgcp/mockbigquery/tables.go
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable-view/_generated_export_bigquerytable-view.golden
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable-view/_generated_object_bigquerytable-view.golden.yaml
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable-view/_http.log
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable-view/create.yaml
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable-view/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable-view/update.yaml
tests/apichecks/testdata/exceptions/missingfields.txt
tests/e2e/unified_test.go

Add test cases for BQ Table from Materialized View

---

mockgcp/mockbigquery/tables.go
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable-full/_generated_export_bigquerytable-full.golden
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable-full/_generated_object_bigquerytable-full.golden.yaml
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable-full/_http.log
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable-full/create.yaml
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable-full/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable-full/update.yaml
tests/apichecks/testdata/exceptions/missingfields.txt

Create full test for Bigquery Table

Bigquerytable full test

---

apis/bigtable/v1beta1/appprofile_types.go
mockgcp/mockbigtable/appprofile.go
pkg/controller/direct/bigtable/bigtableappprofile_controller.go
pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableappprofile/bigtableappprofiledataboost-disable/_generated_object_bigtableappprofiledataboost-disable.golden.yaml
pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableappprofile/bigtableappprofiledataboost-disable/_http.log
pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableappprofile/bigtableappprofiledataboost-disable/create.yaml
pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableappprofile/bigtableappprofiledataboost-disable/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableappprofile/bigtableappprofiledataboost-disable/update.yaml

[Cloud Bigtable] Data Boost Create Support

---

tests/e2e/unified_test.go

I always ask myself which subtest timed out!

tests: name the subtest

---

mockgcp/mock_http_roundtrip.go
mockgcp/mockartifactregistry/normalize.go
mockgcp/mockartifactregistry/repository.go
mockgcp/mockartifactregistry/service.go
mockgcp/mockartifactregistry/testdata/repository/crud/_http.log
mockgcp/mockartifactregistry/testdata/repository/crud/script.yaml
pkg/test/resourcefixture/testdata/basic/artifactregistry/v1beta1/artifactregistryrepository/artifactregistryrepository/_http.log
pkg/test/resourcefixture/testdata/iammemberreferences/serviceidentityref/_http.log

- **mockgcp: create test script for gcloud artifacts repositories**
- **mockgcp: golden output for mockgcp/mockartifactregistry/testdata/repository/crud**
- **mockgcp: more fidelity for artifactregistry repository**

mockgcp: tests for gcloud artifacts repositories

---

tests/e2e/testdata/scenarios/acquisition/bigqueryconnectionconnection/_http01.log

fix: Update scenarios/acquisition/bigqueryconnectionconnection http log

---

experiments/conductor/cmd/runner/prompts.go

To unblock Presubmit / validations

chore: run make fmt

---

mockgcp/mocksql/sqlinstance.go
mockgcp/mocksql/testdata/instance/crud/_http.log
mockgcp/mocksql/testdata/instance/crud/script.yaml
pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqldatabase/sqldatabasesismerge/_http.log
pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-mysql-minimal-direct/_http.log

- **mockgcp: add gcloud test for sql instance**
- **mockgcp: update sql instance fidelity**

mockgcp: sql instance support for mysql 8.4

---

dev/tools/controllerbuilder/pkg/commands/generatefuzzer/README.md
dev/tools/controllerbuilder/pkg/llm/options.go
experiments/conductor/cmd/runner/github_commands.go

Upgraded default model to gemini-2.5-pro-preview-05-06.
Remove a problematic check in the batch clean command.
Ran conductor and built dev/tools.

Upgrade the LLM model.

---

cmd/deletiondefender/main.go
cmd/manager/main.go
cmd/unmanageddetector/main.go
cmd/webhook/main.go
config/tests/samples/create/samples_test.go
operator/pkg/logging/logging.go
pkg/controller/deletiondefender/controller.go
pkg/controller/gsakeysecretgenerator/gsakey_secret_generator.go
pkg/controller/iam/auditconfig/iamauditconfig_controller.go
pkg/controller/iam/iamclient/iamclient.go
pkg/controller/iam/partialpolicy/iampartialpolicy_controller.go
pkg/controller/iam/policy/iampolicy_controller.go
pkg/controller/iam/policymember/iampolicymember_controller.go
pkg/controller/tf/controller.go
pkg/controller/unmanageddetector/controller.go
pkg/logging/logging.go

klog is a different but similar-enough-to-be-confusing library.

chore: don't alias controller-runtime log to klog

---

pkg/controller/iam/partialpolicy/iampartialpolicy_controller.go
scripts/github-actions/tests-scenarios

Not sure what happened here but a simple `make fmt` is all we need!

chore: make fmt

---

pkg/test/resourcefixture/testdata/basic/iam/v1beta1/iamserviceaccount/iamserviceaccount-disabled/_generated_object_iamserviceaccount-disabled.golden.yaml
pkg/test/resourcefixture/testdata/basic/iam/v1beta1/iamserviceaccount/iamserviceaccount-disabled/_http.log
pkg/test/resourcefixture/testdata/basic/iam/v1beta1/iamserviceaccount/iamserviceaccount-disabled/create.yaml
pkg/test/resourcefixture/testdata/basic/iam/v1beta1/iamserviceaccount/iamserviceaccount-disabled/update.yaml
pkg/test/resourcefixture/testdata/basic/iam/v1beta1/iamserviceaccount/iamserviceaccount-full/_generated_object_iamserviceaccount-full.golden.yaml
pkg/test/resourcefixture/testdata/basic/iam/v1beta1/iamserviceaccount/iamserviceaccount-full/_http.log
pkg/test/resourcefixture/testdata/basic/iam/v1beta1/iamserviceaccount/iamserviceaccount-full/create.yaml
pkg/test/resourcefixture/testdata/basic/iam/v1beta1/iamserviceaccount/iamserviceaccount-full/update.yaml
tests/apichecks/testdata/exceptions/missingfields.txt
tests/e2e/unified_test.go

Generated test cases to increase test coverage for IAMServiceAccount

Increase test coverage for IAMServiceAccount

---

.github/workflows/presubmit.yaml
pkg/controller/dynamic/dynamic_controller_integration_test.go
scripts/github-actions/tests-e2e-samples

fix make vet in presubmit/unit-tests

---

pkg/controller/direct/bigquerydatapolicy/datapolicy_fuzzer.go
pkg/controller/direct/bigquerydatapolicy/datapolicy_mapper.go

Add mapper and fuzzer for BigQueryDataPolicy

Add mapper and fuzzer for BigQueryDataPolicy

---

docs/releasenotes/release-1.132.md

Add `CloudIdentityGroup` and `CloudIdentityMembership` direct annotation to release notes 1.132

doc: Update release notes 1.132

---

docs/releasenotes/release-1.132.md

update 1.132.0 release doc

---

config/samples/resources/iapsettings/regionalbackendserviceiapsettings/iap_v1beta1_iapsettings.yaml
pkg/test/resourcefixture/testdata/basic/iap/v1beta1/iapsettings/regionalcomputebackendserviceiapsettings/_http.log
pkg/test/resourcefixture/testdata/basic/iap/v1beta1/iapsettings/regionalcomputebackendserviceiapsettings/create.yaml
pkg/test/resourcefixture/testdata/basic/iap/v1beta1/iapsettings/regionalcomputebackendserviceiapsettings/update.yaml
scripts/generate-google3-docs/resource-reference/generated/resource-docs/iap/iapsettings.md
scripts/generate-google3-docs/resource-reference/overview.md

Fix presubmit checks in cl/767738535

doc: fix presubmit check in release docs

---

docs/develop-resources/deep-dives/5-releases.md

Follow up of #4675 and #4679, add clear instruction for finding the correct product names

doc: clarify instructions for finding product names in user guide

---

docs/releasenotes/release-1.132.md

Update release-1.132.md for Speech

---

scripts/generate-google3-docs/resource-reference/_toc.yaml

Re comment: https://critique.corp.google.com/cl/767844310/depot/google3/third_party/devsite/cloud/en/config-connector/docs/reference/_toc.yaml?version=s1#513

doc: fix doc path in _toc.yaml

---

pkg/test/resourcefixture/testdata/basic/dataproc/v1alpha1/dataprocjob/dataprocjob-minimal/_http.log

chore: fix fixture test

---

docs/develop-resources/deep-dives/5-releases.md
scripts/shared-vars-public.sh

This will fix our postsubmit samples and dynamic tests. 
Verified locally that the tests can now pass.

tests: enable apis for tests

---

experiments/tools/licensescan/main.go
experiments/tools/licensescan/modules/cloud.google.com/go/compute/metadata/v0.7.0.yaml
experiments/tools/licensescan/modules/cloud.google.com/go/networkservices/v0.2.5.yaml
experiments/tools/licensescan/modules/cloud.google.com/go/storage/v1.55.0.yaml
experiments/tools/licensescan/modules/cloud.google.com/go/v0.121.1.yaml
experiments/tools/licensescan/modules/github.com/googleapis/gax-go/v2/v2.14.2.yaml
experiments/tools/licensescan/modules/go.opentelemetry.io/otel/metric/v1.36.0.yaml
experiments/tools/licensescan/modules/go.opentelemetry.io/otel/sdk/metric/v1.36.0.yaml
experiments/tools/licensescan/modules/go.opentelemetry.io/otel/sdk/v1.36.0.yaml
experiments/tools/licensescan/modules/go.opentelemetry.io/otel/trace/v1.36.0.yaml
experiments/tools/licensescan/modules/go.opentelemetry.io/otel/v1.36.0.yaml
experiments/tools/licensescan/modules/golang.org/x/crypto/v0.38.0.yaml
experiments/tools/licensescan/modules/golang.org/x/net/v0.40.0.yaml
experiments/tools/licensescan/modules/golang.org/x/sys/v0.33.0.yaml
experiments/tools/licensescan/modules/golang.org/x/term/v0.32.0.yaml
experiments/tools/licensescan/modules/golang.org/x/text/v0.25.0.yaml
experiments/tools/licensescan/modules/google.golang.org/api/v0.235.0.yaml
experiments/tools/licensescan/modules/google.golang.org/genproto/googleapis/rpc/v0.0.0-20250512202823-5a2f75b736a9.yaml
experiments/tools/licensescan/modules/google.golang.org/grpc/v1.72.1.yaml

chore: update licenses

---

dev/tasks/propose-tag
dev/tasks/update-manifests.sh

Add release script to update the latest manifests to all previous versions except for controller.
Fixes #

Improve KCC release scripts

---

tests/e2e/ratcheting.go

Clarify the reason to exclude bigquerytable-ignore-schema-changes from re-reconciliation

---

apis/datacatalog/v1beta1/policytag_identity.go
apis/datacatalog/v1beta1/policytag_reference.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_bigquerydatapolicies.bigquerydatapolicy.cnrm.cloud.google.com.yaml
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_datacatalogpolicytags.datacatalog.cnrm.cloud.google.com.yaml

Fix policy tag ref

---

pkg/controller/direct/apigateway/api_controller.go
pkg/label/label.go
pkg/test/resourcefixture/testdata/basic/apigateway/v1beta1/apigatewayapi/apigatewayapi-full/_http.log
pkg/test/resourcefixture/testdata/basic/apigateway/v1beta1/apigatewayapi/apigatewayapi-minimal/_http.log
pkg/test/resourcefixture/testdata/basic/apigateway/v1beta1/apigatewayapi/apigatewayapiautogen/_http.log
tests/e2e/testdata/scenarios/labels-apigateway/_http00.log
tests/e2e/testdata/scenarios/labels-apigateway/_http01.log
tests/e2e/testdata/scenarios/labels-apigateway/_http02.log
tests/e2e/testdata/scenarios/labels-apigateway/_http03.log
tests/e2e/testdata/scenarios/labels-apigateway/_http04.log
tests/e2e/testdata/scenarios/labels-apigateway/_object00.yaml
tests/e2e/testdata/scenarios/labels-apigateway/_object01.yaml
tests/e2e/testdata/scenarios/labels-apigateway/_object02.yaml
tests/e2e/testdata/scenarios/labels-apigateway/_object03.yaml
tests/e2e/testdata/scenarios/labels-apigateway/_object04.yaml
tests/e2e/testdata/scenarios/labels-apigateway/script.yaml

feat: Add compatible labels for APIGateway 

---

experiments/promoter/scripts/find_promotion_candidates.sh

This is generated by `make ready-pr`

fmt: add copyright header

---

dev/release/propose-release.md

Add instructions for gemini to generate propose release tag PR

---

mockgcp/mockbigquery/routine.go
pkg/controller/direct/bigquerydataset/bigquerydataset_mappings.go
pkg/controller/direct/bigquerydataset/dataset_controller.go
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/bigquerydatasetaccessblock/update.yaml
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/bigquerydatasetaccessfull-direct/_generated_export_bigquerydatasetaccessfull-direct.golden
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/bigquerydatasetaccessfull-direct/_generated_object_bigquerydatasetaccessfull-direct.golden.yaml
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/bigquerydatasetaccessfull-direct/_http.log
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/bigquerydatasetaccessfull-direct/create.yaml
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/bigquerydatasetaccessfull-direct/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/bigquerydatasetaccessfull-direct/update.yaml
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigqueryroutine/basicbigqueryroutine/_http.log
pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigqueryroutine/fullybigqueryroutine/_http.log
tests/apichecks/testdata/exceptions/missingfields.txt

test: add bigquerydataset test coverage

---

.github/workflows/presubmit.yaml
config/tests/samples/create/samples.go
dev/ci/presubmits/tests-e2e-samples-alloydb
dev/ci/presubmits/tests-e2e-samples-apigateway
dev/ci/presubmits/tests-e2e-samples-apigee
dev/ci/presubmits/tests-e2e-samples-bigquery
dev/ci/presubmits/tests-e2e-samples-cloudbuild
dev/ci/presubmits/tests-e2e-samples-compute
dev/ci/presubmits/tests-e2e-samples-dataflow
dev/ci/presubmits/tests-e2e-samples-dataproc
dev/ci/presubmits/tests-e2e-samples-iam
dev/ci/presubmits/tests-e2e-samples-storage
scripts/github-actions/tests-e2e-samples-unclassified
tests/e2e/unified_test.go

chore: classify samples by apigroup to speed up presubmit run

---

experiments/llm-eval/evaluator.py
experiments/llm-eval/main.py
experiments/llm-eval/tasks/beta-promote/BigQueryReservationReservation-promote/cleanup.sh
experiments/llm-eval/tasks/beta-promote/BigQueryReservationReservation-promote/setup.sh
experiments/llm-eval/tasks/beta-promote/BigQueryReservationReservation-promote/task.yaml
experiments/llm-eval/tasks/beta-promote/BigQueryReservationReservation-promote/verify.sh
experiments/llm-eval/tasks/beta-promote/KMSImportJob-promote/cleanup.sh
experiments/llm-eval/tasks/beta-promote/KMSImportJob-promote/setup.sh
experiments/llm-eval/tasks/beta-promote/KMSImportJob-promote/task.yaml
experiments/llm-eval/tasks/beta-promote/KMSImportJob-promote/verify.sh
experiments/llm-eval/tasks/beta-promote/LoggingLink-promote/cleanup.sh
experiments/llm-eval/tasks/beta-promote/LoggingLink-promote/setup.sh
experiments/llm-eval/tasks/beta-promote/LoggingLink-promote/task.yaml
experiments/llm-eval/tasks/beta-promote/LoggingLink-promote/verify.sh
experiments/llm-eval/tasks/beta-promote/MetastoreBackup-promote/cleanup.sh
experiments/llm-eval/tasks/beta-promote/MetastoreBackup-promote/setup.sh
experiments/llm-eval/tasks/beta-promote/MetastoreBackup-promote/task.yaml
experiments/llm-eval/tasks/beta-promote/MetastoreBackup-promote/verify.sh
experiments/llm-eval/tasks/beta-promote/MetastoreFederation-promote/cleanup.sh
experiments/llm-eval/tasks/beta-promote/MetastoreFederation-promote/setup.sh
experiments/llm-eval/tasks/beta-promote/MetastoreFederation-promote/task.yaml
experiments/llm-eval/tasks/beta-promote/MetastoreFederation-promote/verify.sh
experiments/llm-eval/tasks/beta-promote/VMwareEngineExternalAddress-promote/cleanup.sh
experiments/llm-eval/tasks/beta-promote/VMwareEngineExternalAddress-promote/setup.sh
experiments/llm-eval/tasks/beta-promote/VMwareEngineExternalAddress-promote/task.yaml
experiments/llm-eval/tasks/beta-promote/VMwareEngineExternalAddress-promote/verify.sh
experiments/llm-eval/tasks/beta-promote/report-bak.txt
experiments/mcp/src/pkg/promotion.py
experiments/mcp/src/server.py
experiments/mcp/tests/test_server.py

Main code is in mcp promote.py and server.py.

feat: MCP adds promoting tools with llm-eval corresponding tasks  

---

.gemini/commands/review/main.toml

/review:pull looks for possible problem.
Uses a {{args}} setup to pass command line arg.
Only currently meant to be an aid.
Fixes # N/A
```release-note
NONE
```
```docs
NONE
```

Add a preliminary version of a Gemini github command.

---

docs/releasenotes/release-1.133.md

Fixes #
```release-note
```
```docs
```

Add BigQueryTable release note for 1.133

---

experiments/mcp/src/pkg/promotion.py
experiments/mcp/src/server.py

Validate the MCP tool arguments to give Gemini more dedicated guides. This enhances the chance of promoting APis and controllers using the MCP tools.   
```release-note
```
```docs
```

mcp: Improve the api and controller promotion correctness

---

.github/workflows/ci-presubmit.yaml
dev/ci/presubmits/tests-e2e-fixtures
dev/ci/presubmits/tests-e2e-fixtures-container
dev/ci/presubmits/tests-e2e-fixtures-dataflow

These are some of our slowest tests.

tests: split out dataflow and container tests

---

docs/features/ratelimit.md

Fixes missing documentation on the rate limit configuration feature.
```release-note
NONE
```
```docs
This is adding additional documentation.
```

Add documentation for setting rate_limit.

---

.github/workflows/presubmit.yaml

Fixes #
```release-note
```
```docs
```

tests: Recover presubmit jobs

---

experiments/mcp/src/server.py

Fixes #
```release-note
```
```docs
```

addmcp:  reference doc

---

experiments/llm-eval/evaluator.py
experiments/mcp/src/pkg/promotion.py
experiments/mcp/src/server.py

Fixes #
```release-note
```
```docs
```

mcp: improve promote fixture test and promote api corner cases

---

.github/workflows/ci-presubmit-legacy.yaml

I mistakenly deleted these in #4875

tests: add back legacy tests

---

config/tests/samples/create/harness.go

This is what the webhook does, and it looks like our tests
are deviating from live behaviour here.

tests: only cache CRDs with labels

---

docs/features/ratelimit.md
operator/config/crd/bases/customize.core.cnrm.cloud.google.com_controllerreconcilers.yaml
operator/config/crd/bases/customize.core.cnrm.cloud.google.com_namespacedcontrollerreconcilers.yaml
operator/pkg/apis/core/customize/v1alpha1/controllerreconciler_types.go
operator/pkg/apis/core/customize/v1beta1/controllerreconciler_types.go

Followup of my comment in #4898.

feat: add name validation in rate limit CRDs

---

pkg/gvks/supportedgvks/gvks_generated.go

fix: autogen

---

tests/apichecks/testdata/exceptions/missingfields.txt
tests/apichecks/testdata/exceptions/outputonlyspecfields.txt

tests: Exclude output-only spec fields in missingfields.txt

---

experiments/mcp/src/server.py
experiments/promoter/tasks/add-full-test-suite.md

Fixes #
```release-note
```
```docs
```

feat (llm): add full-test-suite

---

mockgcp/mockcontainer/cluster.go
mockgcp/mockcontainer/lro.go
mockgcp/mockcontainer/nodepool.go
mockgcp/mockcontainer/service.go
mockgcp/mockcontainer/testdata/clusters/crud/_http.log
mockgcp/mockcontainer/testdata/clusters/crud/script.yaml
mockgcp/mockcontainer/utils.go
pkg/test/resourcefixture/testdata/basic/container/v1beta1/containernodepool/containernodepool/_http.log

- **mockgcp: create gcloud test for container clusters**
- **golden output for container clusters test**
- **mockgcp: improve fidelity for container API**

mockgcp: add gcloud test for container cluster

---

pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullpocogkehubfeaturemembership/_generated_object_fullpocogkehubfeaturemembership.golden.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullpocogkehubfeaturemembership/_http.log
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullpocogkehubfeaturemembership/create.yaml
pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullpocogkehubfeaturemembership/update.yaml
tests/apichecks/testdata/exceptions/missingfields.txt

Ensure dynamic integration test against realGCP can pass.
Gob CL to run the integration test in background: https://cnrm-review.git.corp.google.com/c/cnrm/+/74700
Test result: https://prow-gob.gcpnode.com/view/gs/cnrm-prow/pr-logs/pull/cnrm-review.googlesource.com_cnrm/74700/cnrm-test/1952911877692461056
Refered to this [doc](https://g3doc.corp.google.com/company/gfw/support/cloud/jumpstarts/container-engine/k8s-node-taint.md?cl=head#overview) for the updated values.
Note: The API seems to be unstable and randomly returns error, which is causing the test to be flaky. Unrelated to the test itself. 
```release-note
```
```docs
```

tests: Update fullpocogkehubfeaturemembership yaml

---

apis/cloudidentity/v1beta1/membership_types.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_cloudidentitymemberships.cloudidentity.cnrm.cloud.google.com.yaml
scripts/generate-google3-docs/resource-reference/generated/resource-docs/cloudidentity/cloudidentitymembership.md
tests/apichecks/testdata/exceptions/missingfields.txt
tests/apichecks/testdata/exceptions/outputonlyspecfields.txt

- Add comment to CloudIdentityMembership memberkey field
- Add this field to outputonlyspecfields.txt
```release-note
```
```docs
```

doc: Add comment to CloudIdentityMembership memberkey field

---

dev/ci/presubmits/tests-scenarios-gkehubfeaturemembership
dev/tasks/run-e2e

Split out of #4964, focus on the flaky gkehubfeaturemembership scenarios test.
```release-note
NONE
```
```docs
```

chore: Skip flaky gkehubfeaturemembership scenarios test

---

experiments/promoter/results/candidates.json
mockgcp/mockasset/feed.go
pkg/test/resourcefixture/testdata/basic/asset/v1alpha1/assetfeed/assetfeed-full/_generated_object_assetfeed-full.golden.yaml
pkg/test/resourcefixture/testdata/basic/asset/v1alpha1/assetfeed/assetfeed-full/_http.log
pkg/test/resourcefixture/testdata/basic/asset/v1alpha1/assetfeed/assetfeed-full/create.yaml
pkg/test/resourcefixture/testdata/basic/asset/v1alpha1/assetfeed/assetfeed-full/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/asset/v1alpha1/assetfeed/assetfeed-full/update.yaml
tests/apichecks/testdata/exceptions/alpha-missingfields.txt

- The first git-commit is the real gcp log, and the second is mock gcp.
Fixes #
```release-note
```
```docs
```

Add full API coverage for AssetFeed (Gemini)

---

experiments/mcp/src/server.py
experiments/promoter/scripts/check_api_coverage.py
experiments/promoter/tasks/add-full-test-suite.md
tests/apichecks/crds_test.go

Fixes #
```release-note
```
```docs
```
With `TestCRDFieldPresenceInTestsForAlpha`, we don't need the `TARGET_KIND` anymore! This PR is to clean up the code base to avoid confusions (for humans and Gemini).

chore: remove TARGET_KIND

---

dev/tools/coverageanalyzer/finduncovered.go
dev/tools/coverageanalyzer/main.go
go.mod

Added a branch coverage analyzer based on go test coverage report to help developers better identify the true branch coverage gap.
```release-note
NONE
```
```docs
```
Please indicate the intended milestone. 

Create a branch coverage analyzer based on go test coverage report

---

.gitattributes

Address https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/4964#discussion_r2273870332
```release-note
NONE
```
```docs
```

chore: Exclude generated ci-presubmit yaml

---

.gemini/commands/generate/labels.toml
pkg/controller/direct/alloydb/instance_controller.go
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbinstance/alloydbinstance_with_invalid_labels/_generated_object_alloydbinstance_with_invalid_labels.golden.yaml
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbinstance/alloydbinstance_with_invalid_labels/_http.log
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbinstance/alloydbinstance_with_invalid_labels/create.yaml
pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbinstance/alloydbinstance_with_invalid_labels/dependencies.yaml

Fixes issue where outside/kubernetes labels are being incorrectly applied to the AlloyDBInstance.
Added gemini generate command of making a sanitize label fix. Added the result of running the gemini generate command. This includes the fix and the initial test.
```release-note
AlloyDBInstance fix for Kubernetes labels.
```
```docs
NONE
```
1.134

Adding preliminary label fix for alloydbinstance.

---

.github/workflows/ci-presubmit.yaml
dev/ci/presubmits/tests-e2e-fixtures
dev/ci/presubmits/tests-e2e-fixtures-asset
experiments/promoter/results/candidates.json
mockgcp/mockasset/savedquery.go
pkg/test/resourcefixture/testdata/basic/asset/v1alpha1/assetsavedquery/assetsavedquery-full/_generated_object_assetsavedquery-full.golden.yaml
pkg/test/resourcefixture/testdata/basic/asset/v1alpha1/assetsavedquery/assetsavedquery-full/_http.log
pkg/test/resourcefixture/testdata/basic/asset/v1alpha1/assetsavedquery/assetsavedquery-full/create.yaml
pkg/test/resourcefixture/testdata/basic/asset/v1alpha1/assetsavedquery/assetsavedquery-full/update.yaml
pkg/test/resourcefixture/testdata/basic/asset/v1alpha1/assetsavedquery/assetsavedquery-minimal/_generated_object_assetsavedquery-minimal.golden.yaml
pkg/test/resourcefixture/testdata/basic/asset/v1alpha1/assetsavedquery/assetsavedquery-minimal/_http.log
tests/apichecks/testdata/exceptions/alpha-missingfields.txt

Based on #4970, which needs to merge first.  
Fixes #
```release-note
```
```docs
```

Add full API coverage for AssetSavedquery (Gemini) 

---

dev/tasks/sync-crds-folder.sh

Fixes #
```release-note
```
```docs
```

chore: update copyright year

---

pkg/controller/direct/spanner/instance_controller.go
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerinstance/spannerinstance-autoscaling-direct/_http.log
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerinstance/spannerinstance-basic-direct/_http.log
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerinstance/spannerinstance-direct/_generated_object_spannerinstance-direct.golden.yaml
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerinstance/spannerinstance-direct/_http.log
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerinstance/spannerinstance-direct/create.yaml
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerinstance/spannerinstance-direct/update.yaml
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerinstance/spannerinstance-downgrade-edition-direct/_http.log
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerinstance/spannerinstance-processingunits-direct/_http.log
pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerinstance/spannerinstance-unset-compute-fields-direct/_http.log

Add metadata/spec label to SpannerInstance controller.
```release-note
```
```docs
```

[direct] Add metadata/spec label to SpannerInstance controller

---

dev/tasks/verify-crds-folder.sh

Fixes #
```release-note
```
```docs
```

chore: update copyright year in verify CRD check in presubmit

---

dev/ci/presubmits/validate-generated-files
dev/tasks/generate-resource-report
docs/reports/crd_report.csv
docs/reports/crd_report.md

- **chore: ensure that resource report is up to date**
- **autogen: generate resource report**
- **chore: format dev/tasks/generate-resource-report**

chore: ensure that resource report is up to date

---

pkg/controller/direct/networksecurity/mapper.generated.go

Fixes #
```release-note
```
```docs
```

fix: update generate-types-and-mappers

---

experiments/kompanion/hacks/scripts/analyze_iam_policy.py
experiments/kompanion/hacks/scripts/find_not_ready_resources.py

Stage some scripts that I found useful when analyzing kompanion reports. I think a more mature version of these can live as a kompanion command (like `kompanion analyzereport ...`)

experiments:genai: kompanion scripts

---

docs/ai/add-resource-references.md

This guide finds out and edit the resource reference in API. 
See [this git-commit](https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/5108/commits/085970172380930513e07d0999027e80e65416cb#diff-5d3887a7a88d0d3bac7189df53708df07744b4ddbc5cd1491878bdebbf5c3db3) about how it discovers the `vpcAccessRef` from a `vpcAccess` field and makes the backward compatible change for a TF-based beta resource. 
Fixes #
```release-note
```
```docs
```

feat: add gemini guide for resource reference task

---

dev/tools/controllerbuilder/pkg/codegen/mappergenerator.go
pkg/controller/direct/vmwareengine/mapper.generated.go
pkg/controller/direct/vmwareengine/privatecloud_mappers.go

Fixes #
```release-note
```
```docs
```

fix: mapper generator for OneOf if the input is not proto.Message

---

apis/cloudquota/v1beta1/generate.sh

Fixes #
```release-note
```
```docs
```

chore:  require auto-generated files in cloudquota

---

pkg/webhook/register.go

Fixes #
```release-note
```
```docs
```

exempt IAM resources from immutable field webhook

---

apis/iam/v1beta1/auditconfig_types.go
apis/iam/v1beta1/partialpolicy_types.go
apis/iam/v1beta1/policy_types.go
apis/iam/v1beta1/policymember_types.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_iamauditconfigs.iam.cnrm.cloud.google.com.yaml
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_iampartialpolicies.iam.cnrm.cloud.google.com.yaml
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_iampolicies.iam.cnrm.cloud.google.com.yaml
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_iampolicymembers.iam.cnrm.cloud.google.com.yaml

Fixes #
```release-note
```
```docs
```

Add CEL annotation for immutable fields in IAM resources

---

pkg/cli/preview/preview_test.go

Fixes #
```release-note
NONE
```
```docs
```

test: skip preview test instead of suppressing error

---

apis/billing/v1alpha1/billingaccount_types.go
apis/billing/v1alpha1/zz_generated.deepcopy.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_billingaccounts.billing.cnrm.cloud.google.com.yaml
dev/tools/controllerbuilder/pkg/codegen/mappergenerator.go
pkg/controller/direct/billing/billingaccount_fuzzer.go
pkg/controller/direct/billing/mapper.generated.go
tests/apichecks/testdata/exceptions/alpha-missingfields.txt

- **BillingAccount: rename parent to parentRef**
- **autogen: BillingAccount parentRef**
- **controllerbuilder: fix import for refs in same package**

chore: BillingAccount: rename parent to parentRef

---

pkg/controller/iam/auditconfig/iamauditconfig_controller.go
pkg/controller/iam/partialpolicy/iampartialpolicy_controller.go
pkg/controller/iam/policy/iampolicy_controller.go
pkg/controller/iam/policymember/iampolicymember_controller.go

Having the loggers named will help when we start cutting these over to direct!
```release-note
```
```docs
```

refactor: name iam loggers

---

.github/PULL_REQUEST_TEMPLATE.md

Per a comment in https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/5196#issuecomment-3307171735

chore: update template

---

.gitignore

Stop error/complaint about non existent MCP server for Config Connector with Gemini.
Stop error/complaint about non existent MCP server for Config Connector with Gemini.
```release-note
NONE
```
```docs
NONE
```

Ignore settings.json till we ship a MCP server.

---

pkg/controller/iam/partialpolicy/iampartialpolicy_controller.go
pkg/controller/iam/policy/iampolicy_controller.go
pkg/controller/iam/policymember/iampolicymember_controller.go

Add reconcile event start/end to iam controllers:
* IAMPartialPolicy
* IAMPolicy
* IAMPolicyMember
```release-note
Add better logging for starting/ stopping reconciliation for IAM resources.
```
```docs
```

Add reconcile event start/end to iam controllers

---

pkg/controller/iam/partialpolicy/iampartialpolicy_controller.go
pkg/controller/iam/policymember/iampolicymember_controller.go

Fixes #
```release-note
None
```
```docs
```

fix: Report reconciler loop with correct gvk for IAM controllers

---

dev/tasks/run-e2e
tests/e2e/script_test.go
tests/e2e/testdata/scenarios/acquisition/firewallpolicy/_object01.yaml
tests/e2e/testdata/scenarios/acquisition/firewallpolicyrule/_object01.yaml

Address https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/5147/files#r2338156787
```release-note
```
```docs
```

test: Recover cloudidentity scenarios tests

---

.gemini/commands/generate/kompaniontest.toml
.gemini/commands/generate/mockgcplog.toml
GEMINI.md
pkg/test/resourcefixture/resourcefixture.go
pkg/test/resourcefixture/testdata/kompanion/certificatemanagercertificate-kompanion/_generated_object_certificatemanagercertificate-kompanion.golden.yaml
pkg/test/resourcefixture/testdata/kompanion/certificatemanagercertificate-kompanion/_http.log
pkg/test/resourcefixture/testdata/kompanion/certificatemanagercertificate-kompanion/create.yaml
pkg/test/resourcefixture/testdata/kompanion/computebackendservice-kompanion/create.yaml
pkg/test/resourcefixture/testdata/kompanion/computebackendservice-kompanion/dependencies.yaml
pkg/test/resourcefixture/testdata/kompanion/computeregionnetworkendpointgroup-kompanion/create.yaml
pkg/test/resourcefixture/testdata/kompanion/computesslpolicy-kompanion/create.yaml
pkg/test/resourcefixture/testdata/kompanion/computeurlmap-kompanion/_generated_object_computeurlmap-kompanion.golden.yaml
pkg/test/resourcefixture/testdata/kompanion/computeurlmap-kompanion/_http.log
pkg/test/resourcefixture/testdata/kompanion/computeurlmap-kompanion/create.yaml
pkg/test/resourcefixture/testdata/kompanion/computeurlmap-kompanion/dependencies.yaml
tests/apichecks/testdata/exceptions/missingfields.txt

The goal of this PR is to generate test cases using customer Kompanion reports. This will increase test coverage for untested fields and improve the realism tests by using real data.
Areas for Improvement
1. Pre-process Kompanion reports. Sanitize the reports by removing unnecessary files(such as duplicates or failed reports, depending on our goal). This will avoiding the model's quota issues when we use a large volume of reports.
2. Remove/replace sensitive information in the generated tests. And follow other OSS best practices for protecting customer data. (Kudos to @maqiuyujoyce for pointing above out!)
3. Organize test directories. Currently, all generated tests are located in a directory named `kompanion` and have a `-kompanion` suffix. We should consider placing these tests under …

Add gemini prompt for kompanion test generation

---

apis/compute/v1beta1/generate.sh
apis/compute/v1beta1/targettcpproxy_types.go
apis/compute/v1beta1/types.generated.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_computetargettcpproxies.compute.cnrm.cloud.google.com.yaml
pkg/controller/direct/compute/client.go
pkg/controller/direct/compute/targettcpproxy_controller.go
pkg/controller/direct/compute/targettcpproxy_fuzzer.go
pkg/controller/direct/compute/targettcpproxy_mapper.go
pkg/controller/direct/compute/targettcpproxy_resolverefs.go
pkg/controller/direct/register/register.go

Address #5191 for ComputeTargetTCPProxy
```release-note
```
```docs
```

chore: Unify ComputeTargetTCPProxy direct API and controller

---

CONTRIBUTING.md

Add troubleshooting in setup doc to fix command not found issue.
```release-note
NONE
```
```docs
```

Add troubleshooting about command not found during env setup

---

config/tests/samples/create/harness.go
mockgcp/mockcompute/globalsslpolicyv1.go
mockgcp/mockcompute/service.go
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computesslpolicy/_generated_object_computesslpolicy.golden.yaml
pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computesslpolicy/_http.log
pkg/test/resourcefixture/testdata/kompanion/computesslpolicy-kompanion/_generated_object_computesslpolicy-kompanion.golden.yaml
pkg/test/resourcefixture/testdata/kompanion/computesslpolicy-kompanion/_http.log

Add mockGCP support for global ComputeSSLPolicy resource. To cover the test case in #5102
```release-note
```
```docs
```

mockgcp: support mock computesslpolicy

---

apis/backupdr/v1beta1/backupplan_types.go
apis/backupdr/v1beta1/zz_generated.deepcopy.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_backupdrbackupplans.backupdr.cnrm.cloud.google.com.yaml
pkg/controller/direct/backupdr/backupplan_controller.go
pkg/controller/direct/backupdr/backupplan_fuzzer.go
pkg/controller/direct/backupdr/backupplan_mappers.go
pkg/controller/direct/backupdr/mapper.generated.go
pkg/test/resourcefixture/testdata/basic/backupdr/v1beta1/backupdrbackupplan/backupdrbackupplan-full/_http.log
pkg/test/resourcefixture/testdata/basic/backupdr/v1beta1/backupdrbackupplan/backupdrbackupplan-labels/_generated_object_backupdrbackupplan-labels.golden.yaml
pkg/test/resourcefixture/testdata/basic/backupdr/v1beta1/backupdrbackupplan/backupdrbackupplan-labels/_http.log
pkg/test/resourcefixture/testdata/basic/backupdr/v1beta1/backupdrbackupplan/backupdrbackupplan-labels/create.yaml
pkg/test/resourcefixture/testdata/basic/backupdr/v1beta1/backupdrbackupplan/backupdrbackupplan-labels/dependencies.yaml
pkg/test/resourcefixture/testdata/basic/backupdr/v1beta1/backupdrbackupplan/backupdrbackupplan-minimal/_http.log
pkg/test/resourcefixture/testdata/basic/backupdr/v1beta1/backupdrbackupplanassociation/backupdrbackupplanassociation-minimal/_http.log
tests/apichecks/testdata/exceptions/missingfields.txt

Add the label supports for backupDRBackupPlan (just promoted, no user facing changes yet). 
Fixes #
```release-note
```
```docs
```

chore: labels for BackupDRBackupPlan

---

apis/run/v1beta1/job_types.go
apis/run/v1beta1/zz_generated.deepcopy.go
apis/secretmanager/v1beta1/secret_reference.go
apis/secretmanager/v1beta1/secretversion_reference.go
config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_runjobs.run.cnrm.cloud.google.com.yaml
pkg/controller/direct/run/mapper.generated.go
pkg/controller/direct/run/resolverefs.go
pkg/test/resourcefixture/testdata/basic/run/v1beta1/runjob/jobwithsecretmanagersecret/_generated_object_jobwithsecretmanagersecret.golden.yaml
pkg/test/resourcefixture/testdata/basic/run/v1beta1/runjob/jobwithsecretmanagersecret/_http.log
pkg/test/resourcefixture/testdata/basic/run/v1beta1/runjob/jobwithsecretmanagersecret/create.yaml
pkg/test/resourcefixture/testdata/basic/run/v1beta1/runjob/jobwithsecretmanagersecret/update.yaml

Fixes #
```release-note
```
```docs
```

chore: improve legacy secretmanager in RunJob

---

apis/run/v1beta1/job_identity.go
pkg/controller/direct/registry/registry.go
pkg/controller/direct/run/job_controller.go
pkg/test/resourcefixture/testdata/basic/run/v1beta1/runjob/basicjob/_generated_export_basicjob.golden
pkg/test/resourcefixture/testdata/basic/run/v1beta1/runjob/jobwithiamserviceaccount/_generated_export_jobwithiamserviceaccount.golden
pkg/test/resourcefixture/testdata/basic/run/v1beta1/runjob/jobwithkmscryptokey/_generated_export_jobwithkmscryptokey.golden
pkg/test/resourcefixture/testdata/basic/run/v1beta1/runjob/jobwithsecretmanagersecret/_generated_export_jobwithsecretmanagersecret.golden
pkg/test/resourcefixture/testdata/basic/run/v1beta1/runjob/jobwithvpcaccess/_generated_export_jobwithvpcaccess.golden
pkg/test/resourcefixture/testdata/basic/run/v1beta1/runjob/runjobsql/_generated_export_runjobsql.golden
tests/e2e/export.go

Fixes #
```release-note
```
```docs
```

feat: export for runjob
