GoogleCloudPlatform/k8s-config-connector

README.md
The current table of KCC resources does not have IAMPolicy listed. For completeness' sake, we should list every CRD that is being installed in the cluster.
=> add IAMPolicy resource to the table of KCC resources

config/samples/resources/binaryauthorizationpolicy/default-policy/binaryauthorization_v1beta1_binaryauthorizationpolicy.yaml, operator/config/gke-addon/image_configmap.yaml, operator/pkg/test/controller/manifest.go, operator/scripts/update-kcc-manifest/manager_sidecar_patch.yaml, operator/scripts/update-kcc-manifest/recorder_sidecar_patch.yaml, samples/resources/binaryauthorizationpolicy/default-policy/binaryauthorization_v1beta1_binaryauthorizationpolicy.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/binaryauthorization/binaryauthorizationpolicy.md
As per Kubernetes [announcement](https://kubernetes.io/blog/2023/03/10/image-registry-redirect/) , registry switched from k8s.gcr.io to registry.k8s.io which not authorized in private cluster , perhaps is possible to have conditional setting for  prometheus-to-sd image based on cluster type
=> Switch prometheus-to-sd from k8s.gcr.io to gke.gcr.io for private GKE cluster

operator/config/rbac/role.yaml
Fixes  #434
If [OwnerReferencesPermissionEnforcement](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#ownerreferencespermissionenforcement) admission controller is enabled, such as on OpenShift, ConfigConnector operator would fail with error `forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on`
This PR ensures that operator's manager role has sufficient permission to update finalizer on a configconnector resource which will then allow us to set blockOwnerDeletion on resources created via Reconcile of a ConfigConnector.
=> Fix set blockOwnerDeletion failures for OwnerReferencesPermissionEnforcement enabled clusters

scripts/environment-setup/gcp-setup.sh
I see an error on the apt install if I already have the package installed.
Added a check to skip the relevant apt install if the package is already installed.
=> Skipping problematic reinstall of gcloud if setup.

operator/config/crd/kustomization.yaml, operator/config/crd/validate_mutatingwebhookconfigurationcustomizations_name_patch.yaml, operator/config/crd/validate_validatingwebhookconfigurationcustomizations_name_patch.yaml
Validate the name for `ValidatingWebhookConfigurationCustomization` and `MutatingWebhookConfigurationCustomization` custom resource.
CRD diff introduced by this PR:
https://www.diffchecker.com/LW515tRH/
Fixes #879, b/296128049
=> Validate the name for webhook timeout customization CRs.

pkg/test/resourcefixture/testdata/basic/containerattached/v1beta1/containerattachedcluster/create.yaml, pkg/test/resourcefixture/testdata/basic/containerattached/v1beta1/containerattachedcluster/update.yaml
The previous test EKS cluster created under partner team account got deleted by the Janitor job. To avoid this, we need to specify a "do not delete" tag when creating AWS resources.
In this task, I created a new EKS cluster with the same cluster name, deployed the install-agent into that cluster, need to update the configuration in KCC test yaml file to make sure it's using the newly created EKS cluster. Otherwise test will fail because previous EKS cluster no longer exists.
Fixes b/303108135
Dynamic test passed: https://screenshot.googleplex.com/ASJgop8f77GmEZd.png
Commands:
`source scripts/shared-vars-public.sh`
export env variables if there's any
`go test -v -tags=integration ./pkg/controller/dynamic/ -test.run TestCreateNoChangeUpdateDelete -run-tests containerattached -timeout 900s`
=> Update test configuration to use new test EKS cluster

scripts/validate-prereqs.sh
This is likely helpful because when I forget to run one, I probably
forgot to run all the generation steps.
=> CI: suggest running `make ready-pr`

config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_certificatemanagercertificatemapentries.certificatemanager.cnrm.cloud.google.com.yaml, config/servicemappings/certificatemanager.yaml, pkg/clients/generated/apis/certificatemanager/v1beta1/certificatemanagercertificatemapentry_types.go, scripts/generate-google3-docs/resource-reference/generated/resource-docs/certificatemanager/certificatemanagercertificatemapentry.md
=> Fix "certificate" typo in description

.gitignore, Makefile, scripts/generate-go-crd-clients/generate-clients.sh
Some of the kubernetes generators still work better with GOPATH; we
can create a temporary directory structure to keep them happy.
=> Generate clients without requiring GOPATH

.github/workflows/presubmit.yaml, pkg/test/http_recorder.go
This lets us see richer and more structured output than we get with
just the logfile.
=> github CI: upload artifacts directory

go.mod, go.sum, scripts/generate-google3-docs/resource-reference/main.go
It doesn't appear that we were using it, and this avoids GO-2022-0411
=> generate-google3-docs: stop using sprig

scripts/generate-google3-docs/resource-reference/generated/resource-docs/containerattached/containerattachedcluster.md, scripts/generate-google3-docs/resource-reference/templates/containerattached_containerattachedcluster.tmpl
As a follow up of https://cnrm-review.git.corp.google.com/c/cnrm/+/65520, add missing prerequisites info to attached cluster resource public doc.
Fixes b/302729344
No test needed, this is doc update.
=> Add prerequisites info to attached cluster resource reference doc

hack/terraform-overrides/dataflow_flex_template_job_environment_fields.patch, hack/terraform-overrides/dataflow_flex_template_job_max_workers.patch, pkg/test/resourcefixture/testdata/basic/dataflow/v1beta1/dataflowflextemplatejob/streamingdataflowflextemplatejob/update.yaml, third_party/Makefile, third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/services/dataflow/resource_dataflow_flex_template_job.go
Fixes b/304563477
Added a patch to send SdkPipeline parameters via environment block fields and to fix the issue that the retrieved maxWorkers was always 0.
The patch is identical with the fix in TF: https://github.com/GoogleCloudPlatform/magic-modules/pull/9031
Created a streaming job using the DataflowFlexTemplateJob on a locally built KCC and the resource status became UpToDate and stayed to be UpToDate.
=> Patch the change to send SdkPipeline parameters via environment fields in DataflowFlexTemplateJob

operator/Makefile
This Makefile target is required to upgrade operator artifacts (which are now in this GitHub repository) and prepare for a new operator release.
Fixes b/303883337
=> Move upgrade-kcc target to GitHub to prepare for next release

config/tests/samples/create/harness.go, config/tests/samples/create/samples.go, tests/e2e/unified_test.go
We share a kube-apiserver instance rather than bringing it up for each
test, and we reduce some critical polling intervals.
=> e2e: speed up tests

.github/dependabot.yml, build/builder/Dockerfile, operator/Dockerfile
Also tie to specific versions of golang image in our Dockerfile (where
we use them directly), if dependabot is going to keep them up to date.
=> Enable dependabot for docker and gomod

.gitignore, CONTRIBUTING.md, README.ConfigureResourceReferences.md, README.NewResourceFromTerraform.md, README.UpdatingTerraformProvider.md
Add missing info into Add new resource through TF doc
Fixes b/301450585
Doc update, no e2e test is needed.
=> Add missing info into Add new resource through TF doc

mockgcp/common/operations/operations.go, mockgcp/go.mod
It's a wrapper around the same library, but it avoids a go.mod
dependency - and we're already using apimachinery.
=> mockgcp: replace uuid with apimachinery uuid

.github/dependabot.yml
Follow up of #910. Enable dependabot on operator/Dockerfile as well.
=> Enable dependabot for operator Dockerfile

config/samples/resources/computeurlmap/regional-compute-url-map-l7-ilb-path/compute_v1beta1_computeurlmap.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeurlmap/regionalcomputeurlmap/create.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeurlmap/regionalcomputeurlmap/update.yaml, samples/resources/computeurlmap/regional-compute-url-map-l7-ilb-path/compute_v1beta1_computeurlmap.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/compute/computeurlmap.md
Some samples/fixtures were using a field that isn't valid against the
schema.
=> tests: update urlMap tests

.github/workflows/presubmit.yaml
Stop installing the gcloud CLI, so we can validate that it is not a
requirement for the mock tests.
=> github ci: mock tests should not need gcloud CLI

mockgcp/mock_http_roundtrip.go
Minor fix: add clear debug message into mock_http_roundtrip when provided host name is invalid.
=> Minor fix: add debug message into mock_http_roundtrip

.github/dependabot.yml
This will let us pick up patch releases and remind us when 1.29 is
released.
=> Tell dependabot to ignore some k8s releases

config/tests/samples/create/harness.go, mockgcp/mockcertificatemanager/names.go, mockgcp/mockcertificatemanager/v1.go
We can start to mark whole groups as being supported now in mockgcp, rather than doing it for each type.
=> Mark CertificateManager group as supported in mockgcp

scripts/generate-go-crd-clients/generate-clients.sh
There was an extra symbolic link generated after running `make generate-go-client`.
Example:
```
shuxiancai@shuxian:~/go/src/github.com/diviner524/k8s-config-connector$ ls -l k8s-config-connector
lrwxrwxrwx 1 shuxiancai primarygroup 83 Oct 16 23:28 k8s-config-connector -> /usr/local/google/home/shuxiancai/go/src/github.com/diviner524/k8s-config-connector
```
The fix removes this symbolic link loop.
Fixes #
Tried `make generate-go-client` after the fix, the symbolic link is no longer there.
=> Remove existing folder to avoid generating symbolic link loop

pkg/controller/tf/controller.go, pkg/resourceoverrides/compute_forwardingrule.go, pkg/resourceoverrides/operations/terraformapply.go, pkg/resourceoverrides/overrides.go
We can't set the labels on creation for a forwardingRule, only with
PSC.  This is inconsistent with how forwardingRules behave elsewhere,
but we need to work with what exists.
=> Workaround for forwardingRule labels-on-create issue

config/tests/samples/create/harness.go, config/tests/samples/create/samples.go, pkg/controller/dynamic/common_test_functions.go, pkg/controller/dynamic/dynamic_controller_integration_test.go, pkg/controller/iam/auditconfig/iamauditconfig_controller_integration_test.go, pkg/controller/iam/partialpolicy/iampartialpolicy_controller_integration_test.go, pkg/controller/iam/policy/iampolicy_controller_integration_test.go, pkg/controller/iam/policymember/iampolicymember_controller_integration_test.go, pkg/controller/kccmanager/kccmanager_test.go, pkg/test/controller/condition.go
This is more accurate, and means we don't have to rely on waiting and
hoping for a reconcile.
=> tests: Verify the object observedGeneration

pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbbackup/basicalloydbbackup/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbbackup/fullalloydbbackup/create.yaml, pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbbackup/fullalloydbbackup/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbinstance/basicalloydbinstance/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbinstance/fullalloydbinstance/dependencies.yaml
This is to fix the failing test cases from alloydb. Use non-default network to avoid error:
Error waiting for Create Service Networking Connection: Error code 6, message: A tenant resource with tag "projects/940811646928/global/networks/default" already exists on this tenancy unit.
Fixes b/305866115
Local tests shows the test cases are now passing when running together:
$ go test -v -tags=integration ./pkg/controller/dynamic/ -test.run TestCreateNoChangeUpdateDelete -run-tests "fullalloydbbackup|basicalloydbbackup|fullalloydbinstance" -timeout 9000s 2>&1 | tee ~/tmp/log2.txt
--- PASS: TestCreateNoChangeUpdateDelete (6.94s)
--- PASS: TestCreateNoChangeUpdateDelete/basic-fullalloydbbackup (1219.55s)
--- PASS: TestCreateNoChangeUpdateDelete/basic-basicalloydbbackup (1221.71s)
--- PASS: …
=> Fix alloydb test cases

pkg/controller/dynamic/dynamic_controller_integration_test.go, pkg/controller/iam/auditconfig/iamauditconfig_controller_integration_test.go, pkg/controller/iam/partialpolicy/iampartialpolicy_controller_integration_test.go, pkg/controller/iam/policy/iampolicy_controller_integration_test.go, pkg/controller/iam/policymember/iampolicymember_controller_integration_test.go, pkg/test/controller/condition.go
Because we only run the reconcile method of the controller once in
some tests, we can't expect that the object has converged fully
(observedGeneration == generation); that needs another reconciliation.
In these tests, we wait only for the observedGeneration to include the
generation before reconciliation.
=> tests: if we run the controller once then the object does not converge

config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_alloydbclusters.alloydb.cnrm.cloud.google.com.yaml, config/servicemappings/alloydb.yaml, pkg/clients/generated/apis/alloydb/v1beta1/alloydbcluster_types.go, pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbinstance/basicalloydbinstance/dependencies.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/alloydb/alloydbcluster.md
Configure the service mapping for AlloyDB to enable networkRef. The previous configuration (self_link) was not working, which gives error like below:
```
malformed network path: \"[https://www.googleapis.com/compute/v1/projects/foo/global/networks/default\](https://www.googleapis.com/compute/v1/projects/foo/global/networks/default%5C)"",
```
The valueTemplate format avoids the full URL being passed as the value for network field.
Fixes b/305866115
$ go test -v -tags=integration ./pkg/controller/dynamic/ -test.run TestCreateNoChangeUpdateDelete -run-tests basicalloydbinstance -timeout 9000s 2>&1 | tee ~/tmp/log2.txt
--- PASS: TestCreateNoChangeUpdateDelete (1.33s)
--- PASS: TestCreateNoChangeUpdateDelete/basic-basicalloydbinstance (1975.80s)
PASS …
=> Use valueTemplate instead of targetField for AlloyDB networkRef

config/tests/samples/create/harness.go, config/tests/samples/create/samples.go, pkg/cli/cmd/apply.go, pkg/cli/cmd/apply/execute.go, pkg/cli/cmd/bulkexport/execute.go, pkg/cli/cmd/bulkexport/outputstream/outputstream.go, pkg/cli/cmd/export.go, pkg/cli/cmd/export/execute.go, pkg/cli/cmd/export/outputstream/outputstream.go, pkg/cli/cmd/export/outputstream/outputstream_test.go, pkg/cli/cmd/export/parameters/parameters.go, pkg/cli/cmd/printresources/resourcedescription/resourcedescription.go, pkg/cli/gcpclient/quick_test.go, pkg/cli/tf/tf.go, pkg/controller/kccmanager/kccmanager.go, pkg/test/resourcefixture/resourcefixture.go, pkg/test/resourcefixture/testdata/basic/serviceusage/v1beta1/service/export.yaml, pkg/tf/provider/provider.go, tests/e2e/unified_test.go
We need to plumb through the context so we can use this in our mocks, and then we add a test for exporting resources.
Currently just one test (for serviceusage), because it requires some mapping to the export "URI".
=> Add tests for exporting resources

go.mod, go.sum, mockgcp/go.mod
This should now be the canonical place to specify the desired go
version.
golang 1.21 builders now set GOTOOLCHAIN=local to prevent
auto-downloading also.
=> tooling: Bump go version in go.mod

config/tests/samples/create/harness.go, pkg/test/controller/reconcile.go, pkg/webhook/abandon_on_uninstall_webhook.go, pkg/webhook/container_annotation_handler.go, pkg/webhook/generic_defaulter.go, pkg/webhook/iam_defaulter.go, pkg/webhook/iam_validator.go, pkg/webhook/immutable_fields_validator.go, pkg/webhook/immutable_fields_validator_test.go, pkg/webhook/logging_handler.go, pkg/webhook/management_conflict_annotation_defaulter.go, pkg/webhook/no_unknown_fields_validator.go, pkg/webhook/register.go, pkg/webhook/resource_validator.go, pkg/webhook/types.go
The inject framework has been removed, so we need this to continue to
update controller-runtime.
=> refactor: stop using inject framework in controller-runtime

config/samples/resources/gkehubfeaturemembership/config-management-feature-membership/gkehub_v1beta1_gkehubfeaturemembership.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/create.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/update.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/gkehub/gkehubfeaturemembership.md
Remove binauthz from sample as it is no longer support.
Fixes b/307983504
This sample test is currently disabled.
https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/f8961f9694dda6124095cbc2addad4e201790aea/config/tests/samples/create/samples_test.go#L171
=> Remove usage of binauthz in samples as it is no longer supported

pkg/test/resourcefixture/test_runner.go
Pass test info into context. 
Current stage there's no value in context, we initialize it with context.TODO() and never pass any values to it. That would not give us any useful information during test run. 
In this simple code change, I pass the test information(including the test name) to the request context so that we can obtain the test name when writing to the HTTP log.
But I noticed that only works for DCL resources, evidence: https://screenshot.googleplex.com/8jqqFJAuuJ7VpRG.png; I suspect the context gets dropped somewhere when we call Terraform [Apply](https://github.com/hashicorp/terraform-plugin-sdk/blob/main/helper/schema/resource.go#L833). In addition, the test context actually depends on how we set up the test, if we drop the current test context in any method, we may lose …
=> Group http-log by test name-DCL resource

pkg/snippet/snippetgeneration/snippetgeneration.go
=> tests: give clearer test failure when sample is malformed

scripts/generate-google3-docs/resource-reference/generated/resource-docs/iam/iamauditconfig.md, scripts/generate-google3-docs/resource-reference/generated/resource-docs/iam/iampartialpolicy.md, scripts/generate-google3-docs/resource-reference/generated/resource-docs/iam/iampolicy.md, scripts/generate-google3-docs/resource-reference/generated/resource-docs/iam/iampolicymember.md, scripts/generate-google3-docs/resource-reference/templates/iam_iamauditconfig.tmpl, scripts/generate-google3-docs/resource-reference/templates/iam_iampartialpolicy.tmpl, scripts/generate-google3-docs/resource-reference/templates/iam_iampolicy.tmpl, scripts/generate-google3-docs/resource-reference/templates/iam_iampolicymember.tmpl
Because we're generating HTML inline with the markdown, line breaks confuse at least the github markdown parser.
=> docs: Fix line breaks in inline html

config/tests/samples/create/harness.go
Otherwise this had a codepath where it didn't use our mock client.
=> mock tests: also hook the oauth2 library

mockgcp/common/operations/operations.go, mockgcp/mockcertificatemanager/v1.go, mockgcp/mockcloudfunctions/v1.go, mockgcp/mockgkemulticloud/attachedcluster.go, mockgcp/mockiam/serviceaccounts.go, mockgcp/mocknetworkservices/networkservices.go, mockgcp/mockprivateca/capool.go, mockgcp/mocksecretmanager/secrets.go, mockgcp/pkg/storage/interfaces.go, mockgcp/pkg/storage/memory.go
Some clients rely on the value in the LRO; by supporting this we can
also clean up the API for delete.
=> mockgcp: Support returning values from LROs

config/tests/samples/create/samples_test.go
Disable tests for samples that create AlloyDBBackup
b/309167136
- [Done ] Run `make ready-pr` to ensure this PR is ready for review.
- [ NA] Perform necessary E2E testing for changed resources.
=> Disable tests for samples that create AlloyDBBackup - b/309167136

hack/terraform-overrides/send_request_with_context.patch, third_party/Makefile, third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/transport/transport.go
Pass context to Terraform request. Previous PR: https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1000
Evidence: https://screenshot.googleplex.com/gGUWwTkS2iM4aMh
Note: There is still an "unknown" folder, due to Terraform design, some resources, like bigquerytable, iampolicy, etc, they are not using Terraform `sendRequest()` method, to process and send request. We are not able to modify the code to pass current test context into the request. More details: https://docs.google.com/document/d/17ipukWhYa0FCmapGpLH_yPxNpALfNWbFHw3jiOEGeWY/edit#heading=h.7ljxi7p6idva
Integration test:
`go test -v -tags=integration ./pkg/controller/dynamic/ -test.run TestCreateNoChangeUpdateDelete -run-tests pubsub -timeout 300s`
=> TF patch: pass context to Terraform request

config/tests/servicemapping/servicemapping_test.go, pkg/apis/core/v1alpha1/servicemapping_types.go, pkg/crd/crdgeneration/tf2crdgeneration.go
Fixes b/309651922
* Added `observedFields` to the ResourceConfig to enable the configuration of fields exposed in the partial observed state for TF-based CRDs.
* Added the logic to generate the `status` with an `observedState` object containing the fields under `observedFields` in the TF-based CRDs.
* The current implementation focuses on the main use case that the observed field is not under an array, and itself is not an object or array field.
* Added/Updated the unit tests to ensure `observedFields` is not empty when set, and the fields under `observedFields` have no duplicates and are all valid fields in TF schema.
- Configured the `observedFields` locally in …
=> Support the configuration of the partial observed state in TF-based CRDs

pkg/test/controller/k8s.go
Test failed due to a typo in getting env variable.
Fixes b/312873271
Dynamic test passed locally
=> Fix attached cluster dynamic test

.github/workflows/presubmit.yaml, scripts/github-actions/ga-validation.sh
We have recently changed the Terraform Google Provider library as a Git Subtree in this Git repository:
third_party/github.com/hashicorp/terraform-provider-google-beta
As a result, we want to make sure all the custom changes to the Git Subtree are organized as separate commits, instead of having a commit with mixed subtree and parent project changes. 
Otherwise it will be tricky in future, if we want to update the Git Subtree and pick up changes from upstream, or we want to contribute any changes upstream.
An example of how the validation works, with an error message:
https://github.com/GoogleCloudPlatform/k8s-config-connector/actions/runs/7040435304/job/19161354482?pr=1045
Fixes: b/313935741
=> Enforce separate commit for changes in TF Git Subtree

.github/workflows/presubmit.yaml, scripts/github-actions/ga-validation.sh
The current GitHub action is triggered on both pull_request and push events. We don't need the commit validation check on push events. Also the validation will fail for push event since we don't have the required environment var from pull requests.
https://github.com/GoogleCloudPlatform/k8s-config-connector/actions/runs/7048083106/job/19183424021
Fixes b/313935741
=> Skip subtree commit validation if it is not pull_request event

third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/services/container/resource_container_node_pool.go
Fixes #833 where autoscaling would be outright removed when specifying the total totalMaxNodeCount instead of the per zone MaxNodeCount.
I have run `make ready-pr`.
I have deployed it to our dev test cluster and made sure that it works as intended:
My original YAML spec:
```
spec:
autoscaling:
totalMaxNodeCount: 4
locationPolicy: ANY
```
resulted in this container node pool being deployed:
```
Spec:
Autoscaling:
Location Policy:       ANY
Total Max Node Count:  4
```
Changing the spec to:
```
spec:
autoscaling:
totalMaxNodeCount: 1
locationPolicy: ANY
```
Results in this being updated to:
```
Spec:
Autoscaling:
Location Policy:       ANY
Total Max Node Count:  1
```
It seems to work properly.
=> Make sure that totalMaxNodeCount and totalMinNodeCount are considered when scaling the nodepool up or down

CONTRIBUTING.md
This could cause issues if the contributor is not editor or owner of the GCP project.
=> Update CONTRIBUTING.md to mention GCP project role

README.NewResourceFromTerraform.md
Add instructions on capturing HTTP raw logs
Fixes b/317927757
=> Add instructions on capturing HTTP raw logs

.github/workflows/upgrade-operator.yaml
Fixes b/315219970
Tested the GitHub action against my fork repo with the following commands (to create a new test tag):
```
git tag -a "v1.200.9" [LAST_COMMIT_SHA_IN_HISTORY] -m "test"
git push origin v1.200.9
```
The action was triggered here: https://github.com/maqiuyujoyce/k8s-config-connector/actions/runs/7332214200/job/19966023037
And it created a PR containing all the changes in my branch: https://github.com/maqiuyujoyce/k8s-config-connector/pull/13
(This PR contains the changes in one commit so it doesn't have the same commit history as the PR.)
We should verify it works fine against the product repo in the next release.
=> Add the GitHub action to upgrade the operator when a new version tag is created

config/tests/samples/create/contents_test.go, config/tests/samples/create/samples.go, config/tests/samples/create/samples_test.go, tests/e2e/unified_test.go
This lets us load the samples before creating a test project, which in
turn lets us run samples in isolated projects, particularly in mocks.
=> tests: refactor sample loading to defer substitution

scripts/generate-third-party-licenses/main.go
Fixes part of b/317999419.
In order to verify whether the operator still works without kubectl in the Dockerfile, we need to build the image and [generate the licenses for the third party libraries](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/958f7fdac577b11afbda5644ab68ba0cd70e827f/operator/Dockerfile#L41). With the current code, it errored out with the following error message:
```
panic: unhandled domain for repo ario.cat/mergo
goroutine 1 [running]:
main.repoToLicenseURL({0xc00022f6b0, 0xe}, {0xc0001112ac, 0x7})
/go/src/github.com/GoogleCloudPlatform/k8s-config-connector/scripts/generate-third-party-licenses/main.go:178 +0x8a8
main.main()
/go/src/github.com/GoogleCloudPlatform/k8s-config-connector/scripts/generate-third-party-licenses/main.go:58 +0x197
exit status …
```
=> Fix generate-third-party-licenses script

scripts/generate-google3-docs/resource-reference/generated/resource-docs/serviceusage/serviceidentity.md, scripts/generate-google3-docs/resource-reference/templates/serviceusage_serviceidentity.tmpl
This was causing confusions previously when users try to use the ServiceIdentity CRD. As a result we want to provide a link to the list of GCP services supported by this resource.
Fixes b/319135394
=> Add description and link to GCP services supported by ServiceIdentity

operator/Dockerfile
Fixes b/317999419
With kubebuilder-declarative-pattern library upgraded to v0.15.0-beta.2, kubectl is no longer a required dependency, so it can be removed from the operator Dockerfile.
Installed the operator locally onto a cluster following the steps below:
1. `make -C operator docker-build docker-push deploy`
2. `kubectl apply -f configconnector.yaml` (example yaml [here](https://cloud.google.com/config-connector/docs/how-to/install-manually#addon-configuring))
3. `kubectl apply -f configconnectorcontext.yaml` (example yaml [here](https://cloud.google.com/config-connector/docs/how-to/install-namespaced#creating_a_configconnectorcontext))
4. `kubectl apply -f …
=> Remove kubectl from operator image

README.NewResourceFromTerraform.md, scripts/generate-google3-docs/resource-reference/generated/resource-docs/containerattached/containerattachedcluster.md, scripts/generate-google3-docs/resource-reference/generated/resource-docs/secretmanager/secretmanagersecret.md, scripts/generate-google3-docs/resource-reference/overview.md, scripts/generate-google3-docs/resource-reference/templates/containerattached_containerattachedcluster.tmpl, scripts/generate-google3-docs/resource-reference/templates/secretmanager_secretmanagersecret.tmpl
This is a sample PR to add permission requirements to ConfigConnector documentation. It only applies to one doc for now, once approval, same pattern will be applied to all docs.
The idea is to have a new "before you begin" section in each resource doc, service owner should be able to identify the requirements and add there. Every resource should at least have a link to point to the service documentation "before you begin" or "prerequisites" section, including any pre-setup, grant permissions, enable apis, etc.
I also added the link to "best practice" and "troubleshooting", in the KCC resource overview page. So users can more easily find solutions to common questions.
Fixes b/291854102
The doc should now look like: 
overview: https://screenshot.googleplex.com/AL4qA6A5Qf4JgHb.png
attached …
=> Add permission requirements to SecretManagerSecret documentation

config/tests/samples/create/harness.go
As reported in
https://github.com/kubernetes-sigs/controller-runtime/issues/1571, not
doing this can cause timeout errors waiting for kube-apiserver to
stop.
=> Tests: close manager context before envtest context

.github/workflows/upgrade-operator.yaml
The customary email is noreply@github.com.
Without setting an email, we can't pass the CLA.
Issue #1144
=> build: set an email for github actions bot

operator/scripts/utils/cmd.go, operator/scripts/utils/cmd_test.go
Very partially (and hacky-ily) proposes a way to address one of the issues in #1145 .
=> guard and pin kustomize ver for operator script

config/samples/resources/dnsrecordset/dns-routing-policy-geo/dns_v1beta1_dnsmanagedzone.yaml, config/samples/resources/dnsrecordset/dns-routing-policy-geo/dns_v1beta1_dnsrecordset.yaml, config/samples/resources/dnsrecordset/dns-routing-policy-wrr/dns_v1beta1_dnsmanagedzone.yaml, config/samples/resources/dnsrecordset/dns-routing-policy-wrr/dns_v1beta1_dnsrecordset.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/dns/dnsrecordset.md
https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1097 added support for static routing policies. the new tests created public zones, and it seems like they ran into nameserver limitations (too many `example.com.` domains). changing the dnsname fixed the error in local runs.
I'm not sure why this wasn't an issue earlier, though.
```
go test -v -timeout 180s -tags=integration ./config/tests/samples/create/ -run-tests dns-routing-policy-geo
go test -v -timeout 180s -tags=integration ./config/tests/samples/create/ -run-tests dns-routing-policy-wrr
```
=> fix tests introduced in #1097

go.mod, go.sum, pkg/k8s/managedfields.go
~testing out proposed fix from~ context: https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1122#issuecomment-1915758071
In lieu of https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1122
=> chore: updated smd, fix: use typed scalar

config/tests/samples/create/harness.go, config/tests/samples/create/samples.go, config/tests/samples/create/samples_test.go, tests/e2e/unified_test.go
This also allows for context isolation and (in theory) parallel execution.
=> tests: run each mock test in a different project

config/tests/samples/create/harness.go, tests/e2e/unified_test.go
We need to pass the manager context to the mgr.Start method, not just
the mgr.New method.
Also there may have been some variable shadowing going on, and
possibly some unnecessary waiting on a channel.
Hopefully this will now address timeouts - I started hitting it
locally and this cleaned it up immediately, even with
--test.count=10
Also remove the signal handler in the test; it's not standard and it
breaks immediately with --test.count=10
=> tests: Fix shutdown ordering (again)

mockgcp/mock_http_roundtrip.go, mockgcp/mockbilling/service.go, mockgcp/mockcertificatemanager/service.go, mockgcp/mockcloudfunctions/service.go, mockgcp/mockcompute/service.go, mockgcp/mockedgecontainer/service.go, mockgcp/mockedgenetwork/service.go, mockgcp/mockgkemulticloud/service.go, mockgcp/mockiam/service.go, mockgcp/mocknetworkservices/service.go, mockgcp/mockprivateca/service.go, mockgcp/mockresourcemanager/service.go, mockgcp/mocksecretmanager/service.go, mockgcp/mockserviceusage/service.go
This avoids requiring grpc-gateway, and means we can more cleanly
inject advanced behaviours.
=> mockgcp: services should return http.Handler

pkg/controller/iam/partialpolicy/iampartialpolicy_controller_integration_test.go, pkg/controller/iam/policy/iampolicy_controller_integration_test.go, pkg/lease/leaser/leaser_integration_test.go, pkg/test/iam/shouldrun.go
Fixes b/323007209
Recover Leaser integration test, IAMPolicy integration test and IAMPartialPolicy integration test
Ran tests locally with updated test data in https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1170
Leaser integration test:
https://screenshot.googleplex.com/8BbER3TJf2TZtnQ.png
IAMPolicy integration test:
https://screenshot.googleplex.com/BWqiRAMwjBXi9SJ.png
https://screenshot.googleplex.com/5VTvDB7BNWPmxjV.png
https://screenshot.googleplex.com/8NKhFMuMDfNhXX4.png
IAMPartialPolicy integration test:
https://screenshot.googleplex.com/48HcsCwVfasRgYt.png
=> Recover disabled integration test-Leaser,IAMPolicy,IAMPartialPolicy

config/tests/samples/create/harness.go, mockgcp/common/httpmux/errors.go, mockgcp/common/httpmux/mux.go, mockgcp/mock_http_roundtrip.go, mockgcp/mockiam/service.go, mockgcp/mockiam/serviceaccounts.go, pkg/cli/gcpclient/client_integration_test.go, pkg/controller/dynamic/dynamic_controller_integration_test.go, pkg/controller/mocktests/secretmanager_secret_test.go, pkg/dcl/clientconfig/config.go, pkg/test/eventsink.go, pkg/test/http_recorder.go, pkg/test/resourcefixture/testdata/basic/iam/v1beta1/iamserviceaccount/_http.log, tests/e2e/unified_test.go
~WIP: Builds on #870.~
Demonstrates how we can export and verify the HTTP requests using golden-testing.
One gotcha is that sometimes we poll for resources, so we need to implement some basic request normalization (e.g. collapsing redundant queries for the same object)
=> Record and verify HTTP requests

mockgcp/mockapikeys/service.go
Fixes the following error in the unit test:
```
Error: mockgcp/mock_http_roundtrip.go:90:30: cannot use mockapikeys.New(env, storage) (value of type *mockapikeys.MockService) as MockService value in argument to append: *mockapikeys.MockService does not implement MockService (wrong type for method NewHTTPMux)
have NewHTTPMux(context.Context, *grpc.ClientConn) (*"github.com/grpc-ecosystem/grpc-gateway/v2/runtime".ServeMux, error)
want NewHTTPMux(context.Context, *grpc.ClientConn) (http.Handler, error)
```
This was introduced in #1168.
Ran `make test` locally and there was no errors.
=> Fix MockService for mockapikeys

pkg/controller/dynamic/dynamic_controller_integration_test.go
When we create a folder, we then try to reacquire it immediately
afterwards using the eventually-consistent search method.  Eventual
consistency is not good enough, and we regularly see flakes here.
This is a workaround to (hopefully) verify the root cause of these
flakes; we can then move to a strongly-consistent approach in a future
change.
Issue #1199
=> tests: when creating a folder, inject a wait afterwards

scripts/shared-vars-public.sh
Otherwise we don't activate in our e2e tests.
=> tests: Add apikeys to set of supported services

pkg/test/gcp/gcp.go
Deletion of a key is not standard; the key is still returned by the
API, though with deleteTime set.  Actual removal takes 30 days.
=> tests: Don't try to delete APIKeysKey

config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_computeforwardingrules.compute.cnrm.cloud.google.com.yaml, config/samples/resources/computeforwardingrule/global-internal-forwarding-rule-with-target-http-proxy/compute_v1beta1_computeaddress.yaml, config/samples/resources/computeforwardingrule/global-internal-forwarding-rule-with-target-http-proxy/compute_v1beta1_computebackendservice.yaml, config/samples/resources/computeforwardingrule/global-internal-forwarding-rule-with-target-http-proxy/compute_v1beta1_computeforwardingrule.yaml, config/samples/resources/computeforwardingrule/global-internal-forwarding-rule-with-target-http-proxy/compute_v1beta1_computehealthcheck.yaml, config/samples/resources/computeforwardingrule/global-internal-forwarding-rule-with-target-http-proxy/compute_v1beta1_computeinstancegroup.yaml, config/samples/resources/computeforwardingrule/global-internal-forwarding-rule-with-target-http-proxy/compute_v1beta1_computenetwork.yaml, config/samples/resources/computeforwardingrule/global-internal-forwarding-rule-with-target-http-proxy/compute_v1beta1_computesubnetwork.yaml, config/samples/resources/computeforwardingrule/global-internal-forwarding-rule-with-target-http-proxy/compute_v1beta1_computesubnetwork_proxy.yaml, config/samples/resources/computeforwardingrule/global-internal-forwarding-rule-with-target-http-proxy/compute_v1beta1_computetargethttpproxy.yaml, config/samples/resources/computeforwardingrule/global-internal-forwarding-rule-with-target-http-proxy/compute_v1beta1_computeurlmap.yaml, config/servicemappings/compute.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/compute/computeforwardingrule.md
The sample added in this PR will fail when run with the current controller version with the following error:
```
Invalid value for subnetwork: Cannot determine region: set in this resource, or set provider-level 'region' or 'zone'.
```
This is because KCC currently passes the subnetwork `name` to Terraform, with no region information. This is not a problem for regional forwarding rules, since Terraform can use the forwarding rule’s region to infer the subnetwork’s region. However, since global forwarding rules don’t have a region, there is no backup value so we encounter this error.
The fix is to pass the subnetwork’s `self_link` instead, since that additionally includes the subnetwork’s region. This change should be invisible to current users since, for regional forwarding rules, …
=> change ComputeForwardingRule subnetworkRef to use self_link

scripts/generate-go-crd-clients/generate-clients.sh
I think this dir held the temp gen folder but now it's `github.com/...` so let's clean it up.
=> script: cleanup temp generation folder

mockgcp/common/operations/operations.go, mockgcp/mockapikeys/key.go, mockgcp/mockbilling/billingv1.go, mockgcp/mockcertificatemanager/v1.go, mockgcp/mockcloudfunctions/v1.go, mockgcp/mockcompute/networksv1.go, mockgcp/mockcompute/subnetsv1.go, mockgcp/mockedgecontainer/cluster.go, mockgcp/mockedgecontainer/nodepool.go, mockgcp/mockedgenetwork/network.go, mockgcp/mockedgenetwork/subnet.go, mockgcp/mockgkemulticloud/attachedcluster.go, mockgcp/mockiam/serviceaccounts.go, mockgcp/mocknetworkservices/networkservices.go, mockgcp/mockprivateca/capool.go, mockgcp/mockresourcemanager/projects_internal.go, mockgcp/mocksecretmanager/secrets.go, mockgcp/mocksecretmanager/secretversions.go, mockgcp/mockserviceusage/serviceusagev1.go, mockgcp/pkg/storage/interfaces.go, mockgcp/pkg/storage/memory.go
- mockgcp: Refactor errors from storage.Get
- mockgcp: Refactor errors from storage.Update
- mockgcp: Refactor errors from storage.Delete
Builds on #1210, I broke it up to be easier to review.
=> mockgcp: Refactor errors from storage.Update and storage.Delete also

.gitignore
Ignore `.tmp` folder for git. Ran into this while using `golangci-lint`.
=> gitignore: .tmp

mockgcp/mockcompute/disksv1.go, mockgcp/mockcompute/regiondisksv1.go, mockgcp/mockresourcemanager/tagkeys.go
It is unnecessary now that we return "grpc ready" errors from the
storage layer, and may also break HTTP status codes (e.g. 404 on not
found).
=> mockgcp: Don't wrap errors in the storage layer

pkg/controller/dcl/controller.go, pkg/controller/iam/auditconfig/iamauditconfig_controller.go, pkg/controller/iam/partialpolicy/iampartialpolicy_controller.go, pkg/controller/iam/policy/iampolicy_controller.go, pkg/controller/iam/policymember/iampolicymember_controller.go, pkg/controller/lifecyclehandler/handler.go, pkg/controller/tf/controller.go, pkg/k8s/state_into_spec_annotation.go, pkg/k8s/state_into_spec_annotation_test.go, pkg/webhook/generic_defaulter.go
Fixes b/323999277
* Moved the defaulter for the `state-into-spec` annotation from the webhook to the controllers.
* The webhook is at the cluster level and the controllers are at the namespace level. In order to support the default value overrides for the `state-into-spec` annotation at the namespace level, we decided that the defaulter should be moved to the controllers.
* We assume that backwards compatibility is not a concern because users will first upgrade Config Connector to the new version, and after the upgrade is completed (all the existing CRs have been reconciled and all the unset `state-into-spec` annotations have been defaulted to `merge`), they will leverage the new feature to override the namespace-level `state-into-spec` annotation.
* Fixed the EnsureFinalizers function as …
=> Move the state-into-spec defaulter from webhook to controllers

config/tests/samples/create/harness.go, mockgcp/mockcompute/nodegroupsv1.go, mockgcp/mockcompute/nodetemplatesv1.go, mockgcp/mockcompute/service.go, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computenodegroup/_http.log, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computenodetemplate/_http.log, tests/e2e/unified_test.go
Fixes b/323011402
E2E_KUBE_TARGET=envtest RUN_E2E=1 E2E_GCP_TARGET=mock GOLDEN_REQUEST_CHECKS=1 WRITE_GOLDEN_OUTPUT=1 go test -test.count=1 -timeout 300s -v ./tests/e2e -run TestAllInSeries/fixtures/computenodetemplate
E2E_KUBE_TARGET=envtest RUN_E2E=1 E2E_GCP_TARGET=mock GOLDEN_REQUEST_CHECKS=1 WRITE_GOLDEN_OUTPUT=1 go test -test.count=1 -timeout 300s -v ./tests/e2e -run TestAllInSeries/fixtures/computenodegroup
=> mockgcp support for ComputeNodeGroup and ComputeNodeTemplate

config/tests/samples/create/samples.go
Otherwise foo/test and bar/test both get mixed into "test"
=> tests: Fix loading samples to avoid mixing samples with the same name

cmd/deletiondefender/main.go, cmd/manager/main.go, cmd/unmanageddetector/main.go, config/tests/samples/create/harness.go, config/tests/samples/create/samples_test.go, pkg/controller/dcl/controller.go, pkg/controller/gsakeysecretgenerator/service_account_key_integration_test.go, pkg/controller/kccmanager/kccmanager.go, pkg/controller/kccmanager/kccmanager_test.go, pkg/controller/registration/registration_controller.go, pkg/controller/tf/controller.go, pkg/dcl/resource.go, pkg/k8s/constants.go, pkg/k8s/defaulter.go, pkg/k8s/state_into_spec_annotation.go, pkg/krmtotf/resource.go, pkg/test/controller/reconciler/testreconciler.go
Fixes part of b/320784855
Should diff based on https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1151.
* Used the configuration passed from the kccmanager to determine the default value of the `state-into-spec` annotation in the DCL controller.
Ran `go test -v -tags=integration ./pkg/controller/dynamic/ -test.run TestCreateNoChangeUpdateDelete -run-tests containeranalysisnote -timeout 900s` and the created ContainerAnalysisNote has `state-into-spec: merge`.
=> Enable the configuration of state-into-spec default value for DCL controller

cmd/deletiondefender/main.go, cmd/manager/main.go, cmd/unmanageddetector/main.go, config/tests/samples/create/harness.go, config/tests/samples/create/samples_test.go, pkg/controller/gsakeysecretgenerator/service_account_key_integration_test.go, pkg/controller/kccmanager/kccmanager.go, pkg/controller/kccmanager/kccmanager_test.go, pkg/controller/registration/registration_controller.go, pkg/controller/tf/controller.go, pkg/k8s/constants.go, pkg/k8s/defaulter.go, pkg/k8s/state_into_spec_annotation.go, pkg/krmtotf/resource.go, pkg/test/controller/reconciler/testreconciler.go
Fixes part of b/320784855
* Supported struct `StateIntoSpecDefaulter` to validate, persist, determine and apply the default value of the `state-into-spec` annotation.
* Supported new fields `StateIntoSpecDefaultValue` and `StateIntoSpecUserOverride` in `kccmanager.Config` struct to pass the configuration of the `state-into-spec` annotation to the registration controller and then to the other controllers.
* Used the configuration passed from the kccmanager to determine the default value of the `state-into-spec` annotation in the TF controller.
Ran `go test -v -tags=integration ./pkg/controller/dynamic/ -test.run TestCreateNoChangeUpdateDelete -run-tests pubsubtopic -timeout 900s` and the created PubSubTopic has …
=> Enable the configuration of state-into-spec default value for TF controller in kccmanager

pkg/controller/iam/auditconfig/iamauditconfig_controller.go, pkg/controller/iam/partialpolicy/iampartialpolicy_controller.go, pkg/controller/iam/policy/iampolicy_controller.go, pkg/controller/iam/policymember/iampolicymember_controller.go, pkg/controller/registration/registration_controller.go, pkg/test/controller/reconciler/testreconciler.go
Fixes part of b/320784855
Run integration tests under pkg/controller/iam/ to create IAMPolicy, IAMPolicyMember, IAMPartialPolicy and IAMAuditConfig for PubSubTopic and/or Project test cases. Verified that `state-into-spec: merge` was set after the resources were created.
=> Enable the configuration of state-into-spec default value for IAM policy relevant controllers

.github/license-lint-config.yml, .github/workflows/license-lint.yaml
Add a cheap license linter. Currently the linter is https://github.com/istio/tools/tree/master/cmd/license-lint but we can swap it down the road if needed.
This doesn't replace any license gathering tooling we already have. Just a check to make sure we don't use restrictive licenses.
note for reviewers:
* [act](https://github.com/nektos/act) can be used to test a gh action e2e. Here it is in a _made-up_ scenario where the tool fails:
```
$ act -j license-lint
Found licenses: 23 reciprocal, 187 unrestricted, 0 restricted, 1 unrecognized, and 0 unlicensed. 6 are allowlisted.
ERROR: Some modules have unrecognized licenses:
github.com/google/pprof: path '<MY_PATH>/github.com/google/pprof@v0.0.0-20210804190019-f964ff605595/third_party/svgpan/LICENSE'
```
=> chore: add a license-lint gh action

.golangci.yaml
Enables go-vet for golang-ci.
This should be free for us since we already run vet as part of make test:
https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/09c6b365bb1e416e555f86f27011047e449e70dc/Makefile#L42
=> chore:lint: enable go-vet linter

operator/scripts/utils/yaml.go
I think the behaviour here changes in the lint-fixes; refactor to
follow the normal pattern so this is more self-evident code.
=> Refactor: rewrite SplitYAML to be more conventional

pkg/tf/serialization/testdata/cluster.golden.tf
This golden test was ignoring extra lines in the golden output.  We
want to move to a stricter comparison model; start by removing these
lines so that it can be clearer.
=> tests: remove extra lines from our golden cluster test

pkg/servicemapping/servicemappingloader/servicemappingloader.go
Avoids printing a nil error, gives a better contextual hint.
=> chore: better error messages in servicemappingloader

.github/workflows/lint.yaml
This seems to cause double caching.
https://github.com/golangci/golangci-lint-action/issues/135
=> chore: don't use caching for go task in lint github action

.github/workflows/lint.yaml, Makefile
It seems that 1.54.1 had one issue with handling non existing VCS information for binaries. 1.54.2 fixes that. I'm also adding the `lint` target as a required for `ready-pr` so devs get an early signal if there's an issue.
=> chore:ci: bump golangci-lint and add make target

docs/releasenotes/release-1.113.0.md
I figure we can stage these in our repo, and also collaboratively build them before the actual release (e.g. in PRs)
=> Release notes for 1.113.0

pkg/controller/lifecyclehandler/handler.go, pkg/controller/lifecyclehandler/handler_test.go, pkg/k8s/errors.go
errors.Is performs an equality check, which is not normally what we want.
=> chore: avoid errors.Is, replace with IsFoo

pkg/controller/dynamic/dynamic_controller_integration_test.go, pkg/test/controller/reconcile.go, pkg/test/controller/reconciler/testreconciler.go
In particular, we want to know if a reconcile operation is taking a
long time.
=> tests: Add more logging in e2e tests

mockgcp/mockapikeys/key.go, mockgcp/mockbilling/billingv1.go, mockgcp/mockcertificatemanager/v1.go, mockgcp/mockcloudfunctions/v1.go, mockgcp/mockcompute/disksv1.go, mockgcp/mockcompute/networksv1.go, mockgcp/mockcompute/regiondisksv1.go, mockgcp/mockcompute/subnetsv1.go, mockgcp/mockedgecontainer/cluster.go, mockgcp/mockedgecontainer/nodepool.go, mockgcp/mockedgenetwork/network.go, mockgcp/mockedgenetwork/subnet.go, mockgcp/mockgkemulticloud/attachedcluster.go, mockgcp/mockiam/serviceaccounts.go, mockgcp/mocknetworkservices/networkservices.go, mockgcp/mockprivateca/capool.go, mockgcp/mockresourcemanager/projects_internal.go, mockgcp/mockresourcemanager/projectsv3.go, mockgcp/mockresourcemanager/tagkeys.go, mockgcp/mocksecretmanager/secrets.go, mockgcp/mocksecretmanager/secretversions.go, mockgcp/mockserviceusage/serviceusagev1.go
Errors from storage Create/Update should not be wrapped.
=> mockgcp: fix a few more extra-wrappings of errors

mockgcp/README.md
Upon team's request, I added some instructions for obtaining golden HTTP logs in the mockGCP readme.
=> Add http log instructions in mockgcp readme

operator/pkg/controllers/configconnector/configconnector_controller.go, operator/pkg/controllers/configconnector/configconnector_controller_test.go, operator/pkg/controllers/configconnectorcontext/configconnectorcontext_controller.go, operator/pkg/controllers/configconnectorcontext/configconnectorcontext_controller_test.go, operator/pkg/k8s/constants.go
Small err wrap that fooled the errorlint linter. Although if it did fool it, not sure we should fix it 😝 .
=> refactor:chore:lint missed err wrap

operator/config/crd/bases/core.cnrm.cloud.google.com_configconnectorcontexts.yaml, operator/config/crd/bases/core.cnrm.cloud.google.com_configconnectors.yaml, operator/pkg/apis/core/v1beta1/configconnector_types.go, operator/pkg/apis/core/v1beta1/configconnectorcontext_types.go, operator/pkg/apis/core/v1beta1/modes.go, pkg/controller/kccmanager/kccmanager.go, pkg/controller/kccmanager/nocache/clientbuilder.go, pkg/controller/mocktests/harness.go, pkg/controller/resourceactuation/resourceactuation.go, pkg/controller/resourceactuation/resourceactuation_test.go, pkg/controller/tf/controller.go
This PR proposes a way to support a `pause` mode for KCC. In particular, it adds new fields in the CC/ CCC specs to support an `actuationMode`. These values are then consumed before we actuate the GCP resources: see the tf controller.
Work that will come as separate PR(s)
- dcl (or direct) controller support for pausing actuation
- docs changes
- sone higher level e2e tests using golden logs
Abandoned ideas
- having a fully fledged simple reconciler for CC/ CCC to watch the resources and keep track of the `actuationMode` values
Renaming
- the `actuationMode` war originally `actuationAction` then `reconciliationMode`.
=> feat: pause resource actuation

config/tests/samples/create/harness.go
During the `pause` work, I discovered that there's not a golden log for `serviceusage.cnrm.cloud.google.com/Service` just yet. I can capture that later but skipping it if `GOLDEN_REQUEST_CHECKS` is set for now.
=> fix: skip for golden check

config/tests/samples/create/samples_test.go
While running the samples tests it may be helpful to know if no samples load and exist early.
=> tests: log if no samples

config/tests/samples/create/harness.go, pkg/controller/deletiondefender/controller.go, pkg/controller/tf/controller.go
This should hopefully allow us to filter these messages in testing,
and it is also a step towards using the more coherent context-aware
logging introduced over the years.
=> logging: log to configured logger when registering controller

operator/config/crd/bases/core.cnrm.cloud.google.com_configconnectorcontexts.yaml, operator/pkg/apis/core/v1beta1/configconnectorcontext_types.go, operator/pkg/apis/core/v1beta1/zz_generated.deepcopy.go, pkg/k8s/defaulter.go
This follows the KRM conventions.
=> CCC: Switch Enum values for spec.stateIntoSpec to upper camel case

.github/workflows/presubmit.yaml, config/tests/samples/create/samples.go, pkg/controller/dcl/controller.go, pkg/controller/direct/directbase/directbase_controller.go, pkg/controller/iam/auditconfig/iamauditconfig_controller.go, pkg/controller/iam/partialpolicy/iampartialpolicy_controller.go, pkg/controller/iam/policy/iampolicy_controller.go, pkg/controller/iam/policymember/iampolicymember_controller.go, pkg/controller/tf/controller.go, scripts/github-actions/ga-pause-test.sh, tests/e2e/unified_test.go
This patch extends the Pause feature to all other controllers that are responsible for actuating resources onto a cloud provider.
We probably don't want to run a `pause` test for every PR so just including this commit for now here. Finally, there's a `cherry-picked` commit for fixing an issue w a missing golden log file.
=> feat: more controllers supporting pause

tests/e2e/unified_test.go
I think the test method name (the first component) is sufficient here,
and then we don't need to change the test paths for "normal"
TestAllInSeries.
=> chore: avoid changing name of tests

config/servicemappings/alloydb.yaml, pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbcluster/basicalloydbcluster/create.yaml, pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbcluster/basicalloydbcluster/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbcluster/basicalloydbcluster/update.yaml, third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/services/alloydb/resource_alloydb_cluster.go
Fixes b/308185711
Make `spec.displayName` mutable-but-unreadable to work around the always empty displayName in AlloyDBCluster.
Diffbase: #1395 
Added `spec.displayName` in testdata for basicalloydbcluster and ran the following command:
`go test -timeout 1200s -v -tags=integration ./pkg/controller/dynamic/ -test.run TestCreateNoChangeUpdateDelete -run-tests basicalloydbcluster`
It passed.
=> Set displayName to be mutable-but-unreadable in AlloyDBCluster

third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/envvar/envvar_utils.go, third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/fwmodels/provider_model.go, third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/fwprovider/framework_provider.go, third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/fwtransport/framework_config.go, third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/provider/provider.go, third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/provider/universe/universe_domain_compute_test.go, third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/provider/universe/universe_domain_pubsub_test.go, third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/provider/universe/universe_domain_storage_test.go, third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/provider/universe/universe_domain_util.go, third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource/field_helpers.go, third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource/utils.go, third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/transport/config.go, third_party/github.com/hashicorp/terraform-provider-google-beta/website/docs/guides/provider_reference.html.markdown
Backporting https://github.com/GoogleCloudPlatform/magic-modules/pull/8657
Add provider attribute universe_domain
provider: added `universe_domain` attribute as a provider attribute
=> Backport Add provider attribute universe_domain

config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_computedisks.compute.cnrm.cloud.google.com.yaml, config/servicemappings/compute.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/compute/computedisk.md
Clarifies field `spec.resourcePolicies` only applies for zonal ComputeDisk resources.
internal: b/324925137
=> docs: clarify field usage

config/tests/samples/create/harness.go, go.mod, go.sum, pkg/test/resourcefixture/testdata/vcr/cassette/TestAllInSeries_fixtures_computenodetemplate.yaml, tests/e2e/unified_test.go
In this PR, I implemented the same thing as in #1345, with a different approach. I incorporated [go-vcr ](https://github.com/dnaeon/go-vcr) package and used its recorder.
=> vcr: use go-vcr package to setup vcr recorder

Makefile
As suggested by Anh, we can move the golangci-lint cache location outside of our repo for now. After developers clean up their `REPO_ROOT/.tmp/` folder  then our script tooling won't be literred by log lines like:
```
...
tmp/golangci-lint/ff/ffbd2d9bad66f8ad457fbd8f0cb7f56a0758e1bdd37547ebfa306386f3704753-a error: lstat .tmp/golangci-lint/ff/ffbd2d9bad66f8ad457fbd8f0cb7f56a0758e1bdd37547ebfa306386f3704753-a: permission denied
...
```
I probably want to fix the core permissions issue in a follow up PR.
=> fix:"fix:" move cache location

pkg/krmtotf/fetchlivestate.go
Change ShouldCheckParentReadyForDelete to skip immediately for resource kinds in allowlist.
Fixes b/328565395
=> Fix deletion lock for Tags Key/Value

config/tests/samples/create/harness.go, pkg/test/resourcefixture/testdata/vcr/cassette/TestAllInSeries_fixtures_computenodetemplate.yaml, tests/e2e/unified_test.go
ref: https://github.com/dnaeon/go-vcr?tab=readme-ov-file#hooks
The hook will replace values in request/response pairs before we save them to file. 
Note: Applying hook to replace data that we don't want to expose to public. Some data, like timestamp, or id, does not contain sensitive information, so it's fine to leave them for now.
If we can migrate VCR testing as a part of prow job, and save cassette file to GCS bucket, then we may not need hooks since it's a private storage.
=> vcr: Apply hook in  vcr recorder

config/tests/samples/create/harness.go, pkg/test/resourcefixture/testdata/vcr/cassette/TestAllInSeries_fixtures_computenodetemplate.yaml, tests/e2e/unified_test.go
Add custom matcher to match incoming request against saved request
=> vcr: Apply custom matcher

.github/workflows/dcl-upgrade-probe.yaml
Add a cheap solution to know when the dcl upgrade (to latest) is broken. The test is `make upgrade-dcl && make ready-pr` and we'd run it as a daily cron against the latest commit of the main branch.
Fixes https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/1340
=> ci: add dcl upgrade probe

pkg/krmtotf/tftokrm.go
Found this to be useful when debugging a failed test.
=> print the actual error when parsing resourceID panics

cmd/deletiondefender/main.go, cmd/unmanageddetector/main.go, config/tests/samples/create/harness.go, operator/cmd/manager/main.go, operator/pkg/test/main/testmain.go, pkg/controller/kccmanager/kccmanager.go, pkg/controller/kccmanager/nocache/clientbuilder.go, pkg/test/controller/reconcile.go, pkg/test/http_recorder.go, tests/e2e/unified_test.go
- tests: Verify the kubernetes watches we open
- tests: use the same cache options in tests as in controllers
- Control caching by kind using exclude list
=> Verify watches and configure them as we expect

config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_alloydbinstances.alloydb.cnrm.cloud.google.com.yaml, config/samples/resources/alloydbbackup/alloydb_v1beta1_alloydbinstance.yaml, config/samples/resources/alloydbcluster/restored-from-backup-cluster/alloydb_v1beta1_alloydbinstance.yaml, config/samples/resources/alloydbinstance/primary-instance/alloydb_v1beta1_alloydbinstance.yaml, config/samples/resources/alloydbinstance/read-instance/alloydb_v1beta1_alloydbinstance.yaml, config/samples/resources/alloydbinstance/zonal-instance/alloydb_v1beta1_alloydbinstance.yaml, config/samples/resources/alloydbuser/database-user/alloydb_v1beta1_alloydbinstance.yaml, config/samples/resources/alloydbuser/iam-user/alloydb_v1beta1_alloydbinstance.yaml, config/servicemappings/alloydb.yaml, pkg/clients/generated/apis/alloydb/v1beta1/alloydbinstance_types.go, pkg/resourceoverrides/alloydb_instance.go, pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbcluster/basicalloydbsecondarycluster/create.yaml, pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbcluster/basicalloydbsecondarycluster/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbcluster/basicalloydbsecondarycluster/update.yaml, pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbinstance/basicalloydbsecondaryinstance/create.yaml, pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbinstance/basicalloydbsecondaryinstance/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbinstance/basicalloydbsecondaryinstance/update.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/alloydb/alloydbinstance.md
This performs minor clean ups missed in https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1279
Fixed Copyright year for modified and new yaml files
Removed the word "Required" from the instanceTypeRef field description
Nit: Reorder import package
=> Alloydb CRR cleanup for #1279

cmd/deletiondefender/main.go, cmd/unmanageddetector/main.go, config/tests/samples/create/harness.go, operator/cmd/manager/main.go, operator/pkg/test/main/testmain.go, pkg/controller/kccmanager/kccmanager.go, pkg/controller/kccmanager/nocache/clientbuilder.go, pkg/test/controller/reconcile.go, pkg/test/http_recorder.go, tests/e2e/unified_test.go
Cherry pick of #1433 on release-1.114.
#1433: tests: Verify the kubernetes watches we open
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
```release-note
```
=> Automated cherry pick of #1433: tests: Verify the kubernetes watches we open

config/samples/resources/alloydbinstance/secondary-instance/alloydb_v1beta1_alloydbcluster.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/alloydb/alloydbinstance.md
Added initalUser to the primary cluster resource used in secondary-instance example
Fixes the test failure for AlloyDB secondary-instance
- [ N/A] Perform necessary E2E testing for changed resources.
=> Add initialUser to primary cluster for AlloyDB secondary instance sample

scripts/generate-google3-docs/resource-reference/generated/resource-docs/alloydb/alloydbinstance.md, scripts/generate-google3-docs/resource-reference/templates/alloydb_alloydbinstance.tmpl
Added note to ensure users create secondary instances only after primary instance is ready
- [ N/A] Perform necessary E2E testing for changed resources.
=> Added note for secondary instance creation

pkg/test/resourcefixture/test_runner.go
It is confusing that the test says "PASS" when in fact no test case was tested.
```
$ go test -timeout 2400s -v -tags=integration ./pkg/controller/dynamic/ -test.run TestCreateNoChangeUpdat
eDelete -run-tests abc                                                                    
{"severity":"info","timestamp":"2024-04-03T01:31:17.685Z","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/deny-unknown-fields"}
{"severity":"info","timestamp":"2024-04-03T01:31:17.685Z","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/iam-validation"}
{"severity":"info","timestamp":"2024-04-03T01:31:17.685Z","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/iam-defaulter"}
{"severity":"info","timestamp":"2024-04-03T01:31:17.685Z","logger …
```
=> test: fail the test if no test case was run

Makefile, tests/e2e/unified_test.go
Added tests/ and experiments/ folders to goimports command.
I think it is simpler and easier to maintain if we enforce goimports across the entire repository but it seems to modify generated files that don't have a good import grouping rule. So I manually picked two more folders to cover.
=> Make goimports cover the entire repository

experiments/compositions/composition/Makefile
Enforcing it here helps us not forget to run format from the root.
=> chore: automatically add headers as part of fmt

experiments/compositions/composition/Makefile, experiments/compositions/composition/config/default/kustomization.yaml, experiments/compositions/composition/config/manager/kustomization.yaml, experiments/compositions/composition/config/rbac/role.yaml, experiments/compositions/composition/internal/controller/composition_controller.go, experiments/compositions/composition/internal/controller/expander_factory.go, experiments/compositions/composition/release/kind/alice_crds.yaml, experiments/compositions/composition/release/kind/crds.yaml, experiments/compositions/composition/release/kind/operator.yaml, experiments/compositions/demo/context.yaml, experiments/compositions/expanders/jinja-expander/Makefile
Compositions runnable in a kind cluster.
- Validate the composition manifests are working in a kind cluster
- Changes required to grant additional rbac permissions to the composition controller
- Changes to create jobs in the namespace of the composition object instead of default namespace
- Changes to grant appropriate permissions using Roles and bindings instead of ClusterRoles and bindings
- make target to generate manifests deployable to a kind cluster
- make target to build images, create a kind cluster, add images to the kind cluster and deploy the controller there. Allows for e2e tests to be run in kind clusters.
=> Changes to make compositions deployable to a kind cluster

docs/releasenotes/release-1.114.md
Small change to call our CC & CCC usage for `spec.actuationMode` in the release notes for 1.114.1
=> docs: call out CC and CCC for pause

config/tests/samples/create/samples.go, tests/e2e/script_test.go, tests/e2e/testdata/scenarios/README.md, tests/e2e/testdata/scenarios/ccc_pause_change_reconcile/SCENARIO_README.MD, tests/e2e/testdata/scenarios/ccc_pause_change_reconcile/_http02.log, tests/e2e/testdata/scenarios/ccc_pause_change_reconcile/_http05.log, tests/e2e/testdata/scenarios/ccc_pause_change_reconcile/_object00.yaml, tests/e2e/testdata/scenarios/ccc_pause_change_reconcile/_object01.yaml, tests/e2e/testdata/scenarios/ccc_pause_change_reconcile/_object02.yaml, tests/e2e/testdata/scenarios/ccc_pause_change_reconcile/_object03.yaml, tests/e2e/testdata/scenarios/ccc_pause_change_reconcile/_object05.yaml, tests/e2e/testdata/scenarios/ccc_pause_change_reconcile/script.yaml
Adds a first step wise based test for pause/ unpause with a CCC.
generated artifacts by running:
```bash
$ WRITE_GOLDEN_OUTPUT=1 GOLDEN_REQUEST_CHECKS=1 E2E_KUBE_TARGET=envtest E2E_GCP_TARGET=real RUN_E2E=1 \
go test -test.count=1 -timeout 360s -v ./tests/e2e -run TestE2EScript 2>&1
```
=> tests: add step wise for CCC Pause

config/tests/samples/create/harness.go, tests/e2e/unified_test.go
1. Update vcr hook to record failed requests (404, 400, 403) but replace the internal error message. My initial idea was that removing them would speed up vcr replay, but in some cases, missing those requests would cause an "interaction not found" issue in replay mode.
2. Update vcr matcher to sort request json body before comparing. json can be same but reordered
3. Update to use example-project in replay mode
=> vcr: Update vcr hook and matcher to avoid potential failures

.github/workflows/dcl-upgrade-probe.yaml, .github/workflows/license-lint.yaml, .github/workflows/lint.yaml, .github/workflows/presubmit.yaml, .github/workflows/upgrade-operator.yaml
This avoids having to repeat the go version, and in general we want to
keep them in sync.
=> chore: update github actions to use go version in go.mod

experiments/compositions/composition/api/v1/composition_types.go, experiments/compositions/composition/config/crd/bases/composition.google.com_compositions.yaml, experiments/compositions/composition/internal/controller/expander_fetcher.go
Add valuesFrom.resourceRef.nameSuffix to support the use case where he dependent resource name is dynamically generated by a previous stage.
For now it supports the pattern: <inputapi.name><suffix>
This is limiting but provides a way to achieve it.
=> Support dynamic names for valueFrom resources in composition

mockgcp/common/httpmux/mux.go, mockgcp/mockaiplatform/service.go, mockgcp/mockapikeys/service.go, mockgcp/mockbilling/service.go, mockgcp/mockiam/service.go, mockgcp/mockresourcemanager/service.go
We want to send empty values on e.g. the cloudbilling API
=> mockgcp: support options on httpmux

mockgcp/mocklogging/service.go, mockgcp/mockmonitoring/service.go
```
mockgcp/mockmonitoring/service.go:61:45: cannot use pb.RegisterDashboardsServiceHandler (value of type func(ctx context.Context, mux *"github.com/grpc-ecosystem/grpc-gateway/v2/runtime".ServeMux, conn *grpc.ClientConn) error) as httpmux.Options value in argument to httpmux.NewServeMux
mockgcp/mocklogging/service.go:57:3: cannot use pb.RegisterMetricsServiceV2Handler (value of type func(ctx context.Context, mux *"github.com/grpc-ecosystem/grpc-gateway/v2/runtime".ServeMux, conn *grpc.ClientConn) error) as httpmux.Options value in argument to httpmux.NewServeMux
FAIL    github.com/GoogleCloudPlatform/k8s-config-connector/tests/e2e [build failed]
FAIL
```
=> mockgcp: fix build error

config/tests/samples/create/samples_test.go
Until we can enforce that secondary instance should only be created
once primary is created.
=> tests: skip secondary-instance sample test for now

third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/provider/provider.go, third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/transport/config.go
splits off the default API endpoint half of HandleSDKDefaults func into its own function and calls that new function after TPC universe domain is set. This allows the basepath defaults to use the new domain if set
The API custom/default endpoints are not used between when HandleSDKDefaults was called to after the TPC universe logic, so this reorder should be safe. HandleSDKDefaults is also not called anywhere else outside of the one use.
provider: fixed an issue where universe domains would not overwrite API endpoints
=> Backporting https://github.com/GoogleCloudPlatform/magic-modules/pull/9463

README.NewResourceFromTerraform.md
This effectively reverts #1299, which is obsolete after #1465.
=> doc: update new resource guide

experiments/compositions/composition/.gitignore, experiments/compositions/composition/api/v1/composition_types.go, experiments/compositions/composition/cmd/main.go, experiments/compositions/composition/internal/controller/composition_controller.go, experiments/compositions/composition/release/kind/crds.yaml, experiments/compositions/composition/release/kind/operator.yaml, experiments/compositions/composition/tests/data/TestSimpleCompositionStatusFacadeCRDMissing/facade_crd.yaml, experiments/compositions/composition/tests/data/TestSimpleCompositionStatusFacadeCRDMissing/input.yaml, experiments/compositions/composition/tests/data/TestSimpleCompositionStatusFacadeCRDMissing/output.yaml, experiments/compositions/composition/tests/data/TestSimpleCompositionStatusValidation/fixed_composition.yaml, experiments/compositions/composition/tests/data/TestSimpleCompositionStatusValidation/input.yaml, experiments/compositions/composition/tests/data/TestSimpleCompositionStatusValidation/output.yaml, experiments/compositions/composition/tests/scenario/scenario.go, experiments/compositions/composition/tests/testcases/simple_test.go, experiments/compositions/composition/tests/testclient/client.go, experiments/compositions/composition/tests/utils/utils.go
Add event recorder for Composition controller.
Update status of composition cr when reconciling fails.
Fixes #1522
```
go test -timeout 3600s -v -run "^TestSimpleCompositionStatusFacadeCRDMissing$" --images=gcr.io/allotrope-barni/composition:v0.0.1.alpha,gcr.io/allotrope-barni/manifests-inline:v0.0.1.alpha,gcr.io/allotrope-barni/expander-jinja2:v0.0.1.alpha
=== RUN   TestSimpleCompositionStatusFacadeCRDMissing
cluster.go:117: Reserved cluster composition-e2e-0
scenario.go:211: Applying input
scenario.go:188: Creating object "Composition/default/projectconfigmap" on cluster "composition-e2e-0"
scenario.go:219: Verifying input
scenario.go:220: Checking existence of objects ["Composition/default/projectconfigmap"] on "composition-e2e-0"
simple_test.go:139: Checking condition "Error" present …
```
=> Add Events and update Status for Composition CR when processing.

.github/workflows/license-lint.yaml
We first must checkout the repo before we can use its `go.mod` file in the setup go step.
=> ci:refactor: reorder steps

go.mod, go.sum, pkg/controller/direct/apikeys/apikeyskey_controller.go, pkg/controller/direct/directbase/directbase_controller.go, pkg/controller/direct/directbase/interfaces.go, pkg/controller/direct/resourcemanager/client.go, pkg/controller/direct/resourcemanager/tagkey_controller.go, pkg/controller/direct/resourcemanager/utils.go, pkg/controller/registration/registration_controller.go
Also fix up Update method to match Create method.
=> genapi: Add support for TagsTagKey

mockgcp/common/workflows/newproject.go, mockgcp/common/workflows/utils.go, mockgcp/mock_http_roundtrip.go, mockgcp/mockresourcemanager/projectsv3.go
Some actions are cross-service, for example a "default" network is created in new projects.
=> mockgcp: Support workflows

config/tests/samples/create/harness.go, pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbbackup/fullalloydbbackup/dependencies.yaml, tests/e2e/testdata/vcr-cassette/TestAllInSeries_fixtures_computenodegroup-dcl.yaml, tests/e2e/testdata/vcr-cassette/TestAllInSeries_fixtures_computenodegroup-oauth.yaml, tests/e2e/testdata/vcr-cassette/TestAllInSeries_fixtures_computenodegroup-tf.yaml, tests/e2e/testdata/vcr-cassette/TestAllInSeries_fixtures_computenodetemplate-dcl.yaml, tests/e2e/testdata/vcr-cassette/TestAllInSeries_fixtures_computenodetemplate-oauth.yaml, tests/e2e/testdata/vcr-cassette/TestAllInSeries_fixtures_computenodetemplate-tf.yaml, tests/e2e/testdata/vcr-cassette/TestAllInSeries_fixtures_privatecacapool-dcl.yaml, tests/e2e/testdata/vcr-cassette/TestAllInSeries_fixtures_privatecacapool-oauth.yaml, tests/e2e/testdata/vcr-cassette/TestAllInSeries_fixtures_privatecacapool-tf.yaml, tests/e2e/unified_test.go
Setup VCR recorder for DCL and TF Oauth requests. Re-generate cassette files and save them under tests/e2e/testdata/vcr-cassette folder
Unfortunately we need 3 separate recorders for TF, DCL and Oauth, as they are using different transport. go-vcr package doesn't have a built-in way to save interactions from multiple recorders into a single cassette file.
=> vcr: Set up VCR recorder for DCL requests

.github/workflows/presubmit.yaml
There's no artifacts file to upload for pause test: https://screenshot.googleplex.com/BRn7vRxPpCVQUpo.png
Also I noticed that the GH presubmit/pause-test failed in some PRs([job](https://github.com/GoogleCloudPlatform/k8s-config-connector/actions/runs/8635527978/job/23673443666?pr=1498)). Unsure about the root cause but seems the error comes from [http_recorder.go](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/204782804df09f0ec10187bcdc7b13891b0203b7/pkg/test/http_recorder.go#L126). Removing `ARTIFACTS` env variable would be a quick fix.
=> Don't upload artifacts for pause test

pkg/k8s/allowlist_test.go
We don't need to check v1alpha1 resources.
A side note:
When we promote a resource from v1alpha1 to v1beta1, we make all changes to v1alpha1 schema first, so that the updated v1alpha1 and v1beta1 have the same schema. Therefore it is possible for v1alpha1 resources to have observedState field during the resource version promotion.
=> skip alpha resources in TestOutputOnlyFieldsAreUnderObservedState

mockgcp/Makefile
Fix a path to store the generated storage proto from openapi
=> Correct the path for storage proto

experiments/compositions/composition/internal/controller/composition_controller.go, experiments/compositions/composition/internal/controller/expander_applier.go, experiments/compositions/composition/internal/controller/expander_reconciler.go, experiments/compositions/composition/pkg/containerexecutor/jobcontainerexecutor/jobcontainerrunner.go
Starting by moving the code, then we can add a second implementation
to understand the underlying contract.
=> chore: refactor job execution in compositions with a view to making it pluggable

pkg/test/resourcefixture/testdata/basic/accesscontextmanager/v1beta1/accesscontextmanagerserviceperimeter/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/accesscontextmanager/v1beta1/accesscontextmanagerserviceperimeterresource/dependencies.yaml
This is mentioned in PR https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1281 ([comment](https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1281/files#r1503617089)). For this resource, it's unnecessary to use the pre-created project. I think I addressed that in 1281, but it seems the change was reverted in a rebase.
test passed on 2/27 with this change: https://prow-gob.gcpnode.com/view/gs/cnrm-prow/pr-logs/pull/cnrm-review.googlesource.com_cnrm/68740/cnrm-test/1762679866815156224
=> tests: Fix accesscontextmanager test data

experiments/compositions/composition/Makefile, experiments/compositions/composition/api/v1alpha1/zz_generated.deepcopy.go, experiments/compositions/composition/config/crd/bases/composition.google.com_compositions.yaml, experiments/compositions/composition/config/crd/bases/composition.google.com_contexts.yaml, experiments/compositions/composition/config/crd/bases/composition.google.com_plans.yaml, experiments/compositions/composition/release/kind/crds.yaml, experiments/compositions/composition/release/kind/operator.yaml
chore: update to controller-tools 0.14.0
same as https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1473
Doing it on latest baseline and ran tests
```
...
...
scenario.go:227: Verifying output
scenario.go:228: Checking existence of objects ["ConfigMap/team-a/proj-a" "Plan/team-a/pconfigs-team-a-config"] on "composition-e2e-0"
simple_test.go:73: Adding proj-b entry to Facade
simple_test.go:80: Applying patch map["op":"add" "path":"/spec/projects/-" "value":"proj-b"] to "PConfig/team-a/team-a-config" on "composition-e2e-0"
simple_test.go:84: Checking existence of objects ["ConfigMap/team-a/proj-b"] on "composition-e2e-0"
scenario.go:243: Cleaning up input
scenario.go:245: Deleting object "CustomResourceDefinition/pconfigs.facade.foocorp.com" on cluster "composition-e2e-0" …
```
=> chore: update to controller-tools 0.14.0

tests/e2e/script_test.go, tests/e2e/testdata/scenarios/README.md, tests/e2e/testdata/scenarios/cc_pause_change_reconcile/SCENARIO_README.MD, tests/e2e/testdata/scenarios/cc_pause_change_reconcile/_http01.log, tests/e2e/testdata/scenarios/cc_pause_change_reconcile/_http04.log, tests/e2e/testdata/scenarios/cc_pause_change_reconcile/_object00.yaml, tests/e2e/testdata/scenarios/cc_pause_change_reconcile/_object01.yaml, tests/e2e/testdata/scenarios/cc_pause_change_reconcile/_object02.yaml, tests/e2e/testdata/scenarios/cc_pause_change_reconcile/_object04.yaml, tests/e2e/testdata/scenarios/cc_pause_change_reconcile/script.yaml, tests/e2e/testdata/scenarios/ccc_pause_change_reconcile/script.yaml
Patch continues to add more step wise scenarios for pause. It also renames `CHECK-LOG` to ~ `WAIT-FOR-HTTP-REQUEST` as per https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1451#discussion_r1553626724
=> tests: cc pause step test

cmd/deletiondefender/main.go, cmd/unmanageddetector/main.go, config/tests/samples/create/harness.go, config/tests/samples/create/samples_test.go, operator/pkg/controllers/configconnectorcontext/configconnectorcontext_controller.go, pkg/controller/config.go, pkg/controller/dcl/controller.go, pkg/controller/direct/apikeys/apikeyskey_controller.go, pkg/controller/direct/directbase/directbase_controller.go, pkg/controller/direct/resourcemanager/tagkey_controller.go, pkg/controller/gsakeysecretgenerator/gsakey_secret_generator.go, pkg/controller/gsakeysecretgenerator/service_account_key_integration_test.go, pkg/controller/iam/auditconfig/iamauditconfig_controller.go, pkg/controller/iam/partialpolicy/iampartialpolicy_controller.go, pkg/controller/iam/policy/iampolicy_controller.go, pkg/controller/iam/policymember/iampolicymember_controller.go, pkg/controller/jitter/jitter.go, pkg/controller/jitter/jitter_test.go, pkg/controller/kccmanager/kccmanager.go, pkg/controller/registration/registration_controller.go, pkg/controller/tf/controller.go, pkg/test/controller/reconciler/testreconciler.go, pkg/test/jitter/jitter.go
If we add a jitter generator as a dep to the controllers than we can dictate what generator to use for tests. In the final state, tests (pause step, e2e, etc) can use generators that don't timeout our tests.
=> refactor: add a jitter generator

.github/workflows/presubmit.yaml, scripts/github-actions/tests-e2e-fixtures, scripts/github-actions/tests-e2e-samples
We were coming close to the 60 minute timeout; split into two to give
us some room.
=> tests: Split github actions jobs for tests/e2e

experiments/compositions/composition/api/v1alpha1/composition_types.go, experiments/compositions/composition/config/crd/bases/composition.google.com_compositions.yaml, experiments/compositions/composition/internal/controller/expander_applier.go, experiments/compositions/composition/internal/controller/expander_reconciler.go, experiments/compositions/composition/release/kind/crds.yaml, experiments/compositions/composition/release/kind/operator.yaml, experiments/compositions/composition/tests/data/TestSimpleNamespaceExplicit/input.yaml, experiments/compositions/composition/tests/data/TestSimpleNamespaceExplicit/output.yaml, experiments/compositions/composition/tests/data/TestSimpleNamespaceInherit/input.yaml, experiments/compositions/composition/tests/data/TestSimpleNamespaceInherit/output.yaml, experiments/compositions/composition/tests/testcases/simple_test.go
- Provide an option to inherit (default) Facade namespace for all objects.
- For those templates (admin ones) that require cluster level or cross
namespace objects, the template must use `namespaceMode: explicit` and set
the namespaces explicitly for the required objects.
- Add tests
- TestSimpleNamespaceInherit
- TestSimpleNamespaceExplicit
```
=== RUN   TestSimpleNamespaceInherit
cluster.go:117: Reserved cluster composition-e2e-0
scenario.go:211: Applying input
scenario.go:162: Creating object "CustomResourceDefinition/pconfigs.facade.foocorp.com" on cluster "composition-e2e-0"
scenario.go:175: Creating object "Namespace/team-a" on cluster "composition-e2e-0"
scenario.go:188: Creating object "ClusterRole/composition-facade-foocorp" on cluster "composition-e2e-0"
scenario.go:188: …
```
=> Provide an option to inherit Facade namespace for all objects

pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/explicitlogmetric/_generated_object_explicitlogmetric.golden.yaml, pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/exponentiallogmetric/_generated_object_exponentiallogmetric.golden.yaml, pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/linearlogmetric/_generated_object_linearlogmetric.golden.yaml
Sample commands used for generation:
```bash
$ WRITE_GOLDEN_OUTPUT=1 GOLDEN_OBJECT_CHECKS=1 BILLING_ACCOUNT_ID="REDACTED" ORGANIZATION_ID="REDACTED" E2E_KUBE_TARGET=envtest RUN_E2E=1 E2E_GCP_TARGET=real go test -test.count=1 -timeout 600s -v ./tests/e2e -run TestAllInSeries/fixtures/linearlogmetric
```
=> chore: generate logginglogmetric krm exports

hack/compare-mock, hack/record-gcp
When we're using these scripts locally, we should capture/compare as
much golden output as we can, to maximize signal.
=> chore: update hack scripts to generate golden objects

pkg/test/utils.go
While trying to diff 2 KRM exports, I figured it could be easier to use `cmp.Diff` to get all the diff at once!
before
```
...
utils.go:170: unexpected diff in <MY_PATH>/k8s-config-connector/pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/linearlogmetric/_generated_object_linearlogmetric.golden.yaml: field metricDescriptor in the golden file is missing
...
```
after
```
utils.go:170: unexpected diff in<MY_PATH>/k8s-config-connector/pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/linearlogmetric/_generated_object_linearlogmetric.golden.yaml:   map[string]any{
... // 2 identical entries
"metadata": map[string]any{"annotations": map[string]any{"cnrm.cloud.google.com/management-conflict-prevention-policy": string("none")}, "finalizers": …
```
=> tests: use cmp.Diff for golden object check

tests/e2e/normalize.go, tests/e2e/unified_test.go
Probably shouldn't happen, but we shouldn't panic if it does.
=> tests: handle a nil object when normalizing responses

pkg/test/http_recorder.go
There's no good reason for us to panic if we cannot read the request body because the context has been canceled. I think that is an OK situation to be in.
Relaxing this check should eliminate the class of racing that has been making the pause tests flaky!
before
```
{"severity":"error","timestamp":"2024-04-18T18:36:52.713Z","msg":"Reconciler error","controller":"edgecontainercluster-controller","controllerGroup":"edgecontainer.cnrm.cloud.google.com","controllerKind":"EdgeContainerCluster","EdgeContainerCluster":{"name":"edgecontainercluster-stor3b7gzoni2vdypela","namespace":"stor3b7gzoni2vdypela"},"namespace":"stor3b7gzoni2vdypela","name":"edgecontainercluster-stor3b7gzoni2vdypela","reconcileID":"1e21bbd9-c92f-442c-b171-98c230ad9a18","error":"Get …
```
=> tests: relax panic on record

scripts/generate-google3-docs/resource-reference/generated/resource-docs/vertexai/vertexaidataset.md, scripts/generate-google3-docs/resource-reference/templates/vertexai_vertexaidataset.tmpl
@maqiuyujoyce Thank you for pointing out this inconsistency in https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1459#discussion_r1576807155. We have the same inconsistency for `VertexAIDataset`.
=> doc: fix resource name for vertex AI dataset

config/tests/samples/create/samples.go, tests/e2e/unified_test.go
This does mean that we have to have the objects pre-ordered correctly,
but it means that these requests will be made in a consistent order,
making our golden testing easier.
=> tests: run create/delete in order when we're doing golden testing

tests/e2e/unified_test.go
One minute may just be too close for comfort
=> tests: Try a longer per-test timeout in unified_test

tests/apichecks/crds_test.go
We decided that fooUrlRef should probably be fooRef instead, except in
the (pre-existing) case of urlRef.
Add a simple test to warn us if we deviate from the guideline.
=> tests: Add a simple test to verify that we don't have fooUrlRef

config/tests/samples/create/samples_test.go
We now enforce that secondary instance can only be created once primary instance is created. So can remove the sample test from the list.
However, we do see create instance failures as the service networking connection is not ready and it leads to alerts. This is an expected behavior from KCC  as there is no explicit dependency between instance and service networking connection.
Trying to fix this issue either from the AlloyDB API backend by not accounting this as an error or by fixing the alerts to add this alert as an exemption for KCC resources. Will enable them back as soon as it gets fixed.
=> Temporarily skip alloydb instance sample tests

pkg/cli/outputsink/filename/filename.go
This was reported by a customer; though it's not yet fully root-caused
we can avoid the panic and report some diagnostic information.
=> fix: Fix panic during export

pkg/controller/iam/partialpolicy/iampartialpolicy_controller.go, pkg/controller/ratelimiter/ratelimiter.go
We already rate-limit requeues on IAMPolicy, extend this to cover
IAMPartialPolicy also.
Also add a big description as to why we're doing this as a
code-comment.
=> enh: Rate-limit requeues on IAMPartialPolicy

scripts/add-validation-to-crds/parse-crds.go
It's not possible to do this with controller-runtime /
controller-tools annotations, so instead we post-process the CRD.
Adding the tool as-is, with a plan to polish and integrate into the
CRD generation pipeline when needed.
=> chore: tool to add advanced OpenAPI validation for our ResourceRefs

experiments/compositions/samples/AppTeam/README.md, experiments/compositions/samples/CloudSQL/README.md
Fix sample docs for CloudSql and AppTeam.
Use correct namespace for `context` objects.
Use correct group for `CloudSQL` facade.
=> Fix sample docs for CloudSql and AppTeam

tests/e2e/httplog.go, tests/e2e/script_test.go, tests/e2e/testdata/scenarios/README.md, tests/e2e/testdata/scenarios/direct/mutable_but_unreadable/SCENARIO_README.md, tests/e2e/testdata/scenarios/direct/mutable_but_unreadable/_http00.log, tests/e2e/testdata/scenarios/direct/mutable_but_unreadable/script.yaml
Captured with:
```bash
$ WRITE_GOLDEN_OUTPUT=1 GOLDEN_REQUEST_CHECKS=1 \ 
E2E_KUBE_TARGET=envtest E2E_GCP_TARGET=mock RUN_E2E=1 \
go test -test.count=1 -timeout 360s -v ./tests/e2e -run TestE2EScript/scenarios/direct/mutable_but_unreadable 2>&1
```
Follow on PR will add support for mutable but unreadable for llm direct.
=> tests: mutable but unreadable scenario for llm

config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_computenetworks.compute.cnrm.cloud.google.com.yaml, pkg/clients/generated/apis/compute/v1beta1/computenetwork_types.go, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computenetwork/create.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computenetwork/update.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/compute/computenetwork.md, third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/services/compute/resource_compute_network.go
Change ForceNew to false for the field enable_ula_internal_ipv6. The Compute API allows this field to be enabled/disabled on-the-fly.
Fixes b/332834635
=> compute_network.patch

pkg/controller/iam/auditconfig/iamauditconfig_controller.go, pkg/controller/iam/partialpolicy/iampartialpolicy_controller.go, pkg/controller/iam/policy/iampolicy_controller.go, pkg/controller/iam/policymember/iampolicymember_controller.go
Fixes b/338572343.
Issue:
`merge` is considered invalid value for the `state-into-spec` annotation in the handwritten IAM resources.
Root cause:
TypeMeta is missing in the retrieved object in the handwritten IAM controllers. Without type metadata, the kind is `""`, and kind `""` indeed doesn't support `merge`.
=> Fix the error when 'state-into-spec: merge' is configured for handwritten IAM resources

dev/cd/build, dev/tasks/build-cli-bundle, dev/tasks/build-release-bundle, scripts/add-license-header-to-yaml.sh, scripts/config-connector/build.sh
These are (partially) simplified forms of our internal build scripts,
trying to bring them to OSS.
Note that we will treat building separately from pushing to a
registry/GCS.
=> chore: create build scripts

config/tests/samples/create/samples_test.go
Adding back the skipped AlloyDBInstance sample tests as it was suspected to raise alerts. However, it is safe to enable them now as these tests did not contribute to the alerts
=> Reenable skipped AlloyDBInstance tests

config/tests/samples/create/harness.go, mockgcp/mocklogging/logbucket.go, mockgcp/mocklogging/service.go, pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogbucket/projectlogbucket/_generated_object_projectlogbucket.golden.yaml, pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogbucket/projectlogbucket/_http.log
- tests: captured test output for projectlogbucket
- mockgcp: add support for LoggingLogBucket
- mockgcp: Allow services to rewrite errors for accurate golden testing
=> mockgcp: support for LoggingLogBucket

config/samples/resources/vertexaiindex/iam_v1beta1_iampolicymember.yaml, config/samples/resources/vertexaiindex/serviceusage_v1beta1_serviceidentity.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/vertexai/vertexaiindex.md
Error message from prow testing:
```
=== NAME  TestCreateNoChangeUpdateDelete/vertexai/basic-vertexaiindex
testreconciler.go:105: reconcile for IAMPolicyMember:afkqn26w3f7wy3ikjibq/iampolicymember-afkqn26w3f7wy3ikjibq took 1.445401796s, result was ({false 0s}, Update call failed: error setting policy member: error applying changes: summary: Error applying IAM policy for storage bucket "b/kcc-vertex-ai-index-test": Error setting IAM policy for storage bucket "b/kcc-vertex-ai-index-test": googleapi: Error 400: Service account service-65713775505@gcp-sa-aiplatform.iam.gserviceaccount.com does not exist., invalid)
reconcile.go:193: error was not considered transient; chain is [[*fmt.wrapError: Update call failed: error setting policy member: error applying changes: summary: Error applying IAM …
```
=> use service identity to generate P4SA for vertex AI Index

Makefile, apis/resources/logging/v1beta1/doc.go, apis/resources/logging/v1beta1/logmetric_types.go, apis/resources/logging/v1beta1/zz_generated.deepcopy.go, build/tooling/Dockerfile, config/crds/direct/apiextensions.k8s.io_v1_customresourcedefinition_logginglogmetrics.logging.cnrm.cloud.google.com.yaml, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_logginglogmetrics.logging.cnrm.cloud.google.com.yaml, pkg/clients/generated/apis/logging/v1beta1/logginglogmetric_types.go, pkg/clients/generated/apis/logging/v1beta1/zz_generated.deepcopy.go, pkg/controller/registration/registration_controller.go, scripts/generate-google3-docs/resource-reference/generated/resource-docs/logging/logginglogmetric.md, scripts/github-actions/tests-e2e-direct.sh
Patch introduces a way to generate CRDs from the go structs in `apis`. This is not perfect just yet.
Also adds the bucketName field for our KRM's `LoggingLogMetric` resource
=> chore: add direct CRD for LoggingLogMetric, chore: patch existing LoggingLogMetric CRD, feat: switch LLM to direct controller

mockgcp/mockserviceusage/serviceusagev1beta1.go
Add support for more services in mocking `GenerateServiceIdentity`.
=> mockgcp: support more services in GenerateServiceIdentity

pkg/controller/direct/logging/logmetric_controller.go
Patch adds resolution of existing LoggingLogMetric resources and a rename for parentID->projectID.
=> feat: resolve resourceID for existing LLM resources

pkg/controller/direct/directbase/directbase_controller.go
We already honor the `reconcile-period` annotation when generating a jittered value for re-enqueuing but we are not honoring it when it's 0.
=> feat: honor reconcile period anon in direct controller

pkg/controller/direct/logging/utils.go
This should avoid problems in particular with the conditions timestamps.
=> chore: don't overwrite status conditions/observedGeneration in direct controller

mockgcp/mocklogging/logmetric.go, pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/logbucketmetric/_generated_object_logbucketmetric.golden.yaml, pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/logbucketmetric/_http.log, tests/e2e/unified_test.go
- chore: capture golden output for logbucketmetric test
- mockgcp: Improved fidelity for LoggingLogMetric
- tests: Fix repeated-GET removal
=> Golden output for LoggingLogMetric & test/mock fixes

experiments/compositions/expanders/jinja-expander/Dockerfile
Enable the --require-hashes flag for pip usage.
Ensure we use the --require-hashes flag when calling pip.
=> Make sure we secure pip install/upgrade.

experiments/compositions/composition/api/v1alpha1/composition_types.go, experiments/compositions/composition/config/crd/bases/composition.google.com_compositions.yaml, experiments/compositions/composition/go.mod, experiments/compositions/composition/go.sum, experiments/compositions/composition/release/cc/operator.yaml, experiments/compositions/composition/release/crds.yaml, experiments/compositions/composition/release/kind/operator.yaml
Remove the expander type enum to support third party expanders.
`make e2e-test`
=> perf:remove expander type enum

Makefile
This doesn't seem to add anything, and it causes a lot of friction.
=> chore: Don't require headers on generated testdata

pkg/controller/direct/logging/logmetric_controller.go, pkg/controller/direct/logging/utils.go, pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/linearlogmetric/_generated_object_linearlogmetric.golden.yaml, pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/linearlogmetric/_http.log, pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/linearlogmetric/create.yaml, pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/linearlogmetric/update.yaml
By passing the spec to KRMToAPI, we can defend against this.
=> LoggingLogMetric: honor resourceID on creation

.github/workflows/presubmit.yaml
Avoids repeating the go version unnecessarily.
=> chore: use go-version-file in vcr presubmit

config/samples/resources/vertexaidataset/vertexai-dataset-encryptionkey/iam_v1beta1_iampolicymember.yaml, config/samples/resources/vertexaidataset/vertexai-dataset-encryptionkey/serviceusage_v1beta1_serviceidentity.yaml, config/samples/resources/vertexaiendpoint/vertexai-endpoint-encryptionkey/serviceusage_v1beta1_serviceidentity.yaml, pkg/test/resourcefixture/testdata/basic/vertexai/v1beta1/vertexaidataset/vertexaidatasetencryptionkey/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/vertexai/v1beta1/vertexaiendpoint/vertexaiendpointencryptionkey/dependencies.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/vertexai/vertexaidataset.md, scripts/generate-google3-docs/resource-reference/generated/resource-docs/vertexai/vertexaiendpoint.md
Avoid hard-coding P4SA service account in Vertex AI samples and tests.
TESTED
```
$ go test -v -tags=integration ./config/tests/samples/create/ -run-tests vertexai-dataset-encryptionkey
$ go test -v -tags=integration ./config/tests/samples/create/ -run-tests vertexai-endpoint-encryptionkey
$ go test -v -tags=integration ./pkg/controller/dynamic/ -test.run TestCreateNoChangeUpdateDelete -run-tests vertexaidatasetencryptionkey
$ go test -v -tags=integration ./pkg/controller/dynamic/ -test.run TestCreateNoChangeUpdateDelete -run-tests vertexaiendpointencryptionkey
```
=> Use service identity to generate P4SA in samples and tests for Vertex AI resources

pkg/controller/direct/logging/logbucketref.go, pkg/controller/direct/logging/logmetric_controller.go, pkg/controller/direct/logging/projectref.go, pkg/controller/direct/logging/utils.go
Removing a few redundant checks, but also rely on ValueOf when
converting *T to an API value.
=> chore: A few style nits in LoggingLogMetric

third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/services/sql/resource_sql_database_instance.go, third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/services/sql/resource_sql_database_instance_test.go
Pick up the fix in https://github.com/GoogleCloudPlatform/magic-modules/pull/9198
Fixes #1802
TESTED
1. Create a SQL instance with KCC 1.117.0
```
$ kubectl apply -f create.yaml
$ cat create.yaml 
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
name: sqlinstance-sample-333079656-2
spec:
region: us-central1
databaseVersion: MYSQL_5_7
instanceType: CLOUD_SQL_INSTANCE
settings:
tier: db-n1-standard-1
```
2. Update the KCC code to include the patch in this PR. This mimics the case where the users upgrade the KCC to the version with this fix.
3. Setting the "settings.edition" field in the created SQL instance
```
$ kubectl apply -f update.yaml
sqlinstance.sql.cnrm.cloud.google.com/sqlinstance-sample-333079656-2 configured …
```
=> terraform: fix perm diff on edition field in SQL instance

pkg/controller/direct/logging/logmetric_controller.go, pkg/controller/direct/logging/utils.go, pkg/webhook/immutable_fields_validator.go, pkg/webhook/immutable_fields_validator_test.go, tests/e2e/script_test.go, tests/e2e/testdata/scenarios/README.md, tests/e2e/testdata/scenarios/direct/llm_immutable_field/labels_value_type/SCENARIO_README.MD, tests/e2e/testdata/scenarios/direct/llm_immutable_field/labels_value_type/_http00.log, tests/e2e/testdata/scenarios/direct/llm_immutable_field/labels_value_type/_http01.log, tests/e2e/testdata/scenarios/direct/llm_immutable_field/labels_value_type/_object00.yaml, tests/e2e/testdata/scenarios/direct/llm_immutable_field/labels_value_type/_object01.yaml, tests/e2e/testdata/scenarios/direct/llm_immutable_field/labels_value_type/script.yaml, tests/e2e/testdata/scenarios/direct/llm_immutable_field/metric_kind_and_value_type/SCENARIO_README.MD, tests/e2e/testdata/scenarios/direct/llm_immutable_field/metric_kind_and_value_type/_http00.log, tests/e2e/testdata/scenarios/direct/llm_immutable_field/metric_kind_and_value_type/_http01.log, tests/e2e/testdata/scenarios/direct/llm_immutable_field/metric_kind_and_value_type/_object00.yaml, tests/e2e/testdata/scenarios/direct/llm_immutable_field/metric_kind_and_value_type/_object01.yaml, tests/e2e/testdata/scenarios/direct/llm_immutable_field/metric_kind_and_value_type/script.yaml
Fixes b/339129197
Add immutability checks in webhook and llm controller.
Golden log captured using:
GOLDEN_REQUEST_CHECKS=1 E2E_KUBE_TARGET=envtest E2E_GCP_TARGET=real RUN_E2E=1 KCC_USE_DIRECT_RECONCILERS=LoggingLogMetric   go test -test.count=1 -timeout 360s -v ./tests/e2e -run TestE2EScript/scenarios/direct/immutable_field
=> feat: Support immutability checks for llm

pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/logbucketmetric/update.yaml
Path adds update struct  for `logbucketmetric` test.
```bash
$ go test -v -tags=integration ./pkg/controller/dynamic/ -timeout 1600s -test.count=1 -test.run 'TestCreateNoChangeUpdateDelete/logging/basic-logbucketmetric'  2>&1
...
--- PASS: TestCreateNoChangeUpdateDelete (0.12s)
--- PASS: TestCreateNoChangeUpdateDelete/logging (0.00s)
--- PASS: TestCreateNoChangeUpdateDelete/logging/basic-logbucketmetric (79.51s)
PASS
...
ok      github.com/GoogleCloudPlatform/k8s-config-connector/pkg/controller/dynamic      89.455s
```
=> tests:chore: update for logbucketmetric

experiments/compositions/composition/internal/controller/expander_reconciler.go, experiments/compositions/composition/release/manifest.yaml, experiments/compositions/composition/tests/data/TestSimpleCompositionDeleteFacade/input.yaml, experiments/compositions/composition/tests/data/TestSimpleExpanderInvalid/input.yaml, experiments/compositions/composition/tests/data/TestSimpleExpanderInvalid/output.yaml, experiments/compositions/composition/tests/data/TestSimpleExpanderVersionInvalid/input.yaml, experiments/compositions/composition/tests/data/TestSimpleExpanderVersionInvalid/output.yaml, experiments/compositions/composition/tests/data/TestSimpleFacadeByoSchema/input.yaml, experiments/compositions/composition/tests/data/TestSimpleNamespaceExplicit/input.yaml, experiments/compositions/composition/tests/data/TestSimplePlanStatusErrorExpansionFailed/composition_fixed.yaml, experiments/compositions/composition/tests/data/TestSimplePlanStatusErrorExpansionFailed/input.yaml, experiments/compositions/composition/tests/data/TestSimplePlanStatusErrorFailedApplyingManifests/composition_fixed.yaml, experiments/compositions/composition/tests/data/TestSimplePlanStatusErrorFailedApplyingManifests/input.yaml, experiments/compositions/composition/tests/data/TestSimplePlanStatusErrorFailedLoadingManifestsFromPlan/composition_fixed.yaml, experiments/compositions/composition/tests/data/TestSimplePlanStatusErrorFailedLoadingManifestsFromPlan/input.yaml, experiments/compositions/composition/tests/data/TestSimplePlanStatusWaitingForValues/input.yaml, experiments/compositions/composition/tests/testcases/simple_test.go
The expander CR has been moved to a different folder https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1775.
- Update the expander version CR name from jinja2 to composition-jinja2
- Add version validation when user selections a specific version
- Add tests for invalid expander/version usecase.
`make e2e-test`
=> perf:update expander selection and add validation after expander migration

pkg/controller/direct/logging/logmetric_controller.go
There can be a situation where the a failed update gets marked afterwards as `UpToDate` .
Big shout out to @gemmahou for catching this.
=> enh: check failed updates in conditions 

apis/resources/logging/v1beta1/logmetric_types.go, apis/resources/logging/v1beta1/zz_generated.deepcopy.go, pkg/controller/direct/logging/logmetric_controller.go, pkg/controller/direct/logging/utils.go
metav1.Time is overly strict about the input format, and we can't
parse values that were written with nanosecond precision.
=> LoggingLogMetric: use string instead of metav1.Time

docs/releasenotes/release-1.118.md
=> docs: Update 1.118.1 release notes

experiments/compositions/composition/internal/controller/expander_reconciler.go, experiments/compositions/composition/pkg/containerexecutor/jobcontainerexecutor/jobcontainerrunner.go, experiments/compositions/composition/tests/testcases/simple_test.go
Refactor using expanderversion in reconciler.
- Read the image value from expanderversion.status
- Pass image to jobfactory
- refactor jobfactory code into a separate function in the reconciler
- Add a placeholder function for grpc callout
=> Refactor ExpanderVersion, JobFactory usage in reconciler

.github/workflows/presubmit.yaml
We shouldn't need it, and if we do need it, we should set it in the
script, for reproducibility.
=> chore: stop setting GOPATH in github actions

docs/features/index.md, docs/features/pause.md, docs/releasenotes/release-1.114.md
Pause docs for the repo.
cc @ziyue-101
=> docs: pause docs on repo

experiments/compositions/facade/go.mod, experiments/compositions/facade/go.sum
The older version has a CVE (though it does not appear to be reachable)
=> chore: update protobuf in experiments/compositions/facade

experiments/compositions/composition/api/v1alpha1/composition_types.go, experiments/compositions/composition/config/crd/bases/composition.google.com_compositions.yaml
Add ExpanderConfig to Expander
- Allows structured config for inbuilt expanders
- The ability to support refs for external configs
- remove proto annotations (cleanup)
=> Add structured config support for Expander

pkg/controller/dynamic/dynamic_controller_integration_test.go, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/mysqlinstance/update.yaml
Make a no-change update after the update test. Ensure there is no unexpected update call.
This test could help catch bugs like #1802.
Without the fix in #1803, the test fails with
```
go test -timeout 1200s -v -tags=integration ./pkg/controller/dynamic/ -test.run TestCreateNoChangeUpdateDelete -run-tests mysqlinstance
...
k8s.go:84: expected event with reason 'Updating' to not be recorded for SQLInstance epqxuxkxxi5dnnbghdaq/sqlinstance-sample-epqxuxkxxi5dnnbghdaq, but it was
...
--- FAIL: TestCreateNoChangeUpdateDelete (0.16s)
--- FAIL: TestCreateNoChangeUpdateDelete/sql (0.00s)
--- FAIL: TestCreateNoChangeUpdateDelete/sql/basic-mysqlinstance (337.22s)
...
```
With the fix in #1803, the test passes
```
go test -timeout 1200s -v -tags=integration ./pkg/controller/dynamic/ -test.run …
```
=> test: test NoChange after Update in dynamic test

dev/tasks/build-images
This avoids depending on the current gcloud project (which is likely
not set in github actions, at least).
=> chore: update presubmit build-images script to override image names

pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/logbucketmetric/_generated_export_logbucketmetric.golden, pkg/test/resourcefixture/testdata/basic/logging/v1beta1/logginglogmetric/logbucketmetric/_http.log, scripts/github-actions/tests-e2e-direct.sh
Run the logbucketmetric in the direct tests. ~Note, I am not convinced we need it since the postsubmits hit the direct controller now but~ it's probably good practice to add it for now until we can better target all of the tests under a GVK.
=> tests: add logbucketmetric to direct tests

tests/e2e/unified_test.go
Working towards being able to run samples & fixtures the same way.
=> chore: refactor unified_test to split out scenario execution

pkg/controller/direct/logging/diffs.go, pkg/controller/direct/logging/logmetric_controller.go
This should make it easier to understand why re-reconciliation is happening.
=> feat: LoggingLogMetric now logs changed fields

experiments/compositions/composition/Makefile, experiments/compositions/composition/cmd/main.go, experiments/compositions/composition/config/release/kustomization.yaml, experiments/compositions/composition/internal/controller/composition_controller.go, experiments/compositions/composition/internal/controller/expander_reconciler.go, experiments/compositions/composition/release/manifest.yaml, experiments/compositions/composition/tests/utils/utils.go
Remove image-registry parameter from the composition controller
- Was added initially when we hardcoded the image in the job template
- ExpanderVersion removes the need for this parameter
=> [cleanup] Remove image-registry parameter from the composition controller

mockgcp/mockalloydb/instance.go
Support mock pscInstanceConfig field for alloydb instance in PR 1903
=> Add pscInstanceConfig fields for AlloyDB instance Update

scripts/environment-setup/golang-setup.sh
Populate the ~/.profile with the $PATH variable name, not its contents.
=> fix: Prevent expansion of $PATH shell variable in setup script

mockgcp/README.md
I realized that the proto file for `CloudIDSEndpoint` was not quite right as it was missing Update funcs and fields that were autogenerated in our spec file, like `ThreatExceptions`.
Let's document how to generate the protos in this case from the open api.
=> docs: add instr to gen proto

experiments/compositions/composition/api/v1alpha1/expanderversion_types.go, experiments/compositions/composition/api/v1alpha1/plan_types.go, experiments/compositions/composition/config/crd/bases/composition.google.com_expanderversions.yaml, experiments/compositions/composition/config/crd/bases/composition.google.com_plans.yaml, experiments/compositions/composition/config/expanders/expander_versions.yaml, experiments/compositions/composition/config/expanders/jinja2-v0.0.1.yaml, experiments/compositions/composition/expanders.mk, experiments/compositions/composition/internal/controller/expander_reconciler.go, experiments/compositions/composition/internal/controller/expanderversion_controller.go, experiments/compositions/composition/release/manifest.yaml, experiments/compositions/composition/tests/data/TestSimpleCompositionExpansionGrpc/input.yaml, experiments/compositions/composition/tests/data/TestSimpleCompositionExpansionJob/input.yaml, experiments/compositions/composition/tests/scenario/scenario.go, experiments/compositions/composition/tests/testcases/simple_test.go
Switch jinja2 to grpc based expansion:
- rename gjinjg2 -> jinja2 (making jinja2 grpc based)
- rename existing pod based jinja2 -> pjinja2
- Add `image` field to ExpanderVersion
- allow specifying an image that doesnt follow the
removePrefix(expanderversion.name , "composition-") pattern.
- provides more flexibility
- In our case the type is pjinja and the image is expander-jinja
- Add a custom ratelimiter for the facade reconciler
- Due to a bug, the reconciler is not restarted across tests.
- Old failures add to rate limiting causing random failures
- make ratelimiter max backoff 120s
- Add a small sleep b/w tests
- Move all ExistTimeout to CompositionReconcileTimeout
- Check if a plan was updated and if so check if the applier sees the
latest plan object. If not retry again.
- Add …
=> Switch jinja2 to grpc based expansion

pkg/controller/direct/alloydb/cluster_controller.go
#1676 went in without syncing for the latest interface changes in the `direct` package
=> fix: interface changes

.github/workflows/dcl-upgrade-probe.yaml, scripts/github-actions/ga-upgrade-dcl-probe.sh
Patch
* reorders GH actions steps
* wraps the probe func to prep env
=> ci:chore: update upgrade-dcl probe

experiments/compositions/composition/Makefile, experiments/compositions/composition/internal/controller/expander_reconciler.go, experiments/compositions/composition/tests/cluster/kind/cluster.go, experiments/compositions/composition/tests/data/TestSimpleCompositionStatusFacadeCRDMissing/input.yaml, experiments/compositions/composition/tests/data/TestSimpleCompositionStatusValidation/fixed_composition.yaml, experiments/compositions/composition/tests/data/TestSimpleExpanderJinjaWithQuotes/input.yaml, experiments/compositions/composition/tests/data/TestSimpleExpanderJinjaWithQuotes/output.yaml, experiments/compositions/composition/tests/scenario/scenario.go, experiments/compositions/composition/tests/testcases/kcc_samples_test.go, experiments/compositions/composition/tests/testcases/simple_test.go, experiments/compositions/samples/AppTeam/composition/appteam.yaml, experiments/compositions/samples/CloudSQL/README.md, experiments/compositions/samples/CloudSQL/composition/hasql.yaml
Fixes to make the latest GCP samples work.
- KCC Sample Test changes
- In CloudSQL test, Create an AppTeam and in the new project create CloudSQL (testing user , demo flow)
- Samples changes
- Remove alpha from expander names (grpc ones)
- In hasql composition,
- Use new grpc getter, GetterConfiguration
- Test infra changes
- Add support for dependent samples for KCC Scenario (CloudSQL on AppTeam)
- Makefile changes
- add run-test target to run a single testcase
- make CloudSQL the default kcc-test
- Reconciler changes
- dont json.Marshall() the expander template
- conversely no need to unquote the result
- json.Marshall() was escaping double quotes, and converting '>' to
uni-code
- e2e Test changes
- Add new test case to verify roundtripping template is not broken
- …
=> Fixes to make the latest GCP samples work with GRPC based expanders

Makefile
We want to keep these separated (experiments has its own build/CI scripts)
=> chore: don't apply formatting from root into experiments

pkg/k8s/stateintospecdefaulter_test.go
Fixes b/339701967
TestStateIntoSpecDefaulter_ApplyDefaults is extremely flaky in the integration test suite due to the following error:
```
{"severity":"error","timestamp":"2024-05-12T10:04:24.605Z","logger":"controller-runtime.test-env","msg":"unable to start the controlplane","tries":0,"error":"timeout waiting for process etcd to start successfully (it may have failed to start, or stopped unexpectedly before becoming ready)"}
```
It kept retrying for 5 times and then timed out.
I suspected that the issue is caused by parallelism because it will try to start 8 test manager in parallel. I updated the test workflow to make test cases run in series and verified the issue disappeared for 3 consecutive integration test runs.
- …
=> Make TestStateIntoSpecDefaulter_ApplyDefaults test cases run in series

pkg/test/utils.go, scripts/github-actions/tests-e2e-direct.sh, tests/e2e/testdata/scenarios/fields/llm_custom_diff/value_type/label/_http00.log, tests/e2e/testdata/scenarios/fields/llm_custom_diff/value_type/label/_http01.log, tests/e2e/testdata/scenarios/fields/llm_immutable_field/labels_value_type/_http00.log, tests/e2e/testdata/scenarios/fields/llm_immutable_field/labels_value_type/_http01.log, tests/e2e/testdata/scenarios/fields/llm_immutable_field/metric_kind_and_value_type/_http00.log, tests/e2e/testdata/scenarios/fields/llm_immutable_field/metric_kind_and_value_type/_http01.log, tests/e2e/testdata/scenarios/fields/llm_lazy_reconcile/_http00.log, tests/e2e/testdata/scenarios/fields/llm_lazy_reconcile/_http01.log, tests/e2e/testdata/scenarios/fields/llm_set_unset/basic/_http00.log, tests/e2e/testdata/scenarios/fields/llm_set_unset/basic/_http01.log, tests/e2e/testdata/scenarios/fields/llm_set_unset/basic/_http02.log, tests/e2e/testdata/scenarios/fields/llm_set_unset/metric_descriptor/_http00.log, tests/e2e/testdata/scenarios/fields/llm_set_unset/metric_descriptor/_http01.log, tests/e2e/testdata/scenarios/fields/llm_set_unset/metric_descriptor/_http02.log, tests/e2e/testdata/scenarios/fields/mutable_but_unreadable/_http00.log, tests/e2e/testdata/scenarios/fields/mutable_but_unreadable/_http01.log
We should update the golden data, rather than ignoring it.
=> tests: Don't ignore annotations with direct reconciler

pkg/test/main/testmain.go
One liner to quit if we are attempting to use a mock gcp with the dynamic controller integration tests.
Why? Should the dynamic integration tests work with mock gcp? 
That is a good question but we already have a place where the fixtures are called in TestAll under e2e. We can continue that discussion. I just want this papercut to be a bit more evident when I forget I can't use the dynamic controller with a mock gcp backend 😛 .
In practice:
```bash
$ E2E_GCP_TARGET=mock go test -v -tags=integration ./pkg/controller/dynamic/ -timeout 2600s -test.count=1 -test.run 'TestCreateNoChangeUpdateDelete/ids/basic-idsendpoint'  2>&1
2024/06/04 20:15:14 dynamic integration tests do not support variable E2E_GCP_TARGET
FAIL    github.com/GoogleCloudPlatform/k8s-config-connector/pkg/controller/dynamic …
```
=> tests:refactor: fatal if e2e_gcp_target set

mockgcp/mock_http_roundtrip.go
Some small refactors on the mock_http_roundtrip; should be pretty low risk.
=> refactor: mock_http_roundtrip

pkg/controller/direct/gkehub/featuremembership_controller.go
For the resource, the controller needs to do a get before `delete` because the `delete` only cleans up a field for the Gkehub feature resource. Otherwise , `adapter.actual` is not initialized in Delete in the base controller
=> Find the hubfeaturemembership resource when doing the Delete

pkg/test/constants/presubmitconstants.go
Remove tests from the GoB presubmit skipCRUDTest list, they won't be triggered in GoB presubmit, so no longer need to include them.
Since we switch to OSS, the GoB presubmit constants may not be used anymore, but I just want to keep things updated to avoid confusions.
=> minor fix: Remove tests from skipCRUDTests list

experiments/compositions/composition/internal/controller/expander_reconciler.go, experiments/compositions/composition/pkg/applier/applier.go, experiments/compositions/composition/tests/scenario/scenario.go
Refactor Applier
- Move applier into pkg/applier, simplify parameters
- Split Evaluate and Apply
- old: expanders [evaluate + apply]
- new: expanders [evaluate] , expanders [apply]
=> Refactor Applier

config/tests/samples/create/harness.go, go.mod, mockgcp/common/operations/operations.go, mockgcp/mock_http_roundtrip.go, pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtabletable/_generated_object_bigtabletable.golden.yaml, pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtabletable/_http.log, third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/transport/bigtable_client_factory.go, third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/transport/config.go
- tfprovider: support intercepting GRPC requests
- tests: record grpc requests in our golden tests
- tests: capture golden output for bigtabletable test
=> tests: capture GRPC traffic also

pkg/cli/stream/url_to_unstructured_resource_stream.go, pkg/config/controllerconfig.go, pkg/controller/config.go, pkg/controller/direct/alloydb/client.go, pkg/controller/direct/alloydb/cluster_controller.go, pkg/controller/direct/apikeys/apikeyskey_controller.go, pkg/controller/direct/directbase/directbase_controller.go, pkg/controller/direct/gkehub/client.go, pkg/controller/direct/gkehub/featuremembership_controller.go, pkg/controller/direct/logging/client.go, pkg/controller/direct/logging/logmetric_controller.go, pkg/controller/direct/registry.go, pkg/controller/direct/resourcemanager/client.go, pkg/controller/direct/resourcemanager/tagkey_controller.go, pkg/controller/kccmanager/kccmanager.go, pkg/controller/registration/registration_controller.go, pkg/dcl/clientconfig/config.go, pkg/test/controller/reconciler/testreconciler.go, pkg/test/resourcefixture/contexts/register.go
This makes it more reusable, and means we can likely DRY the
calculation of the client.Options
=> chore: Refactor ControllerConfig into its own package

mockgcp/Makefile
One liner to have `gen-proto` depend on generating from the gapi api. 
I got bit by this when working on `mockcloudids` and forgot to run `gen-proto`.
=> chore: gen-proto requires gen-api

pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardrefs/_generated_object_monitoringdashboardrefs.golden.yaml, pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardrefs/_http.log, pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardrefs/update.yaml, scripts/github-actions/tests-e2e-direct.sh
Changing to a random display name is not very intuitive (and doesn't
get us much).
Also add this to tests-e2e-direct, so we verify the golden output
=> tests: simplify monitoringdashboard test case, add to tests-e2e-direct

dev/tasks/install-tools
The -x option was not working when go _was_ installed - I don't think
it does a PATH lookup.
=> chore: fix detection of go on path

pkg/test/resourcefixture/test_runner.go
We don't run TestAcquire on ALL dynamic tests, it's expected that there were no tests to run. That should not be an error and make the TestAcquire test to fail.
=> test: Use log instead of error when no TestAcquire tests 

scripts/shared-vars-public.sh
For our post submits to run the `cloudidsendpoint`, we need to enable the `ids.googleapis.com` service.
=> chore: enable ids service

dev/tasks/install-tools
We may be running in a container / build environment that does not
have jq.  Try to install it using apt.
=> chore: postsubmits should also install jq if missing

cmd/manager/main.go, pkg/controller/kccmanager/kccmanager.go, pkg/controller/ratelimiter/ratelimiter.go
We want to allow users to configure the client side rate limit via flags.
follow up PR https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1988
=> feat: Make the client-side rate limit configurable via flags (Part 1)

tests/e2e/unified_test.go
When TEST_ORG_ID is unset, don't perform the replace
=> test: Minor fix on VCR test_org_id replacement

experiments/compositions/composition/config/expanders/expander_versions.yaml, experiments/compositions/composition/tests/data/TestSimpleExpansionJob/input.yaml
Update the expander to use the most recent versions
- reference: https://pantheon.corp.google.com/gcr/images/krmapihosting-release/global/expander-jinja2?inv=1&invt=AbTxWw
Updating the version first to update the composition manifest in CC.
=> Update expander versions.

dev/tasks/install-tools
Verified by running in docker that this now works when run with the
gcr.io/cloud-builders/docker image.
=> chore: install zip in CLI build

pkg/cli/cmd/bulkexport/singleresourceiamclient/singleresourceiamclient.go, pkg/controller/direct/alloydb/cluster_controller.go, pkg/controller/direct/apikeys/apikeyskey_controller.go, pkg/controller/direct/directbase/directbase_controller.go, pkg/controller/direct/export.go, pkg/controller/direct/gkehub/featuremembership_controller.go, pkg/controller/direct/logging/logmetric_controller.go, pkg/controller/direct/registry/registry.go, pkg/controller/direct/resourcemanager/tagkey_controller.go, pkg/controller/kccmanager/kccmanager.go, pkg/controller/registration/registration_controller.go, pkg/test/controller/reconciler/testreconciler.go, pkg/test/resourcefixture/contexts/register.go
We need to move things around to avoid import cycles as we add IAM
support.
=> chore: Refactor registry to be more reusable

pkg/webhook/register.go, pkg/webhook/state_into_spec_annotation_validator.go
Added a validating webhook that checks whether the `state-into-spec` annotation is explicitly set to `merge` and returns a warning if so.
Further improvement would be validating whether the `state-into-spec` annotation will be defaulted to `merge` for a resource, and/or validating whether `stateIntoSpec` field is set to `Merge` for CC or CCC.
Ran `make docker-build docker-push deploy` to install a locally built version, and verified that the warning is returned when `cnrm.cloud.google.com/state-into-spec: merge` is set:
```
$ kubectl apply -f pubsubtopic-merge.yaml 
Warning: 'cnrm.cloud.google.com/state-into-spec: merge' is unsupported for CRDs added in 1.114.0 and later. Use 'absent' instead. More details can be found at …
```
=> Add validator to return a warning when `state-into-spec` is set to `merge`

experiments/compositions/composition/api/v1alpha1/plan_types.go, experiments/compositions/composition/config/crd/bases/composition.google.com_plans.yaml, experiments/compositions/composition/pkg/applier/applier.go
Replace boolean for ResourceStatus.isHealthy with string enum per request on PR #2017. The currently supported values are "Healthy" and "Unhealthy".
Deployed to a KIND cluster and applied a test composition (`experiments/compositions/composition/tests/data/TestSimpleDeleteFacade/input.yaml`). Described the composition to see the status:
```
Status:
Composition Generation:  1
Composition UID:         f8fa482a-4e35-48b1-b28d-934a5bb7f489
Conditions:
Last Transition Time:  2024-06-17T17:51:42Z
Message:               Evaluated and Applied stages: project
Reason:                ProcessedAllStages
Status:                True
Type:                  Ready
Generation:              2
Input Generation:        1
Stages:
Project:
Applied Count:  1
Last Applied:
Health:        Healthy
Kind: …
```
=> Compositions: Replace boolean for ResourceStatus.isHealthy with string enum.

scripts/generate-google3-docs/resource-reference/generated/resource-docs/alloydb/alloydbinstance.md, scripts/generate-google3-docs/resource-reference/generated/resource-docs/logging/logginglogmetric.md, scripts/generate-google3-docs/resource-reference/templates/alloydb_alloydbinstance.tmpl, scripts/generate-google3-docs/resource-reference/templates/logging_logginglogmetric.tmpl
Added warning to the reference doc as the behavior for the `state-into-spec` annotation is changed after LoggingLogMetric uses the direct controller.
Also did a small clean up for the note in AlloyDBInstance.
=> Add explanation for state-into-spec in LoggingLogMetric reference doc

pkg/controller/direct/monitoring/client.go, pkg/controller/direct/monitoring/monitoringdashboard_controller.go, pkg/controller/direct/monitoring/refs.go, pkg/controller/direct/monitoring/roundtrip_test.go, pkg/controller/direct/monitoring/utils.go, pkg/controller/direct/references/projectref.go, pkg/controller/direct/references/resourceid.go, pkg/controller/direct/register/register.go, pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardbasic/_generated_object_monitoringdashboardbasic.golden.yaml, pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardbasic/_http.log, pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardrefs/_generated_object_monitoringdashboardrefs.golden.yaml, pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardrefs/_http.log, scripts/github-actions/tests-e2e-direct.sh
- **feat: implement direct controller for MonitoringDashboard**
- **chore: update monitoringdashboard golden output**
=> feat: implement direct controller for MonitoringDashboard

apis/cloudbuild/v1alpha1/workerpool_types.go, apis/cloudbuild/v1alpha1/zz_generated.deepcopy.go, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_cloudbuildworkerpools.cloudbuild.cnrm.cloud.google.com.yaml, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_monitoringdashboards.monitoring.cnrm.cloud.google.com.yaml, go.mod, pkg/clients/generated/apis/cloudbuild/v1alpha1/cloudbuildworkerpool_types.go, pkg/clients/generated/apis/cloudbuild/v1alpha1/zz_generated.deepcopy.go, pkg/clients/generated/apis/monitoring/v1beta1/monitoringdashboard_types.go, pkg/controller/direct/cloudbuild/externalresource.go, pkg/controller/direct/cloudbuild/workerpool_controller.go, pkg/controller/direct/directbase/directbase_controller.go, pkg/controller/direct/externalresource/resource.go, pkg/controller/direct/externalresource/resource_test.go, pkg/test/resourcefixture/testdata/basic/cloudbuild/v1alpha1/cloudbuildworkerpool/_generated_object_cloudbuildworkerpool.golden.yaml, pkg/test/resourcefixture/testdata/basic/cloudbuild/v1alpha1/cloudbuildworkerpool/_http.log, scripts/generate-google3-docs/resource-reference/generated/resource-docs/monitoring/monitoringdashboard.md
Follow up PR to resolve comment in https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1920#discussion_r1630938449
=> feat: add ExternalReference (selfLink) with GCP update/deletion uniqueness guardrail

pkg/controller/direct/directbase/directbase_controller.go, pkg/controller/direct/registry/registry.go, pkg/test/controller/reconciler/testreconciler.go
The `model`s for the dynamic controller presubmits are nil bc we never `Init` the registry. This also proved to me that we probably want to error out in `AddController` if `model` is nil for a `gvk`. Finally, if the `registration` for a `gk` contains a `nil` model, we probably want to err out to signal to consumers that `Init` was not called.
=> fix: guard against nil model

mockgcp/common/fields/etag.go, mockgcp/mockcloudbuild/workerpool.go, pkg/test/resourcefixture/testdata/basic/cloudbuild/v1alpha1/cloudbuildworkerpool/_generated_object_cloudbuildworkerpool.golden.yaml, tests/e2e/normalize.go
Also simplify etag computation, as we don't rely on the value itself
any more.
=> chore: normalize status.observedState.etag in golden tests

config/tests/samples/create/harness.go, mockgcp/mockcompute/globalsslcertificatesv1.go, mockgcp/mockcompute/service.go, pkg/test/resourcefixture/testdata/basic/cloudbuild/v1alpha1/cloudbuildworkerpool/_http.log, pkg/test/resourcefixture/testdata/basic/compute/v1alpha1/computemanagedsslcertificate/managedsslcertificate/_http.log, pkg/test/resourcefixture/testdata/basic/compute/v1alpha1/computemanagedsslcertificate/managedsslcertificate/create.yaml, tests/e2e/unified_test.go
Breaking up from https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/936 for the mockgcp of `ComputeManagedSSLCertificate`. Did a few integration changes but mostly cherry picking Justin's changes 🙏🏼
=> mockgcp: ComputeManagedSSLCertificate

experiments/compositions/composition/internal/controller/expander_reconciler.go, experiments/compositions/samples/FirstComposition/README.md
This is to allow simpler compositions and especially compositions that don't use any cloud resources.
=> Make context optional for evaluation

pkg/test/resourcefixture/testdata/basic/tags/v1beta1/tagstagkey/tagkeyorgbasic/_generated_object_tagkeyorgbasic.golden.yaml, pkg/test/resourcefixture/testdata/basic/tags/v1beta1/tagstagkey/tagkeyprojectbasic/_generated_object_tagkeyprojectbasic.golden.yaml, pkg/test/resourcefixture/testdata/basic/tags/v1beta1/tagstagvalue/tagvaluebasic/_generated_object_tagvaluebasic.golden.yaml, pkg/test/resourcefixture/testdata/basic/tags/v1beta1/tagstagvalue/tagvalueproject/_generated_object_tagvalueproject.golden.yaml, tests/e2e/normalize.go
=> fix: add TODO to the mockgcp TagKey resourceID

pkg/test/resourcefixture/testdata/basic/container/v1beta1/containernodepool/_generated_object_containernodepool.golden.yaml, pkg/test/resourcefixture/testdata/directives/removedefaultnodepool/_generated_object_removedefaultnodepool.golden.yaml, tests/e2e/normalize.go
=> fix: sort mockgcp string slice fields

pkg/test/resourcefixture/testdata/basic/resourcemanager/v1beta1/project/projectinfolder/_generated_object_projectinfolder.golden.yaml, pkg/test/resourcefixture/testdata/basic/resourcemanager/v1beta1/project/projectinorg/_generated_object_projectinorg.golden.yaml, pkg/test/resourcefixture/testdata/basic/resourcemanager/v1beta1/project/projectmovedfoldertofolder/_generated_object_projectmovedfoldertofolder.golden.yaml, tests/e2e/normalize.go
=> fix: replace mockresourcemanager generated Project number

pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringnotificationchannel/_generated_object_monitoringnotificationchannel.golden.yaml, pkg/test/resourcefixture/testdata/basic/vertexai/v1alpha1/vertexaitensorboard/_generated_object_vertexaitensorboard.golden.yaml, tests/e2e/normalize.go
=> fix: replace mockgcp dynamic resourceID to id marker

dev/tools/proto-to-mapper/main.go
It is the same as uint64, just represented differently on the wire.
=> fix: add proto-to-mapper support for fixed64

dev/tools/proto-to-mapper/main.go
These are not unexpected now we're processing (almost) all GCP APIs;
we don't expect go types for the whole API (yet).
Logging hides any important messages and also slows down the process.
=> proto-to-mapper: log missing objects at V(2)

pkg/test/resourcefixture/testdata/externalref/externalwithsubresource/_generated_object_externalwithsubresource.golden.yaml, pkg/test/resourcefixture/testdata/externalref/externalwithsubresource/_http.log
=> fix: Add more new golden http log for  external-with-subresource

pkg/test/resourcefixture/testdata/basic/compute/v1alpha1/computemanagedsslcertificate/managedsslcertificate/_generated_object_managedsslcertificate.golden.yaml, tests/e2e/normalize.go
=> fix: Add more new golden http log for managed SSL Certificate

pkg/test/resourcefixture/testdata/basic/vertexai/v1alpha1/vertexaitensorboard/_generated_object_vertexaitensorboard.golden.yaml, tests/e2e/normalize.go
=> fix: override mockgcp vertexai pathPrefix

dev/tools/controllerbuilder/go.mod
=> controllerbuilder: use go 1.22

pkg/test/resourcefixture/testdata/basic/storage/v1beta1/storagebucket/_generated_object_storagebucket.golden.yaml, pkg/test/resourcefixture/testdata/basic/storage/v1beta1/storagebucket/_http.log, pkg/test/resourcefixture/testdata/directives/forcedestroy/_generated_object_forcedestroy.golden.yaml, pkg/test/resourcefixture/testdata/reconcileintervalannotations/storagebucket/_generated_object_storagebucket#01.golden.yaml, pkg/test/resourcefixture/testdata/stateabsentinspec/clusterleveloverride/_generated_object_clusterleveloverride.golden.yaml
Note:
The golden object shows some output-only spec fields. We shall have them fixed (and have the golden logs updated correspondingly) before next launch.
cc @maqiuyujoyce @600lyy @justinsb
=> chore: add golden log for soft-deletion

pkg/test/resourcefixture/testdata/basic/cloudbuild/v1alpha1/cloudbuildworkerpool/_http.log, pkg/test/resourcefixture/testdata/basic/compute/v1alpha1/computemanagedsslcertificate/managedsslcertificate/_http.log, tests/e2e/unified_test.go
More context: many golden http log uses targetId (see https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2061/files#diff-45e74dc3e22d6fbc3f979edfe4959d40c702bf51bea40854de4e4ab393bb5330). Override the targetId may be a little bit too aggressive. 
cc @acpana
=> fix: replace targetId with id marker

tests/README.VCRTesting.md
When developers are looking at the markdown, we still want copy-paste to work nicely.
=> chore: reformat VCR command in docs for easier copy-paste

dev/tools/proto-to-mapper/Makefile
Install `protoc` cmd as prerequisite to run `make generate-pb`
=> chore: install protoc in proto-to-mapper

experiments/compositions/composition/internal/controller/composition_controller.go, experiments/compositions/composition/internal/controller/expander_reconciler.go, experiments/compositions/composition/tests/data/TestSimpleCompositionUpdate/input.yaml, experiments/compositions/composition/tests/data/TestSimpleCompositionUpdate/modified_composition.yaml, experiments/compositions/composition/tests/data/TestSimpleCompositionUpdate/output.yaml, experiments/compositions/composition/tests/testcases/simple_test.go
When the composition controller reconciles a change in a composition, the desired outcome is that affected resources be re-processed to reflect the changes.
Set up a side-channel to the expander and send events on it when compositions change. The expander will then enqueue the necessary events for all relevant resources.
Added `TestSimpleCompositionUpdate` to e2e tests and ran the scenario manually. The test exercises updating multiple CRs and ensures CRs for a different GVK aren't affected.
=> Invoke the expander when a composition changes to update resources.

config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_computetargethttpsproxies.compute.cnrm.cloud.google.com.yaml, config/servicemappings/compute.yaml, pkg/clients/generated/apis/compute/v1beta1/computetargethttpsproxy_types.go, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargethttpsproxy/globaltargethttpsproxycertificatemanagercertificates/create.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargethttpsproxy/globaltargethttpsproxycertificatemanagercertificates/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargethttpsproxy/globaltargethttpsproxycertificatemanagercertificates/update.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargethttpsproxy/globaltargethttpsproxycertificatemap/create.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargethttpsproxy/globaltargethttpsproxycertificatemap/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargethttpsproxy/globaltargethttpsproxycertificatemap/update.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/compute/computetargethttpsproxy.md
Fixes b/345274481
Fix value template for global ComputeTargetHTTPSProxy. 
Resource created successfully:
```
Events:
Type     Reason              Age              From                                Message
----     ------              ----             ----                                -------
Warning  DependencyNotFound  49s              computetargethttpsproxy-controller  reference ComputeURLMap default/computetargethttpsproxy-dep-certmgr is not found
Normal   Updating            16s              computetargethttpsproxy-controller  Update in progress
Normal   UpToDate            4s (x2 over 5s)  computetargethttpsproxy-controller  The resource is up to date
```
=> Fix value template for global ComputeTargetHTTPSProxy

pkg/controller/lifecyclehandler/handler_test.go, pkg/test/kubeharness.go
This test was using the full controller test machinery, which caused
circular dependencies when we used the lifecycle handler in
controllers.
=> refactor: Refactor lifecyclehandler test to avoid circular dependency

dev/tools/proto-to-mapper/Makefile
This avoids requiring sudo every invocation of make.
=> chore: don't try to install protoc if already available

dev/tools/controllerbuilder/template/controller.go, docs/releasenotes/release-1.120.md, go.mod, go.sum, pkg/controller/direct/alloydb/cluster_controller.go, pkg/controller/direct/apikeys/apikeyskey_controller.go, pkg/controller/direct/cloudbuild/workerpool_controller.go, pkg/controller/direct/directbase/directbase_controller.go, pkg/controller/direct/directbase/interfaces.go, pkg/controller/direct/export.go, pkg/controller/direct/gkehub/featuremembership_controller.go, pkg/controller/direct/iam.go, pkg/controller/direct/logging/logmetric_controller.go, pkg/controller/direct/monitoring/monitoringdashboard_controller.go, pkg/controller/direct/privateca/client.go, pkg/controller/direct/privateca/privatecapool_controller.go, pkg/controller/direct/privateca/utils.go, pkg/controller/direct/references/projectref.go, pkg/controller/direct/register/register.go, pkg/controller/direct/registry/references.go, pkg/controller/direct/registry/registry.go, pkg/controller/direct/resourcemanager/tagkey_controller.go, pkg/controller/iam/iamclient/iamclient.go, pkg/k8s/errors.go, pkg/test/resourcefixture/testdata/basic/privateca/v1beta1/privatecacapool/privatecacapooliam/_generated_object_privatecacapooliam.golden.yaml, pkg/test/resourcefixture/testdata/basic/privateca/v1beta1/privatecacapool/privatecacapooliam/_http.log, pkg/test/resourcefixture/testdata/basic/privateca/v1beta1/privatecacapool/privatecacapooliam/create.yaml, pkg/test/resourcefixture/testdata/basic/privateca/v1beta1/privatecacapool/privatecacapooliam/dependencies.yaml, pkg/webhook/iam_validator.go, tests/e2e/unified_test.go
We do this in our direct controller, though we only need to implement the (new) IAM-related methods.
These methods are optional (at least for now!)
=> Support setting IAM on PrivateCACAPool

pkg/apis/core/v1alpha1/servicemapping_types.go, scripts/generate-crds/main.go
Verified this in CBWP via `make ready-pr`
=> feat: use resource mapper to generate g3doc for direct resource

config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_cloudidsendpoints.cloudids.cnrm.cloud.google.com.yaml, pkg/clients/generated/apis/cloudids/v1beta1/cloudidsendpoint_types.go, pkg/clients/generated/apis/cloudids/v1beta1/zz_generated.deepcopy.go, pkg/resourceoverrides/cloudids_overrides.go, pkg/resourceoverrides/overrides.go, scripts/generate-google3-docs/resource-reference/generated/resource-docs/cloudids/cloudidsendpoint.md, tests/apichecks/testdata/exceptions/acronyms.txt
Adds resource overrides for `CloudIDSEndpoint` to rename the output only field `endpointIp` to `endpointIP`.
=> fix: endpointIp -> endpointIP

pkg/controller/direct/monitoring/refs.go
I neglected to return the value in the external case, previously.
=> fix: alertPolicyRef with external references

mockgcp/common/httpmux/mux.go, pkg/test/resourcefixture/testdata/basic/cloudbuild/v1beta1/cloudbuildworkerpool/_http.log, pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardbasic/_http.log, pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardfull/_http.log, pkg/test/resourcefixture/testdata/basic/monitoring/v1beta1/monitoringdashboard/monitoringdashboardrefs/_http.log
Clients can specify a query parameter of $alt=json;enum-encoding=int
(with some escaping) to get integer encoded values from protos.
We support this for more fidelity with mockgcp (though it does make
things a bit harder to read - ideally the clients would not do this,
but if we use the default clients we don't have full control here)
=> mockgcp: support enum-encoding=int alt specifier

dev/tasks/find-missing-fields, docs/releasenotes/release-1.120.md, pkg/controller/direct/monitoring/maputils.go, pkg/controller/direct/monitoring/roundtrip_test.go
Create a script to run our round-trip tests, also stop excluding some fields we
have added support for, and normalize more values to be valid
(e.g. alignment_period only supports whole seconds)
=> monitoringdashboard: round trip tests

apis/monitoring/v1beta1/monitoringdashboard_types.go, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_monitoringdashboards.monitoring.cnrm.cloud.google.com.yaml, pkg/clients/generated/apis/monitoring/v1beta1/monitoringdashboard_types.go, scripts/generate-google3-docs/resource-reference/generated/resource-docs/monitoring/monitoringdashboard.md
I tried the new CRD size in the operator and it passes the  `TestConfigConnectorE2E` check. 
related to https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2217
Capture some solutions to the root cause:
1.  Switch the cc operator's default applier to use server-side-apply. This requires upstream change to k-d-p  https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/399
2. Switch the cc operator to use the `ApplysetApplier` (use ssa already). This requires not setting the `metadata.managedFields`. But the DCL/TF based controllers already have many handlings around `managedFields`. So this may not be a good option.
3. Turn on the operator check in presubmit to capture this issue earlier.
=> fix: truncate monitoringdashboard CRD to fit into cc operator check

pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/mysqlinstance/_generated_object_mysqlinstance.golden.yaml, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/mysqlinstance/_http.log, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/mysqlinstance/create.yaml, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/mysqlinstance/update.yaml, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlserverinstance/_generated_object_sqlserverinstance.golden.yaml, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlserverinstance/_http.log, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlserverinstance/create.yaml, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlserverinstance/update.yaml
Seems that the existing `metadata.labels` changes do not incur updates to the resources. So that we exercise the mockgcp update path, made some changes to `spec.settings.diskSize` for these resources.
=> fix: Trigger updates for mysqlinstance + sqlserverinstance mockgcp tests

dev/codebots/update-golang-version, dev/tasks/update-dependency
=> chore: don't assume "co" git alias for checkout

dev/tasks/update-dependency
This stops bumping versions for dependencies we aren't using.
=> chore: only update dependencies in dev scripts if they are in go.mod

pkg/test/resourcefixture/testdata/basic/dataform/v1alpha1/dataformrepository/_http.log, pkg/test/resourcefixture/testdata/basic/dataform/v1alpha1/dataformrepository/create.yaml, pkg/test/resourcefixture/testdata/basic/dataform/v1alpha1/dataformrepository/update.yaml
Adds basic test for `DataformRepository`, an autogen tf resource. Will update the `update.yaml` and add log, golden files once we have a mock for this.
=> tests: basic dataform fixture tests

pkg/resourceskeleton/testdata/uri-skeleton.yaml
Fix resource skeleton for BigQueryConnectionConnection so that TestNewFromURI() passes.
=> Fix resource skeleton for BigQueryConnectionConnection

config/tests/samples/create/harness.go, mockgcp/mockcompute/service.go, mockgcp/mockcompute/vpngatewayv1.go, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computevpngateway/_generated_object_computevpngateway.golden.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computevpngateway/_http.log, pkg/test/resourcefixture/testdata/externalref/externalwithpartialuri/_generated_object_externalwithpartialuri.golden.yaml, pkg/test/resourcefixture/testdata/externalref/externalwithpartialuri/_http.log
Add mock support for ComputeVPNGateway, that's required for ComputeForwardingRule
Cherry-picked code from https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/936
=> MockGCP: Support for ComputeVPNGateway

config/tests/samples/create/harness.go, mockgcp/mockcompute/service.go, mockgcp/mockcompute/targetvpngatewayv1.go, mockgcp/mockcompute/vpngatewayv1.go, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargetvpngateway/_generated_object_computetargetvpngateway.golden.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargetvpngateway/_http.log, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computevpngateway/_generated_object_computevpngateway.golden.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computevpngateway/_http.log, pkg/test/resourcefixture/testdata/externalref/externalwithpartialuri/_generated_object_externalwithpartialuri.golden.yaml, pkg/test/resourcefixture/testdata/externalref/externalwithpartialuri/_http.log, tests/e2e/normalize.go
Add mock support for ComputeTargetVPNGateway, that's required for ComputeForwardingRule
Cherry-picked code from https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/936
=> MockGCP: Support for ComputeTargetVPNGateway

dev/tools/proto-to-mapper/.gitignore
This is to help with cleanup when running `make generate-pb` as the artifacts probably don't need to live in the tree at `dev/tools/proto-to-mapper` .
=> chore: gitignore generated

mockgcp/mockgkehub/gkehubfeature.go, mockgcp/mockgkehub/gkehubmembership.go, mockgcp/mockgkehub/service.go, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeature/acmfeature/_http.log, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeature/mcifeature/_generated_object_mcifeature.golden.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeature/mcifeature/_http.log, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeature/mcsdfeature/_http.log, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicacmgkehubfeaturemembership/_http.log, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullacmgkehubfeaturemembership/_http.log, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/meshgkehubfeaturemembership/_generated_object_meshgkehubfeaturemembership.golden.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/meshgkehubfeaturemembership/_http.log, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/meshgkehubfeaturemembership/create.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubmembership/_generated_object_gkehubmembership.golden.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubmembership/_http.log
=> Imporve GKEhub mocks using startLRO

config/tests/samples/create/harness.go, mockgcp/mockcompute/globalbackendservicesv1.go, mockgcp/mockcompute/globalforwardingrulesv1.go, mockgcp/mockcompute/globaltargethttpproxiesv1.go, mockgcp/mockcompute/globalurlmapsv1.go, mockgcp/mockcompute/regionalbackendservicev1.go, mockgcp/mockcompute/regionalforwardingrulev1.go, mockgcp/mockcompute/regionaltargethttpproxiesv1.go, mockgcp/mockcompute/regionalurlmapsv1.go, mockgcp/mockcompute/service.go, mockgcp/mockcompute/vpngatewayv1.go, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrule/_generated_object_globalcomputeforwardingrule.golden.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrule/_http.log, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/regionalcomputeforwardingrule/_generated_object_regionalcomputeforwardingrule.golden.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/regionalcomputeforwardingrule/_http.log, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargethttpproxy/globaltargethttpproxy/_generated_object_globaltargethttpproxy.golden.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargethttpproxy/globaltargethttpproxy/_http.log, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargethttpproxy/regionaltargethttpproxy/_generated_object_regionaltargethttpproxy.golden.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computetargethttpproxy/regionaltargethttpproxy/_http.log, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeurlmap/regionalcomputeurlmap/_generated_object_regionalcomputeurlmap.golden.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeurlmap/regionalcomputeurlmap/_http.log, tests/e2e/normalize.go
Add mock support for ComputeForwardingRule
Cherry-picked code from https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/936
Note: 
This is the basic implementation of mock ComputeForwardingRule, include its dependencies. I will have a full test in a followup PR.
Since this resource has many dependencies, I did not have full test coverage for those dependency resources, and some of those mock tests are skipped. As long as they work for ComputeForwardingRule, we are good for now. We will try to cover them during their Sci-fi migration in the future.
=> MockGCP: Support for ComputeForwardingRule

dev/tasks/update-proto-dependencies, experiments/compositions/composition/go.mod, experiments/compositions/composition/go.sum, go.mod, go.sum, mockgcp/go.mod, mockgcp/go.sum
renovate-bot is telling us we have an out-of-date dependency, so
update all our GRPC/proto libraries as a set.
=> chore: update proto dependencies

dev/tools/proto-to-mapper/Makefile, dev/tools/proto-to-mapper/main.go
1. Fix error in `make  generate-code`:
```
F0712 20:24:29.727911 1320557 main.go:411] unhandled kind "enum" for repeated field FieldDescriptor{Syntax: proto3, FullName: google.cloud.kms.v1.KeyAccessJustificationsPolicy.allowed_access_reasons, Number: 1, Cardinality: repeated, Kind: enum, HasJSONName: true, JSONName: "allowedAccessReasons", IsPacked: true, IsList: true, Enum: google.cloud.kms.v1.AccessReason}
exit status 255
make: *** [Makefile:3: generate-code] Error 1
```
2. Handle a List of enum during mapper generation([allowed access reasons](https://github.com/googleapis/googleapis/blob/4472b64f1c110e8e951a0ffaa08842d485ca1cc8/google/cloud/kms/v1/resources.proto#L1014) is a list of enum type)
Before:
```
func KeyAccessJustificationsPolicy_FromProto(mapCtx *MapContext, in …
```
=> chore: Handle list of enum during mapper generation

mockgcp/mockserviceusage/knownservices.go, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicacmgkehubfeaturemembership/_http.log, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicacmgkehubfeaturemembership/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullacmgkehubfeaturemembership/_http.log, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullacmgkehubfeaturemembership/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/meshgkehubfeaturemembership/_http.log, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/meshgkehubfeaturemembership/dependencies.yaml
I think it recently becomes a requirement to enable anthos API(may be related to GKEE).
```
reconcile.go:193: error was not considered transient; chain is [[*fmt.wrapError: Update call failed: error applying desired state: operation received error: error code "9", message: configmanagement feature requires enablement of anthos.googleapis.com, details: []
details: map[]] [*fmt.wrapError: error applying desired state: operation received error: error code "9", message: configmanagement feature requires enablement of anthos.googleapis.com, details: []
```
=> Enable anthos api for gkehubfeaturemembership tests

config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_bigquerytables.bigquery.cnrm.cloud.google.com.yaml, config/samples/resources/bigquerytable/bigquery_v1beta1_bigquerytable.yaml, config/tests/samples/create/harness.go, pkg/clients/generated/apis/bigquery/v1beta1/bigquerytable_types.go, pkg/clients/generated/apis/bigquery/v1beta1/zz_generated.deepcopy.go, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable/_generated_object_bigquerytable.golden.yaml, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable/_vcr_cassettes/dcl.yaml, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable/_vcr_cassettes/oauth.yaml, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable/_vcr_cassettes/tf.yaml, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable/create.yaml, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable/update.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/bigquery/bigquerytable.md, third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/services/bigquery/resource_bigquery_table.go
require_partition_filter.patch
Make require_partition_filter a top level field.
This will replace the same field in the time_partitioning.
Fixes [1654](https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/1654)
=> bigquery table require_partition_filter.patch

operator/pkg/kccstate/kccstate.go, pkg/k8s/stateintospecdefaulter_test.go
Fetch the ConfigConnectorContext object when the ConfigConnector object exists but `spec.mode` is unset.
Mode in ConfigConnector is defaulted to `namespaced` ([code logic here](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/v1.120.1/operator/pkg/apis/core/v1beta1/configconnector_types.go#L121)) so it's valid to have `spec.mode` unset in it.
=> ConfigConnectorContext should be fetched when 'spec.mode' in ConfigConnector is not set

config/servicemappings/vertexai.yaml, pkg/resourceskeleton/resourceskeleton.go, pkg/resourceskeleton/testdata/uri-skeleton.yaml
=> Fix skeleton test for Vertex AI resources

experiments/compositions/composition/config/rbac/role.yaml, experiments/compositions/composition/internal/controller/composition_controller.go, experiments/compositions/composition/internal/controller/expander_reconciler.go, experiments/compositions/composition/release/crds.yaml, experiments/compositions/composition/release/manifest.yaml, experiments/compositions/composition/tests/data/TestSimpleAddFacadeField/input.yaml, experiments/compositions/composition/tests/data/TestSimpleCompositionUpdate/input.yaml, experiments/compositions/composition/tests/data/TestSimpleDeleteFacade/input.yaml, experiments/compositions/composition/tests/data/TestSimpleDeleteFacadeField/input.yaml, experiments/compositions/composition/tests/data/TestSimpleExpanderInvalid/input.yaml, experiments/compositions/composition/tests/data/TestSimpleExpanderJinjaWithQuotes/input.yaml, experiments/compositions/composition/tests/data/TestSimpleExpanderVersionInvalid/input.yaml, experiments/compositions/composition/tests/data/TestSimpleExpansionGrpc/input.yaml, experiments/compositions/composition/tests/data/TestSimpleExpansionJob/input.yaml, experiments/compositions/composition/tests/data/TestSimpleFacadeByoSchema/input.yaml, experiments/compositions/composition/tests/data/TestSimpleNamespaceExplicit/input.yaml, experiments/compositions/composition/tests/data/TestSimpleNamespaceExplicit/output.yaml, experiments/compositions/composition/tests/data/TestSimpleNamespaceInherit/input.yaml, experiments/compositions/composition/tests/data/TestSimplePlanStatusErrorExpansionFailed/input.yaml, experiments/compositions/composition/tests/data/TestSimplePlanStatusErrorFailedApplyingManifests/input.yaml, experiments/compositions/composition/tests/data/TestSimplePlanStatusErrorFailedLoadingManifestsFromPlan/input.yaml, experiments/compositions/composition/tests/data/TestSimplePlanStatusWaitingForValues/input.yaml, experiments/compositions/composition/tests/data/TestUpdateCompositionCRAddStage/input.yaml, experiments/compositions/composition/tests/data/TestUpdateCompositionCRRemoveStage/input.yaml, experiments/compositions/composition/tests/data/TestUpdateCompositionModifyStage/input.yaml, experiments/compositions/samples/AppTeam/composition/appteam.yaml, experiments/compositions/samples/CloudSQL/composition/hasql.yaml
Update composition controller RBAC
Tests all manually grant superuser permissions to the composition controller for simplicity, but that hid the fact that the controller did not have the right permissions to carry out its tasks.
This change removes the broad permissions from the tests and samples and updates the controller RBAC to cover more of the requirements (while still expecting users to grant any additional permissions as necessary).
As a hack to make preview smoother for customers, globally grant superuser to the controller for the short term.
=> Update composition controller RBAC

.github/license-lint-config.yml, apis/dataform/v1alpha1/groupversion_info.go, apis/dataform/v1alpha1/repository_types.go, go.mod, go.sum, pkg/controller/direct/dataform/repository_controller.go, pkg/controller/direct/dataform/repository_mappings.go, pkg/controller/direct/maputils.go, pkg/controller/direct/register/register.go
Add `direct` controller for `DataformRepository`.
=> feat: direct dataformrepository ctrl

dev/tools/controllerbuilder/template/controller.go
Per conversations w Justin, we want to stick with the `nil, nil` over `nil, ErrNotImplemented` for now. Maybe in the future we will add a `nil, not_implemented_bool, nil`. Reverting this so it doesn't confuse devs.
=> Revert "enh: return nil for unimplemented"

mockgcp/Makefile
Optionally allow developers to specify a commit hash to pull from googleapis.
The default behavior is still the same - pull from HEAD.
Specifying a commit hash could be useful when
- HEAD is broken
- There is an open PR to update googleapis in mockgcp but the PR hasn't merge yet. Specifying a previous commit hash could improve the stability and consistency of proto generation.
=> build: make commit hash for googlapis configurable

experiments/compositions/samples/FirstComposition/README.md, experiments/compositions/samples/FirstComposition/composition/teampage.yaml
Fixes for the first composition sample
- Use generated CRD instead of Facade
- change the CRD group to make it generic
- change the facade to get the list of team members instead of apps
- Update the landing page configmap to use the list of team members instead of apps
=> Fixes for the first composition sample

experiments/compositions/samples/AppTeam/README.md, experiments/compositions/samples/AppTeam/cleanup_appteam.sh, experiments/compositions/samples/AppTeam/composition/appteam.yaml, experiments/compositions/samples/AppTeam/get_appteam.sh
Remove hardcoded values from the AppTeam sample.
Parameterize the additional fields.
=> Compositions [feat] Remove hardcoded values and parameterize AppTeam sample

experiments/compositions/samples/AttachedEKS/01-composition.yaml
fix issue while creating eks cluster
use subnet id instead of subnet resference in eks cluster creation to address subnet reference resolution issue
save subnet ids into a configmap
use the subnet ids instead of subnet refs during eks creation
- [*] Run `make ready-pr` to ensure this PR is ready for review.
- [*] Perform necessary E2E testing for changed resources.
=> Fix subnet ref resolving issue during eks creation in EKS composition sample

experiments/compositions/samples/AttachedAKS/01-composition.yaml, experiments/compositions/samples/AttachedEKS/01-composition.yaml
Update the compositions for AKS and EKS to use the defined k8s cluster version instead of the hard-coded 1.28.
=> Fix cluster version setting in attached compositions.

experiments/compositions/samples/AttachedAKS/01-composition.yaml, experiments/compositions/samples/AttachedEKS/01-composition.yaml
use different suffix for aks/eks oidc issuer configmap to avoid conflict if customer is using the same name for different type of clusters
use different suffix for aks/eks oidc issuer configmap to avoid conflict if customer is using the same name for different type of clusters
- [*] Run `make ready-pr` to ensure this PR is ready for review.
- [*] Perform necessary E2E testing for changed resources.
=> differentiate aks/eks oidc issuer name in composition samples

dev/tasks/build-images
When building images with dev/tasks/build-images, currently all the
images get the same base path, so the extra cnrm "directory" is not
what we do today.
=> chore: don't add cnrm prefix to the operator image path

experiments/compositions/samples/AttachedAKS/01-composition.yaml, experiments/compositions/samples/AttachedAKS/03-attached-1.yaml, experiments/compositions/samples/AttachedEKS/01-composition.yaml, experiments/compositions/samples/AttachedEKS/03-attached-1.yaml
- Grabbed the CRD from the cluster after applying the Facade and replaced the contents in the yaml.
- Renamed the group something more generic to better demonstrate the definition is something users own.
- Tested both AKS and EKS flows.
=> Update Attached samples to use CRD instead of Facade.

experiments/compositions/composition/internal/controller/expander_reconciler.go
A logging statement was malformed causing a panic. Rewrote the logging statement and verified all tests pass.
=> Fix panic when enabling expander debug logs.

dev/tools/controllerbuilder/pkg/codegen/mappergenerator.go, dev/tools/controllerbuilder/pkg/codegen/typegenerator.go
- stabilize the ordering of the generated types (always in sorted order)
- refactor the generator to have function `writeMessage` and `writeField` so they can be reused in the future
=> chore: refactor type generator code, stabilize the ordering of the generated types

scripts/generate-third-party-licenses/main.go
We need to hard-code new dependencies, this one is coming with a GCP
client update.
=> chore: recognize cel.dev/expr in our license utils

apis/gkehub/v1beta1/gkehubfeaturemembership_types.go, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_gkehubfeaturememberships.gkehub.cnrm.cloud.google.com.yaml, mockgcp/generated/mockgcp/cloud/gkehub/v1beta/configmanagement/configmanagement.pb.go, pkg/clients/generated/apis/gkehub/v1beta1/gkehubfeaturemembership_types.go, scripts/generate-google3-docs/resource-reference/generated/resource-docs/gkehub/gkehubfeaturemembership.md
Add a deprecation note that Policy Controller should be configured through the policycontroller feature instead.
This is to reduce the usage of configuring Policy Controller using the ACM KCC resource.
=> Add a deprecation note that Policy Controller should be configured through the policycontroller feature instead.

experiments/kompanion/main.go, experiments/kompanion/pkg/version/version.go
Let's include a version "watermark" so we can distinguish between version, especially in the early stages:
```
$ kompanion -v
kompanion version kompanion/devel (ff6b33cf00a80c04c1d324f30a49caf826c2761a) (linux/amd64) ff6b33cf00a80c04c1d324f30a49caf826c2761a-dirty/2024-07-29T23:13:55Z
```
=> tool:kompanion: add version

experiments/kompanion/README.md, experiments/kompanion/cmd/export/export.go
Adds worker support so namespaces can be processed in parallel. 
I've also marked where I can add debug level logs and will add those as a follow on PR.
=> enh:kompanion: support goroutines

.github/workflows/lint.yaml, .golangci.yaml, Makefile
Previously, was getting the following error when running `make ready-pr` locally:
```
level=error msg="Running error: context loading failed: failed to load
packages: failed to load with go/packages: err: exit status 1: stderr:
go: go.work requires go >= 1.22.5 (running go 1.22.0;
GOTOOLCHAIN=local)\n"
```
Also, updated .golangci.yaml to move away from deprecated `run.skip-dirs` to the new `issues.exclude-dirs` rule.
=> chore: Update golangci-lint

scripts/resource-autogen/main.go
klog.Warningf should be used with %v, not %w
=> chore: fix some linter warnings

tests/e2e/script_test.go, tests/e2e/testdata/scenarios/README.md, tests/e2e/testdata/scenarios/powertool/logginglogmetric_clear_state_into_spec/SCENARIO_README.md, tests/e2e/testdata/scenarios/powertool/logginglogmetric_clear_state_into_spec/script.yaml
* Added the test step `READ-OBJECT-AND-COMPARE-SPEC` to compare the spec of the golden objects of the current step and the step configured in `TARGET_STEP_FOR_READ_AND_COMPARE`.
* Configured the newly added test step for logginglogmetric_clear_state_into_spec test case.
=> Add a step to automate the kube object comparison in powertool test

dev/tools/controllerbuilder/pkg/codegen/generatorbase.go
When scaffolding a new resource, the directory for types file is not yet created. In this case, we should not skip generating the types.
/cc @jasonvigil
=> tools: do not skip type generation when scaffolding a new resource

.golangci.yaml
Small change to exclude the tooling generate snippets from lint as they don't compile yet.
=> ci: exclude mapper generations

tests/e2e/normalize.go, tests/e2e/unified_test.go
We were only normalizing a handful of the URLs from the compute requests.
=> tests: more complete compute normalization

dev/tools/controllerbuilder/generate.sh, dev/tools/controllerbuilder/pkg/commands/generatetypes/generatetypescommand.go, dev/tools/controllerbuilder/pkg/options/generateoptions.go, dev/tools/controllerbuilder/scaffold/apis.go, dev/tools/controllerbuilder/scaffold/controller.go
Problem:
When we export the generated type to `./apis`, the _types.go generation no longer works (triggered by `--kind` flag). 
Because the _type.go file template contains the same `kcc:proto` tag as the _type.generated.go file suppose to use. This skips the actual proto-to-go generation of that resource.
=> chore: change the _type.go template to not skip target resource when --kind is specified

config/tests/samples/create/harness.go, mockgcp/mockpubsub/topic.go, mockgcp/mockstorage/bucket.go, mockgcp/mockstorage/notification.go, mockgcp/mockstorage/service.go, pkg/test/resourcefixture/testdata/basic/container/v1beta1/containercluster/_http.log, pkg/test/resourcefixture/testdata/basic/pubsub/v1beta1/pubsubtopic/_generated_object_pubsubtopic.golden.yaml, pkg/test/resourcefixture/testdata/basic/pubsub/v1beta1/pubsubtopic/_http.log, pkg/test/resourcefixture/testdata/basic/secretmanager/v1beta1/secretmanagersecret/_http.log, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlserverinstance/_http.log, pkg/test/resourcefixture/testdata/basic/storage/v1beta1/storagenotification/storagenotificationbase/_http.log, pkg/test/resourcefixture/testdata/basic/storage/v1beta1/storagenotification/storagenotificationfull/_http.log, pkg/test/resourcefixture/testdata/directives/forcedestroy/_http.log, pkg/test/resourcefixture/testdata/iammemberreferences/serviceaccountref/_http.log, pkg/test/resourcefixture/testdata/iammemberreferences/sqlinstanceref/_http.log
based from #2446
- add MockGCP for StorageNotification (v1beta1)
- Fixed MockGCP for `StorageBucket` and `PubSubTopic` to fit real GCP outcome.
=> feat: add mockgcp for storageNotification

config/tests/samples/create/harness.go, mockgcp/mockbigquery/service.go, mockgcp/mockbigquery/tables.go, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable/_http.log, pkg/test/resourcefixture/testdata/resourceid/referencewithuserspecifiedresourceid/_generated_object_referencewithuserspecifiedresourceid.golden.yaml, pkg/test/resourcefixture/testdata/resourceid/referencewithuserspecifiedresourceid/_http.log
Add required mockGCP tests for bigquery tables, including mock testing against the golden http logs from the real GCP service.
This PR is to complement a previous merged one: https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1733
Fixes https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/1654
E2E_KUBE_TARGET=envtest RUN_E2E=1 E2E_GCP_TARGET=mock GOLDEN_OBJECT_CHECKS=1 GOLDEN_REQUEST_CHECKS=1 \                  
go test -timeout 600s -v ./tests/e2e \
-run TestAllInSeries/fixtures/bigquerytable
=> generate mockGCP tests for bigquery table resource

dev/tasks/run-e2e, pkg/test/gcp/gcp.go
Otherwise we fall back to the credentials and gcloud default project.
This allows us to override the project in our e2e tests.
=> tests: use GCP_PROJECT_ID (if set) as default project

.github/workflows/lint.yaml
We were seeing some failures from it without corresponding error
messages, try updating.
=> chore: update golangci-lint-action

pkg/test/resourcefixture/contexts/register.go
Return an error when Export() is not supported so the dynamic test won't panic.
`mysqlinstance` test failed with the expected message:
```
dynamic_controller_integration_test.go:248: [validateCreate] unexpected error when GET-ing 'sqlinstance-sample-20240812': SQLInstance uses direct controller and Export() is not implemented yet
```
=> Return an error in dynamic test when Export() is not supported

mockgcp/mockcompute/globaladdress.go, mockgcp/mockcompute/globalforwardingrulesv1.go, mockgcp/mockcompute/instancesv1.go, mockgcp/mockcompute/regionalforwardingrulev1.go, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeaddress/regionalcomputeaddress/_http.log, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrule/_generated_object_globalcomputeforwardingrule.golden.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrule/_http.log, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/regionalcomputeforwardingrule/_generated_object_regionalcomputeforwardingrule.golden.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/regionalcomputeforwardingrule/_http.log, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeinstance/computeinstancebasicexample/_generated_object_computeinstancebasicexample.golden.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeinstance/computeinstancebasicexample/_http.log, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeinstance/computeinstancewithencrypteddisk/_generated_object_computeinstancewithencrypteddisk.golden.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeinstance/computeinstancewithencrypteddisk/_http.log, pkg/test/resourcefixture/testdata/resourceoverrides/computeinstance/networkipcomputeinstance/_generated_object_networkipcomputeinstance.golden.yaml, pkg/test/resourcefixture/testdata/resourceoverrides/computeinstance/networkipcomputeinstance/_http.log, tests/e2e/normalize.go, tests/e2e/unified_test.go
Comparing with realGCP logs, there are something I missed in the mock:
1) the current mock is missing some fields, which appear to be API defaulted if unspecified by user(but I do not find any compute documentation mentioning those default values, that's a bit concerning): LabelFingerprint, Fingerprint, IPProtocol, NetworkTier.
2) if only one number is provided for portRange, i.e. 80, it will be changed to "80-80" as per the realGCP log
=> mocks: Update ComputeForwardingRule mock responses with API default fields

pkg/test/controller/reconciler/testreconciler.go, pkg/test/runner/runner.go
Some simple log lines to help me to more easily narrow down which resources are failing to create dependencies.
=> tests: log resource name for dependency failure

pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableinstance/bigtableinstanceautoscaling/_generated_object_bigtableinstanceautoscaling.golden.yaml, pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableinstance/bigtableinstanceautoscaling/_http.log, pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableinstance/bigtableinstanceautoscaling/create.yaml, pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableinstance/bigtableinstanceautoscaling/update.yaml, pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableinstance/bigtableinstanceautoscaling2/_generated_object_bigtableinstanceautoscaling2.golden.yaml, pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableinstance/bigtableinstanceautoscaling2/_http.log, pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableinstance/bigtableinstanceautoscaling2/create.yaml, pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableinstance/bigtableinstanceautoscaling2/update.yaml
Integration tests have been failing due to the large bigtable maxNodes request sizes. This PR adjusts the bigtable maxNode requests to be smaller, and moves all resources into zones with larger quota limits.
=> fix: Reduce bigtable request size to meet project quotas

.github/workflows/presubmit-compositions.yaml, experiments/compositions/composition/README.md, experiments/compositions/composition/expanders/getter/main_test.go
For some reason the global linter was not catching any errors in experiments. 
Add a github actions for experiments/compositions:
- go linter
=> Add linter that targets only compositions folder

mockgcp/mockstorage/notification.go, mockgcp/mockstorage/utils.go
It would be nice, but it does introduce a circular dependency that
go.mod can't figure out.
=> chore: don't use "direct" package from mockgcp

config/tests/samples/create/samples.go, dev/tasks/run-e2e, tests/e2e/script_test.go
Also refactor to demonstrate where the 35 minute pause comes from.
=> tests: increase default e2e timeout to 2 hours

pkg/controller/direct/sql/mapping.go, pkg/controller/direct/sql/sqlinstance_controller.go, pkg/controller/dynamic/dynamic_controller_integration_test.go, pkg/test/resourcefixture/contexts/register.go, pkg/test/resourcefixture/contexts/sql_context.go
This fixes some of the failing SQL Instance dynamic tests caused by nil pointer dereferences of nil objects returned by the (previously) empty export implementation.
=> feat: Implement "Export" for SQLInstance

mockgcp/mockcompute/imagesv1.go, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeimage/_generated_object_computeimage.golden.yaml
Support SetLabels() in mock compute image to avoid 501 errors when regenerating the http logs.
`WRITE_GOLDEN_OUTPUT=1 RUN_E2E=1 GOLDEN_OBJECT_CHECKS=1 GOLDEN_REQUEST_CHECKS=1 E2E_KUBE_TARGET=envtest E2E_GCP_TARGET=mock KCC_USE_DIRECT_RECONCILERS="SQLInstance"   go test -test.count=1 -timeout 3600s -v ./tests/e2e -run TestAllInSeries/fixtures/computeimage` passed.
=> Support SetLabels() in mock compute image

config/samples/resources/computebackendservice/internal-managed-load-balancing-backend-service/compute_v1beta1_computebackendservice.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/compute/computebackendservice.md
Error message:  error applying desired state: summary: Error creating RegionBackendService: googleapi: Error 400: Invalid value for field 'resource.consistentHash.httpHeaderName': 'Hash string'. Must be a match of regex '[!#$%&'*+-.^_`|~0-9a-zA-Z]+', invalid"}
Local test passed:
```
--- PASS: TestAll (1.02s)
--- PASS: TestAll/internal-managed-load-balancing-backend-service (119.04s)
PASS
{"severity":"info","timestamp":"2024-08-15T22:05:16.896Z","msg":"Stopping and waiting for non leader election runnables"}
{"severity":"info","timestamp":"2024-08-15T22:05:16.896Z","msg":"Stopping and waiting for leader election runnables"}
{"severity":"info","timestamp":"2024-08-15T22:05:16.896Z","msg":"Stopping and waiting for caches"}
{"severity":"info","timestamp":"2024-08-15T22:05:16.896Z","msg":"Stopp …
```
=> fixit: Fix samples test data for internal-managed-load-balancing-backend-service

pkg/controller/direct/alloydb/cluster_controller.go, pkg/controller/direct/alloydb/mapping.go, pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbcluster/basicalloydbcluster/_generated_object_basicalloydbcluster.golden.yaml, pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbcluster/basicalloydbcluster/_http.log, pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbcluster/basicalloydbcluster/create.yaml, pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbcluster/basicalloydbcluster/update.yaml, pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbcluster/fullalloydbcluster/_generated_object_fullalloydbcluster.golden.yaml, pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbcluster/fullalloydbcluster/_http.log, pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbcluster/fullalloydbcluster/create.yaml, pkg/test/resourcefixture/testdata/basic/alloydb/v1beta1/alloydbcluster/fullalloydbcluster/update.yaml
Also, added support for user labels in the direct controller.
Had to fix some of the test cases so they pass when running with direct controller + realgcp:
- Remove `displayName` field (it is currently broken / not working in the GCP API).
- Remove `maintenanceUpdatePolicy` field (it is not implemented in direct controller yet).
=> Implement Export capability for AlloyDB

apis/gkehub/v1beta1/gkehubfeaturemembership_types.go, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_gkehubfeaturememberships.gkehub.cnrm.cloud.google.com.yaml, mockgcp/generated/mockgcp/cloud/gkehub/v1beta/configmanagement/configmanagement.pb.go, pkg/clients/generated/apis/gkehub/v1beta1/gkehubfeaturemembership_types.go, scripts/generate-google3-docs/resource-reference/generated/resource-docs/gkehub/gkehubfeaturemembership.md
Add a note for deprecating Hierarchy Controller in Config Management feature. This is to reduce the usage of configuring Hierarchy Controller using the ACM KCC resource.
Fixes #
=> Add a note for deprecating Hierarchy Controller in Config Management feature

dev/ci/periodics/_create_project_and_run_e2e, pkg/test/utils.go, tests/e2e/unified_test.go
Because we don't want to treat a new upstream field as an error here.
=> tests: don't fail on changes in the http log during e2e

mockgcp/mockspanner/admin/database.go, pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerdatabase/_generated_object_spannerdatabase.golden.yaml, pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerdatabase/_http.log, pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerdatabase/_vcr_cassettes/tf.yaml, pkg/test/resourcefixture/testdata/basic/spanner/v1beta1/spannerdatabase/create.yaml
Spanner database has a length limitation of 30 but the current name (and by default, the resource ID) of SpannerDatabase in testdata exceeds the limit and caused test failures against the real GCP API. So shortened the name to match the length limitation and improved mockspanner to detect the violation.
=> Fix SpannerDatabase resource name in testdata and improve mockspanner

.github/workflows/presubmit.yaml, scripts/github-actions/tests-e2e-fixtures
Increase test timeout to unblock dev
This will be a temporary change. When #1822 is done, we can determine a reasonable timeout.
=> test: Temporarily increase presubmit fixtures timeout

experiments/compositions/composition/api/v1alpha1/composition_types.go, experiments/compositions/composition/config/crd/bases/composition.google.com_compositions.yaml, experiments/compositions/composition/pkg/applier/applier.go
Support Name,Namespace when setting up readiness rules: 
- In addition to GVK, we want to support Name, Namespace to have custom rule per object. 
- Name and Namespace are optional.
=> Feature: Support optional Name, Namespace for cel readiness rules

config/tests/samples/create/samples_test.go
So we can skip flaky test cases in main job and split them into another job
[Gob CL](https://cnrm-review.git.corp.google.com/c/cnrm/+/70800 ) with the change passed [cnrm-samples-test](https://prow-gob.gcpnode.com/view/gs/cnrm-prow/pr-logs/pull/cnrm-review.googlesource.com_cnrm/70800/cnrm-samples-test/1825647277872517120) presubmit
=> fixit: Add flag to skip samples tests

mockgcp/mocksecretmanager/tests/service_test.go, pkg/controller/mocktests/secretmanager_secret_test.go, scripts/unit-test.sh
* Fixed TestSecretManagerSecretVersion. It failed because the mockresourcemanager change when creating a new mock project: it no longer immediately marks LRO done.
* Added the failed test to the unit test suite as this is the main reason why it failed for so long but didn't get much attention.
=> Fix TestSecretManagerSecretVersion

pkg/controller/direct/registry/registry.go
If we haven't registered the direct controller here, log a warning
rather than treating this as an error.
=> fix: don't raise errors in SupportsIAM

Makefile, config/installbundle/release-manifests/kustomization.yaml
Add build commands to generate the config connector manifests for standard GKE clusters.
The config connector manifests  is generated with a reference to https://cloud.google.com/config-connector/docs/how-to/install-manually#installing_the_operator.
example release manifests generated by running
`make all-manifests`
https://paste.googleplex.com/5174914120417280#l=1332
=> Add build for config connector manifests

experiments/kompanion/cmd/export/export.go
With some kube versions (I believe) the group version is empty and
should be defaulted from the containing list.
=> kompanion: default group version to resource list GV

experiments/kompanion/cmd/export/export.go
I simply had the test backwards before.
=> kompanion: fix namespace auto-selection logic

experiments/kompanion/cmd/export/export.go
We aim to use the full name to avoid "jargon".
=> kompanion: use "Config Connector" instead of KCC

tests/e2e/testdata/scenarios/gkehubfeaturemembership/iam_test/_http00.log, tests/e2e/testdata/scenarios/gkehubfeaturemembership/iam_test/_http01.log, tests/e2e/testdata/scenarios/gkehubfeaturemembership/iam_test/_http02.log, tests/e2e/testdata/scenarios/gkehubfeaturemembership/iam_test/_http03.log, tests/e2e/testdata/scenarios/gkehubfeaturemembership/iam_test/_http04.log, tests/e2e/testdata/scenarios/gkehubfeaturemembership/iam_test/_http05.log, tests/e2e/testdata/scenarios/gkehubfeaturemembership/iam_test/_object00.yaml, tests/e2e/testdata/scenarios/gkehubfeaturemembership/iam_test/_object01.yaml, tests/e2e/testdata/scenarios/gkehubfeaturemembership/iam_test/_object02.yaml, tests/e2e/testdata/scenarios/gkehubfeaturemembership/iam_test/_object03.yaml, tests/e2e/testdata/scenarios/gkehubfeaturemembership/iam_test/_object04.yaml, tests/e2e/testdata/scenarios/gkehubfeaturemembership/iam_test/_object05.yaml, tests/e2e/testdata/scenarios/gkehubfeaturemembership/iam_test/script.yaml
Add golden output of gkehub resource with IAM references
=> Add golden output of gkehub resource with IAM references

dev/ci/periodics/README.md, dev/ci/periodics/_create_project_and_run_e2e
The typo fix should now work, and the README describes how to verify them locally.
=> tests: fix typo and add README to periodics

config/samples/resources/gkehubfeaturemembership/config-management-feature-membership/gkehub_v1beta1_gkehubfeature.yaml, config/samples/resources/gkehubfeaturemembership/config-management-feature-membership/gkehub_v1beta1_gkehubfeaturemembership.yaml, config/samples/resources/gkehubfeaturemembership/config-management-feature-membership/gkehub_v1beta1_gkehubmembership.yaml, config/samples/resources/gkehubfeaturemembership/config-management-feature-membership/serviceusage_v1beta1_service.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/gkehub/gkehubfeaturemembership.md
* Mark the deletion policy to be "abandon" for global resources
* Remove deprecated PoCo and HNC fields in the sample
* Changed the membership resource location  from global to regional so that we don't accidentally have >=1 golbal memberships in a project, which causes KCC/Hub can't figure out the correct membership. see b/350963989#comment7
=> Fix gkehub sample

apis/sql/v1beta1/sqlinstance_types.go, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_sqlinstances.sql.cnrm.cloud.google.com.yaml, pkg/clients/generated/apis/sql/v1beta1/sqlinstance_types.go, pkg/controller/direct/directbase/directbase_controller.go, pkg/controller/direct/registry/registry.go, pkg/controller/direct/sql/sqlinstance_controller.go, pkg/controller/predicate/reconcilegate.go, pkg/controller/registration/registration_controller.go, pkg/controller/tf/controller.go
If spec.cloneSource is specified, use direct reconciler. Otherwise, use
the terraform-based reconciler.
However, if `KCC_USE_DIRECT_RECONCILERS=SQLInstance` is set, always use
the direct reconciler.
This commit adds a reusable way for other direct reconcilers to
accomplish a similar goal of partially enabling the direct reconciler,
based on the resource to-be-reconciled. The ReconcileGate can be
registered for any direct reconciler, with custom logic based on the
resource.
Depends on https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2429
=> Add predicate to partially enable SQLInstance direct reconciler

config/tests/samples/create/harness.go, mockgcp/mockdataflow/jobs.go, mockgcp/mockdataflow/workflows.go, mockgcp/mockpubsub/service.go, mockgcp/mockpubsub/subscription.go, mockgcp/mockpubsub/topic.go, mockgcp/mockpubsub/utils.go, pkg/test/resourcefixture/testdata/basic/container/v1beta1/containercluster/_http.log, pkg/test/resourcefixture/testdata/basic/dataflow/v1beta1/dataflowflextemplatejob/streamingdataflowflextemplatejob/_generated_object_streamingdataflowflextemplatejob.golden.yaml, pkg/test/resourcefixture/testdata/basic/dataflow/v1beta1/dataflowflextemplatejob/streamingdataflowflextemplatejob/_http.log, pkg/test/resourcefixture/testdata/basic/pubsub/v1beta1/pubsubsubscription/basicpubsubsubscription/_generated_object_basicpubsubsubscription.golden.yaml, pkg/test/resourcefixture/testdata/basic/pubsub/v1beta1/pubsubsubscription/basicpubsubsubscription/_http.log, pkg/test/resourcefixture/testdata/basic/pubsub/v1beta1/pubsubsubscription/bigquerypubsubsubscription/_generated_object_bigquerypubsubsubscription.golden.yaml, pkg/test/resourcefixture/testdata/basic/pubsub/v1beta1/pubsubsubscription/bigquerypubsubsubscription/_http.log, pkg/test/resourcefixture/testdata/basic/pubsub/v1beta1/pubsubtopic/_http.log, pkg/test/resourcefixture/testdata/basic/secretmanager/v1beta1/secretmanagersecret/_http.log, pkg/test/resourcefixture/testdata/basic/storage/v1beta1/storagenotification/storagenotificationbase/_http.log, pkg/test/resourcefixture/testdata/basic/storage/v1beta1/storagenotification/storagenotificationfull/_http.log, pkg/test/resourcefixture/testdata/externalref/externalwithname/_generated_object_externalwithname.golden.yaml, pkg/test/resourcefixture/testdata/externalref/externalwithname/_http.log, pkg/test/resourcefixture/testdata/iammemberreferences/sqlinstanceref/_http.log
- **tests: capture golden output for PubSub**
- **mockgcp: support for PubSubSubscription**
=> mockgcp: support for PubSubSubscription

experiments/compositions/composition/tests/data/TestSimpleExpanderInvalid/input.yaml, experiments/compositions/composition/tests/data/TestSimpleExpanderVersionInvalid/input.yaml, experiments/compositions/composition/tests/testcases/simple_test.go
The two tests which verify controller behavior for compositions with invalid expanders have been asserting that the resultant Plan objects similarly show an error. This check is incorrect because a resource relying on an invalid Composition should never generate a Plan to begin with. An existing bug is creating Plans incorrectly and the test was mistakenly checking on those.
Remove the check of the Plan and only verify the Composition status.
=> Remove incorrect assertions for invalid expander tests

dev/tasks/run-e2e, scripts/github-actions/tests-e2e-fixtures, scripts/github-actions/tests-e2e-fixtures-compute, scripts/github-actions/tests-e2e-fixtures-gkehub
This means we only need to maintain the KCC_USE_DIRECT_RECONCILERS list in one spot.
=> tests: funnel all tests through run-e2e

dev/tools/controllerbuilder/template/controller.go, pkg/controller/direct/alloydb/cluster_controller.go, pkg/controller/direct/apikeys/apikeyskey_controller.go, pkg/controller/direct/cloudbuild/workerpool_controller.go, pkg/controller/direct/compute/forwardingrule_controller.go, pkg/controller/direct/dataform/repository_controller.go, pkg/controller/direct/directbase/directbase_controller.go, pkg/controller/direct/directbase/interfaces.go, pkg/controller/direct/directbase/operations.go, pkg/controller/direct/gkehub/featuremembership_controller.go, pkg/controller/direct/logging/logmetric_controller.go, pkg/controller/direct/monitoring/monitoringdashboard_controller.go, pkg/controller/direct/networkconnectivity/serviceconnectionpolicy_controller.go, pkg/controller/direct/privateca/privatecapool_controller.go, pkg/controller/direct/redis/cluster/rediscluster_controller.go, pkg/controller/direct/resourcemanager/tagkey_controller.go, pkg/controller/direct/sql/sqlinstance_controller.go, pkg/test/resourcefixture/contexts/register.go
This should allow for richer behaviours, such as intermediate updates of status.
=> refactor: pass operation objects to adapters

experiments/compositions/composition/internal/controller/expander_reconciler.go, experiments/compositions/composition/pkg/applier/applier.go
Refactor Reconcile loop
- Existing loop does eager evaluation; evaluate as many expanders as possible before apply loop.
- New one does a simple for all expanders: evaluate + apply loop
Why this change:
We want to start implementing implicit getter. This requires us passing latest objects to evaluate() functions. 
So having apply after evaluate allows us to grab latest applied results for next evaluate stage.
=> Compositions: Refactor Reconcile loop

experiments/compositions/composition/release/manifest.yaml
Manual install version had a `v` prefix which our release images does not have.
=> Compositions: Fix manual install version

pkg/test/eventsink.go, pkg/test/resourcefixture/testdata/basic/dataflow/v1beta1/dataflowflextemplatejob/batchdataflowflextemplatejob/_http.log, pkg/test/resourcefixture/testdata/basic/dataflow/v1beta1/dataflowflextemplatejob/streamingdataflowflextemplatejob/_http.log, tests/e2e/httplog.go, tests/e2e/unified_test.go
LROs (and things like LROs) are timing dependent, so we remove them from LROs.
=> tests: refactor to share code for removing extra events

dev/tools/controllerbuilder/template/apis/types.go
In controller builder template, use CEL to validate `resourceID` as immutable field.
=> tool: mark resourceID as immutable field in template

hack/compare-mock
This avoids another copy of the direct-reconciler list, with the accompanying possibilities for skew.
=> refactor: have compare-mock call into run-e2e

pkg/controller/direct/sql/sqlinstance_controller.go, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-mysql-minimal/_http.log, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-mysql/_http.log, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqluser/_http.log, pkg/test/resourcefixture/testdata/iammemberreferences/sqlinstanceref/_http.log
MySQL requires that the host is passed-in along with the username. Otherwise, the delete request will fail.
=> fix: Delete mysql root user after creation

pkg/controller/dynamic/dynamic_controller_integration_test.go
This issue was never hit before because testNoChangeAfterUpdate is currently only enabled for SQLInstances resources. We recently added a SQLInstance test case that does not set an update.yaml resource (sqlinstance-clone-minimal), and it revealed the problem causing a nil pointer dereference when getting update object.
=> fix: Skip testNoChangeAfterUpdate if update resource is empty

experiments/compositions/composition/go.mod, experiments/compositions/composition/go.sum, experiments/compositions/composition/internal/controller/expander_reconciler.go, experiments/compositions/composition/pkg/applier/applier.go, experiments/compositions/composition/tests/data/TestImplicitGetter/input.yaml, experiments/compositions/composition/tests/data/TestImplicitGetter/output.yaml, experiments/compositions/composition/tests/testcases/simple_test.go
Implicit Getter
- Automatically add last applied objects into the values passed to expanders
- We add the objects under path: values.<kind>.<name>. This may have conflicts
- on conflict we choose the first seen object
- Refactor Reconciler() function to separate evaluation code into
evaluate() function to reduce cyclomatic complexity
- Add test: TestImplicitGetter
- Uses latest kdp that includes patch to return last applied object: https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/404
Limitations:
- Cant use if the object name is templated on input 
Future work:
- Support templated input object name OR something similar.
- Support explicit naming of objects
=> Compositions: Implicit Getter - first attempt

cmd/recorder/main.go
We were using Errorf placeholders with structured logging.
=> chore: fix formatting of recorder error message

dev/tools/controllerbuilder/template/apis/types.go
In controller builder template, remove unnecessary `// +optional` annotations in resource `Status`.
=> tool: remove unnecessary optional annotation in template

dev/ci/periodics/_create_project_and_run_e2e, dev/tasks/run-e2e
Some of our test suites take a long time.
=> tests: use a longer timeout in (real) e2e tests

config/tests/samples/create/harness.go
The tests are currently failing and it probably needs a re-record.
=> tests: turn off VCR tests for SQLUser

pkg/controller/dynamic/dynamic_controller_integration_test.go
There is no way to check for diffs in these fields, because export can only return the external reference, not the in-cluster object name/namespace.
=> fix: Skip checking for diffs in resource reference fields

config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_computeforwardingrules.compute.cnrm.cloud.google.com.yaml, dev/tasks/generate-crds, pkg/clients/generated/apis/compute/v1beta1/computeforwardingrule_types.go, pkg/clients/generated/apis/compute/v1beta1/zz_generated.deepcopy.go, pkg/controller/direct/compute/forwardingrule_externalresource.go, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrule/_generated_object_globalcomputeforwardingrule.golden.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/regionalcomputeforwardingrule/_generated_object_regionalcomputeforwardingrule.golden.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/regionalforwardingrulepsc/_generated_object_regionalforwardingrulepsc.golden.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/compute/computeforwardingrule.md
Generated CRD and populate status.externalRef in golden log
=> direct: Generate crd and upload status.externalRef

mockgcp/mockcloudbuild/workerpool.go, pkg/test/resourcefixture/testdata/basic/cloudbuild/v1beta1/cloudbuildworkerpool/_http.log
When LRO is finished, we should update the resource object in mockgcp storage.
I checked against real GCP, a `GET` call on Cloud Build Worker Pool does include "createTime, etag, state" in the response.
=> mockgcp: improve cloud build worder pool

pkg/controller/dcl/controller.go, pkg/controller/direct/monitoring/utils.go, pkg/controller/direct/registry/registry.go, pkg/controller/direct/sql/sqlinstance_controller.go, pkg/controller/predicate/optin.go, pkg/controller/registration/registration_controller.go, pkg/controller/tf/controller.go, pkg/test/resourcefixture/testdata/basic/dataflow/v1beta1/dataflowflextemplatejob/batchdataflowflextemplatejob-direct/_generated_object_batchdataflowflextemplatejob-direct.golden.yaml, pkg/test/resourcefixture/testdata/basic/dataflow/v1beta1/dataflowflextemplatejob/batchdataflowflextemplatejob-direct/_http.log, pkg/test/resourcefixture/testdata/basic/dataflow/v1beta1/dataflowflextemplatejob/batchdataflowflextemplatejob-direct/create.yaml, pkg/test/resourcefixture/testdata/basic/dataflow/v1beta1/dataflowflextemplatejob/batchdataflowflextemplatejob-direct/dependencies.yaml, tests/e2e/httplog.go
Add support for a new label, 'alpha.cnrm.cloud.google.com/reconciler'
If set to `direct`, the direct reconciler will be used.
=> feat: allow users to opt-in to direct reconciliation

apis/refs/v1beta1/alertpolicyref.go, apis/refs/v1beta1/computerefs.go, apis/refs/v1beta1/projectref.go, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_apikeyskeys.apikeys.cnrm.cloud.google.com.yaml, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_cloudbuildworkerpools.cloudbuild.cnrm.cloud.google.com.yaml, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_computeforwardingrules.compute.cnrm.cloud.google.com.yaml, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_dataflowflextemplatejobs.dataflow.cnrm.cloud.google.com.yaml, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_dataformrepositories.dataform.cnrm.cloud.google.com.yaml, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_logginglogmetrics.logging.cnrm.cloud.google.com.yaml, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_monitoringdashboards.monitoring.cnrm.cloud.google.com.yaml, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_networkconnectivityserviceconnectionpolicies.networkconnectivity.cnrm.cloud.google.com.yaml, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_redisclusters.redis.cnrm.cloud.google.com.yaml, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_securesourcemanagerinstances.securesourcemanager.cnrm.cloud.google.com.yaml, pkg/clients/generated/apis/monitoring/v1beta1/monitoringdashboard_types.go, scripts/generate-google3-docs/resource-reference/generated/resource-docs/cloudbuild/cloudbuildworkerpool.md, scripts/generate-google3-docs/resource-reference/generated/resource-docs/compute/computeforwardingrule.md, scripts/generate-google3-docs/resource-reference/generated/resource-docs/dataflow/dataflowflextemplatejob.md, scripts/generate-google3-docs/resource-reference/generated/resource-docs/logging/logginglogmetric.md, scripts/generate-google3-docs/resource-reference/generated/resource-docs/monitoring/monitoringdashboard.md
Fixes comment https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2599#discussion_r1742680977
Note: There are still many `KCC` usages in existing code comments and function names. Since they are not directly exposed to Cx, I think it's fine to keep them as is.
=> chore: Change `KCC` in field description to `Config Connector`

pkg/controller/direct/directbase/directbase_controller.go, pkg/k8s/finalizers.go
This avoids exiting early and not setting them.
=> fix: write finalizers eagerly in direct controller

mockgcp/mocksql/sqlinstance.go, pkg/controller/direct/sql/mapping.go, pkg/controller/direct/sql/merge.go, pkg/test/resourcefixture/contexts/sql_context.go, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-authorizednetworks/_http.log, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-clone-minimal/_http.log, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-encryptionkey/_http.log, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-locationpreference/_generated_object_sqlinstance-locationpreference.golden.yaml, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-locationpreference/_http.log, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-locationpreference/create.yaml, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-locationpreference/update.yaml, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-mysql-minimal/_http.log, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-mysql/_http.log, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-postgres-minimal/_http.log, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-postgres/_http.log, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-privatenetwork/_http.log, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-sqlserver-minimal/_http.log, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-sqlserver/_http.log, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-ssl/_http.log
Update locationPreference mapping code to improve readability, make similar to generated mapping code.
Also, update ipConfiguration export code (this was missed before).
=> Add test case for SQLInstance location preference

apis/gkehub/v1beta1/gkehubfeaturemembership_types.go, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_gkehubfeaturememberships.gkehub.cnrm.cloud.google.com.yaml, config/samples/resources/gkehubfeaturemembership/config-management-feature-membership/gkehub_v1beta1_gkehubfeature.yaml, crds/gkehub_v1beta1_gkehubfeaturemembership.yaml, mockgcp/generated/mockgcp/cloud/gkehub/v1beta/configmanagement/configmanagement.pb.go, pkg/clients/generated/apis/gkehub/v1beta1/gkehubfeaturemembership_types.go, scripts/generate-google3-docs/resource-reference/generated/resource-docs/gkehub/gkehubfeaturemembership.md
There's legal reason that we cannot use the term "deprecated" for Hierarchy Controller
=> doc: correct the term "deprecated" in Hierarchy Controller

pkg/controller/direct/sql/mapping.go, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-locationpreference/_generated_object_sqlinstance-locationpreference.golden.yaml, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-locationpreference/_http.log, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-locationpreference/create.yaml, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-locationpreference/update.yaml
Always return boolean fields in export (even if value is false). Also, specify regional availability type in locationPreference test cases so that the secondaryZone is utilized.
=> Fix failing sql postsubmit tests

pkg/controller/direct/firestore/firestoredatabase_controller.go, pkg/controller/dynamic/dynamic_controller_integration_test.go, pkg/test/resourcefixture/contexts/firestore_context.go, pkg/test/resourcefixture/contexts/register.go
Due to issue with FirestoreDatabase service LRO / eventual consistency, wait after creating / updating so that the changes eventually become visible.
Also, do not attempt to update if the concurrency_mode or point_in_time_recovery_enablement fields are unspecified.
=> fix: Fix FirestoreDatabase postsubmit failures

pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicacmgkehubfeaturemembership/_generated_object_basicacmgkehubfeaturemembership.golden.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicacmgkehubfeaturemembership/_http.log, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicacmgkehubfeaturemembership/create.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicacmgkehubfeaturemembership/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicacmgkehubfeaturemembership/update.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullacmgkehubfeaturemembership/_generated_object_fullacmgkehubfeaturemembership.golden.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullacmgkehubfeaturemembership/_http.log, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullacmgkehubfeaturemembership/create.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullacmgkehubfeaturemembership/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullacmgkehubfeaturemembership/update.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/meshgkehubfeaturemembership/_generated_object_meshgkehubfeaturemembership.golden.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/meshgkehubfeaturemembership/_http.log, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/meshgkehubfeaturemembership/create.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/meshgkehubfeaturemembership/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/meshgkehubfeaturemembership/update.yaml
* Use regional membership instead of global one to deflake the parallel tests.
* Removed HNC fields in the tests as it is deprecated  https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/crds/gkehub_v1beta1_gkehubfeaturemembership.yaml#L245
=> Deflake test using regional memberships

mockgcp/mockcompute/globalforwardingrulesv1.go, mockgcp/mockcompute/operations.go, mockgcp/mockcompute/regionalforwardingrulev1.go, pkg/controller/direct/compute/forwardingrule_controller.go, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrule/_http.log, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrulefull/_http.log, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrulehttps/_http.log, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrulessl/_http.log, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingruletcp/_http.log, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/regionalcomputeforwardingrule/_http.log
Fixed diffs identified in #2695
1. Updated operation type `SetLabels` -> `setLabels`
2. `POST setLabels` returns `operation DONE`(100) instead of `RUNNING`(0)
3. Compared realGCP w/ TFcontroller and realGCP w/ direct controller in #2711, noticed a diff:
TF:       POST setLabels(return operation done) -> GET forwarding rule
direct: POST setLabels(return operation done) -> GET operation(return operation done) -> GET forwarding rule
So we should not make extra `GET operation` call if it's already done.
4. Updated the 404 error message for forwarding rule
5. Reformat `regions` field
=> (Part 1)Fix diffs in compute forwarding rule: operations

apis/sql/v1beta1/sqlinstance_types.go, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_sqlinstances.sql.cnrm.cloud.google.com.yaml, pkg/clients/generated/apis/sql/v1beta1/sqlinstance_types.go, pkg/controller/registration/registration_controller.go, scripts/github-actions/tests-e2e-fixtures-vcr.sh
Fixes https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/2706
=> fix: Enable TF-based reconciler for SQLInstances without clone source

dev/tasks/deploy-to-kube
We also try to create a storage bucket during development of this
script - we aren't setting up IAM permissions so it won't work yet.
Once this is more real we probably want to stop auto-creating storage
buckets.
Example usage: VERSION=7b7142e dev/tasks/deploy-to-kube
=> chore: create simple script to deploy the operator to a kube cluster

pkg/krmtotf/krmtotf.go
Shift-left the defaulting of the following spec fields to the TF controller fix the unexpected diffs in re-reconciliation when there is no change in the CR:
* `spec.location` in `CloudBuildTrigger`.
* `spec.initialGroupConfig` in `CloudIdentityGroup`.
* `spec.database` in `FirestoreIndex`.
This looks like an old bug and was only exposed when `state-into-spec: absent` became the default configuration.
More context: https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2704#issue-2529378867
=> Set default values to immutable and optional spec fields for certain kinds

dev/tools/controllerbuilder/pkg/commands/generatetypes/generatetypescommand.go
This PR introduces the following changes:
- Marks the `--proto-resource` flag as explicitly required, since the proto resource name is required for identifying the starting point of type generation.
- Ensures that the first character (rune) of the proto resource name is automatically capitalized within the tool, eliminating the need for users to remember to capitalize the first letter in their input.
- Also marks the `--kind` flag as required, given that kind and proto message often do not have the same name.
=> tools: require "--kind" and "--proto-resource" when generating types

pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrule/_http.log, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrulefull/_http.log, tests/e2e/unified_test.go
based on #2724, check the last commit in this PR
When executing the tests against realGCP, the ip address will be generated by GCP if not provided. Normalize the ip address to be `8.8.8.8` as the fake ip we wrote in ComputeAddress mock server, to avoid diffs between mock and real.
=> (Part 4)Fix diffs in compute forwarding rule: normalize `IPAddress` in golden logs

docs/releasenotes/release-1.123.md
Added the announcement that all the new CRs will by default support `state-into-spec: absent` since v1.123.
=> Update release-1.123.md with announcement about state-into-spec absent

config/samples/resources/containerattachedcluster/container-attached-cluster-basic/containerattached_v1beta1_containerattachedcluster.yaml, config/samples/resources/containerattachedcluster/container-attached-cluster-full/containerattached_v1beta1_containerattachedcluster.yaml, config/samples/resources/containerattachedcluster/container-attached-cluster-ignore-errors/containerattached_v1beta1_containerattachedcluster.yaml, config/tests/samples/create/harness.go, config/tests/samples/create/samples.go, mockgcp/mockgkemulticloud/attachedcluster.go, pkg/test/controller/k8s.go, pkg/test/gcp/gcp.go, pkg/test/resourcefixture/testdata/basic/containerattached/v1beta1/containerattachedclusterbasic/_generated_object_containerattachedclusterbasic.golden.yaml, pkg/test/resourcefixture/testdata/basic/containerattached/v1beta1/containerattachedclusterbasic/_http.log, pkg/test/resourcefixture/testdata/basic/containerattached/v1beta1/containerattachedclusterfull/_generated_object_containerattachedclusterfull.golden.yaml, pkg/test/resourcefixture/testdata/basic/containerattached/v1beta1/containerattachedclusterfull/_http.log, scripts/generate-google3-docs/resource-reference/generated/resource-docs/containerattached/containerattachedcluster.md
- Set all the fields that are returned by the attached cluster service
- Update resource not found message
- Regenerate golden files
- Update env var substitution for platform version so the samples tests pass
=> Update attached clusters mockGCP responses to more closely match GCP.

pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/fullybigquerydataset/_generated_export_fullybigquerydataset.golden, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/fullybigquerydataset/_generated_object_fullybigquerydataset.golden.yaml, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/fullybigquerydataset/_http.log, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/fullybigquerydataset/create.yaml, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/fullybigquerydataset/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/fullybigquerydataset/update.yaml
This PR is the first PR [reference](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/docs/develop-resources/scenarios/migrate-tf-resource-beta.md#add-mockgcp-tests), where the create.yaml and the update.yaml are the same. [Here](https://paste.googleplex.com/5881785281150976) are the logs recorded against real GCP.
Will create a second PR to change the mutable field in the update.yaml file.
=> test:add mockgcp test full suite for bigquerydataset

dev/tools/controllerbuilder/pkg/gocode/ast.go
When running the mapper tool (example: 
```
go run main.go generate-mapper \
--service google.cloud.bigquery.analyticshub.v1 \
--proto-source-path ../proto-to-mapper/build/googleapis.pb \
--output-dir $REPO_ROOT/pkg/controller/direct/ \
--api-dir $REPO_ROOT/apis \
--api-go-package-path $REPO_ROOT/apis/bigqueryanalyticshub \
--api-version "bigqueryanalyticshub.cnrm.cloud.google.com/v1alpha1"
```
), I ran into the following err:
```
...
inspecting go code: loading package "<MY_PATH>/kcc/8/k8s-config-connector/apis/refs/v1beta1": inspecting package "v1beta1": unhandled type spec in "ExternalNormalizer": *ast.InterfaceType, &{Interface:24559 Methods:0xc00d5d7620 Incomplete:false}
exit status 1
```
=> dev:tool: small fix for interface type

mockgcp/apply-proto-patches.sh
maintenance_update_policy has now been published in the public protos.
Keep it around as a comment though, so we know how to use this for next time - it isn't trivial.
=> mockgcp: we don't need the alloydb maintenance_update_policy patch any more

dev/tools/controllerbuilder/pkg/commands/generatemapper/generatemappercommand.go, dev/tools/controllerbuilder/pkg/commands/generatetypes/generatetypescommand.go, dev/tools/controllerbuilder/pkg/options/generateoptions.go
Add default values to some of the flags used by type generator and mapper generator. So that users do not need to specify them.
=> tools: add default values to type and mapper generator flags

dev/tools/controllerbuilder/scaffold/controller.go
```
$ go run main.go add --service google.cloud.iap.v1 --api-version iap.cnrm.cloud.google.com/v1alpha1 --kind IAPSettings --proto-resource IapSettings
...
multiple errors occurred:
parse external resource template: %!s(*template.Template=<nil>)
exit status 1
```
=> tools: fix parsing error in controller builder

dev/tools/controllerbuilder/template/controller/controller.go
As I'm working with more resources in the BigQueryAnalyticsHub service group, I want to start adding nice-ness to the tooling when having more than one resource.
=> refactor: use resource name in ctrl name

config/tests/samples/create/harness.go, mockgcp/mockcompute/globalforwardingrulesv1.go, mockgcp/mockcompute/regionalforwardingrulev1.go, pkg/controller/direct/compute/forwardingrule_controller.go, pkg/controller/direct/compute/refs.go, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/regionalforwardingrulepsc/_http.log, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeserviceattachment/_generated_object_computeserviceattachment.golden.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeserviceattachment/_http.log
Deleting a resource does not require resolving dependencies. However, if dependencies are deleted prior to the resource itself, it will prevent the deletion of that resource.
Therefore, we should move resolvers to their own function outside the Adapter. We can resolve them during the create and update only.
Fixes #2621
=> fix: Move resolvers out of Adapter

pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrulefull/_generated_object_globalcomputeforwardingrulefull.golden.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrulefull/_http.log, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrulefull/create.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrulefull/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computeforwardingrule/globalcomputeforwardingrulefull/update.yaml
`globalcomputeforwardingrule` dynamic test failed due to conflict port range with `globalcomputeforwardingrulefull`.
Update port range for `globalcomputeforwardingrulefull` from "80" to "90".
Verified locally, both tests passed.
=> test: Fix global forwarding rule dynamic test

pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/fullybigquerydataset/_generated_export_fullybigquerydataset.golden, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/fullybigquerydataset/_generated_object_fullybigquerydataset.golden.yaml, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/fullybigquerydataset/_http.log, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/fullybigquerydataset/create.yaml, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/fullybigquerydataset/update.yaml
Run the test against real GCP with annotation to set the state-into-spec to both absent and merge, without setting the storagebillingmodel.
| state-into-spec | storagebillingmodel in create.yaml | storagebillingmodel in golden object yaml |
| ----------------|----------------------------------- | ------------------------------------------| 
| absent                | Not set                                               | Not populated                                               |
| merge                 | Not set                                               | Not populated                                               |
If annotations are not set explicitly in the `create.yaml` file, it will default to absent and in the golden object yaml file, the storagebillingmodel will not be …
=> test: second PR to update mutable fields for bigQueryDataset

pkg/controller/direct/dataform/repository_controller.go, pkg/controller/direct/dataform/repository_externalresource.go, pkg/test/resourcefixture/testdata/basic/dataform/v1beta1/dataformrepository-base/_generated_object_dataformrepository-base.golden.yaml, pkg/test/resourcefixture/testdata/basic/dataform/v1beta1/dataformrepository-full/_generated_object_dataformrepository-full.golden.yaml
Refactor DataformRepository's externalRef as per https://github.com/yuwenma/k8s-config-connector/blob/real-id/docs/develop-resources/api-conventions/external-reference.md
=> refactor: use new externalRef convention

Makefile, config/installbundle/components/clusterroles/cnrm_admin.yaml, config/installbundle/components/clusterroles/cnrm_viewer.yaml, pkg/apis/core/v1alpha1/servicemapping_types.go, pkg/controller/direct/registry/registry.go, pkg/controller/mocktests/harness.go, pkg/crd/crdgeneration/dcl2crdgeneration_test.go, pkg/gvks/gvks.go, pkg/gvks/supportedgvks/supportedgvks.go, pkg/gvks/supportedgvks/supportedgvks_test.go, pkg/test/controller/reconciler/testreconciler.go, pkg/webhook/iam_defaulter.go, pkg/webhook/register.go, scripts/generate-cnrm-cluster-roles/main.go, scripts/generate-crds/main.go, scripts/generate-google3-docs/resource-reference/main.go
Fixes #2646
* Added direct GVKs into supportedgvks.All() function so that reference doc generation and cnrm role generation logic can cover direct GVKs.
* Added supportedgvks.AllWithoutDirect() to handle the situations when direct GVKs are not necessary. We should avoid calling supportedgvks.All() repetitively, and we should avoid calling it during resource reconciliation. supportedgvks.All() loops through all the CRDs (i.e. 400+ files) and it is time consuming.
* Updated the reference doc generation logic to make it work for direct GVKs.
I think we should enforce samples and reference doc template work for Scifi as well. 
=> Add GVKs supported by direct controllers to supportedgvks.All()

pkg/test/constants/presubmitconstants_test.go
Presubmit constants are rarely used these days and covering all services in map is no longer important. Removing TestAllServicesInMap to reduce cost to maintain the constant whenever a new service is supported.
=> Delete unit test TestAllServicesInMap

pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-datacacheconfig-direct/create.yaml, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-datacacheconfig/_http.log, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-datacacheconfig/create.yaml
TF-based controller cannot update the edition at the same time as modifying dataCacheEnabled.
=> fix: Adjust sqlinstance-datacacheconfig test case for tf controller

pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-datacacheconfig/_http.log, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-datacacheconfig/create.yaml
Missed this required update in the previous fix: https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2832
=> fix: Fix sqlinstance-datacacheconfig periodic

scripts/github-actions/ga-pause-test.sh
When I first added the e2e pause tests, the idea was for us to make sure that when KCC is paused, we don't send requests to GCP. We easily do this with mocks (check the log). As we've added more fixtures tests, the run time has ballooned and I think it's overly ambitious to run these for every fixture. 
A given KCC resource will use one of the 4 controllers:
- the Direct controller
- the Terraform (TF) controller
- the DCL controller
- a hand-rolled/ special controller (usually IAM related)
So if any resource can be reduced to one of the 4 categories, it is sufficient (and necessary) to only test an example of each flavor of controller. 
This change will significantly decrease the runtime for the ci job for pause while still fully testing the feature functionality.
=> refactor:ci: selectively run pause tests

.gitattributes
This should make PR review a bit easier.
=> chore: mark *.generated.go as generated

dev/tools/controllerbuilder/scaffold/controller.go, dev/tools/controllerbuilder/template/controller/controller.go, dev/tools/controllerbuilder/template/controller/externalresource.go
Breaking off from https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2839, cherry-picked the controller part of the effort which is more straightforward than the types gen.
=> refactor: make add cmd kind aware

apis/bigquery/v1beta1/bigquerydataset_types.go, apis/bigqueryconnection/v1alpha1/connection_types.go, apis/bigquerydatatransfer/v1alpha1/bigquerydatatransferconfig_types.go, apis/bigtable/v1beta1/bigtableinstance_types.go, apis/cloudbuild/v1beta1/workerpool_types.go, apis/firestore/v1alpha1/firestoredatabase_types.go, apis/networkconnectivity/v1alpha1/networkconnectivityserviceconnectionpolicy_types.go, apis/redis/v1alpha1/rediscluster_types.go, apis/secretmanager/v1beta1/secretmanagersecret_types.go, apis/workstations/v1alpha1/workstationcluster_types.go, dev/tools/controllerbuilder/template/apis/types.go, pkg/apis/common/v1alpha1/types.go
It is optional (because omitempty is specified in the struct tag), and
our docs recommend only specifying '+required' markers.
Follow-on to https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2833#issuecomment-2389692484
=> chore: Remove '+optional' marker from types template

pkg/webhook/register.go
Webhook failed with `unable to locate repo root in working directory "/"` because supportedgvks.All() calls LoadCRDs() which checks the local git path. This won't work if the webhook is registered/created at the path where a local [k8s-config-connector](https://github.com/GoogleCloudPlatform/k8s-config-connector) Git repo doesn't exist. LoadCRDs() should only be called under the repo path.
Using supportedgvks.AllWithoutDirect() in the webhook instead to avoid loading CRDs.
=> Avoid loading CRDs when registering the webhook

dev/tools/controllerbuilder/template/apis/refs.go, pkg/k8s/errors.go
This way, we will properly detect the source of the error being an unresolveable dependency and can requeue immediately once it's ready.
=> fix: Update ref template to return ReferenceNotReadyError

experiments/compositions/samples/Eventarc/eventarc-composition.yaml, experiments/compositions/samples/Eventarc/eventarcconfigs-crd.yaml, experiments/compositions/samples/Eventarc/facade.yaml
Fixes a diff that appears after running `make manifests`
=> fix: Add copyright headers to compositions samples

config/installbundle/releases/scopes/cluster/autopilot-withsecretvolume/kustomization.yaml, config/installbundle/releases/scopes/namespaced/autopilot-shared-components/kustomization.yaml, dev/tasks/build-release-bundle, dev/tasks/propose-tag, operator/config/autopilot-channels/cluster-gcp-identity/kustomization.yaml, operator/config/autopilot-channels/cluster-gcp-identity/recorder_remove_hostport_patch.yaml, operator/config/autopilot-channels/cluster-workload-identity/kustomization.yaml, operator/config/autopilot-channels/cluster-workload-identity/recorder_remove_hostport_patch.yaml, operator/config/autopilot-channels/crds/kustomization.yaml, operator/config/autopilot-channels/namespaced-main/kustomization.yaml, operator/config/autopilot-channels/namespaced-main/recorder_remove_hostport_patch.yaml, operator/config/autopilot-channels/namespaced-per-namespace-components/finalizer_patch.yaml, operator/config/autopilot-channels/namespaced-per-namespace-components/kustomization.yaml, operator/config/channels/cluster-gcp-identity/kustomization.yaml, operator/config/channels/cluster-workload-identity/kustomization.yaml, operator/config/channels/cluster-workload-identity/manager_sidecar_patch.yaml, operator/config/channels/cluster-workload-identity/recorder_sidecar_patch.yaml, operator/config/channels/crds/kustomization.yaml, operator/config/channels/namespaced-main/kustomization.yaml, operator/config/channels/namespaced-main/recorder_sidecar_patch.yaml, operator/config/channels/namespaced-per-namespace-components/finalizer_patch.yaml, operator/config/channels/namespaced-per-namespace-components/kustomization.yaml, operator/config/channels/namespaced-per-namespace-components/manager_sidecar_patch.yaml, operator/scripts/update-kcc-manifest/README.md
This script will update the manifests in the repository for a new release.
=> chore: create a script for updating the version

config/tests/samples/create/harness.go, mockgcp/mockprivilegedaccessmanager/entitlement.go, mockgcp/mockprivilegedaccessmanager/names.go, mockgcp/mockprivilegedaccessmanager/service.go, tests/e2e/unified_test.go
Diff base is #2659 where I added the CRD, mapper, controller and a basic test case for PrivilegedAccessManagerEntitlement.
This PR is built on top of #2659 to fix the mock service and ensure mock test passes. Only changes in commit https://github.com/GoogleCloudPlatform/k8s-config-connector/commit/4d9641627b7d5be574074c731b91b6fa40b9aa4b is relevant.
=> Support mockgcp test for PrivilegedAccessManagerEntitlement

pkg/controller/direct/bigqueryanalyticshub/dataexchange_controller.go, pkg/test/resourcefixture/testdata/basic/bigqueryanalyticshub/v1alpha1/bigqueryanalyticshubdataexchange-full/_generated_object_bigqueryanalyticshubdataexchange-full.golden.yaml, pkg/test/resourcefixture/testdata/basic/bigqueryanalyticshub/v1alpha1/bigqueryanalyticshubdataexchange-full/_http.log, pkg/test/resourcefixture/testdata/basic/bigqueryanalyticshub/v1alpha1/bigqueryanalyticshubdataexchange-full/create.yaml, pkg/test/resourcefixture/testdata/basic/bigqueryanalyticshub/v1alpha1/bigqueryanalyticshubdataexchange-full/update.yaml
We should have a check for enums that verifies whether the field was set or not. `discoveryType` is an optional field. Without this check, we will always find a diff with the defaulted server value.
=> fix: check set for enum

.github/workflows/presubmit.yaml, scripts/github-actions/tests-e2e-fixtures-sql
There are enough sql tests at this point that we should split them into
a separate suite to reduce overall presubmit time.
=> chore: Add SQLInstance presubmit test suite

pkg/controller/direct/gkehub/featuremembership_controller.go, pkg/controller/direct/gkehub/mappings.go
Adds the `Export` for the GKEHubFeatureMembership direct controller. Mappings mostly autogened
=> feat: add export for gkehubfeatmem

pkg/test/resourcefixture/contexts/sql_context.go
Now that we are using the GCP-preferred format (done in https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2908), the terraform-based controller passes the nochange test.
Forgot to include this in https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2908
=> fix: Enable sqlinstance-denymaintenanceperiod nochange test

CONTRIBUTING.md, Makefile, config/installbundle/base/kustomization.yaml
This PR 
- moves all kcc related image into the same cnrm subdirectory when pushing the built image to image registry
- add push config connector operator image to image registry
Tested on a GKE cluster:
```
$ kubectl get ns
NAME                 STATUS   AGE
default              Active   156m
gke-managed-cim      Active   156m
gke-managed-system   Active   156m
gmp-public           Active   155m
gmp-system           Active   155m
kube-node-lease      Active   156m
kube-public          Active   156m
kube-system          Active   156m
$ kubectl get deployments -A
NAMESPACE     NAME                            READY   UP-TO-DATE   AVAILABLE   AGE
gmp-system    gmp-operator                    1/1     1            1           156m
gmp-system    rule-evaluator                  0/0     0 …
```
=> chore:improve KCC build commands

pkg/controller/direct/directbase/directbase_controller.go, pkg/controller/direct/directbase/operations.go, pkg/controller/direct/sql/sqlinstance_controller.go
This will help detect issues with the direct reconciler in the periodic tests.
Now, "testNoChange" will be able to detect when SQLInstance is incorrectly / unnecessarily performing updates.
Also, it provides a similar UX as the TF/DCL controllers, which record events and conditions on update.
=> feat: Record events when updating SQLInstances

scripts/github-actions/tests-e2e-fixtures-sql
It was using ONLY_TEST_APIGROUP, which is the old form.
=> tests: fix env var to be ONLY_TEST_APIGROUPS

dev/tools/controllerbuilder/scaffold/controller.go, dev/tools/controllerbuilder/template/controller/controller.go
This work comes back to look at the controller builder cmd.
* it reverts the per package work as we're moving away from that direction to having a structure like:
```
resourceA_controller.go
resourceB_controller.go
```
* For any datastructure or function that needs a resource specific name, I added the necessary changes in the template.
Been testing this with the `BigQueryAnalyticsHubDataExchange` and `BigQueryAnalyticsHubListing`
=> feat:refactor: kind aware cmd add

third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/services/container/node_config.go
Cherry pick the fix in https://github.com/GoogleCloudPlatform/magic-modules/pull/11971.
This resolves the reconciliation error that occurs when `kubeletConfig` is empty in the user's configuration, but a subfield under kubeletConfig is set externally outside of KCC.
```
{"severity":"error","timestamp":"2024-10-21T23:33:23.865Z","logger":"containernodepool-controller","msg":"error applying desired state","resource":{"name":"test-b-374795345-10212024-pool","namespace":"default"},"error":"summary: googleapi: Error 400: At least one of ['node_version', 'image_type', 'updated_node_pool', 'locations', 'workload_metadata_config', 'upgrade_settings', 'kubelet_config', 'linux_node_config', 'tags', 'taints', 'labels', 'node_network_config', 'gcfs_config', 'gvnic', 'confidential_nodes', …
```
=> fix: mark "node_config[0].kubelet_config" as "computed"

tests/e2e/unified_test.go
This shouldn't happen, but we need to know why it happens if it does.
=> tests: warn, don't panic, if we can't read spec.resourceID

dev/tasks/download-e2e-logs
This is often faster than running the tests against real GCP directly.
Currently we don't expose the logs publicly in case they have
credentials in them (though they should be fine), so this script is
probably only usable by googlers.
=> chore: add script to download the e2e golden output from real-gcp

third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/services/container/node_config.go
Pick up the fix in https://github.com/GoogleCloudPlatform/magic-modules/pull/11152.
Default driver installation was enabled with release R17 on 5/24 in GKE 1.30.1-gke.1156000, which causes permanent diff in our test case.
Original error:
```
{"severity":"error","timestamp":"2024-10-22T19:34:52.878Z","msg":"Reconciler error","controller":"containernodepool-controller","controllerGroup":"container.cnrm.cloud.google.com","controllerKind":"ContainerNodePool","ContainerNodePool":{"name":"duxakctmptrllzcmjraupzbigsicqv","namespace":"cnrm-jingyih-test"},"namespace":"cnrm-jingyih-test","name":"duxakctmptrllzcmjraupzbigsicqv","reconcileID":"6adda282-8f22-471d-9635-a185a3963b49","error":"Update call failed: cannot make changes to immutable field(s): [Field Name: …
```
=> Fix permanent diff caused by default GPU driver installation in GKE node pools

dev/ci/periodics/e2e-service-container
Add the container.cnrm.cloud.google.com API group to the e2e tests.
=> tests: add gke to e2e

tests/e2e/unified_test.go
Today, if we just want to `WRITE_GOLDEN_OUTPUT`, the golden output objects are not actually written to file. They are only created if the respective GOLDEN object checks are added. Small change to just write the golden output if needed.
=> tests: write goldens

apis/containerattached/v1beta1/containerattachedcluster_types.go, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_containerattachedclusters.containerattached.cnrm.cloud.google.com.yaml, go.mod, go.sum, pkg/clients/generated/apis/containerattached/v1beta1/containerattachedcluster_types.go, pkg/clients/generated/apis/containerattached/v1beta1/zz_generated.deepcopy.go, pkg/controller/direct/containerattached/containerattachedcluster_mappings.go, pkg/controller/direct/containerattached/mapper.generated.go, scripts/generate-google3-docs/resource-reference/generated/resource-docs/containerattached/containerattachedcluster.md
Followed step 3 of the Direct Controller migration guide.
Manually implemented functions which the generator was unable to handle on its own.
Since this is a migration for an existing resource, some `NOTYET`s are in the code for new, unimplemented fields.
Fix the change that made the required `ProjectRef` optional in the previous PR.
=> Add field mapper for attached clusters direct controller migration.

config/tests/samples/create/harness.go, pkg/crd/crdloader/crdloader.go, pkg/k8s/crds.go, tests/e2e/unified_test.go
Speeds up tests a little, but also keeps the logs much more focused.
=> tests: Only load the CRDs we are using

config/samples/resources/computeimage/image-from-url-raw/compute_v1beta1_computeimage.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/compute/computeimage.md
The bucket was deleted and rendered the test to fail. Updated the yaml with new bucket and tested locally.
=> fix: update the compute image test yaml

experiments/compositions/README.md
While developing a KCC Composition, I often was unsure whether resources were created or not, due to not immediately being able to see them via `kubectl`. This note provides some guidance and can inform the dev experience.
Fixes #
=> InputReconciler length note

pkg/controller/dynamic/dynamic_controller_integration_test.go, pkg/test/resourcefixture/contexts/bigquerydatatransfer_context.go
This PR includes:
- Skipped the "drift correction test" for this resource because it has a service-generated ID.
- Added functionality in the dynamic e2e test to ignore sensitive fields (masked by the GCP API) during "update test".
Tested
```
$ go test -v -tags=integration ./pkg/controller/dynamic/ -test.run TestCreateNoChangeUpdateDelete -run-tests bigquerydatatransferconfig-salesforce
$ go test -v -tags=integration ./pkg/controller/dynamic/ -test.run TestCreateNoChangeUpdateDelete -run-tests bigquerydatatransferconfig-scheduledquery
```
For reference, the original error in "update test":
```
dynamic_controller_integration_test.go:820: unexpected diff:   string(
-       "AKfZ4pamHD_459mErG-pofG1xFFX1F3JRWRCh8nULWvFVHa1U3ZG1vFywgzDKR8",
+       "client-id2",
)
```
=> test: fix dynamic tests for BigQueryDataTransferConfig

cmd/recorder/main.go
Follow up on #2972 .
Verified that the error showed up in the log when orphaned CRD existed, and disappeared after the orphaned CRD was deleted.
=> Add warning log to clean up orphaned CRDs

config/tests/samples/create/harness.go
Because we start the manager in a goroutine, there is a race where the
webhook may not have started yet.  We were observing some test
failures because of this.
=> tests: wait for the webhook server to start

pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-clone-minimal-direct/_generated_object_sqlinstance-clone-minimal-direct.golden.yaml, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-clone-minimal-direct/_http.log, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-clone-minimal-direct/create.yaml, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-clone-minimal-direct/dependencies.yaml
This way, the test will not need to re-reconcile after cloning in order to update the backup configuration.
=> fix: Specify missing fields in clone backup configuration

dev/tasks/generate-crds
We added a "parent" field in the type "_reference.go" template, which does not intended to have [json tags](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/dev/tools/controllerbuilder/template/apis/refs.go#L47) to hide it from the CRD. 
This PR adjusts the `dev/tasks/generate-crds` to let it skip that "parent" field.
=> fix: controller-gen crd to allow unexported field

pkg/test/resourcefixture/testdata/basic/secretmanager/v1beta1/fullsecretmanagersecret/_generated_object_fullsecretmanagersecret.golden.yaml, pkg/test/resourcefixture/testdata/basic/secretmanager/v1beta1/fullsecretmanagersecret/_http.log, pkg/test/resourcefixture/testdata/basic/secretmanager/v1beta1/fullsecretmanagersecret/create.yaml, pkg/test/resourcefixture/testdata/basic/secretmanager/v1beta1/fullsecretmanagersecret/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/secretmanager/v1beta1/fullsecretmanagersecret/update.yaml
This PR adds back the test coverage for those fields that is previously broken in the TF-based approach.
1st git-commit is running agaisnt real GCP, and the second is against mockgcp.  
This also verified https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/3051 is fixed in the direct approach
=> chore: Enable more SecretManagerSecret fields 

config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_computebackendservices.compute.cnrm.cloud.google.com.yaml, config/servicemappings/compute.yaml, pkg/krmtotf/templating.go, pkg/test/resourcefixture/contexts/compute_context.go, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computebackendservice/globalcomputebackendservicesecuritysettings/create.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computebackendservice/globalcomputebackendservicesecuritysettings/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computebackendservice/globalcomputebackendservicesecuritysettings/update.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/compute/computebackendservice.md, third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/services/compute/resource_compute_backend_service.go
Fixes b/374166656
Resource created successfully:
```
kubectl describe ComputeBackendService computebackendservice-yuhou1025
Spec:
Load Balancing Scheme:  INTERNAL_SELF_MANAGED
Location:               global
Resource ID:            computebackendservice-yuhou1025
Security Settings:
Client TLS Policy Ref:
Name:  clienttlspolicy-yuhou1025
Subject Alt Names:
spiffe://junk.svc.id.goog/ns/test/sa/frontend
Timeout Sec:  10
Status:
Conditions:
Last Transition Time:  2024-10-25T19:18:09Z
Message:               The resource is up to date
Reason:                UpToDate
Status:                True
Type:                  Ready
Creation Timestamp:      2024-10-25T12:03:28.186-07:00
Fingerprint:             KkS0AHjQtyc=
Generated Id:            2810711594725955000
Observed Generation:     2
Self Link: …
```
=> fix: Incorrect value of clientTLSPolicy from ComputeBackendService

config/tests/samples/create/harness.go
It isn't (normally) an error, we're just waiting
for the webhook to start.
=> tests: clearer log when waiting for webhook

mockgcp/common/fields/updatemask.go
It just wasn't in the initial list.
=> mockgcp: support int32 in update_mask

config/samples/resources/iampolicy/external-project-level-policy/iam_v1beta1_iampolicy.yaml, config/samples/resources/iampolicy/project-level-policy/iam_v1beta1_iampolicy.yaml, config/samples/resources/privilegedaccessmanagerentitlement/folder-level-entitlement/privilegedaccessmanager_v1beta1_privilegedaccessmanagerentitlement.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/iam/iampolicy.md, scripts/generate-google3-docs/resource-reference/generated/resource-docs/privilegedaccessmanager/privilegedaccessmanagerentitlement.md
In sample yamls, quote the strings that contain colon (':') followed by only env var(s). This is to avoid misleading error messages like below:
```
error creating resource: PrivilegedAccessManagerEntitlement.privilegedaccessmanager.cnrm.cloud.google.com 
"uwewbiibxqnycqcqinjtavlwhssvbdgloygejrxlbolmhkgx" is invalid: 
spec.approvalWorkflow.manualApprovals.step.approvers.principals: Invalid value: "object": 
spec.approvalWorkflow.manualApprovals.step.approvers.principals in body must be of type string: "object"
```
In the folder-level-entitlement sample, while the principals list was correctly configured, because the value of `GROUP_EMAIL` was empty, the value of `spec.approvalWorkflow.manualApprovals.step.approvers.principals` became `- group:`, and APIserver considered it an object …
=> Avoid misleading error message when a string contains colon and followed by only env vars

config/tests/samples/create/harness.go
If there's a port conflict, the webhook may not
start.  Don't wait forever in this case.
=> tests: set time limit for webhook start

pkg/controller/direct/sql/sqlinstance_defaults.go
Otherwise, the controller will always detect a diff and try to update on each re-reconcile.
=> fix: Use actual sqlinstance location preference if not specified

.github/workflows/lint.yaml
We seem to be hitting the timeout, particularly with the go update.
=> tests: increase timeout for lint job

pkg/controller/direct/privilegedaccessmanager/entitlement_controller.go, pkg/controller/direct/privilegedaccessmanager/util.go, pkg/controller/direct/privilegedaccessmanager/util_test.go
AccessControlEntry.Principals slices in PrivilegedAccessManagerEntitlement will be returned with an unexpected, random order, and reflect.DeepEqual() will take entry order into consideration when doing comparison. So we need to sort the AccessControlEntry.Principals slices before compare the actual state and the desired state of a PrivilegedAccessManagerEntitlement.
Verified that the change of order of principals in EligibleUsers and ApprovalWorkflow.ManualApprovals.Steps.Approvers won't trigger an update call to the API.
=> Sort the AccessControlEntry slice in PrivilegedAccessManagerEntitlement before diffing

docs/develop-resources/deep-dives/2-define-apis.md
Super minor, but this caused an issue for me when copy/pasting the command into my terminal, editing, and attempting to run it.
The error I got was:
```
`--proto-resource` is required
exit status 1
```
=> fix: Remove whitespace from docs command

operator/scripts/generate-image-configmap/main.go
We use a structured logger from the context,
and we also avoid calling Fatalf/panic.
=> chore: clean up logging in configmap tool

pkg/test/resourcefixture/testdata/basic/run/v1beta1/runservice/runservicemulticontainer/create.yaml, pkg/test/resourcefixture/testdata/basic/run/v1beta1/runservice/runservicemulticontainer/update.yaml
Fixes the failed runservicemulticontainer test (b/375678794).
When getting the underlying Cloud Run service resource in runservicemulticontainer test, `launchStage` value was updated to `GA` in the GET response. (https://cloud.google.com/run/docs/reference/rest/v2/projects.locations.services) So during the reconciliation of the testNoChange step(s) in dynamic test, the value of `launchStage` is `GA` in the live state and is `BETA` in the desired state, and this caused an unexpected diff and triggers an unexpected API call.
This behavior comes from the underlying Cloud Run API so we can't really fix it. To resolve the failed test, the workaround is to match the `launchStage` in the test case with the `launchStage` returned by the Cloud Run API. 
- [N/A] Run `make ready-pr` to ensure this …
=> Fix the unexpected diff in runservicemulticontainer test

config/installbundle/base/kustomization.yaml
This causes it to be included twice, which is an error.
=> fix: don't include unmanageddetector in base

operator/config/crd/bases/customize.core.cnrm.cloud.google.com_controllerreconcilers.yaml, operator/config/crd/bases/customize.core.cnrm.cloud.google.com_namespacedcontrollerreconcilers.yaml, operator/pkg/apis/core/customize/v1alpha1/controllerreconciler_types.go, operator/pkg/controllers/configconnector/configconnector_controller.go, operator/pkg/controllers/configconnectorcontext/configconnectorcontext_controller.go, operator/pkg/controllers/utils.go, operator/pkg/preflight/upgrade.go
Generated file.
Adding cluster mode changes.
Updated version for cluster mode.
Skipping version check on dev mode controllers.
Make pprof support case insensitive.
Allows you to enable pprof and use it as follows.
apiVersion: customize.core.cnrm.cloud.google.com/v1alpha1
kind: NamespacedControllerReconciler
metadata:
name: cnrm-controller-manager 
namespace: kcc-test
spec:
pprof:
support: all
port: 1234
kubectl port-forward cnrm-controller-manager-<id> -n cnrm-system 1234
curl http://localhost:1234/debug/pprof/heap > heap.outheap.out
Fixes #
=> Configure pprof on controller-manager.

docs/releasenotes/release-1.125.md
=> docs: Update release notes 1.125

apis/refs/v1beta1/computerefs.go, mockgcp/mockcloudbuild/workerpool.go, pkg/controller/direct/cloudbuild/workerpool_controller.go, pkg/controller/direct/dataflow/refs.go, pkg/controller/direct/networkconnectivity/refs.go, pkg/controller/direct/redis/cluster/refs.go, pkg/controller/direct/sql/sqlinstance_resolverefs.go, pkg/controller/direct/workstations/workstationcluster_normalize.go, pkg/test/resourcefixture/testdata/basic/cloudbuild/v1beta1/cloudbuildworkerpool/_http.log
- **ComputeNetworkRef: split into ref and ID**
- **mockgcp: CloudBuildWorkerPool: normalize peered network link to use project number**
=> Refactor CloudNetworkRef to use Ref / ID split pattern

docs/develop-resources/deep-dives/4-add-controller.md, docs/develop-resources/scenarios/migrate-tf-resource-beta.md
Use new fuzzer example; context: https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/3102
=> docs: use new fuzzer example

docs/develop-resources/deep-dives/2-define-apis.md
Following the tooling changes in https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3023, this PR updates the guide.
=> docs: update guide on type generation

operator/pkg/preflight/configconnectorcontextchecker.go, operator/pkg/preflight/configconnectorcontextchecker_test.go
Create a CCC object with invalid GSA.
```
$ cat ~/tmp/ccc.yaml 
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata:
name: configconnectorcontext.core.cnrm.cloud.google.com
namespace: config-control
spec:
googleServiceAccount: foo@bar.com
$ k apply -f ~/tmp/ccc.yaml 
configconnectorcontext.core.cnrm.cloud.google.com/configconnectorcontext.core.cnrm.cloud.google.com created
```
CCC Status:
```
$ k describe -f ~/tmp/ccc.yaml 
(...)
Spec:
Google Service Account:  foo@bar.com
Status:
Errors:
error during reconciliation: invalid GoogleServiceAccount format for "foo@bar.com"
Healthy:  false
Events:
Type     Reason        Age                From                               Message
----     ------        ----               ---- …
```
=> Validate format of GoogleServiceAccount in CCC

dev/tools/controllerbuilder/template/controller/controller.go
Fix naming mismatch between
https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/93278d704875450549554368b37a5742f8c29856/dev/tools/controllerbuilder/template/controller/controller.go#L234
and 
https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/93278d704875450549554368b37a5742f8c29856/dev/tools/controllerbuilder/template/apis/types.go#L70
=> tools: fix naming mismatch on ObservedState in template

pkg/controller/direct/protoutils.go, pkg/controller/direct/securesourcemanager/instance_controller.go
We can keep the desired state in proto.
=> chore: refactor SecureSourceManagerInstance to work in proto

pkg/test/resourcefixture/testdata/resourceid/userspecifiedresourceid/create.yaml, pkg/test/resourcefixture/testdata/resourceid/userspecifiedresourceid/update.yaml
Add back the projectRef, which was likely removed unintentionally in a previous PR https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2814.
Fixes #3170
=> test: fix TestAcquire/bigquery/resourceid-userspecifiedresourceid

dev/tools/controllerbuilder/cmd/root.go, dev/tools/controllerbuilder/pkg/commands/generatecontroller/generatecontrollercommand.go, docs/develop-resources/deep-dives/4-add-controller.md
Unify the scifi cmd names and the code structure. This is a prep for the next PR.
Previous:  
`go run . add ...` 
`go run . generate-type`
`go run . generate-map` 
Current: 
`go run . generate-controller ...` 
`go run . generate-type`
`go run . generate-map`
=> chore: restructure scifi controller cmd

pkg/test/resourcefixture/contexts/register.go
Going off of #3162 , let's add a simple exp backoff to the delete. The underlying 1P API calls  may benefit from this. Ideally we'd get the retries for free from the testing framework but starting off here for now.
=> tests: simple backoff on direct dynamic

pkg/controller/dynamic/dynamic_controller_integration_test.go
Fixes dynamic tests:
basic-computefirewallpolicyrule-egress-full-direct
basic-computefirewallpolicyrule-ingress-full-direct
```
--- PASS: TestCreateNoChangeUpdateDelete (0.16s)
--- PASS: TestCreateNoChangeUpdateDelete/compute (0.00s)
--- PASS: TestCreateNoChangeUpdateDelete/compute/basic-computefirewallpolicyrule-egress-full-direct (303.03s)
PASS
{"severity":"info","timestamp":"2024-11-13T09:43:57.826Z","msg":"Stopping and waiting for non leader election runnables"}
{"severity":"info","timestamp":"2024-11-13T09:43:57.826Z","msg":"Stopping and waiting for leader election runnables"}
{"severity":"info","timestamp":"2024-11-13T09:43:57.826Z","msg":"Stopping and waiting for caches"}
{"severity":"info","timestamp":"2024-11-13T09:43:57.827Z","msg":"Stopping and waiting for webhooks"} …
```
=> tests: Skip checking for changes in reference field

pkg/clients/generated/README.md, scripts/unit-test.sh, scripts/validate-prereqs.sh
This PR does two things
-  add a announcement to guide users using the direct api and dynamic client instead of the problematic one. 
-  skip the old lib from the KCC presubmit and stop updating it since then.
Discussed with Walter and Justin separately offlilne.  I think this is the agreement we get (correct me if I missed anything).  
More context in #3037
=> feat: migrate the problematic go-client

tests/e2e/testdata/scenarios/fields/gkehubfeaturemembership/set_unset/_http00.log, tests/e2e/testdata/scenarios/fields/gkehubfeaturemembership/set_unset/_http01.log, tests/e2e/testdata/scenarios/fields/gkehubfeaturemembership/set_unset/_http02.log, tests/e2e/testdata/scenarios/fields/gkehubfeaturemembership/set_unset/_http03.log, tests/e2e/testdata/scenarios/fields/gkehubfeaturemembership/set_unset/_http04.log, tests/e2e/testdata/scenarios/fields/gkehubfeaturemembership/set_unset/_http05.log, tests/e2e/testdata/scenarios/fields/gkehubfeaturemembership/set_unset/_object00.yaml, tests/e2e/testdata/scenarios/fields/gkehubfeaturemembership/set_unset/_object01.yaml, tests/e2e/testdata/scenarios/fields/gkehubfeaturemembership/set_unset/_object02.yaml, tests/e2e/testdata/scenarios/fields/gkehubfeaturemembership/set_unset/_object03.yaml, tests/e2e/testdata/scenarios/fields/gkehubfeaturemembership/set_unset/_object04.yaml, tests/e2e/testdata/scenarios/fields/gkehubfeaturemembership/set_unset/_object05.yaml, tests/e2e/testdata/scenarios/fields/gkehubfeaturemembership/set_unset/script.yaml
https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2027 got closed unexpectedly
Creating a new PR
=> Generate set-unset golden output for gkehubfeaturemembership

mockgcp/mockserviceusage/serviceusagev1beta1.go, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/fullybigquerydataset-direct/_http.log, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/fullybigquerydataset-direct/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/fullybigquerydataset-direct/update.yaml, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/fullybigquerydataset/_http.log, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/fullybigquerydataset/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerydataset/fullybigquerydataset/update.yaml
TestCreateNoChangeUpdateDelete/bigquery/fullybigquerydataset and TestCreateNoChangeUpdateDelete/bigquery/fullybigquerydataset-direct is failling in our periodic testgrid.
`$ go test -v -tags=integration ./pkg/controller/dynamic/ -run TestCreateNoChangeUpdateDelete/bigquery/basic-fullybigquerydataset`
```
Error: Update call failed: error setting policy: error applying changes: summary: Error setting IAM policy for KMS CryptoKey "projects/cnrm-test-u4u89p82eb10y2be/locations/us/keyRings/kmskeyring-q3rgzenwbr2ehbi/cryptoKeys/kmscryptokey-q3rgzenwbr2ehbi": googleapi: Error 400: Service account bq-753194153036@bigquery-encryption.iam.gserviceaccount.com does not exist.,
```
This P4SA is created by the service team.
```
--- PASS: TestCreateNoChangeUpdateDelete (0.22s)
--- PASS: …
```
=> fix:TestCreateNoChangeUpdateDelete/bigquery

dev/tools/controllerbuilder/generate.sh, pkg/controller/direct/workstations/cluster_mappings.go, pkg/controller/direct/workstations/config_mappings.go, pkg/controller/direct/workstations/shared_mappings.go
Forgot to rename some of the shared mapping functions previously (had meant to do that in https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3159). So, renamed and fixed the shared mapping function names in this commit also.
Also, for now, using `_Alpha` to distinguish between shared mapping functions that act on the v1alpha1 API vs the "normal" shared mapping functions that act on the v1beta1 API, but they are functionally equivalent. Will delete these functions and switch over to the "normal", non-`_Alpha` (v1beta1) version ones upon promoting WorkstationConfig to v1beta1.
=> feat: Generate and fixup WorkstationConfig mapping functions

pkg/test/utils.go, tests/e2e/unified_test.go
The go formatting of t.Fatalf and t.Errorf is not very obvious.
Manually change the messages so that they stand out more.
=> tests: log test failures with FAIL

dev/tools/controllerbuilder/pkg/commands/generatetypes/generatetypescommand.go, dev/tools/controllerbuilder/scaffold/apis.go, dev/tools/controllerbuilder/scaffold/controller.go, dev/tools/controllerbuilder/template/apis/identity.go, dev/tools/controllerbuilder/template/apis/refs.go, dev/tools/controllerbuilder/template/controller/controller.go
Improvements:
- Separate resource Identity and external Ref
- Added in-line comments to guide the contributors on the functionality and expected behaviors. 
- Make the variable names shorter. e.g. `SecretManagerSecretVersion` --> `SecretVersion`
- Applied some best practice like introducing the CompareProtoMessage
Fixes:
- Remove `parent` from the reference API to avoid the json tag hack, and potential client-go unstructured parsing issues.  
- Parent and Identity should be read-only for adapter.
=> chore: improvements around Direct identity and external  

apis/bigqueryanalyticshub/v1alpha1/dataexchange_types.go
Looks like we don't consider CRD tags
per version.
=> chore: fix inconsistent tags on types

pkg/controller/direct/compute/targettcpproxy/targettcpproxy_controller.go
Refactor the direct controller code, to prevent nil pointer issue when there's no UPDATE call. Surprisingly the presubmit tests didn't catch this...
error message:
```
dynamic_controller_integration_test.go:353: reconcile for ComputeTargetTCPProxy:ytcsjujcrrraiyy/computetargettcpproxy-ytcsjujcrrraiyy took 231.481942ms, result was ({false 0s}, INTERNAL ERROR: panic: observed a panic: runtime error: invalid memory address or nil pointer dereference
/home/prow/go/src/cnrm.googlesource.com/cnrm/pkg/execution/builtin.go:40 +0x45
panic({0x5fbf340?, 0xb0ea990?})
/home/prow/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.5.linux-amd64/src/runtime/panic.go:770 +0x132
cloud.google.com/go/compute/apiv1.(*Operation).Done(...)
/home/prow/go/pkg/mod/cloud.google.com/go/compute@v1.28.1/apiv1/operations.go: …
```
=> fix: Fix potential nil pointer issue in ComputeTargetTCPProxy direct update operation

Makefile
=> chore: skip update client in ready-pr

dev/tools/controllerbuilder/generate-proto.sh, dev/tools/controllerbuilder/generate.sh
This ensures that we have one version of the googleapis, which would otherwise get confusing,  for example if the mocks had  fields that the clients did not.
=> chore: controllergen uses pinned googleapi version

mockgcp/apis/mockgcp/cloud/apigee/v1/service.proto
When trying to generate protos, got the following error
```
--grpc-gateway_out: ProjectsServer.ProvisionOrganizationProject: project
is a protobuf message type. Protobuf message types cannot be used as
path parameters, use a scalar value type (such as string) instead:
```
It seems to be due to a naming conflict around "project" which is allowed in the JSON API definition, but causes issues when converting. Probably the easiest fix is to manually make this update.
=> fix: Update apigee proto definition to fix naming conflict

dev/tasks/download-e2e-logs
This is helpful when the test is still running.
=> chore: specify run for download-e2e-logs

pkg/controller/dynamic/dynamic_controller_integration_test.go, pkg/test/resourcefixture/contexts/register.go, pkg/test/resourcefixture/contexts/sql_context.go
This is should longer be necessary after waiting for LRO completion: https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3034/commits/d9baf0bcffb932e8c8516117aec591c54790d437
=> fix: Remove wait after SQLInstance periodic test steps

pkg/controller/direct/privilegedaccessmanager/entitlement_controller.go
The deletion of PrivilegedAccessManagerEntitlement resource is stuck if the underlying GCP resource doesn't exist. But this deletion should go through successfully. Ignoring the resource not found error in the deletion fixes this error.
=> Ignore NotFound error when deleting PrivilegedAccessManagerEntitlement

Makefile
Save us $$$ time on `make ready-pr` and `make manifests`
=> chore: skip dcl code-generation in read-pr

dev/tasks/install-tools
Otherwise if the docker container has not been updated in a while,
the installation fails.
=> chore: add apt-get update to install-tools

apis/bigqueryanalyticshub/v1alpha1/dataexchange_reference.go, apis/memorystore/v1alpha1/instance_reference.go
I think https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3233 wasn't synced to the most recent changes and we forgot one old reference to the an old style `ResolveProject`
=> fix: update to use new ResolveProject func

tests/e2e/testdata/scenarios/fields/management/logging/logmetric/set-zero/_export0.yaml, tests/e2e/testdata/scenarios/fields/management/logging/logmetric/set-zero/_export1.yaml, tests/e2e/testdata/scenarios/fields/management/logging/logmetric/set-zero/_http00.log, tests/e2e/testdata/scenarios/fields/management/logging/logmetric/set-zero/_http00.log.real, tests/e2e/testdata/scenarios/fields/management/logging/logmetric/set-zero/_http01.log, tests/e2e/testdata/scenarios/fields/management/logging/logmetric/set-zero/_http01.log.real, tests/e2e/testdata/scenarios/fields/management/logging/logmetric/set-zero/_object00.yaml, tests/e2e/testdata/scenarios/fields/management/logging/logmetric/set-zero/_object01.yaml, tests/e2e/testdata/scenarios/fields/management/logging/logmetric/set-zero/script.yaml
Adds a scenario test for setting 0 for native types for the LoggingLogMetric.
A few call outs
- test was hand written
- no issues were detected
Note in the future we will want tooling that can generate these tests for us and run against the direct controllers. To that end, both the filler mechanism in the random filler (https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3151) and the field analysis tool (https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2326/) will help.
=> tests: set 0 llm

config/tests/samples/create/harness.go, mockgcp/mockworkstations/service.go, mockgcp/mockworkstations/workstations.go, pkg/controller/direct/workstations/config_controller.go, pkg/test/resourcefixture/testdata/basic/workstations/workstationcluster/workstationcluster-full/_http.log, pkg/test/resourcefixture/testdata/basic/workstations/workstationcluster/workstationcluster-minimal/_http.log, pkg/test/resourcefixture/testdata/basic/workstations/workstationconfig/workstationconfig-full/_generated_object_workstationconfig-full.golden.yaml, pkg/test/resourcefixture/testdata/basic/workstations/workstationconfig/workstationconfig-full/_http.log, pkg/test/resourcefixture/testdata/basic/workstations/workstationconfig/workstationconfig-minimal/_http.log
This PR depends on https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3265, would suggest reviewing by commit.
Also, there are a couple of minor quirks with this resource:
- Seems impossible to remove annotations / labels, so adjusted the test to make the updates additive.
- allowedPorts field is not yet supported in the proto.
=> feat: Add mockgcp for WorkstationConfig

dev/tools/controllerbuilder/pkg/commands/generatecontroller/generatecontrollercommand.go
The behavior seems to have changed, and help text was not updated.
=> fix: Update help text for controller-builder command

scripts/shared-vars-public.sh
Currently the post submits are failing for discovery engine with:
"
> dynamic_controller_integration_test.go:235: reconcile for DiscoveryEngineDataStore:4pvzd6wll2p7dby/datastore-4pvzd6wll2p7dby took 364.66735ms, result was ({false 0s}, Update call failed: getting discoveryengine datastore "projects/<REDACTED>" from gcp: googleapi: Error 403: Discovery Engine API has not been used in project <REDACTED> before or it is disabled. Enable it by visiting ...
"
=> chore: enable disco api for tests

operator/config/gke-addon/manager_patch.yaml
This is required by GKE add-on
=> chore: turn on readOnlyRootFilesystem for GKE add-on release'

mockgcp/apply-proto-patches.sh, mockgcp/tools/patch-proto/go.mod, mockgcp/tools/patch-proto/go.sum, mockgcp/tools/patch-proto/main.go
Use this new capability to codify the Apigee proto hack that was originally made (manually) in https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3183.
This addresses the suggested changes in https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3183#pullrequestreview-2447281185 and https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3262#discussion_r1861004371.
=> feat: Add capability to replace proto contents in patch-proto

pkg/controller/direct/gkehub/mappings.go
Super small fix to add the `Version` field to the FromProto conversion.
=> fix: add version

tests/e2e/normalize.go, tests/e2e/testdata/scenarios/fields/management/bigquery/dataset/set_unset/_export5.yaml, tests/e2e/testdata/scenarios/fields/management/bigquery/dataset/set_unset/_export6.yaml, tests/e2e/testdata/scenarios/fields/management/bigquery/dataset/set_unset/_export7.yaml, tests/e2e/testdata/scenarios/fields/management/bigquery/dataset/set_unset/_http00.log, tests/e2e/testdata/scenarios/fields/management/bigquery/dataset/set_unset/_http01.log, tests/e2e/testdata/scenarios/fields/management/bigquery/dataset/set_unset/_http02.log, tests/e2e/testdata/scenarios/fields/management/bigquery/dataset/set_unset/_http03.log, tests/e2e/testdata/scenarios/fields/management/bigquery/dataset/set_unset/_http04.log, tests/e2e/testdata/scenarios/fields/management/bigquery/dataset/set_unset/_http05.log, tests/e2e/testdata/scenarios/fields/management/bigquery/dataset/set_unset/_http06.log, tests/e2e/testdata/scenarios/fields/management/bigquery/dataset/set_unset/_http07.log, tests/e2e/testdata/scenarios/fields/management/bigquery/dataset/set_unset/_object00.yaml, tests/e2e/testdata/scenarios/fields/management/bigquery/dataset/set_unset/_object01.yaml, tests/e2e/testdata/scenarios/fields/management/bigquery/dataset/set_unset/_object02.yaml, tests/e2e/testdata/scenarios/fields/management/bigquery/dataset/set_unset/_object03.yaml, tests/e2e/testdata/scenarios/fields/management/bigquery/dataset/set_unset/_object04.yaml, tests/e2e/testdata/scenarios/fields/management/bigquery/dataset/set_unset/_object05.yaml, tests/e2e/testdata/scenarios/fields/management/bigquery/dataset/set_unset/_object06.yaml, tests/e2e/testdata/scenarios/fields/management/bigquery/dataset/set_unset/_object07.yaml, tests/e2e/testdata/scenarios/fields/management/bigquery/dataset/set_unset/script.yaml
This PR adds a scenario test to log the behavior of the BigQueryDataset terraform controller when updating the resource with fields unset
- Terraform finds the existing values of the unset field and maintain the value.
This test will later be used to verify the behavior of direct controller being backward compatible after https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3125 is merged.
=> test:add a scenario test for unset fields in bigquerydataset

dev/tools/controllerbuilder/pkg/commands/updatetypes/updatetypescommand.go, dev/tools/controllerbuilder/pkg/typeupdater/insertfield-ast.go, dev/tools/controllerbuilder/pkg/typeupdater/insertfield-gemini.go, dev/tools/controllerbuilder/pkg/typeupdater/insertmessage-ast.go, dev/tools/controllerbuilder/pkg/typeupdater/insertmessage-gemini.go, dev/tools/controllerbuilder/pkg/typeupdater/typeupdater.go, dev/tools/controllerbuilder/update.sh, docs/develop-resources/scenarios/new-field.md
- commit 1: Refactor the typeupdater tool and fix some minor bugs.
- commit 2: Ensure that when the parent proto message of the field to be inserted matches 2 Go structs (`Spec` and `ObservedState`), the field is inserted into the appropriate struct.
=> tool: correctly insert field into Spec or ObservedState.

apis/compute/v1beta1/targettcpproxy_reference.go, pkg/controller/direct/compute/targettcpproxy/targettcpproxy_controller.go
Fixes b/380362493
Address https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3236#discussion_r1853057354
Log error when update is not supported(by API), but fields get updated by user. However, if this happens, the resource will remain in error state. The only way to fix it might be to delete the resource and recreate a new one. Users won't be able to just revert the change.
I should also add a warning message that in our public doc, this will be done in #3227 
As mentioned in above discussion, there're several other ways to handle this:
1. GCP approach: do nothing on our side, and let the GCP API to handle the potential error(Users won't be able to revert the change too)
2. TF approach: trigger a `forceNew` feature to delete the old resource and create a new one with …
=> fix: Log error when update is not supported for regional TCP Proxy

dev/tools/controllerbuilder/template/controller/controller.go
Even when adopting resources, we want to update status.
=> fix: Update resource status even if no GCP fields are updated

dev/tools/controllerbuilder/pkg/codegen/typegenerator.go
This provides an easier way to track the mapping between generate Go fields and their corresponding proto fields. I think we should start tracking this information.
/cc @jasonvigil @yuwenma
=> tool: add annotation to the generated Go fields with their corresponding proto fields

pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicacmgkehubfeaturemembership/_generated_object_basicacmgkehubfeaturemembership.golden.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicacmgkehubfeaturemembership/_http.log, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicacmgkehubfeaturemembership/update.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basiccsaugkehubfeaturemembership/_generated_object_basiccsaugkehubfeaturemembership.golden.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basiccsaugkehubfeaturemembership/_http.log, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basiccsaugkehubfeaturemembership/create.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basiccsaugkehubfeaturemembership/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basiccsaugkehubfeaturemembership/update.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullacmgkehubfeaturemembership/_generated_object_fullacmgkehubfeaturemembership.golden.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullacmgkehubfeaturemembership/_http.log, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullacmgkehubfeaturemembership/create.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullacmgkehubfeaturemembership/update.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullcsaugkehubfeaturemembership/_generated_object_fullcsaugkehubfeaturemembership.golden.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullcsaugkehubfeaturemembership/_http.log, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullcsaugkehubfeaturemembership/create.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullcsaugkehubfeaturemembership/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullcsaugkehubfeaturemembership/update.yaml
Remove version filed if auto-upgrade is turned on.
=> tests: csau test

tests/e2e/script_test.go
Maybe introduced from recent golang change.
=> fix:  golang non-constant format string

mockgcp/mockgkehub/gkehubfeature.go, pkg/controller/direct/gkehub/featuremembership_controller.go, tests/e2e/testdata/scenarios/gkehubfeaturemembership/update_single_membership/_http00.log, tests/e2e/testdata/scenarios/gkehubfeaturemembership/update_single_membership/_http01.log, tests/e2e/testdata/scenarios/gkehubfeaturemembership/update_single_membership/_http02.log, tests/e2e/testdata/scenarios/gkehubfeaturemembership/update_single_membership/_http03.log, tests/e2e/testdata/scenarios/gkehubfeaturemembership/update_single_membership/_http04.log, tests/e2e/testdata/scenarios/gkehubfeaturemembership/update_single_membership/_http05.log, tests/e2e/testdata/scenarios/gkehubfeaturemembership/update_single_membership/_http06.log, tests/e2e/testdata/scenarios/gkehubfeaturemembership/update_single_membership/_http07.log, tests/e2e/testdata/scenarios/gkehubfeaturemembership/update_single_membership/_object00.yaml, tests/e2e/testdata/scenarios/gkehubfeaturemembership/update_single_membership/_object01.yaml, tests/e2e/testdata/scenarios/gkehubfeaturemembership/update_single_membership/_object02.yaml, tests/e2e/testdata/scenarios/gkehubfeaturemembership/update_single_membership/_object03.yaml, tests/e2e/testdata/scenarios/gkehubfeaturemembership/update_single_membership/_object04.yaml, tests/e2e/testdata/scenarios/gkehubfeaturemembership/update_single_membership/_object05.yaml, tests/e2e/testdata/scenarios/gkehubfeaturemembership/update_single_membership/_object06.yaml, tests/e2e/testdata/scenarios/gkehubfeaturemembership/update_single_membership/_object07.yaml, tests/e2e/testdata/scenarios/gkehubfeaturemembership/update_single_membership/script.yaml
Before, the controller patches the whole GKEHub Feature resource, which may contains multiple membershipSpecs.
This broad update is not a problem for the associated membership, but would be a problem for other non-associated ones(created by other means) when there are mutually exclusive fields like management and version. The two fields are mutually exclusive in the request, but not in the GET response. The gkehub server defaults the version field if management field is set as automatic(they are both present in the GET response).  Thus, during the patch, the controller sends the request with what it gets from the server for non-associated memberships, which would get rejected by the server because both field are present.
The gkehub server has special logic to prevent other memberships …
=> fix: only patch membership config for one membership

scripts/generate-google3-docs/resource-reference/generated/resource-docs/gkehub/gkehubmembership.md, scripts/generate-google3-docs/resource-reference/templates/gkehub_gkehubmembership.tmpl
This is a small fix to point to the right references docs.
=> docs:fix: point to the right ref

apis/bigqueryanalyticshub/v1beta1/dataexchange_reference.go, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_bigqueryanalyticshublistings.bigqueryanalyticshub.cnrm.cloud.google.com.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/bigqueryanalyticshub/bigqueryanalyticshublisting.md
I think https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3398 upset the `make manifest` for this resource.
=> regen: fix head

apis/bigqueryanalyticshub/v1alpha1/listing_types.go, apis/bigqueryanalyticshub/v1beta1/listing_types.go, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_bigqueryanalyticshublistings.bigqueryanalyticshub.cnrm.cloud.google.com.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/bigqueryanalyticshub/bigqueryanalyticshublisting.md, tests/apichecks/testdata/exceptions/shortnames.txt
=> fix: add shortnames

tests/e2e/normalize.go
For reasons unclear, operations emit `done: false`
and `metadata.cancelRequested: false`.
This seems to violate the normal behaviour of proto bool fields
with implicit presence.
Easiest just to normalize away the GCP responses that are very hard
to mock; these values should be semantically equal anyway.
=> tests: remove LRO false fields

dev/tools/controllerbuilder/pkg/codegen/mappergenerator.go
If there's a field with the same name but different case,
add the near-miss to the output.
=> tooling: add hints when we can't match a field

dev/tools/controllerbuilder/pkg/codegen/typegenerator.go
Use distinct annotation prefixes for proto messages vs fields.
The special case is that when a proto message is also a field of another proto message.
Before this PR
```
// +kcc:proto=google.cloud.bigquery.datatransfer.v1.ScheduleOptionsV2
type ScheduleOptionsV2 struct {
// ... fields ...
}
type TransferConfig struct {
// +kcc:proto=google.cloud.bigquery.datatransfer.v1.TransferConfig.schedule_options_v2
ScheduleOptionsV2 *ScheduleOptionsV2 `json:"scheduleOptionsV2,omitempty"`
}
```
After this PR
```
// +kcc:proto=google.cloud.bigquery.datatransfer.v1.ScheduleOptionsV2
type ScheduleOptionsV2 struct {
// ... fields ...
}
type TransferConfig struct {
// +kcc:proto:field=google.cloud.bigquery.datatransfer.v1.TransferConfig.schedule_options_v2
ScheduleOptionsV2 *ScheduleOptionsV2 …
```
=> tool: use a different annotation prefix for go fields

apis/bigqueryanalyticshub/v1alpha1/listing_reference.go
Forgot to actually record the dataExchangeID in a parent for the listing reference. The dynamic post submit caught this but only in `testDriftDetection` for some reason.
```
$     go test -v -tags=integration ./pkg/controller/dynamic/ -timeout 1600s -test.count=1 -test.run 'TestCreateNoChangeUpdateDelete/bigqueryanalyticshub/basic-bigqueryanalyticshublisting-base'  2>&1 
...
testreconciler.go:187: reconcile for BigQueryDataset:67ynb4sojpz6wri/bigquerydataset67ynb4sojpz6wri took 493.033563ms, result was ({false 5m48.428911865s}, <nil>)
--- PASS: TestCreateNoChangeUpdateDelete (0.23s)
--- PASS: TestCreateNoChangeUpdateDelete/bigqueryanalyticshub (0.00s)
--- PASS: TestCreateNoChangeUpdateDelete/bigqueryanalyticshub/basic-bigqueryanalyticshublisting-base (83.60s)
PASS
...
ok …
```
=> fix: listing ref

scripts/generate-google3-docs/resource-reference/generated/resource-docs/workstations/workstation.md, scripts/generate-google3-docs/resource-reference/generated/resource-docs/workstations/workstationconfig.md, scripts/generate-google3-docs/resource-reference/templates/workstations_workstation.tmpl, scripts/generate-google3-docs/resource-reference/templates/workstations_workstationconfig.tmpl
Accidentally placed the quotation mark in the wrong position in https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3447
=> fix: Actually fix workstation docs

pkg/controller/direct/firestore/firestoredatabase_controller.go, pkg/controller/direct/firestore/firestoredatabase_defaults.go, pkg/controller/direct/firestore/firestoredatabase_mappings.go
Seems there were quite a few fields added to FirestoreDatabase since it was originally implemented.
=> feat: Add fuzz test for FirestoreDatabase

.golangci.yaml, config/tests/samples/create/samples.go, operator/pkg/test/controller/manifest.go, operator/scripts/generate-image-configmap/main.go, operator/scripts/utils/yaml.go, pkg/cli/cmd/apply/yamlresource/yaml_to_unstructured_resource.go, pkg/cli/cmd/printresources/printer/printer.go, pkg/cli/outputsink/filename/filename.go, pkg/cli/outputsink/sink_test.go, pkg/cli/stream/yamlstream.go, pkg/controller/dynamic/common_test_functions.go, pkg/crd/crdloader/crdloader.go, pkg/snippet/snippetgeneration/snippetgeneration.go, pkg/test/resourcefixture/resourcefixture.go, pkg/test/unstructured.go, pkg/test/yaml/yaml.go, scripts/generate-cnrm-cluster-roles/main.go, scripts/generate-crds/main.go, scripts/generate-gvks/main.go, scripts/parse-crds/parse-crds.go, scripts/resource-autogen/servicemapping/servicemappingloader/servicemappingloader.go
Using `depguard` to highlight the imports we don't want to use. I will `//nolint` existing usages and this will prevent future imports.
=> lint: add depguard

dev/tools/controllerbuilder/pkg/commands/generatecontroller/generatecontrollercommand.go, dev/tools/controllerbuilder/pkg/commands/generatedirectreconciler/command.go, dev/tools/controllerbuilder/scaffold/controller.go, docs/develop-resources/deep-dives/4-add-controller.md
=> feat: Simplify the controller registration step via tooling 

dev/tools/controllerbuilder/cmd/root.go, dev/tools/controllerbuilder/pkg/commands/apply/apply.go, dev/tools/controllerbuilder/pkg/io/cache.go, dev/tools/controllerbuilder/pkg/io/comments.go, dev/tools/controllerbuilder/pkg/io/replace.go
This go file merge cannot handle comments well because it uses ast which does not treat comment as first citizen (comment is inserted by its relative position in the file so refactoring the go file place all comments in the wrong place)  
This PR drops the comments in the updated file. I have some plans to add back the comments, so I keep the comment Pos code in this PR.
=> feat: add  cmd to merge two go files (struct only)

.golangci.yaml
Now that we have depguard we can further lint packages we'd rather avoid using in our project(s).
Fixes https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/2389
=> ci: lint more yaml

mockgcp/tools/gapic/main.go, mockgcp/tools/gapic/pkg/openapi/openapi.go
We're parsing "strictly" (errors for unknown fields),
and we hadn't encountered this field before.
=> mockgcp: tolerate deprecated field in swagger

scripts/resource-autogen/servicemapping/embed/generated/main/assets_generate_fallback.go
We need a main even if the integration build tag is not specified.
This enables go build ./...
Our placeholder just panics if run.
=> chore: hack to workaround broken go build

apis/workstations/v1alpha1/types.generated.go, dev/tools/controllerbuilder/pkg/codegen/typegenerator.go, dev/tools/controllerbuilder/pkg/commands/generatetypes/generatetypescommand.go, dev/tools/controllerbuilder/pkg/typeupdater/typeupdater.go
The ObservedState structs contain the output-only fields of the original messages, and are intended to be used in the KRM status. The types intended for the KRM spec no longer contain the output-only fields.
This PR depends on https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3337
=> feat: Generate "ObservedState" structs in type generator

config/tests/samples/create/harness.go, mockgcp/mockapigee/organization.go, mockgcp/mockapigee/service.go, mockgcp/mockserviceusage/knownservices.go, pkg/test/resourcefixture/testdata/basic/apigee/v1beta1/apigeeorganization/_generated_object_apigeeorganization.golden.yaml, pkg/test/resourcefixture/testdata/basic/apigee/v1beta1/apigeeorganization/_http.log, pkg/test/resourcefixture/testdata/basic/apigee/v1beta1/apigeeorganization/create.yaml, pkg/test/resourcefixture/testdata/basic/apigee/v1beta1/apigeeorganization/update.yaml, tests/e2e/normalize.go
Mostly rips #2297 so I can use it in `ApigeeEnvironment`s so I can use it in `ApigeeEnvgroupAttachment`s
=> mockgcp: apigeeorganization

dev/tools/controllerbuilder/pkg/commands/generatetypes/generatetypescommand.go
Generate the visited proto messages first before scaffolding the files. Otherwise, the type generator will skip generating proto messages that are already present in the scaffolded files.
This commit was split from https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/2785 to avoid blocking other resources.
=> tool: scaffold files after generating the visited messages

config/tests/samples/create/harness.go, mockgcp/mockcloudidentity/groups.go, mockgcp/mockcloudidentity/groupsmembership.go, mockgcp/mockcloudidentity/service.go, mockgcp/mockcloudidentity/utils.go, pkg/test/resourcefixture/testdata/basic/cloudidentity/v1beta1/cloudidentitymembership/addexpirydatecloudidentitymembership/_generated_object_addexpirydatecloudidentitymembership.golden.yaml, pkg/test/resourcefixture/testdata/basic/cloudidentity/v1beta1/cloudidentitymembership/addexpirydatecloudidentitymembership/_http.log, pkg/test/resourcefixture/testdata/basic/cloudidentity/v1beta1/cloudidentitymembership/addrolecloudidentitymembership/_generated_object_addrolecloudidentitymembership.golden.yaml, pkg/test/resourcefixture/testdata/basic/cloudidentity/v1beta1/cloudidentitymembership/addrolecloudidentitymembership/_http.log, pkg/test/resourcefixture/testdata/basic/cloudidentity/v1beta1/cloudidentitymembership/removerolecloudidentitymembership/_generated_object_removerolecloudidentitymembership.golden.yaml, pkg/test/resourcefixture/testdata/basic/cloudidentity/v1beta1/cloudidentitymembership/removerolecloudidentitymembership/_http.log, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeature/mcifeature/_http.log, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicacmgkehubfeaturemembership/_http.log, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basiccsaugkehubfeaturemembership/_http.log, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/basicpocogkehubfeaturemembership/_http.log, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullacmgkehubfeaturemembership/_http.log, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullcsaugkehubfeaturemembership/_http.log, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/fullpocogkehubfeaturemembership/_http.log, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubfeaturemembership/meshgkehubfeaturemembership/_http.log, pkg/test/resourcefixture/testdata/basic/gkehub/v1beta1/gkehubmembership/_http.log, tests/e2e/normalize.go, tests/e2e/replacements.go, tests/e2e/testdata/scenarios/fields/management/gkehub/featuremembership/set_unset/_http02.log
Adding mocks for cloudidentity membership API
The following tests passed:
E2E_KUBE_TARGET=envtest RUN_E2E=1 E2E_GCP_TARGET=mock go test -test.count=1 -timeout 3600s -v ./tests/e2e -run TestAllInSeries/fixtures/addexpirydatecloudidentitymembership  2>&1 | tee log.cloudidentity
E2E_KUBE_TARGET=envtest RUN_E2E=1 E2E_GCP_TARGET=mock go test -test.count=1 -timeout 3600s -v ./tests/e2e -run TestAllInSeries/fixtures/addrolecloudidentitymembership  2>&1 | tee log.cloudidentity
E2E_KUBE_TARGET=envtest RUN_E2E=1 E2E_GCP_TARGET=mock go test -test.count=1 -timeout 3600s -v ./tests/e2e -run TestAllInSeries/fixtures/removerolecloudidentitymembership  2>&1 | tee log.cloudidentity
=> Adding mocks for cloudidentity membership API

apis/bigquerydatatransfer/v1beta1/transferconfig_types.go, apis/bigquerydatatransfer/v1beta1/types.generated.go, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_bigquerydatatransferconfigs.bigquerydatatransfer.cnrm.cloud.google.com.yaml, dev/tools/controllerbuilder/pkg/codegen/common.go, dev/tools/controllerbuilder/pkg/codegen/typegenerator.go, dev/tools/controllerbuilder/pkg/commands/updatetypes/insertcommand.go, dev/tools/controllerbuilder/pkg/commands/updatetypes/synccommand.go, dev/tools/controllerbuilder/pkg/commands/updatetypes/updatetypescommand.go, dev/tools/controllerbuilder/pkg/typeupdater/common.go, dev/tools/controllerbuilder/pkg/typeupdater/fieldinserter.go, dev/tools/controllerbuilder/pkg/typeupdater/fieldupdateplan.go, dev/tools/controllerbuilder/pkg/typeupdater/insertfield-ast.go, dev/tools/controllerbuilder/pkg/typeupdater/insertfield-gemini.go, dev/tools/controllerbuilder/pkg/typeupdater/insertmessage-ast.go, dev/tools/controllerbuilder/pkg/typeupdater/insertmessage-gemini.go, dev/tools/controllerbuilder/pkg/typeupdater/messageinfo.go, dev/tools/controllerbuilder/pkg/typeupdater/protopackagesyncer.go, dev/tools/controllerbuilder/update.sh, docs/develop-resources/scenarios/new-field.md, scripts/generate-google3-docs/resource-reference/generated/resource-docs/bigquerydatatransfer/bigquerydatatransferconfig.md
Add a new command `update-types sync` that synchronizes existing Go types with corresponding proto definitions (at the pinned version). This ensures that Go field types and comments stay in sync with the proto definitions while preserving:
- Special annotations (e.g. `// +required`, `// +kubebuilder:xxx`)
- Reference fields
- Manual edits
```
go run . update-types sync \
--service google.cloud.bigquery.datatransfer.v1 \
--api-version bigquerydatatransfer.cnrm.cloud.google.com/v1beta1 \
--legacy-mode
```
Use the `--legacy-mode` flag for resources that were previously generated with KRM fields without the `// +kcc:proto` annotations.
=> tool: add `update-types sync` command to synchronize go types with proto definitions

dev/tools/controllerbuilder/pkg/commands/exportcsv/prompt.go, dev/tools/controllerbuilder/pkg/toolbot/csv.go, dev/tools/controllerbuilder/pkg/toolbot/datapoint.go, dev/tools/controllerbuilder/pkg/toolbot/enhancewithprotodefinition.go, dev/tools/controllerbuilder/pkg/toolbot/extracttoolmarkers.go, mockgcp/mockdiscoveryengine/datastore.go, mockgcp/mockedgecontainer/service.go, mockgcp/mockfirestore/service.go, mockgcp/mockgkehub/service.go, mockgcp/mockiam/service.go, mockgcp/mockkms/autokeyconfig.go, mockgcp/mockkms/cryptokey.go, mockgcp/mockkms/cryptokeyversion.go, mockgcp/mockkms/keyhandle.go, mockgcp/mockkms/keyring.go, mockgcp/mocklogging/logbucket.go, mockgcp/mocklogging/logmetric.go, mockgcp/mocklogging/logsink.go, mockgcp/mocklogging/logview.go, mockgcp/mockmonitoring/servicelevelobjective.go, mockgcp/mockpubsublite/reservation.go, mockgcp/mockpubsublite/subscription.go, mockgcp/mockpubsublite/topic.go, mockgcp/mockvpcaccess/connector.go
- **mockgcp: clean up the tool annotations**
- **controllerbuilder: strict mode to catch inconsistent training examples**
- **controllerbuilder: precompute proto service definitions**
=> controllerbuilder: strict mode to catch inconsistent training examples

dev/tools/controllerbuilder/pkg/codegen/mappergenerator.go
We were mistakenly using the KRM field name
=> controllerbuilder: fix to use proto field name

apis/refs/v1beta1/secretmanagerrefs.go, pkg/test/resourcefixture/testdata/basic/dataform/v1beta1/dataformrepository-full/_generated_object_dataformrepository-full.golden.yaml, pkg/test/resourcefixture/testdata/basic/dataform/v1beta1/dataformrepository-full/_http.log, pkg/test/resourcefixture/testdata/basic/dataform/v1beta1/dataformrepository-full/create.yaml, pkg/test/resourcefixture/testdata/basic/dataform/v1beta1/dataformrepository-full/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/dataform/v1beta1/dataformrepository-full/update.yaml, tests/apichecks/testdata/exceptions/missingfields.txt
Fix error
```
{"severity":"error","timestamp":"2025-01-22T07:00:49.994Z","msg":"Reconciler error","controller":"dataformrepository-controller","controllerGroup":"dataform.cnrm.cloud.google.com","controllerKind":"DataformRepository","DataformRepository":{"name":"dataformrepository-2tmq7a3ku34xkma","namespace":"2tmq7a3ku34xkma"},"namespace":"2tmq7a3ku34xkma","name":"dataformrepository-2tmq7a3ku34xkma","reconcileID":"645ec9cc-8246-42bb-ad57-b3ded07f6cd1","error":"Update call failed: failed to resolve resource references format of secretManagerSecretVersionRef external=\"projects/518915279/secrets/secretmanagersecret-2tmq7a3ku34xkma/versions/1\" was not known (use projects/<projectId>/secrets/<secretID>/versions/<versionID>)"}
```
=> Fix format validation for SecretManagerSecretRef and SecretManagerSecretVersionRef

apis/apigee/v1alpha1/environmentgroup_identity.go, apis/apigee/v1alpha1/environmentgroup_types.go, apis/apigee/v1alpha1/zz_generated.deepcopy.go, apis/refs/v1alpha1/apigeeorganizationref.go, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_apigeeenvgroups.apigee.cnrm.cloud.google.com.yaml, pkg/controller/direct/apigee/envgroup_controller.go
This is to disambiguate Apigee organizations from GCP organizations.
=> chore: Rename v1alpa1/OrganizationRef to ApigeeOrganizationRef

pkg/controller/direct/privilegedaccessmanager/entitlement_mappings.go, pkg/controller/direct/privilegedaccessmanager/fuzzers.go
Added fuzz test for PrivilegedAccessManagerEntitlement.
The mappers of PrivilegedAccessManagerEntitlement are customized so added local mappers just for fuzzing purpose.
=> Add fuzz test for PrivilegedAccessManagerEntitlement

docs/releasenotes/release-1.127.md, docs/releasenotes/release-1.128.md
=> doc: 1.127 release note

dev/tasks/propose-tag, operator/scripts/update-kcc-manifest/main.go
Fix duplicate cnrm/ in image path, reference: https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3164/commits/295914cae9d5f087ec130df19ed4bdfc5b648e7b
More investigations and details are in the Issue link: https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/3336.
=> fix: duplicate cnrm in image path

pkg/controller/direct/apigee/client.go, pkg/controller/direct/apigee/envgroup_controller.go, pkg/controller/direct/apigee/instance_controller.go, pkg/controller/direct/apigee/instance_mappings.go, pkg/controller/direct/apigee/instance_resolverefs.go, pkg/controller/direct/apigee/lro.go, pkg/controller/direct/common/lro.go, pkg/test/resourcefixture/testdata/basic/apigee/v1alpha1/apigeeinstance/apigeeinstance-basic/_generated_object_apigeeinstance-basic.golden.yaml, pkg/test/resourcefixture/testdata/basic/apigee/v1alpha1/apigeeinstance/apigeeinstance-basic/_http.log, pkg/test/resourcefixture/testdata/basic/apigee/v1alpha1/apigeeinstance/apigeeinstance-basic/create.yaml, pkg/test/resourcefixture/testdata/basic/apigee/v1alpha1/apigeeinstance/apigeeinstance-full/_generated_object_apigeeinstance-full.golden.yaml, pkg/test/resourcefixture/testdata/basic/apigee/v1alpha1/apigeeinstance/apigeeinstance-full/_http.log, pkg/test/resourcefixture/testdata/basic/apigee/v1alpha1/apigeeinstance/apigeeinstance-full/create.yaml, pkg/test/resourcefixture/testdata/basic/apigee/v1alpha1/apigeeinstance/apigeeinstance-full/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/apigee/v1alpha1/apigeeinstance/apigeeinstance-full/update.yaml
This PR adds the mappers, controller, and records GCP interaction for ApigeeInstance. MockGCP tests will come in a separate PR.
=> feat: Add Apigee instance controller

dev/tasks/sync-crds-folder.sh
The public documentation on [installing alpha CRDs](https://cloud.google.com/config-connector/docs/how-to/install-alpha-crds) still references the legacy "/crds" folder. Let's ensure it stays up to date.
```
$ dev/tasks/sync-crds-folder.sh 1.127.0
```
=> chore: sync CRDs inside "/crds" folder

apis/managedkafka/v1alpha1/cluster_types.go, dev/tools/controllerbuilder/pkg/commands/exportcsv/prompt.go, dev/tools/controllerbuilder/pkg/toolbot/enhancewithgostruct.go, docs/develop-resources/deep-dives/3-add-mapper.md, pkg/controller/direct/discoveryengine/datastoretargetsite_fuzzer.go, pkg/controller/direct/discoveryengine/engine_fuzzer.go, pkg/controller/direct/discoveryengine/fuzzers.go, pkg/controller/direct/iap/iapsettings_fuzzer.go, pkg/controller/direct/managedkafka/cluster_fuzzer.go, pkg/controller/direct/privilegedaccessmanager/fuzzers.go
This PR:  
- Enhances the "prompt" tool by incorporating matching Go structs. For example, when generating the fuzzer for the `ManagedKafkaCluster` resource, the enhancer will identify the corresponding Go structs, `ManagedKafkaClusterSpec` and `ManagedKafkaClusterObservedState`, and include them in the prompt.
- Adds the `// +tool:fuzz-gen` annotation to existing fuzzers in the codebase as data points.  
- Adds default values to the "prompt" command flags for developer convenience, accommodating their various source code locations.  
- Generates the fuzzer for `ManagedKafkaCluster` using the following command, with **no** manual edits (besides updating the year in the license).
```
$ controllerbuilder prompt <<EOF > cluster_fuzzer.go
// +tool:fuzz-gen
// proto.message: …
```
=> tool: use LLM to generate fuzzer

dev/tasks/propose-tag
Integrate all the necessary steps in propose release candidate to the propose-tag script.
=> improve propose-tag script

pkg/controller/direct/managedkafka/cluster_controller.go, pkg/test/resourcefixture/testdata/basic/managedkafka/v1alpha1/managedkafkacluster/managedkafkacluster-basic/_http.log, pkg/test/resourcefixture/testdata/basic/managedkafka/v1alpha1/managedkafkacluster/managedkafkacluster-cmek/_http.log
Fix the update diff on the `name` field in `ManagedKaflaCluster`, similar to how it's handled for `ManagedKaflaTopic` in #3585.
=> fix: fix the update diff in ManagedKaflaCluster

apis/iap/v1alpha1/iapsettings_types.go, apis/managedkafka/v1alpha1/cluster_types.go, apis/managedkafka/v1alpha1/topic_types.go, dev/tools/controllerbuilder/template/apis/types.go
Not sure if there was a merge error, but I noticed this while generating the new resources.
=> tool: fix the `types.go` template

scripts/github-actions/tests-e2e-scenarios.sh
I'm seeing a test timeout on one of my PRs. Let's bump up the timeout from `6 min` to `10 min` to reduce flakiness.
https://github.com/GoogleCloudPlatform/k8s-config-connector/actions/runs/13144550223/job/36679496601?pr=3585#step:4:2110
=> test: increase timeout for scenarios tests

pkg/test/resourcefixture/testdata/basic/managedkafka/v1alpha1/managedkafkacluster/managedkafkacluster-cmek/_generated_object_managedkafkacluster-cmek.golden.yaml
There was an error when merging my branches locally. I'm fixing it in this PR.
```
2025-02-06T06:10:23.9221606Z {"severity":"info","timestamp":"2025-02-06T06:10:23.921Z","msg":"resource is ready","kind":"ManagedKafkaCluster","name":"managedkafkacluster-mfv2jaejjrs6hsq"}
2025-02-06T06:10:23.9252813Z     utils.go:235: FAIL: unexpected diff in /home/runner/work/k8s-config-connector/k8s-config-connector/pkg/test/resourcefixture/testdata/basic/managedkafka/v1alpha1/managedkafkacluster/managedkafkacluster-cmek/_generated_object_managedkafkacluster-cmek.golden.yaml:   map[string]any{
2025-02-06T06:10:23.9254576Z           	... // 2 identical entries
2025-02-06T06:10:23.9256735Z           	"metadata": map[string]any{"finalizers": []any{string("cnrm.cloud.google.com/finalizer"), …
```
=> fix: fix merge error on golden test file

apis/bigquery/v1beta1/dataset_reference.go, apis/bigqueryanalyticshub/v1alpha1/listing_types.go, apis/bigqueryanalyticshub/v1alpha1/zz_generated.deepcopy.go, apis/bigqueryanalyticshub/v1beta1/listing_types.go, apis/bigqueryanalyticshub/v1beta1/zz_generated.deepcopy.go, apis/bigquerydatatransfer/v1alpha1/config_types.go, apis/bigquerydatatransfer/v1alpha1/zz_generated.deepcopy.go, apis/bigquerydatatransfer/v1beta1/transferconfig_types.go, apis/bigquerydatatransfer/v1beta1/zz_generated.deepcopy.go, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_bigqueryanalyticshublistings.bigqueryanalyticshub.cnrm.cloud.google.com.yaml, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_bigquerydatatransferconfigs.bigquerydatatransfer.cnrm.cloud.google.com.yaml, pkg/controller/direct/bigqueryanalyticshub/listing_controller.go, pkg/controller/direct/bigqueryanalyticshub/mapper.go, pkg/controller/direct/bigquerydatatransfer/bigquerydatatransfer_mappings.go, pkg/controller/direct/bigquerydatatransfer/bigquerydatatransferconfig_controller.go, scripts/generate-google3-docs/resource-reference/generated/resource-docs/bigqueryanalyticshub/bigqueryanalyticshublisting.md, scripts/generate-google3-docs/resource-reference/generated/resource-docs/bigquerydatatransfer/bigquerydatatransferconfig.md
This PR gets rid of the "old" refs. usage for BigQueryDatasetRef. It doesn't get rid of it just yet; that will be in a separate PR when I change the `ResolveBigQueryTable` behavior
=> refactor: no refs for BigQueryDatasetRef

apis/alloydb/v1beta1/instance_types.go
Although this Go struct isn’t auto generated, let’s add the proto annotation to help various LLM tools.
=> chore: add a missing proto annotation

dev/tools/controllerbuilder/cmd/root.go, dev/tools/controllerbuilder/generate-proto.sh, dev/tools/controllerbuilder/pkg/codegen/typegenerator.go, dev/tools/controllerbuilder/pkg/commands/detectnewfields/README.md, dev/tools/controllerbuilder/pkg/commands/detectnewfields/detectnewfieldscommand.go, dev/tools/controllerbuilder/pkg/newfieldsdetector/ignoredfields.go, dev/tools/controllerbuilder/pkg/newfieldsdetector/newfieldsdetector.go, dev/tools/controllerbuilder/pkg/newfieldsdetector/targetfields.go
This tool identifies changes in GCP API proto definitions by comparing the pinned version specified in the `git.version` file with the latest version at HEAD.
It can identify:
- New fields **added** to messages
- Fields **removed** from messages
- Fields that **changed type**
```bash
$ go run . detect-new-fields
$ go run . detect-new-fields \
--target-messages="google.cloud.bigquery.datatransfer.v1.TransferConfig"
$ go run . detect-new-fields \
--ignored-fields-file=config/ignored_fields.yaml
```
An example ignored_fields.yaml
```yaml
google.cloud.bigquery.connection.v1:
Connection:
- salesforceDataCloud
google.api.apikeys.v2:
Key:
- createTime
- updateTime
```
```
$ go run . detect-new-fields
...
Changes detected in message: google.cloud.redis.cluster.v1.AutomatedBackupConfig
New field: …
```
=> tool: implement a proto-parsing based new field detector

config/tests/samples/create/harness.go, mockgcp/mock_http_roundtrip.go, mockgcp/mockmanagedkafka/cluster.go, mockgcp/mockmanagedkafka/service.go, mockgcp/mockserviceusage/knownservices.go, mockgcp/mockserviceusage/serviceusagev1beta1.go, pkg/test/resourcefixture/testdata/basic/managedkafka/v1alpha1/managedkafkacluster/managedkafkacluster-basic/_http.log, pkg/test/resourcefixture/testdata/basic/managedkafka/v1alpha1/managedkafkacluster/managedkafkacluster-cmek/_http.log
The mock is mostly generated by the LLM, with non-trivial [manual edits](https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3602/commits/8db09d8e50fc1d2a25126fd3563e1550119e8675).
=> mockgcp: add support for ManagedKafkaCluster

tests/apichecks/crds_test.go, tests/apichecks/testdata/exceptions/missingfields.txt
Unblocks #3632
Fixed the incorrect detection of list fields in `TestCRDFieldPresenceInUnstructured`.
e.g.
```
=== FAIL: tests/apichecks TestCRDFieldPresenceInUnstructured (6.00s)
utils.go:149: FAIL: unexpected diff in testdata/exceptions/missingfields.txt:   (
"""
... // 2370 identical lines
[missing_field] crd=logginglogsinks.logging.cnrm.cloud.google.com version=v1beta1: field ".spec.exclusions[].filter" is not set in unstructured objects
[missing_field] crd=logginglogsinks.logging.cnrm.cloud.google.com version=v1beta1: field ".spec.exclusions[].name" is not set in unstructured objects
+ 	[missing_field] crd=managedkafkaclusters.managedkafka.cnrm.cloud.google.com version=v1beta1: field ".spec.gcpConfig.accessConfig.networkConfigs[].subnetworkRef" is not set; neither 'external' nor …
```
=> test: fix list fields detection in TestCRDFieldPresenceInUnstructured

pkg/test/resourcefixture/testdata/basic/workstations/workstation/workstation-full/_generated_object_workstation-full.golden.yaml, pkg/test/resourcefixture/testdata/basic/workstations/workstation/workstation-full/_http.log, pkg/test/resourcefixture/testdata/basic/workstations/workstation/workstation-full/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/workstations/workstation/workstation-minimal/_generated_object_workstation-minimal.golden.yaml, pkg/test/resourcefixture/testdata/basic/workstations/workstation/workstation-minimal/_http.log, pkg/test/resourcefixture/testdata/basic/workstations/workstation/workstation-minimal/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/workstations/workstationcluster/workstationcluster-full/_generated_object_workstationcluster-full.golden.yaml, pkg/test/resourcefixture/testdata/basic/workstations/workstationcluster/workstationcluster-full/_http.log, pkg/test/resourcefixture/testdata/basic/workstations/workstationcluster/workstationcluster-full/create.yaml, pkg/test/resourcefixture/testdata/basic/workstations/workstationcluster/workstationcluster-full/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/workstations/workstationcluster/workstationcluster-full/update.yaml, pkg/test/resourcefixture/testdata/basic/workstations/workstationcluster/workstationcluster-minimal/_generated_object_workstationcluster-minimal.golden.yaml, pkg/test/resourcefixture/testdata/basic/workstations/workstationcluster/workstationcluster-minimal/_http.log, pkg/test/resourcefixture/testdata/basic/workstations/workstationcluster/workstationcluster-minimal/create.yaml, pkg/test/resourcefixture/testdata/basic/workstations/workstationcluster/workstationcluster-minimal/dependencies.yaml
Our periodic tests are sometimes failing with the following error:
```
Error 429: Quota limit 'WorkstationClustersPerProjectPerRegion' has been
exceeded. Limit: 5 in region us-west1.
```
This change fixes that flake by distributing our workstation cluster test cases across us-{west,central,east}1 so that there are only 2 workstation clusters created in each region, for each test run.
=> fix: Distribute WorkstationClusters to avoid quota limits

pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-replica-direct/_generated_object_sqlinstance-replica-direct.golden.yaml, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-replica-direct/_http.log, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-replica-direct/create.yaml, tests/apichecks/testdata/exceptions/missingfields.txt
As of January 13, 2025, the SQLInstance API deprecated the previous method of failover configuration. This fixes the test case to no longer use the deprecated configuration method.
Ref: https://cloud.google.com/sql/docs/mysql/configure-legacy-ha
=> fix: Remove deprecated SQLInstance failover configuration

dev/tools/controllerbuilder/cmd/root.go, dev/tools/controllerbuilder/pkg/commands/generatefuzzer/README.md, dev/tools/controllerbuilder/pkg/commands/generatefuzzer/generatefuzzercommand.go, dev/tools/controllerbuilder/pkg/toolbot/csv.go, docs/develop-resources/deep-dives/3-add-mapper.md, pkg/controller/direct/managedkafka/cluster_fuzzer.go, pkg/controller/direct/managedkafka/topic_fuzzer.go
Add a tool to automatically generate and validate the fuzzer for a direct resource.
```
$ go run main.go generate-fuzzer \
--message "google.cloud.managedkafka.v1.Topic" \
--api-version "managedkafka.cnrm.cloud.google.com/v1alpha1" \
--max-attempts 3
Generating fuzzer for managedkafka.topic (attempt 1/3)...
Verifying fuzzer for managedkafka.topic (attempt 1/3)...
Fuzzer generated and verified for managedkafka.topic
```
```
$ go run main.go generate-fuzzer \
--message "google.cloud.managedkafka.v1.Cluster" \
--api-version "managedkafka.cnrm.cloud.google.com/v1alpha1" \
--max-attempts 3
Generating fuzzer for managedkafka.cluster (attempt 1/3)...
Verifying fuzzer for managedkafka.cluster (attempt 1/3)...
Fuzzer generated and verified for managedkafka.cluster
```
=> tool: add `generate-fuzzer` to generate and qualify fuzzer

dev/tools/controllerbuilder/README.md, dev/tools/controllerbuilder/pkg/commands/generatecontroller/generatecontrollercommand.go, dev/tools/controllerbuilder/pkg/commands/generatedirectreconciler/command.go, dev/tools/controllerbuilder/pkg/commands/generatetypes/generatetypescommand.go, dev/tools/controllerbuilder/pkg/options/resource.go, docs/develop-resources/deep-dives/4-add-controller.md
Update "generate-controller" and "generate-direct-reconciler" commands to use the same`--resource Kind:ProtoName` flag format as other commands for consistency in the CLI interface.
=> tool: unify --resource flag format across commands

Makefile, dev/tools/controllerbuilder/generate-proto.sh, scripts/validate-prereqs.sh
Follow up of #3375.
This PR adds a presubmit check to prevent accidental manual edits to the generated types for direct resources, ensuring the tools can be safely rerun. (Diff in copyright year within the generated file is ignored)
To ***opt-in*** the check, create a configuration YAML file and place it in the `dev/tools/controllerbuilder/config` directory. Here’s an example configuration file:
```
service: google.cloud.bigquery.datatransfer.v1
apiVersion: bigquerydatatransfer.cnrm.cloud.google.com/v1beta1
generateMapper: true
resources:
- kind: BigQueryDataTransferConfig
protoName: TransferConfig
skipScaffoldFiles: true # files were scaffolded using a previous template, making them incompatible with the new scaffolding template.
```
=> chore: add presubmit check for generated types for direct resources

dev/tools/controllerbuilder/pkg/codebot/tool_run_cmd.go
allows codebot to discover the gcloud-based mock
=> chore: add gcloud to RunTerminalCommand

dev/tools/controllerbuilder/pkg/codebot/tool_create_file.go
otherwise, say I want to create a new file under "mockXXX/testdata/YYY/script.yaml", if  mockXXX or mockXXX/testdata does not exist, the codebot will fail
=> fix: CreateFile to create its parent dir

.github/workflows/presubmit.yaml, dev/ci/presubmits/validate-generated-types.sh, scripts/validate-prereqs.sh
#3396 introduced a step to validate the generated Go types for direct resources within `scripts/validate-prereqs.sh`. However, since this script is used by multiple systems, it may lead to unexpected errors. Let's separate the validation into its own script and presubmit workflow.
=> chore: add a dedicated presubmit workflow to validate generated types

apis/bigquerydatatransfer/v1beta1/transferconfig_types.go, dev/tools/controllerbuilder/pkg/commands/exportcsv/prompt.go, dev/tools/controllerbuilder/pkg/commands/generatefuzzer/README.md, dev/tools/controllerbuilder/pkg/commands/generatefuzzer/generatefuzzercommand.go, dev/tools/controllerbuilder/pkg/llm/vertexai.go, dev/tools/controllerbuilder/pkg/toolbot/csv.go, dev/tools/controllerbuilder/pkg/toolbot/enhancewithmappers.go, docs/develop-resources/deep-dives/3-add-mapper.md, pkg/controller/direct/bigquerydatatransfer/bigquerydatatransfer_mappings.go, pkg/controller/direct/bigquerydatatransfer/transferconfig_fuzzer.go, pkg/controller/direct/iap/iapsettings_fuzzer.go, pkg/controller/direct/managedkafka/cluster_fuzzer.go, pkg/controller/direct/privilegedaccessmanager/fuzzers.go
Making some improvements to the fuzz-gen tool:  
- A configurable LLM model  
- An improved prompt  
- Enhanced data points with mapping functions (providing this info to the LLM since contributors also need it when manually writing a fuzzer)
- Generating a fuzzer for `BigQueryDataTransferConfig`, which is a fairly complex resource.
Example run:
```
go run main.go generate-fuzzer \
--message "google.cloud.bigquery.datatransfer.v1.TransferConfig" \
--api-version "bigquerydatatransfer.cnrm.cloud.google.com/v1beta1" \
--llm-model "gemini-2.0-flash-exp" \
--max-attempts 3
Generating fuzzer for bigquerydatatransfer.transferconfig (attempt 1/3)...
Verifying fuzzer for bigquerydatatransfer.transferconfig (attempt 1/3)...
Fuzzer verification failed: exit status 1
stderr: 
Generating fuzzer for …
```
=> codebot: improve fuzzer generation

pkg/test/gcp/gcp.go
TESTED
```
$ go test -v -timeout 1800s -tags=integration ./pkg/controller/dynamic/ -run TestCreateNoChangeUpdateDelete/iap/basic-projectiapsettings
$ go test -v -timeout 1800s -tags=integration ./pkg/controller/dynamic/ -run TestCreateNoChangeUpdateDelete/iap/basic-regionalcomputebackendserviceiapsettings
```
=> test: fix dynamic test for IAPSettings

apis/apigee/v1beta1/groupversion_info.go
This should probably be `v1beta1`. Yet another thing we can write a linter for 😝
=> fix: update groupversion_info.go

.github/workflows/presubmit.yaml, Makefile, dev/ci/scenarios-tests
* github actions should map to a script in dev/ci/
* scripts should be runnable directly
* tests that verify golden output should write the golden output
=> chore: move scenarios-tests github action to follow pattern

scripts/github-actions/tests-e2e-fixtures-apigee, scripts/github-actions/tests-e2e-fixtures-secretmanager, scripts/github-actions/tests-e2e-fixtures-vertexai
The fixtures test time is getting big again, so splitting out a few more services.
=> tests: split out some more services

dev/tools/controllerbuilder/pkg/commands/exportcsv/prompt.go, experiments/conductor/branches.yaml, experiments/conductor/cmd/runner/mock_commands.go, experiments/conductor/cmd/runner/runner.go, experiments/conductor/cmd/runner/utilities.go
Added conductor runner to generate mock service and resource go files.
./bin/conductor runner --branch-repo=/usr/local/google/home/wfender/go/src/github.com/cheftako/k8s-config-connector_branches --branch-conf=branches.yaml --logging-dir=./logs --command=6
=> Added conductor runner to generate mock service and resource go files.

config/samples/resources/computenetwork/compute_v1beta1_computenetwork.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computenetwork/computenetworkautocreatesubnets/_generated_object_computenetworkautocreatesubnets.golden.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computenetwork/computenetworkautocreatesubnets/create.yaml, pkg/test/resourcefixture/testdata/basic/compute/v1beta1/computenetwork/computenetworkautocreatesubnets/update.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/compute/computenetwork.md
error message: `ULA internal ipv6 is not supported for auto mode network`
This was introduced in #1506. `enable_ula_internal_ipv6` should remain `false` when `autoCreateSubnetworks` is set to true. The update of this field was covered in computenetworkbasic test.
Also updated the samples yaml with a comment.
--- PASS: TestCreateNoChangeUpdateDelete (0.17s)
--- PASS: TestCreateNoChangeUpdateDelete/compute (0.00s)
--- PASS: TestCreateNoChangeUpdateDelete/compute/basic-computenetworkautocreatesubnets (316.60s)
PASS
=> test: fix computenetworkautocreatesubnets test

apis/bigquerydatatransfer/v1alpha1/config_types.go, apis/bigquerydatatransfer/v1beta1/transferconfig_types.go, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_bigquerydatatransferconfigs.bigquerydatatransfer.cnrm.cloud.google.com.yaml, pkg/controller/direct/bigquerydatatransfer/bigquerydatatransferconfig_controller.go, pkg/test/resourcefixture/testdata/basic/bigquerydatatransfer/v1beta1/bigquerydatatransferconfig/bigquerydatatransferconfig-scheduledquery/_generated_object_bigquerydatatransferconfig-scheduledquery.golden.yaml, pkg/test/resourcefixture/testdata/basic/bigquerydatatransfer/v1beta1/bigquerydatatransferconfig/bigquerydatatransferconfig-scheduledquery/_http.log, pkg/test/resourcefixture/testdata/basic/bigquerydatatransfer/v1beta1/bigquerydatatransferconfig/bigquerydatatransferconfig-scheduledquery/create.yaml, pkg/test/resourcefixture/testdata/basic/bigquerydatatransfer/v1beta1/bigquerydatatransferconfig/bigquerydatatransferconfig-scheduledquery/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/bigquerydatatransfer/v1beta1/bigquerydatatransferconfig/bigquerydatatransferconfig-scheduledquery/update.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/bigquerydatatransfer/bigquerydatatransferconfig.md
=> fix: datasetRef is not a required field in BigQueryDataTransferConfig

mockgcp/mockstorage/normalize.go
=> mockgcp: fix for mockstorage normalization

third_party/github.com/GoogleCloudPlatform/declarative-resource-client-library/services/google/dataproc/alpha/cluster_internal.go, third_party/github.com/GoogleCloudPlatform/declarative-resource-client-library/services/google/dataproc/beta/cluster_internal.go, third_party/github.com/GoogleCloudPlatform/declarative-resource-client-library/services/google/dataproc/cluster_internal.go
Fixed the unexpected diff during reconciliation caused by the newly introduced server-generated label `goog-drz-dataproc-uuid` in DataprocCluster.
=> Suppress diff for labels starting with 'goog-' in DataprocCluster

dev/tools/controllerbuilder/pkg/toolbot/csv.go
Skip `experiements/` folder when extracting data points. This avoid incorrectly picking up strings in files such as 
https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/fdb3f32b63d8424d95f844416e3c6f99e978dfd2/experiments/conductor/cmd/runner/mock_commands.go#L366-L374
=> codebot: skip experiments folder when extracting data points

experiments/conductor/branches-all.yaml, experiments/conductor/branches.yaml, experiments/conductor/cmd/runner/mock_commands.go, experiments/conductor/cmd/runner/runner.go, experiments/conductor/cmd/runner/utilities.go
Added a proto-msg metadata field.
Switch proto-path values to being proto-msg values. Reserved proto-path for the actual proto file path. Added 2 new commands.
Removed the old createScriptYamlBash command as confusing. Added a few new utility methods.
./bin/conductor runner --branch-repo=/usr/local/google/home/wfender/go/src/github.com/cheftako/k8s-config-connector_branches --branch-conf=branches.yaml --logging-dir=./logs --command=7
./bin/conductor runner --branch-repo=/usr/local/google/home/wfender/go/src/github.com/cheftako/k8s-config-connector_branches --branch-conf=branches.yaml --logging-dir=./logs --command=8
=> Add serviceToRoundTip and protoToMakefile commands.

mockgcp/mockbigquerybiglake/service.go, mockgcp/mockbigquerybiglake/table.go
LLM assisted mock for BigLakeTable.
Note there's not a simple gcloud command for this resource (https://cloud.google.com/bigquery/docs/reference/biglake/rest/v1/projects.locations.catalogs.databases.tables).
I'm hoping we can check this in and enhance the mock once we have a controller in hand.
Note: see the commits for manual edits made.
=> mockgcp: bigquerybiglake

dev/tools/controllerbuilder/Makefile, experiments/conductor/cmd/runner/mock_commands.go, experiments/conductor/cmd/runner/utilities.go
Fixes:
* Was seeing a panic in the conductor. Fixing it.
* make ctf fails and is not needed for tooling build. so removing it.
* cmd=6 mocks-go generation was skipped even if file did not exist. fixing logic that checks for file existance
* fix git add vargs passing to allow adding multiple files
```
❯ ./experiments/conductor/bin/conductor runner --branch-repo=/usr/local/google/home/barni/workspace/src/github.com/barney-s/vertex-notebook/k8s-config-connector  --branch-conf=./experiments/conductor/branches.yaml --logging-dir=./logs --command=4
2025/02/27 13:41:05 Running conductor runner with branch config: ./experiments/conductor/branches.yaml
2025/02/27 13:41:05 Starting Runner
2025/02/27 13:41:05 Create Script YAML: 0 name: notebooks-instance, branch: resource-notebooks-instance
panic: …
```
=> Fix panic in the conductor tooling and remove ctf from makefile

experiments/conductor/cmd/runner/mock_commands.go
Removing the file name seems to help. Not sure why it was added in the first place. I was seeing some proto blocks in the generate code. Fixed the branches.yaml to include correct paths. That removed a lot of erroneous generated code. But there were still some snippets of proto in the generated code. Modified the prompts and this seems better.
=> Non-determinism alert: Tweaking prompt to get better generated files

experiments/conductor/branches-all.yaml, experiments/conductor/branches.yaml, experiments/conductor/cmd/runner/mock_commands.go, experiments/conductor/cmd/runner/runner.go, experiments/conductor/cmd/runner/utilities.go
Fixed a few preconditions.
Cleaned up my test sample metadata.
Added missing help commands.
Cleaned up log messages.
./bin/conductor runner --branch-repo=/usr/local/google/home/wfender/go/src/github.com/cheftako/k8s-config-connector_branches --branch-conf=branches.yaml --logging-dir=./logs --command=9
=> Added a runner for runmockgcptests against mock.

.github/workflows/presubmit.yaml, scripts/github-actions/tests-e2e-fixtures-apigee, scripts/github-actions/tests-e2e-fixtures-vertexai
They were split into separate test scripts, but are not run by the presubmit.
=> test: include apigee, secretmanager and vertexai in presubmit

pkg/controller/direct/vertexai/featurestore_controller.go
The `KMSKeyRef` need be resolved before making CREATE and UPDATE calls. This was overlooked in the previous PR because the test did not include this field. Let's address this after the KMSRefs refactoring PR (#3836) is merged.
=> chore: add a TODO to resolve reference fields in VertexAIFeaturestore

experiments/conductor/cmd/runner/crd_generator_commands.go, experiments/conductor/cmd/runner/mock_commands.go, experiments/conductor/cmd/runner/runner.go, experiments/conductor/cmd/runner/utilities.go
- refactor fixMetadata to take a function that modifies branchdata
- implement addEnableAPIsModifier branch modifier
- add cmd -3 to invoke fixMetadata with addEnableAPIsModifier
- REFACTOR replace exec.Command calls to use executeCommand util function
- more modular code
- consistent logging of inputs, output, err
- consistent timeout support
- Add global timeout option
- Add cmd=4 to enable GCP APIs
- Moved cmd numbers over to accommodate enable APIs cmd
```shell
cd experiments/conductor
make build
./bin/conductor runner --branch-repo=/usr/local/google/home/barni/workspace/src/github.com/barney-s/vertex-notebook/k8s-config-connector  --branch-conf=branches-user.yaml --logging-dir=logs --command=-3
diff branches-new.yaml branches-user.yaml
mv branches-new.yaml branches-user.yaml
```
* …
=> Add cmd to add api-enbalement metadata and refactor exec.Command

mockgcp/mockapigee/instance.go, pkg/controller/direct/apigee/instance_controller.go, pkg/test/resourcefixture/testdata/basic/apigee/apigeeinstance/apigeeinstance-full/_http.log
Only allow mutations to the mutable fields. This fixes the error observed when running in real GCP:
> {"severity":"error","timestamp":"2025-03-05T18:21:51.323Z","msg":"Reconciler error","controller":"apigeeinstance-controller","controllerGroup":"apigee.cnrm.cloud.google.com","controllerKind"
:"ApigeeInstance","ApigeeInstance":{"name":"apigeeinstance-sample","namespace":"default"},"namespace":"default","name":"apigeeinstance-sample","reconcileID":"cebb8672-4452-4657-829a-7a8ed673
b1e3","error":"Update call failed: error updating: updating ApigeeInstance organizations/xyz/instances/apigeeinstance-sample: googleapi: Error 400: Request contains a
n invalid argument.\nDetails:\n[\n  {\n    \"@type\": \"type.googleapis.com/google.rpc.RequestInfo\",\n    \"requestId\": \"4518562949576557033\"\n …
=> fix: Fix ApigeeInstance update mask

experiments/conductor/cmd/runner/runner.go
Also filter out resources without CRUD in gcloud. 
We can add more filter rules in `setSkipOnBranchModifier` as well.
=> tool: Filter out resources without proper gcloud support

experiments/conductor/cmd/runner/crd_generator_commands.go, experiments/conductor/cmd/runner/mock_commands.go, experiments/conductor/cmd/runner/runner.go, experiments/conductor/cmd/runner/utilities.go
Add support for retries for failed commands.
- each command can cap the retry count using MaxRetries. This is useful for deterministic commands.
- global retry flag (default: 3) is used for all commands.
=> Conductor: Add support for retries for failed commands

apis/firestore/v1beta1/groupversion_info.go
Noticed this service had the same issue as originally discovered in https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/3745.
=> fix: Fix Firestore v1beta1 GVK

pkg/test/resourcefixture/contexts/sql_context.go
This test has the same issue as the other SQLInstance backup tests, because backup configuration is required to configure a replica.
=> fix: Fix SQLInstance replica periodic

mockgcp/mockgcptests/e2e_test.go
We use env vars and proxies on unique ports
=> chore: mark mockgcptests as parallel-safe

.github/workflows/fuzz.yaml
I noticed we ran these under `experiments/` too. Probably can do without.
=> ci: no fuzz on experiments

experiments/conductor/cmd/runner/crd_generator_commands.go, experiments/conductor/cmd/runner/mock_commands.go, experiments/conductor/cmd/runner/runner.go, mockgcp/mockgcptests/proxy.go
- tweak the prompt to use correct projectId variable
- update readFiles for script yaml to produce structured output under logs/all_scripts.yaml [BULK READ]
- The user can inspect and manually edit all_scripts.yaml [MANUAL EDIT]
- add writeFiles to write the contents from all_scripts.yaml to each branch. [BULK_WRITE]
- If there are no changes it skips the update
- Update proxy to allow wildcard googleapis. This avoid a TLS warning in the logs
=> conductor: script yaml generation improvements

dev/tools/controllerbuilder/pkg/commands/exportcsv/prompt.go, dev/tools/controllerbuilder/pkg/toolbot/csv.go, dev/tools/controllerbuilder/pkg/toolbot/extracttoolmarkers.go
This is more efficient and reduces the blast radius of bad input data.
=> controllerbuilder: support filters on extraction

dev/tools/controllerbuilder/pkg/toolbot/enhancewithmappers.go, pkg/controller/direct/vertexai/featurestore_fuzzer.go
With `// api.group: aiplatform.cnrm.cloud.google.com`, the prompt gives the following error and it is kinda confusing.
```
walking directory tree: processing file "/usr/local/google/home/maqiuyu/go/src/github.com/maqiuyujoyce/5-k8s-config-connector/pkg/controller/direct/vertexai/featurestore_fuzzer.go": reading mapper directory: open /usr/local/google/home/maqiuyu/go/src/github.com/maqiuyujoyce/5-k8s-config-connector/pkg/controller/direct/aiplatform: no such file or directory
```
The root cause is `api.group` data point in featurestore_fuzzer.go contained incorrect value.
Fixed `api.group` and also improved the error message in mapper enhancer.
=> Improve error message in mapper enhancer and fix api.group

pkg/test/eventsink.go
* Was causing json parse failures when recording the request.
* also recording tokens is not a good idea
```
2025/03/08 03:47:42   > F0308 03:47:42.302034  337173 http_recorder.go:285] error from json.Unmarshal("grant_type=refresh_token&client_id=32555940559.apps.googleusercontent.com&client_secret=****&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fappengine.admin+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsqlservice.login+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Faccounts.reauth"): invalid character 'g' looking for beginning of value
```
```
request:
body: grant_type=refresh_token&client_id=32555940559.apps.googleuserco …
```
=> Skip recording auth token exchanges

experiments/conductor/cmd/runner/mock_commands.go
gcloud based recording using go tests was timing out in 10m for some commands that need 30m to complete.
=> conductor: pass global timeouts to the go test commands to deal with  LRO operations 

mockgcp/generated/google/bigtable/admin/v2/bigtable_instance_admin.pb.gw.go, mockgcp/generated/google/bigtable/admin/v2/bigtable_table_admin.pb.gw.go
On head, we are seeing bq diff when running `make gen-proto`.
Caused presubmit failure for one of my PRs: 
https://github.com/GoogleCloudPlatform/k8s-config-connector/actions/runs/13759284116/job/38471846394?pr=3939
=> Broken Head: make gen-proto on latest, uploading diff

mockgcp/mockresourcemanager/service.go, mockgcp/mockresourcemanager/tagkeys.go, mockgcp/mockresourcemanager/testdata/tagkey/crud/_http.log, mockgcp/mockresourcemanager/testdata/tagkey/crud/script.yaml, tests/e2e/httplog.go, tests/e2e/replacements.go
- **autogen: generate-script for gcloud resource-manager tags keys**
- **autogen: Capture golden output for mockresourcemanager/testdata/tagkey/crud**
- **mockgcp: update service for resourcemanager tagkey**
- **tests: fix confusion around unusual search syntax**
=> mockgcp: support for resource-manager tagkey

mockgcp/mockgcptests/e2e_test.go
This header is (always) sent by gcloud if a quota project is set,
so this header reflects configuration, not the actual protocol.
=> mockgcp tests: ignore x-goog-user-project header

experiments/conductor/cmd/runner/utilities.go
The primary motivation for this refactor is that we can now use a safer pattern:
```
close := setLoggingWriter(opts, branch)
defer close()
```
=> refactor: processBranch function for better maintainability

experiments/conductor/branches-all.yaml
For not valid resource we don't want to `skip` them in the main branches/ metadata file but rather delete them altogether.
=> conductor:branches: delete operations resources

dev/tools/controllerbuilder/pkg/toolbot/enhancewithmappers.go
The fuzzer generation should not fail due to missing (mismatching) mapper functions.
Example error:
```
Error: walking directory tree: processing file "/usr/local/google/home/jingyih/kccai/work1/pkg/controller/direct/tasks/queue_fuzzer.go": api.group "cloudtasks.cnrm.cloud.google.com" might be incorrect
```
=> controllerbuilder: gracefully handle missing mapper directory during enhancement

mockgcp/mockcompute/computeexternalvpngateways.go, mockgcp/mockcompute/service.go, mockgcp/mockcompute/testdata/computeexternalvpngateways/crud/_http.log, mockgcp/mockcompute/testdata/computeexternalvpngateways/crud/script.yaml
- **conductor: "Adding LLM/gcloud generated test script.yaml for compute-computeexternalvpngateways"**
- **conductor: "Adding mockgcptests generated _http.log for compute-computeexternalvpngateways"**
- **conductor: "Adding mock service and resource for compute-computeexternalvpngateways"**
=> mockgcp: support for compute externalVpnGateways

experiments/conductor/cmd/runner/crd_generator_commands.go, experiments/conductor/cmd/runner/github_commands.go, experiments/conductor/cmd/runner/runner.go, experiments/conductor/cmd/runner/utilities.go
* Move delete branch from 3 to -5
* Add confirmation for delete branch
* Add make ready-pr, push to origin to cmd 9
* Support providing --branch-suffix for pushing to remote without conflicting with other work. eg: --branch-suffix='-mocks'
* Run go imports on generated files
=> conductor improvements

experiments/conductor/cmd/runner/controller_commands.go, experiments/conductor/cmd/runner/scripts/controller/04-create-test.sh
Add license header. Rename `locationID` to `location` which is more commonly used by resources.
=> conductor: minor adjustment to test generation

experiments/conductor/cmd/runner/mock_commands.go
For resources without the gcloud test log "_http.log" or even those do not have gcloud commands entirely, we should still be able to generate mock files.
=> conductor: do not require gcloud http log when creating mocks

mockgcp/mockresourcemanager/service.go, mockgcp/mockresourcemanager/tagbinding.go, mockgcp/mockresourcemanager/tagkeys.go, mockgcp/mockresourcemanager/tagvalues.go, mockgcp/mockresourcemanager/testdata/tagbinding/crud/_http.log, mockgcp/mockresourcemanager/testdata/tagbinding/crud/script.yaml
- **autogen: generate-script for gcloud resource-manager tags bindings**
- **autogen: Capture golden output for mockresourcemanager/testdata/tagbinding/crud**
- **mockgcp: support for resourcemanager tagbinding**
=> mockgcp: support for resource-manager TagBindings

mockgcp/Makefile
Currently the mockgcp Makefile is broken due to duplicated entries.
```
$ make gen-proto
...
...
...
--grpc-gateway_out: duplicate annotation: method=POST, template=/v1/{parent=*/*}:exportAssets
make[1]: *** [Makefile:37: gen-proto-no-fixup] Error 1
make: *** [Makefile:31: gen-proto] Error 2
```
=> chore: fix mockgcp Makefile

experiments/conductor/cmd/runner/controller_commands.go
Let's keep the filename consistent. In the `xxx_types.go` file, we use the "proto name" as the prefix.
https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/5ba0bc4e29a8dfae187b00dc49e31483fc9bb549/dev/tools/controllerbuilder/scaffold/apis.go#L144
I also noticed that the conductor used "branch.Resource" for the fuzzer file. I'm not sure what the difference is between "resource" and the proto name. Is "resource" the GCP resource name?
https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/5ba0bc4e29a8dfae187b00dc49e31483fc9bb549/experiments/conductor/cmd/runner/crd_generator_commands.go#L294
=> conductor: use proto name for controller filename

.github/workflows/lint.yaml, .github/workflows/presubmit-compositions.yaml, Makefile, experiments/compositions/composition/Makefile, experiments/compositions/expanders/cel-expander/Makefile, experiments/compositions/expanders/helm-expander/Makefile, experiments/compositions/facade/Makefile
Otherwise fails with golang 1.24.1
=> chore: bump golangci for newer go versions

dev/tools/controllerbuilder/pkg/toolbot/csv.go
I noticed that the files generated by `controllerbuilder prompt` sometimes still contain the following at the end. I suspect this might be due to empty lines between the decoration markers.
```
</out>
```
=> controllerbuilder: remove empty lines in response decorations

dev/tools/controllerbuilder/pkg/toolbot/csv.go
When generating mock or controller, pick examples from the same proto service (which also means the same API group). If no such examples exist, fallback to the previous behavior.
=> controllerbuilder: find better examples when prompt

experiments/conductor/cmd/runner/mock_commands.go
This update ensures conductor runner checks and creates the mock directory before writing service and resource files, preventing file write errors when the directory doesn't exist.
```
2025/03/23 00:10:09 failed to process branch gkebackup-backupplan on attempt 1: WRITE MOCK SERVICE xxx/mockgcp/mockgkebackup/service.go error: open xxx/mockgcp/mockgkebackup/service.go: no such file or directory
```
=> conductor: ensure mock directory exists before writing files

pkg/controller/direct/bigquerydataset/roundtrip_test.go
=> test:add a fuzz test for bigquerydataset

config/tests/samples/create/harness.go, mockgcp/mockvmwareengine/privatecloud.go, pkg/controller/direct/vmwareengine/privatecloud_controller.go, pkg/test/resourcefixture/testdata/basic/vmwareengine/v1alpha1/vmwareengineprivatecloud/vmwareengineprivatecloud-minimal/_generated_object_vmwareengineprivatecloud-minimal.golden.yaml, pkg/test/resourcefixture/testdata/basic/vmwareengine/v1alpha1/vmwareengineprivatecloud/vmwareengineprivatecloud-minimal/_http.log, pkg/test/resourcefixture/testdata/basic/vmwareengine/v1alpha1/vmwareengineprivatecloud/vmwareengineprivatecloud-minimal/create.yaml, pkg/test/resourcefixture/testdata/basic/vmwareengine/v1alpha1/vmwareengineprivatecloud/vmwareengineprivatecloud-minimal/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/vmwareengine/v1alpha1/vmwareengineprivatecloud/vmwareengineprivatecloud-minimal/update.yaml, tests/e2e/unified_test.go
The resource takes a few hours to be created and takes a week to be deleted (scheduled deletion).  
I had to modify some hardcoded timeouts in the test to get the resource creation to finish.
- Wait for ready timeout
https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/b932c0a671f9380ce64704a6113b7fb692e40c76/config/tests/samples/create/samples.go#L48
- Wait for ready poll interval (avoid log spam)
https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/b932c0a671f9380ce64704a6113b7fb692e40c76/config/tests/samples/create/samples.go#L182
- Reconcile timeout
https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/b932c0a671f9380ce64704a6113b7fb692e40c76/pkg/controller/direct/directbase/directbase_controller.go#L159
- Per test timeout …
=> feat: add controller, test and mock support for VMwareEnginePrivateCloud

dev/tasks/create-test-project
=> e2e: enable sourcerepo.googleapis.com

dev/tasks/create-test-project
Needed by cloudfunctions tests
=> e2e: enable vpcaccess API in e2e tests

.github/workflows/ci-presubmit.yaml, scripts/github-actions/tests-e2e-fixtures, scripts/github-actions/tests-e2e-fixtures-backupdr, scripts/github-actions/tests-e2e-fixtures-bigquery, scripts/github-actions/tests-e2e-fixtures-vmwareengine
The `tests-e2e-fixtures` is timing out again.
=> test: split out vmwareengine and backupdr into individual tests

experiments/conductor/cmd/runner/crd_generator_commands.go, experiments/conductor/cmd/runner/fuzzer_commands.go, experiments/conductor/cmd/runner/github_commands.go, experiments/conductor/cmd/runner/mock_commands.go, experiments/conductor/cmd/runner/runner.go, experiments/conductor/cmd/runner/utilities.go
conductor: type/crd/mapper/fuzzer improvements
* Add more llm based fixes for types:
* removeNameField - Remove Name field in Spec (ResourceID instead) and Status (ExternalRef instead)
* moveEtagField - Belongs to Status
* addRequiredFieldTags - add KRM +reuired tag
* Improve existing prompts for:
* fixing mockgcp failures
* Autofix: Add fuzz testing and fix loop
* Autofix: Add apichecks and fix loop
* Add crunAPIChecks to run apichecks as part of cmd=9
* Add --skip-makereadypr when pushing changes (cmd=9)
* Add ability to run make ready-pr until no changes are detected.
Sometime make ready-pr makes a change once and we need to rerun make
ready-pr again. So add AttemptsOnChanges to handle this case.
=> conductor: type/crd/mapper/fuzzer improvements

pkg/controller/kccmanager/kccmanager.go
Likely only done in tests, but if set we should pass it down,
otherwise it does not make it to the GRPC clients (for example).
=> Plumb through GCPAccessToken if provided in controllers

experiments/conductor/cmd/runner/utilities.go
Avoids red herring such as:
```
conductor: "Create minimal test. WARN: go cmds failed."
```
=> conductor: only run goimports on go files

config/tests/samples/create/harness.go, pkg/test/resourcefixture/testdata/basic/kms/v1beta1/kmsautokeyconfig/_generated_object_kmsautokeyconfig.golden.yaml, pkg/test/resourcefixture/testdata/basic/privilegedaccessmanager/v1beta1/privilegedaccessmanagerentitlement/privilegedaccessmanagerentitlementfullfolder/_generated_object_privilegedaccessmanagerentitlementfullfolder.golden.yaml, pkg/test/resourcefixture/testdata/basic/resourcemanager/v1beta1/folder/folderinfolder/_generated_object_folderinfolder.golden.yaml, pkg/test/resourcefixture/testdata/basic/resourcemanager/v1beta1/project/projectinfolder/_generated_object_projectinfolder.golden.yaml, pkg/test/resourcefixture/testdata/containerannotations/folderid/_generated_object_folderid.golden.yaml, tests/e2e/normalize.go, tests/e2e/script_test.go, tests/e2e/unified_test.go
Actual folder values were appearing in the output,
which means we cannot have parity with realgcp.
=> tests: normalize folderID

dev/tools/controllerbuilder/template/controller/controller.go
I noticed that I kept changing this line for conductor/ controllerbuilder. I think the right thing to do here is to use the ID (read name) from the resource identity.
=> template: use id.ID

dev/tools/controllerbuilder/pkg/commands/generatefuzzer/README.md, dev/tools/controllerbuilder/pkg/toolbot/csv.go, pkg/controller/direct/iap/iapsettings_fuzzer.go, pkg/controller/direct/managedkafka/topic_fuzzer.go, pkg/controller/direct/redis/cluster/cluster_fuzzer.go, pkg/controller/direct/redis/cluster_fuzzer.go, pkg/controller/direct/securesourcemanager/instance_fuzzer.go, pkg/controller/direct/securesourcemanager/repository_fuzzer.go
Couple findings:
- Many existing direct resources do not fully adhere to best practices, which means the fuzz gen tool won’t work well for them.
- For some resources with the legacy "roundtrip_test.go" files. I noticed that some "roundtrip_test.go" files incorrectly mark fields—for example, in `XXXSpecFuzz`, unimplemented fields and status fields have the same effect, making them easy to mix up. The generated fuzzer does not have this issue.
=> chore: generate more fuzzers

dev/tools/controllerbuilder/pkg/commands/exportcsv/prompt.go, dev/tools/controllerbuilder/pkg/llm/gemini.go, dev/tools/controllerbuilder/pkg/llm/vertexai.go, experiments/conductor/cmd/runner/crd_generator_commands.go, experiments/conductor/cmd/runner/github_commands.go, experiments/conductor/cmd/runner/runner.go, experiments/conductor/cmd/runner/utilities.go
controllerbuilder: switch to new default model
Conductor: Improvements for Type and Mapper generation
* Tweak prompts
* Refactor code to move repetitive code under prepareCodebotPrompt (for
crd steps)
* Add option to run subset of processors in multi-processor step like
21. Rationale is to rerun processors that did not generate output.
*  --processors=p1,p2,....
* Fix bugs with repetititve steps:
* for step 9 where it was running make ready-pr many times
* everywhere where changes were not generated
=> Conductor improvements and switch controllerbuilder to new default model

config/samples/resources/bigqueryconnectionconnection/cloudspanner-connection/spanner_v1beta1_spannerinstance.yaml, config/samples/resources/spannerdatabase/spanner_v1beta1_spannerinstance.yaml, pkg/controller/direct/spanner/instance_controller.go, scripts/generate-google3-docs/resource-reference/generated/resource-docs/bigqueryconnection/bigqueryconnectionconnection.md, scripts/generate-google3-docs/resource-reference/generated/resource-docs/spanner/spannerdatabase.md
=> Update Sample Test for SpannerInstance

pkg/controller/direct/sql/sqlinstance_equality.go, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-backupconfiguration-diff/_generated_object_sqlinstance-backupconfiguration-diff.golden.yaml, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-backupconfiguration-diff/_http.log, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-backupconfiguration-diff/create.yaml
This PR
- Add a test case to reproduce #4207
- Fix the permanent diff in `backupConfiguration` for `SQLInstance`. This is a behavior change introduced when migrating the resource from the TF controller to the direct controller. The fix effectively reverts the behavior change.
Fixes: #4207
Without the change:
```
$ go test -v -tags=integration ./pkg/controller/dynamic/ -run TestCreateNoChangeUpdateDelete/sql/basic-sqlinstance-backupconfiguration-diff 
...
k8s.go:84: expected event with reason 'Updating' to not be recorded for SQLInstance pxx4um5zs4ihvqa/test-pxx4um5zs4ihvqa, but it was
...
--- FAIL: TestCreateNoChangeUpdateDelete (0.17s)
--- FAIL: TestCreateNoChangeUpdateDelete/sql (0.00s)
--- FAIL: TestCreateNoChangeUpdateDelete/sql/basic-sqlinstance-backupconfiguration-diff  (310.95s) …
```
=> fix: fix permanent diff in SQLInstance backupConfiguration

experiments/conductor/cmd/runner/utilities.go
conductor is the tool, not the outcome.
=> conductor: do not add conductor prefix to git commits

experiments/conductor/cmd/runner/utilities.go
Remove the "conductor: " prefix from the commit message and set conductor Bot as the commit author instead.
=> conductor: make conductor bot as author

experiments/conductor/cmd/runner/utilities.go
Reverts GoogleCloudPlatform/k8s-config-connector#4209
Will add it back when the bot is allowlisted for "SignCLA".
Initially, I wasn't sure if it was necessary, since developers will open the PRs and the commits will be authored by the bot but committed by the developers. However, it appears we can't bypass the CLA check for the bot.
=> Revert "conductor: make conductor bot as author"

apis/apigateway/v1alpha1/api_identity.go, config/tests/samples/create/harness.go, mockgcp/mockapigateway/api.go, mockgcp/mockapigateway/testdata/api/crud/_http.log, pkg/controller/direct/apigateway/api_controller.go, pkg/controller/direct/apigateway/api_fuzzer.go, pkg/controller/direct/apigateway/client.go, pkg/controller/direct/register/register.go, pkg/test/resourcefixture/testdata/basic/apigateway/v1alpha1/apigatewayapi/apigatewayapi-minimal/_generated_object_apigatewayapi-minimal.golden.yaml, pkg/test/resourcefixture/testdata/basic/apigateway/v1alpha1/apigatewayapi/apigatewayapi-minimal/_http.log, pkg/test/resourcefixture/testdata/basic/apigateway/v1alpha1/apigatewayapi/apigatewayapi-minimal/create.yaml, pkg/test/resourcefixture/testdata/basic/apigateway/v1alpha1/apigatewayapi/apigatewayapi-minimal/update.yaml, pkg/test/resourcefixture/testdata/basic/apigateway/v1alpha1/apigatewayapi/apigatewayapiautogen/_generated_object_apigatewayapiautogen.golden.yaml, pkg/test/resourcefixture/testdata/basic/apigateway/v1alpha1/apigatewayapi/apigatewayapiautogen/_http.log, tests/e2e/unified_test.go
=> feat: Direct controller ApiGatewayApi

mockgcp/mock_http_roundtrip.go, mockgcp/mockmonitoring/normalize.go, mockgcp/mockmonitoring/notificationchannel.go, mockgcp/mockmonitoring/service.go, mockgcp/mockmonitoring/testdata/monitoringnotificationchannel/crud/_http.log, mockgcp/mockmonitoring/testdata/monitoringnotificationchannel/crud/script.yaml, tests/e2e/unified_test.go
- **conductor: "Create gcloud script.yaml. WARN: go cmds failed."**
- **conductor: "Capture HTTP Log for mocks"**
- **mockgcp: more fidelity for monitoring notificationchannel**
=> mockgcp: fill in monitoring notificationchannel

experiments/conductor/cmd/runner/utilities.go
Revert the revert!
So basically we are adding back https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/4209
Now that the bot is allowlisted by "SignCLA".
=> Revert "Revert "conductor: make conductor bot as author""

.github/workflows/presubmit.yaml
Fixes the error in presubmit workflow `build-images`.
```
System.IO.IOException: No space left on device
```
=> test: freeup space before building images in presubmit

.github/workflows/ci-presubmit.yaml, scripts/github-actions/tests-e2e-fixtures, scripts/github-actions/tests-e2e-fixtures-bigtable, scripts/github-actions/tests-e2e-fixtures-certificatemanager, scripts/github-actions/tests-e2e-fixtures-resourcemanager, scripts/github-actions/tests-e2e-fixtures-spanner, scripts/github-actions/tests-e2e-fixtures-workstations
Split bigtable, certificatemanager, resourcemanager spanner, workstation
=> ci: Split presubmit fixtures test into more API groups

dev/tools/controllerbuilder/pkg/codegen/typegenerator.go, dev/tools/controllerbuilder/pkg/commands/generatetypes/generatetypescommand.go
Fix a bug that was missed in PR #4075.
Write visited messages AFTER the file annotation is added.
=> tool: fix a bug when annotating types file

experiments/conductor/branches-all.yaml
Removing the `locations` resources from my batch of metadata.
=> conductor:branches: remove locations

dev/tasks/run-e2e, pkg/test/resourcefixture/resourcefixture.go, tests/e2e/unified_test.go
It looks like tests are not being properly skipped in test-e2e-fixtures
Simplify and add logging.
=> chore: clean up test skip logic

config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_storagebuckets.storage.cnrm.cloud.google.com.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/storage/storagebucket.md, tests/e2e/testdata/scenarios/storagebucket/updatebucketlocation/_http00.log, tests/e2e/testdata/scenarios/storagebucket/updatebucketlocation/_http01.log, tests/e2e/testdata/scenarios/storagebucket/updatebucketlocation/_object00.yaml, tests/e2e/testdata/scenarios/storagebucket/updatebucketlocation/_object01.yaml, tests/e2e/testdata/scenarios/storagebucket/updatebucketlocation/script.yaml, third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/services/storage/resource_storage_bucket.go
Allow updating the bucket location field. 
Customer is able to set the new bucket location in the KCC resource. The actual bucket relocation is trigger from the API.
=> Allow updating the bucket location field

experiments/conductor/cmd/runner/runner.go, experiments/conductor/cmd/runner/utilities.go
New command 3 merges a separate metadata file into the main and out to branches-new.yaml. Assumes the merge file takes precedense. Also undoes any skips it finds.
Also added a stable order write file. We will take a 1 time hit the first time this is run but the order should be stable after that.
./bin/conductor runner --branch-repo=<repo-dir> --logging-dir=./logs --branch-conf=branches-all.yaml --merge-conf=branches-test.yaml --command=3
branches-test.yaml had 2 skip=true resources with other changed. Confirmed the changes came through.
=> Added a merge metadata command.

experiments/conductor/cmd/runner/utilities.go
Kind should not be empty but we have a few cases still where it is. Stabilizing the order for these cases.
Using name for this case.
Assuming name will usually approximate group-kind so should be a similar order.
=> Fix ordering when kind is empty.

experiments/conductor/branches-all.yaml
This includes a list of additional metadata from the compute group. Removed metadata entries marked as not needed by gemmahou.
- bigtable-operations
- functions-regions
- notebooks-locations
- spanner-operation
- tpu-location
- compute-computenetworksvpcaccessoperations
Ran conductor command 1 to ensure metadata looked ok.
Visually inspected metadata.
Checked on the additional resources which had been added.
=> Added updated metadata from gemmahou.

apis/speech/v1alpha1/phraseset_types.go, apis/speech/v1alpha1/types.generated.go
Overlooked in #4303. Moving the manually edited Go type out of the generated file.
=> SpeechPhraseSet: move modified types out of generated file

pkg/controller/direct/backupdr/managementserver_controller.go
The previous implementation is technically correct but somewhat unclear. It normalizes the reference in `network`, which is a copy of `obj.Spec.Networks[i]`. This works only because `network.NetworkRef` is a pointer—modifying the copy inadvertently updates the original. The new implementation clarifies the intent and improves readability and maintainability.
=> chore: fix NetworkRef normalization in `BackupDRManagementServer` controller

experiments/conductor/branches-all.yaml, experiments/conductor/cmd/runner/runner.go
Determined the set of TF-v1beta1 resources based on the following. 
```
for file in `egrep "cnrm.cloud.google.com/tf2crd: \"true\"" * | sed 's|:.*||;'`; do echo `yq '.spec.group' $file | sed 's|.cnrm.cloud.google.com||;' && yq '.spec.names.kind' $file && yq '.spec.versions.[] | select(.name == "v1beta1") | .name' $file` | egrep v1beta1 | sed 's|\"||g;' ; done 
```
Marked the relevant resources with the controller type. Small amounts of related metadata cleanup.
A few entried had to be deduped.
Also added a new command to filter metadata based on controller type.
Made sure command 1 indicated the metadata was still good.
Checked the number of controllers of the new type matched.
Made sure I could filter the right number of metadata entries.
=> Marked KCC resources as terraform-v1beta1 based on CRD evaluation.

config/servicemappings/bigquery.yaml, mockgcp/mockbigquery/tables.go, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable-ignore-schema-changes/_generated_export_bigquerytable-ignore-schema-changes.golden, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable-ignore-schema-changes/_generated_object_bigquerytable-ignore-schema-changes.golden.yaml, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable-ignore-schema-changes/_http.log, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable-ignore-schema-changes/create.yaml, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable-ignore-schema-changes/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/bigquery/v1beta1/bigquerytable-ignore-schema-changes/update.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/bigquery/bigquerytable.md, tests/apichecks/testdata/exceptions/missingfields.txt, third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/services/bigquery/resource_bigquery_table.go
Add new `unmanaged` directive to TF controller for BQ Table. The spec fields specified in the annotation is unmanaged during Update call. The only spec field supported is `spec.schema` at the moment.
Add new test case for the directives, TF controller makes a PATCH call instead of PUT call. The table object has nil schema to avoid schema to be updated.
=> tf: Add annotation to BigqueryTable to ignore schema change during update

config/tests/samples/create/harness.go, mockgcp/mockvmwareengine/externalaccessrule.go, mockgcp/mockvmwareengine/privatecloud.go, pkg/controller/direct/vmwareengine/externalaccessrule_controller.go, pkg/test/resourcefixture/testdata/basic/vmwareengine/v1alpha1/vmwareengineexternalaccessrule/vmwareengineexternalaccessrule-minimal/_generated_object_vmwareengineexternalaccessrule-minimal.golden.yaml, pkg/test/resourcefixture/testdata/basic/vmwareengine/v1alpha1/vmwareengineexternalaccessrule/vmwareengineexternalaccessrule-minimal/_http.log, pkg/test/resourcefixture/testdata/basic/vmwareengine/v1alpha1/vmwareengineexternalaccessrule/vmwareengineexternalaccessrule-minimal/create.yaml, pkg/test/resourcefixture/testdata/basic/vmwareengine/v1alpha1/vmwareengineexternalaccessrule/vmwareengineexternalaccessrule-minimal/dependencies.yaml, pkg/test/resourcefixture/testdata/basic/vmwareengine/v1alpha1/vmwareengineexternalaccessrule/vmwareengineexternalaccessrule-minimal/update.yaml
HTTP log: real vs. mock (only includes requests relevant to this resource):
https://www.diffchecker.com/GdM306Ad/
The diff includes additional GET requests related to VMware networks, network policies, and similar resources. I think these are triggered by periodic reconciliations that occur roughly every 10 minutes during testing against real GCP, which takes considerably longer.
=> feat: add controller, test and mock support for VMwareEngineExternalAccessRule

config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_storagebuckets.storage.cnrm.cloud.google.com.yaml, scripts/generate-google3-docs/resource-reference/generated/resource-docs/storage/storagebucket.md, tests/e2e/testdata/scenarios/storagebucket/dualregionbucketrelocation/_http00.log, tests/e2e/testdata/scenarios/storagebucket/dualregionbucketrelocation/_http01.log, tests/e2e/testdata/scenarios/storagebucket/dualregionbucketrelocation/_object00.yaml, tests/e2e/testdata/scenarios/storagebucket/dualregionbucketrelocation/_object01.yaml, tests/e2e/testdata/scenarios/storagebucket/dualregionbucketrelocation/script.yaml, third_party/github.com/hashicorp/terraform-provider-google-beta/google-beta/services/storage/resource_storage_bucket.go
Allow users to pick up a new pair of locations so that KCC won't reconcile the locations when they move a dual-region bucket.
This is a complement to the PR http://github.com/GoogleCloudPlatform/k8s-config-connector/pull/4344/.
Moving a bucket will be from CLI/UI.
=> Allows updating the location placement in a dual-region bucket.

pkg/controller/direct/backupdr/backupvault_controller.go, pkg/controller/direct/gkebackup/backup_controller.go, pkg/controller/direct/gkebackup/backupplan_controller.go, pkg/controller/direct/gkebackup/restore_controller.go, pkg/controller/direct/gkebackup/restoreplan_controller.go, pkg/controller/direct/speech/customclass_controller.go, pkg/controller/direct/vmwareengine/externaladdress_controller.go, pkg/controller/direct/vmwareengine/networkpeering_controller.go, pkg/controller/direct/vmwareengine/networkpolicy_controller.go, pkg/controller/direct/vmwareengine/privatecloud_controller.go, pkg/controller/direct/vmwareengine/vmwareenginenetwork_controller.go
Following up on a comment in #4403 - add `externalRef` in "update" for some of the controllers I recently added.
=> chore: update externalRef in adapter update

pkg/controller/direct/alloydb/cluster_controller.go, pkg/controller/direct/alloydb/instance_controller.go, pkg/controller/direct/privilegedaccessmanager/entitlement_controller.go
I kept the `if` check to update status only when `status.externalRef` is not set for AlloyDBCluster and AlloyDBInstance. This is to reduce unnecessary updates.
In the future, I think we should update status in Update() when:
1.  Drift is detected and fixed.
2. `status.externalRef` is unset.
3. `status.observedState` is updated.
Right now for many controllers we update status regardlessly, and I'm a bit concerned this will impact scalability when there are many resources. Though it might be cheap/free to update status (?); we need to discuss further.
=> Update status in adapter Update() even without change

mockgcp/mockcloudidentity/groupsmembership.go, mockgcp/mockcloudidentity/service.go, pkg/test/resourcefixture/testdata/basic/cloudidentity/v1beta1/cloudidentitymembership/addexpirydatecloudidentitymembership/_generated_object_addexpirydatecloudidentitymembership.golden.yaml, pkg/test/resourcefixture/testdata/basic/cloudidentity/v1beta1/cloudidentitymembership/addexpirydatecloudidentitymembership/_http.log, pkg/test/resourcefixture/testdata/basic/cloudidentity/v1beta1/cloudidentitymembership/addrolecloudidentitymembership/_generated_object_addrolecloudidentitymembership.golden.yaml, pkg/test/resourcefixture/testdata/basic/cloudidentity/v1beta1/cloudidentitymembership/addrolecloudidentitymembership/_http.log, pkg/test/resourcefixture/testdata/basic/cloudidentity/v1beta1/cloudidentitymembership/removerolecloudidentitymembership/_generated_object_removerolecloudidentitymembership.golden.yaml, pkg/test/resourcefixture/testdata/basic/cloudidentity/v1beta1/cloudidentitymembership/removerolecloudidentitymembership/_http.log
1st commit https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/4443/commits/7f27152b577120ca48a95bd1f0e8efce41224a58: collect realGCP logs. Triggered a prow job in [CL#73200](https://cnrm-review.git.corp.google.com/c/cnrm/+/73200)(the -1 is expected, since we start a new pipeline for each run, there's no golden log to compare with. Other than the diff I don't see other errors), realGCP logs located in GCS storage: https://pantheon.corp.google.com/storage/browser/cnrm-prow/pr-logs/pull/cnrm-review.googlesource.com_cnrm/73200/cnrm-test/1915505218699661312/artifacts?e=13802955&mods=pan_ng2&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))
2nd commit https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/4443/commits/6a1af1075efcdfb0a01ce92197a9ac2515a5 …
=> mockGCP: More fidelity for CloudIdentityMembership mock

tests/apichecks/crds_test.go
Let's make sure the shortnames start with `gcp` too.
=> tests: gcp suffix

config/tests/samples/create/harness.go, operator/Dockerfile, pkg/cli/preview/intercepting_gcp_client.go, pkg/cli/preview/intercepting_kube_client.go, pkg/cli/preview/preview.go, pkg/cli/preview/preview_test.go, pkg/cli/preview/recorder.go, pkg/cli/preview/streaming_client.go, pkg/cli/preview/streaming_informer.go, pkg/cli/preview/typeinfo.go, pkg/cli/preview/utils.go, pkg/controller/kccmanager/kccmanager.go, pkg/controller/kccmanager/nocache/clientbuilder.go, pkg/controller/lifecyclehandler/handler.go, pkg/controller/tf/controller.go, pkg/structuredreporting/context.go, pkg/structuredreporting/diffs.go, pkg/structuredreporting/events.go, scripts/github-actions/ga-unit-test.sh
The goal of the command is to capture for each object the changes that will be made at the cloud level.
This step adds some of the mechanics and a test, it does not yet expose the functionality.
=> Start experimental preview command

docs/releasenotes/release-1.131.md
Technically, they were released in version 1.130. However, I was told that updating a release document already published on GCP might not be easy.
=> doc: add BigQueryReservation resources to release note

experiments/conductor/cmd/runner/controller_commands.go, experiments/conductor/cmd/runner/github_commands.go, experiments/conductor/cmd/runner/runner.go, experiments/conductor/cmd/runner/utilities.go
A lot of resources only have one test case and they are directly under `pkg/test/resourcefixture/testdata/basic/<group>/v1beta1/<kind>` directory.
To support new test cases, we need to move these test cases to a sub directory first.
=> Support moving existing test to subdir in preparation for adding more test cases

cmd/deletiondefender/main.go, cmd/unmanageddetector/main.go, config/tests/samples/create/harness.go, config/tests/samples/create/samples_test.go, pkg/controller/kccmanager/kccmanager.go, pkg/controller/registration/registration_controller.go
We still need to skip duplicate name detection in the tests,
because of how the check is implemented,
but we can avoid duplicate names outside of tests.
=> fix: avoid duplicate names for controllers

config/tests/samples/create/harness.go, tests/e2e/normalize.go, tests/e2e/script_test.go, tests/e2e/testdata/scenarios/iam/iampartialpolicy/_http00.log, tests/e2e/testdata/scenarios/iam/iampartialpolicy/_http01.log, tests/e2e/testdata/scenarios/iam/iampartialpolicy/_http02.log, tests/e2e/testdata/scenarios/iam/iampartialpolicy/_http03.log, tests/e2e/testdata/scenarios/iam/iampartialpolicy/_object00.yaml, tests/e2e/testdata/scenarios/iam/iampartialpolicy/_object01.yaml, tests/e2e/testdata/scenarios/iam/iampartialpolicy/_object02.yaml, tests/e2e/testdata/scenarios/iam/iampartialpolicy/script.yaml
This patch adds support for scenario based tests to just observe the system reconciling. We can then look at IAMPartialPolicy and see the number of GETs they make. This will come in handy when comparing the output with #4501
=> tests:  observe IAMPartialPolicy runs

pkg/webhook/cert/certclient/certclient.go, pkg/webhook/register.go
We can't create a service if we have no clusterIPs remaining,
even if the service already exists
(and we don't get the normal 404/NotFound error).
This confuses our webhook-creation logic.
=> fix: webhooks should pre-check for existence using get

.github/workflows/ci-presubmit.yaml, mockgcp/mocknetworkconnectivity/testdata/internalranges/crud/_http.log
Following up on https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/4498#issuecomment-2858595050
It seems without this the HEAD is broken and some PRs on the `immutable` field being absent (!) in some other gcloud version.
=> ci: pin gcloud

Makefile, config/installbundle/release-manifests/autopilot/kustomization.yaml, config/installbundle/release-manifests/standard/kustomization.yaml, dev/tasks/deploy-release-manifest
This PR only adds a script to create the release bundle. 
I am separating the github workflow (to trigger this script by a git tag push) and this script to two different PRs.
=> Add a script to create release bundle

pkg/controller/unmanageddetector/controller_test.go
These currently share a kube apiserver,
and check whether a statefulset is running,
but one of them starts the statefulset.
We can't run them in parallel.
=> tests: don't run unmanageddetector tests in parallel

pkg/controller/dcl/controller.go, pkg/controller/tf/controller.go, pkg/managementconflict/annotations.go, pkg/managementconflict/annotations_test.go
- **chore: refactor managementconflict logic**
Put it in its own package so we can better reason about it.
- **Make the management-conflict annotation optional**
There's no reason to enforce the annotation - it is mutable.
Making it optional means one less thing we depend on the webhook for.
=> management conflict is not required

mockgcp/mockserviceusage/service.go, mockgcp/mockserviceusage/testdata/identity/crud/_http.log, mockgcp/mockserviceusage/testdata/identity/crud/script.yaml
- **mockgcp: create test for gcloud beta services identity**
- **mockgcp: golden output for mockserviceusage/testdata/identity/crud**
=> mockgcp: gcloud test coverage for serviceidentity

go.mod, go.sum, operator/cmd/manager/main.go, operator/pkg/controllers/configconnector/configconnector_controller.go, operator/pkg/controllers/configconnector/e2e_test.go, operator/pkg/controllers/configconnector/golden_test.go, operator/pkg/controllers/configconnector/testdata/golden/simple/_expected.yaml, operator/pkg/controllers/configconnector/testdata/golden/simple/input.yaml, operator/pkg/controllers/configconnectorcontext/golden_test.go, operator/pkg/controllers/configconnectorcontext/testdata/golden/simple/_expected.yaml, operator/pkg/controllers/configconnectorcontext/testdata/golden/simple/dependencies.yaml, operator/pkg/controllers/configconnectorcontext/testdata/golden/simple/input.yaml
- **Simple golden tests**
- **tests: add tests for CCC operator**
=> tests: add golden tests for operator

pkg/controller/direct/bigtable/appprofile_controller.go, pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableappprofile/bigtableappprofile-direct/_generated_object_bigtableappprofile-direct.golden.yaml, pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableappprofile/bigtableappprofiledataboost-disable-direct/_generated_object_bigtableappprofiledataboost-disable-direct.golden.yaml, pkg/test/resourcefixture/testdata/basic/bigtable/v1beta1/bigtableappprofile/bigtableappprofiledataboost-enable-direct/_generated_object_bigtableappprofiledataboost-enable-direct.golden.yaml
I asked the original author to "write back resourceID" for backward compatibility, as we are migrating this resource from TF-beta to direct. However, I’ve realized that we no longer want to keep this behavior in the direct controller.
(In 1.132, the controller still defaults to TF controller)
=> BigtableAppProfile: do not write back ResourceID

mockgcp/common/fields/impliedfieldmask.go, mockgcp/mockpubsub/topic.go, pkg/test/resourcefixture/testdata/basic/pubsub/v1beta1/pubsubtopic/pubsubtopic/_generated_object_pubsubtopic.golden.yaml, pkg/test/resourcefixture/testdata/basic/pubsub/v1beta1/pubsubtopic/pubsubtopic/_http.log, pkg/test/resourcefixture/testdata/basic/pubsub/v1beta1/pubsubtopic/pubsubtopic/update.yaml, tests/apichecks/testdata/exceptions/missingfields.txt
- **tests: don't just change labels on pubsubtopic test**
Because changing the labels does not bump observedGeneration,
the tests do not correctly wait for reconciliation.
- **mockgcp: implement implied field mask in pubsub topic**
=> tests: don't just update labels in pubsub topic test

dev/tools/controllerbuilder/pkg/codegen/mappergenerator.go, pkg/controller/direct/bigtable/appprofile_fuzzer.go, pkg/controller/direct/bigtable/mapper.generated.go
We have a contributor working on a new resource in bigtable API. Let's make sure the generated mapping function file is regenerate-safe.
=> chore: clean up mapping functions for bigtable

docs/releasenotes/release-1.132.md
Update release note from https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/4553.
=> doc: release note for SpeechRecognizer

pkg/controller/lifecyclehandler/handler_test.go, pkg/controller/registration/registration_controller.go, pkg/controller/unmanageddetector/controller.go, pkg/controller/unmanageddetector/controller_test.go, pkg/test/kubeharness.go, pkg/test/resources.go
- **chore: modernize unmanageddetector test**
We can use envtest and avoid a lot of the setup complexity.
=> chore: modernize unmanageddetector controller & test

.github/workflows/ci-presubmit.yaml, dev/ci/presubmits/tracker-tests
Even if we are just starting with the `Project` kind, I am turning on some early testing for our mock/ presubmits tests where the tracker flag gate is on!
As we turn on more of these, I'll revisit how we select the RUN_TESTS var.
=> tests: run tracker presubmits too

scripts/generate-google3-docs/resource-reference/main.go
The original check is a too strict. Does not work when the repo is copied to g3.
=> chore: fix sample check

pkg/controller/kccmanager/kccmanager.go, pkg/gcpwatch/tracker.go
Might be temporary but I think we will start using a configurable interval, especially in dynamic tests (postsubmits) soon! Can also configure the jitter to reflect current behavior. Still TBD how we are going to handle the reconcile annotation.
=> refactor: configurable poll intervals

experiments/conductor/cmd/runner/controller_commands.go, experiments/conductor/cmd/runner/github_commands.go, experiments/conductor/cmd/runner/github_commands_test.go, experiments/conductor/cmd/runner/runner.go, experiments/conductor/cmd/runner/utilities.go, scripts/unit-test.sh
Added the command that generates test cases to increase coverage for supported resources:
* Currently, the command attempt to generate the test at least once and at most three times to ensure most coverage.
* Use the updated result of tests/apichecks/testdata/exceptions/missingfields.txt to determine whether the test cases cover all the supported fields and gets a list of uncovered fields. We ignore `XXXRef.external` fields as we want to test references via `.name` field. We also ignore `value` field under sensitive fields as we encourage usage of `valueFrom` and currently are focusing on testing the encouraged option.
* Uncovered fields extraction is not done by LLM because several lines of functions do a better job than codebot.
* Use LLM to generate the create.yaml to cover as many …
=> Support maximal test generation in conductor

.github/workflows/presubmit.yaml, apis/iam/v1beta1/policy_types.go, apis/iam/v1beta1/register.go, pkg/controller/direct/directbase/directbase_controller.go, pkg/controller/direct/directbase/interfaces.go, pkg/controller/direct/iam/iambindings.go, pkg/controller/direct/iam/iambindings_test.go, pkg/controller/direct/iam/mappings.go, pkg/controller/direct/iam/partialpolicy_controller.go, pkg/controller/direct/register/register.go, pkg/controller/registration/registration_controller.go, pkg/test/controller/reconciler/testreconciler.go, scripts/github-actions/ga-iam-direct-tests.sh
This converts the iampartialpolicy controller to the new direct approach.
NOTE: this controller is not turned on so no changes to existing IAM handling are made.
Follow ups
* fuzzer test (will come out as a separate PR)
* export using THIS direct approach https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/4667
=> feat: direct iampartialpolicy controller

dev/ci/periodics/_create_project_and_run_e2e, dev/ci/periodics/e2e-service-storage, docs/releasenotes/release-1.133.md, tests/e2e/unified_test.go
1. Increase the subtest timeout for anywherecache resource.
2. Update release notes for AnywhereCache resource
=> increase the subtest timeout, and Update release notes for AnywhereCache resource

pkg/controller/direct/directbase/directbase_controller.go
Controller-runtime has been reported with https://github.com/kubernetes-sigs/controller-runtime/issues/2937 where they check the uniqueness of controller names globally. 
Disable the name check with `SkipNameValidation` option.
=> fix: skip controller name validation 

dev/tasks/sync-crds-folder.sh, scripts/parse-crds/parse-crds.go
* Require VERSION to be set rather than silently choosing a bad version.
* Modernize the go script
=> chore: clean up sync-crds release step

pkg/test/resourcefixture/resourcefixture.go, pkg/test/resourcefixture/testdata/iam/iampartialpolicy/iam-bigqueryconnectionconnectionref/_generated_object_iam-bigqueryconnectionconnectionref.golden.yaml, pkg/test/resourcefixture/testdata/iam/iampartialpolicy/iam-bigqueryconnectionconnectionref/_http.log, pkg/test/resourcefixture/testdata/iam/iampartialpolicy/iam-bigqueryconnectionconnectionref/create.yaml, pkg/test/resourcefixture/testdata/iam/iampartialpolicy/iam-bigqueryconnectionconnectionref/dependencies.yaml, pkg/test/resourcefixture/testdata/iam/iampartialpolicy/iam-logsinkref/_generated_object_iam-logsinkref.golden.yaml, pkg/test/resourcefixture/testdata/iam/iampartialpolicy/iam-logsinkref/_http.log, pkg/test/resourcefixture/testdata/iam/iampartialpolicy/iam-logsinkref/create.yaml, pkg/test/resourcefixture/testdata/iam/iampartialpolicy/iam-logsinkref/dependencies.yaml, pkg/test/resourcefixture/testdata/iam/iampartialpolicy/iam-serviceaccountref/_generated_object_iam-serviceaccountref.golden.yaml, pkg/test/resourcefixture/testdata/iam/iampartialpolicy/iam-serviceaccountref/_http.log, pkg/test/resourcefixture/testdata/iam/iampartialpolicy/iam-serviceaccountref/create.yaml, pkg/test/resourcefixture/testdata/iam/iampartialpolicy/iam-serviceaccountref/dependencies.yaml, pkg/test/resourcefixture/testdata/iam/iampartialpolicy/iam-serviceidentityref/_generated_object_iam-serviceidentityref.golden.yaml, pkg/test/resourcefixture/testdata/iam/iampartialpolicy/iam-serviceidentityref/_http.log, pkg/test/resourcefixture/testdata/iam/iampartialpolicy/iam-serviceidentityref/create.yaml, pkg/test/resourcefixture/testdata/iam/iampartialpolicy/iam-serviceidentityref/dependencies.yaml, pkg/test/resourcefixture/testdata/iam/iampartialpolicy/iam-sqlinstanceref/_generated_object_iam-sqlinstanceref.golden.yaml, pkg/test/resourcefixture/testdata/iam/iampartialpolicy/iam-sqlinstanceref/_http.log, pkg/test/resourcefixture/testdata/iam/iampartialpolicy/iam-sqlinstanceref/create.yaml, pkg/test/resourcefixture/testdata/iam/iampartialpolicy/iam-sqlinstanceref/dependencies.yaml, pkg/webhook/iam_validator.go, tests/apichecks/testdata/exceptions/missingfields.txt, tests/e2e/unified_test.go
This adds test for the IAMPartialPolicy resource around the memberFrom reference to create a baseline. 
Technically, these tests are duplicates of how IAMPolicyMember is tested today but it will be good to have this duplicate since we are about to change IAMPartialPolicy internals and the code paths could diverge!
=> tests: memberRefs for IAMPartialPolicy

.gitattributes, apis/storage/v1beta1/anywherecache_types.go, config/crds/resources/apiextensions.k8s.io_v1_customresourcedefinition_storageanywherecaches.storage.cnrm.cloud.google.com.yaml, dev/tasks/generate-crds, experiments/promoter/scripts/find_promotion_candidates.sh, pkg/gvks/supportedgvks/gvks_generated.go, scripts/crd-tools/cmd/backport-alpha/backport-alpha.go, scripts/crd-tools/main.go, tests/apichecks/crds_test.go, tests/apichecks/testdata/exceptions/multi_version_crd_diff/APIGatewayAPI.diff
This is for multi-version CRD  code review. 
It keeps both Alpha and Beta versions in the CRD, even if we moved the alpha api (so git-diff is simpler) 
I verified those exception CRDs. Backporting the alpha is expected:
1. `ComputeFirewallPolicyRule` has been defaulted to Scifi, no alpha version. 
2. `GKEHubFeatureMembership` has been defaulted to Scifi, no alpha version. 
3. `Logginlogmetrics` has been defaulted to Scifi, no alpha version. 
4. `StorageAnywhereCare` is a pure SciFi. It removes its Alpha  when promoting to Beta.
=> feat: backport alpha for multi-version CRD

.gitignore, experiments/llm-eval/evaluator.py, experiments/llm-eval/main.py, experiments/llm-eval/tasks/beta-promote/BigQueryReservationReservation-promote/setup.sh, experiments/llm-eval/tasks/beta-promote/KMSImportJob-promote/setup.sh, experiments/llm-eval/tasks/beta-promote/LoggingLink-promote/setup.sh, experiments/llm-eval/tasks/beta-promote/MetastoreBackup-promote/setup.sh, experiments/llm-eval/tasks/beta-promote/MetastoreFederation-promote/setup.sh, experiments/llm-eval/tasks/beta-promote/VMwareEngineExternalAddress-promote/setup.sh, experiments/mcp/criteria/apis.json, experiments/mcp/src/pkg/promotion.py, experiments/mcp/src/run.py, experiments/mcp/src/server.py
The "beta-promote" tasks will git-clone a KCC repo under its own dir. We want Gemini to only consider the codebase in the sub dir repo rather than the root repo and make code changes in sub repo.    
```release-note
NONE
```
```docs
```
=> llm-eval: run root Gemini CLI (and config) with different KCC repos

pkg/controller/dcl/controller.go, pkg/controller/direct/directbase/directbase_controller.go, pkg/controller/iam/auditconfig/iamauditconfig_controller.go, pkg/controller/iam/partialpolicy/iampartialpolicy_controller.go, pkg/controller/iam/policy/iampolicy_controller.go, pkg/controller/iam/policymember/iampolicymember_controller.go, pkg/controller/resourcewatcher/resourcewatcher.go, pkg/controller/resourcewatcher/resourcewatcher_test.go, pkg/controller/tf/controller.go
It isn't going to become ready from deletion,
and this is causing our tests to hang.
=> fix: resourcewatcher should terminate on delete

config/tests/samples/create/samples.go, tests/e2e/unified_test.go
The logic for SKIP_TEST_APIGROUP and ONLY_TEST_APIGROUPS was not working reliably because the API group for a sample was
determined by the first resource in the sample file, which could be a dependency.
This change fixes the issue by:
- Introducing an APIGroup field to the Sample and SampleKey structs.
- Updating ListMatchingSamples to parse the sample files and identify the main resource by matching the resource kind with the sample's directory name.
- Extracting the apiGroup from the apiVersion of the main resource.
- Using the new APIGroup field in the E2E test filtering logic.
This ensures that the test filtering based on API groups works correctly.
Fixes #
```release-note
```
```docs
```
=> Fix: Correctly determine sample API group for test filtering

tests/apichecks/crds_test.go, tests/apichecks/testdata/exceptions/missingfields.txt
Partially revert the filter function added in #4806
I encountered an issue in #4832 so I have this PR to revert the filter function, see https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/4832/files#r2224181901
=> tests: Partially revert #4806

pkg/cli/preview/preview_test.go, pkg/cli/preview/recorder.go, pkg/controller/tf/controller.go, pkg/structuredreporting/context.go, pkg/structuredreporting/events.go
This should avoid a potential (though unlikely) race condition where we catch an object mid-reconcile.
=> preview mode: introduce reconcile end event

dev/codebots/update-golang-version
sed behaves differently on MacOS vs Linux
Also add support for updating go.work
=> chore: move update-golang-version to python

pkg/metrics/metrics.go
As encouraged by @cheftako, warn about these metrics.
Testing:
```
$ SERVICE_MAPPING_DIR=config/servicemappings/ go run ./cmd/manager/main.go 2>&1
...
( in another terminal/ process: )
$ curl http://localhost:8888/metrics | grep "WARNING"
...
```
=> refactor: warn metrics

config/installbundle/components/manager/base/manager.yaml, operator/config/manager/manager.yaml
It is generally recommended to set `GOMEMLIMIT` to help with OOM kills.
=> feat: set GOMEMLIMIT for KCC operator and controller manager

mockgcp/mocksql/sqlinstance.go, pkg/controller/direct/sql/sqlinstance_controller.go, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-postgres-direct/_http.log, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-postgres-minimal-direct/_generated_object_sqlinstance-postgres-minimal-direct.golden.yaml, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-postgres-minimal-direct/_http.log, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-postgres-minimal-direct/create.yaml, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-postgres-minimal-direct/update.yaml
feat: separate op for maintenanceVersion for SQLInstance
Note the error without the patch on the controller:
```
...
Upgrading maintenance version and changing other fields at the same time is not allowed.
...
```
```release-note
Fix bug in SQLInstance `maintenanceVersion` UPDATE operation
```
=> feat: separate op for maintenanceVersion

.gemini/commands/fix/findlabels.toml, GEMINI.md
Added hints in GEMINI.md for classifying controller types. Added a custom command to find direct controllers which are missing the call to do label sanitization.
```release-note
NONE
```
```docs
NONE
```
=> Added a command to find missing label sanitization.

mockgcp/mocksql/sqlinstance.go, pkg/controller/direct/sql/sqlinstance_controller.go, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-postgres-minimal-direct/_generated_object_sqlinstance-postgres-minimal-direct.golden.yaml, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-postgres-minimal-direct/_http.log, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-postgres-minimal-direct/create.yaml, pkg/test/resourcefixture/testdata/basic/sql/v1beta1/sqlinstance/sqlinstance-postgres-minimal-direct/update.yaml
Follow up on https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/4838#discussion_r2226661307
```release-note
Support SQLInstance `maintenanceVersion` in CREATE operation
```
=> feat: support setting maintenanceVersion on CREATE

operator/pkg/controllers/configconnectorcontext/configconnectorcontext_controller.go, operator/pkg/controllers/configconnectorcontext/configconnectorcontext_controller_test.go
The ConfigConnectorContext reconciler implements its own status builder logic, so it needs to set the observedGeneration itself.
Note that some of the other controllers also are not properly setting the observedGeneration, but this change is focused on just fixing ConfigConnectorContext.
See:
- https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/v1.133.0/operator/pkg/controllers/configconnectorcontext/configconnectorcontext_controller.go#L133 (Empty `BuildStatusImpl`)
- https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/v1.133.0/operator/pkg/controllers/configconnectorcontext/configconnectorcontext_controller.go#L182
```release-note
status.observedGeneration is now being set on the ConfigConnectorContext.
```
```docs
NONE
```
1.134
Please indicate the intended …
=> fix: set observedGeneration of ConfigConnectorContext

.gemini/commands/release/propose-release.json, .gemini/commands/release/propose-release.toml, .github/workflows/presubmit-crds.yaml, dev/release/propose-release.md, dev/tasks/verify-crds-folder.sh
- Update the prompts for propose release candidate.
- Add a script to verify the CRD updates in the crds/ folder
- Add a presubmit test, that is only triggered when changes are made to the crds/ folder
Fixes #
=> chore: update propose release instructions and add presubmits for updating crds/ folder

pkg/controller/direct/alloydb/cluster_controller.go, pkg/controller/direct/alloydb/instance_controller.go
- Fix the nil pointer dereference error in AlloyDB direct controller and clear repeated code.
- Set status.externRef after the creation of AlloyDBCluster.
```release-note
*   [PR#5009](https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/5009)
Fix the nil pointer dereference error(error message: "error":"INTERNAL ERROR: panic: observed a panic: runtime error: invalid memory address or nil pointer dereference) in AlloyDB direct controller
```
```docs
```
1.134
=> Fix: nil pointer dereference in alloydb direct controller

mockgcp/mockdns/managedzone.go, mockgcp/mockdns/recordset.go, mockgcp/mockdns/service.go, mockgcp/mockdns/testdata/record-set/crud/_http.log, mockgcp/mockdns/testdata/record-set/crud/script.yaml, mockgcp/mockdns/util.go
- **mockgcp: create test for gcloud dns record-sets**
- **autogen: golden output for gcloud dns record-sets tests**
- **mockgcp: support dns resourceRecordSets**
=> mockgcp: support for dns resourceRecordSets

pkg/controller/direct/orgpolicy/policy_controller.go
The Update method for the OrgPolicy KCC component now fetches the current policy and compares it with the desired policy before calling the backend. The backend `Update` is only called if the policies differ.
This avoids unnecessary API calls when the policy is already in the desired state, improving performance and reducing quota usage.
Fixes #
```release-note
```
```docs
```
=> Optimize Update by comparing policies

pkg/controller/dcl/controller.go
Add reconcile start/end to dcl controller for preview tool to know when a resource is done reconciling.
```release-note
Improve reconcile reporting for DCL controller
```
```docs
```
=> [preview] Add reconcile start/end reporting to DCL controller
